= Auto Update Statistics
:description: Auto Update Statistics (AUS) is a solution designed to keep the optimizer statistics up to date. 

[abstract]
{description}

== Overview

Auto Update Statistics (AUS) is a feature that helps keep the optimizer statistics up to date by automatically identifying and refreshing outdated statistics.

Optimizer statistics are used by the xref:n1ql:n1ql-language-reference/cost-based-optimizer.adoc[Cost Based Optimizer] to generate optimal query plans.
These statistics are created when you run the xref:n1ql:n1ql-language-reference/updatestatistics.adoc[] statement or build an index (available from 7.6.0 onwards). 
However, as data changes over time, the statistics can become stale, leading to sub-optimal query plans and reduced query performance.

AUS addresses this challenge by running a scheduled task on the query nodes that regularly checks for outdated statistics using expiration policies and refreshes them by executing xref:n1ql:n1ql-language-reference/updatestatistics.adoc[]. 
// This way, AUS ensures that the optimizer statistics are always up to date and the CBO has the current information. 

[NOTE]
====
* AUS is only available in Couchbase Server 8.0 and later. For more information, see <<availability, Availability>>.
* AUS only updates existing statistics; it does not create new ones.
* AUS primarily maintains statistics for expressions based on index keys, and not for expressions on non-indexed fields.
====

[#availability]
== Availability

AUS is only available on query nodes running version 8.0 and later.

* You can enable AUS in a cluster that has been fully migrated to 8.0, or in a cluster that includes both 7.6.x and 8.0 query nodes. 
In such mixed clusters, the 7.6.x query nodes will not perform any AUS tasks.   

* For clusters migrating from pre-7.6.x versions (to a configuration described above), the AUS task can only be enabled once the automatic migration of optimizer statistics to the `_query` collection in the `_system` scope of the buckets has been completed. 

== How AUS Works

AUS is an opt-in feature. 
You must explicitly enable it and configure a schedule for when it should run. 
This allows you to align the AUS task with your cluster's workloads and run it at a time that minimizes the impact on performance.

An AUS task consists of two phases: 

. **Evaluation Phase**: 
In this phase, AUS evaluates whether the exisiting statistics are stale based on the <<expiration_policy, expiration policy>>.
For every index, AUS calculates the percentage of change to measure how much the data in the index has changed since the last update of the optimizer statistics for the index key expressions. 
If this percentage exceeds the configured `change_percentage` threshold, the statistics for the index's key expressions are marked as stale and require an update.

. **Update Phase**:
After the evaluation, this phase executes the necessary xref:n1ql:n1ql-language-reference/updatestatistics.adoc[] statements to refresh the statistics identified as stale. 
The AUS system ensures that the refreshed statistics maintains the same level of details as the original statistics.

//Once the Evaluation of a collection is completed, the Update phase will be executed.

//This phase will update the statistics flagged as stale in the previous phase by executing the appropriate UPDATE STATISTICS statements.

//The statistics update performed by AUS maintains the original resolution at which the statistic was collected.

Every query node in the cluster participates in the AUS task following the same configured schedule.
During the scheduled AUS window, each query node performs the following: 

* The query node selects the specific collections to perform AUS operations on. 
This ensures that no other query node processes the same collection during this window. 

* For each selected collection, the Evaluation and Update phases are executed on the statistics gathered on expressions based on fields within that collection.

* Once the AUS operation is complete for all statistics in all buckets, the query node schedules the next AUS run.

* If the scheduled window ends before the AUS task is complete, the task is aborted and the next AUS run is scheduled.

IMPORTANT: When AUS is enabled, the very first scheduled task run might update all existing optimizer statistics, regardless of the expiration policy evaluation.
This is because the index change information might not have been recorded prior to this initial run.

__Add a flowchart here to illustrate the AUS process__

[#expiration_policy]
=== Expiration Policy

AUS uses expiration policies to determine when statistics are outdated and require an update.
The policy is based on the percentage of changes to data within an index. 
It defines the threshold for how much data in an index must change before the statistics are considered outdated.

If the percentage of changed data (since the last time the statistic was collected) exceeds the defined threshold, AUS flags the statistic as stale. 
The subsequent AUS operation then updates this statistic.

== Enable and Schedule AUS

To start using AUS for your cluster, you will need to enable it and configure a schedule.

AUS stores its global configurations in the <<system_aus, system:aus>> catalog. 
You can enable AUS and set its schedule by modifying the relevant configurations within this catalog.

If you need more granluar control, you can use the <<system_aus_settings, system:aus_settings>> catalog to customize certain AUS configurations at the bucket, scope, and collection levels.

Once AUS is enabled and a schedule is set, every query node in the cluster participates in AUS.
Each query node gets its own AUS task, which performs AUS operations on that specific node.
You can find a record of recent AUS tasks across all query nodes in the `system:tasks_cache` catalog.
For more information, see <<view_aus_tasks, View AUS Tasks>>.

[#system_aus]
=== system:aus

The `system:aus` catalog contains a single document that holds all the global configurations of AUS.
You can update this document to modify the settings. 

[NOTE]
====
* Only SELECT and UPDATE DMLs are allowed on this keyspace.
* To execute SELECT on `system:aus`, you need the `query_system_catalog` role.
* To execute UPDATE on `system:aus`, you need the `query_manage_system_catalog` role. 
====

Each attribute in the document represents a particular global configuration. 
The following are the attribute names and the configurations they represent: 

[cols="1a,3a,1a"]
|===
| Name | Description | Schema

| **enable** +
__required__
| Indicates whether AUS is enabled for the cluster or not.

Set this attribute to `true` to enable AUS. 
If set to `true`, then the `schedule` attribute must be set.

*Default:* `false`

| Boolean

| **schedule** +
__optional__

| Defines the schedule for AUS operations.

This attribute is required only if `enable` is set to `true`.

| <<aus_schedule, Schedule>> object

| **change_percentage** +
__optional__

| The percentage of change to items within an index that must be exceeded for the statistics to be refereshed. 
This is the threshold for determining whether the statistics are stale or not.

The value must be an integer between `0` and `100`.

For example, a value of `30` means that if 30% or more of the items in an index have changed, the statistics for that index will be refreshed.

*Default:* `10`

| Interger 

| **all_buckets** + 
__required__

| Indicates whether AUS should be performed on all buckets or only those buckets whose metadata information is loaded on the query node.

*Default:* `false`

| Boolean

|===


[[aus_schedule]]
==== Schedule  
[cols="1a,4a,1a"]
|===
| Name | Description | Schema

| **start_time** +
__required__

| The start time of the AUS schedule in “HH:MM” format.
The `start_time` must be at least 30 minutes earlier than the `end_time`.

*Example:* `“01:30”`

| String

| **end_time** +
__required__

| The end time of the AUS schedule in “HH:MM” format. 

The `end_time` must be at least 30 minutes later than the `start_time`.

*Example:* `“05:30”`
| String

| **days** +
__required__

| An array of strings specifying the days on which the AUS schedule runs. 
Valid values include: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday. 

*Example:* `[“Saturday”, “Sunday”]`

| String array

| **timezone** +
__optional__

| The timezone that applies to the schedule's start and end times. 
The value must be a valid IANA timezone string.

*Default:* `“UTC”`

*Example:* `US/Pacific”`

| String

|===

When changing the global configurations, consider the following: 

* *Enabling AUS*: If AUS was previously disabled and is now enabled, the next AUS task will be scheduled immediately.
* *Rescheduling AUS*: Currently scheduled AUS task will be canceled, and a new AUS task will be scheduled according to the updated schedule.
Running AUS tasks will not be canceled.
* *Other Settings*: If other global settings such as `all_buckets` or `change_percentage` are modified, the new values will be applied during the next scheduled AUS run.

==== Example
====
Using the UPDATE statement to enable AUS and set a schedule with some customizations:

.Query
[source,sqlpp]
----
UPDATE system:aus SET enable = true, change_percentage = 20,
schedule = { "start_time": "01:30", 
             "end_time": "04:30", 
             "timezone": "Asia/Calcutta", 
             "days": ["Monday", "Friday"] 
        };
----
====

[#system_aus_settings]
=== system:aus_settings

The `system:aus_settings` catalog stores granular configuration settings for AUS. 
These settings can be applied at the bucket, scope, and collection levels.

By default, this catalog has no documents, and the AUS settings for all keyspaces inherit the configurations defined at the global level. 
In other words, unless you explicitly configure AUS for a specific keyspace, it will use the global AUS settings.

To customize AUS for a specific keyspace, you must insert a settings document into the `system:aus_settings` catalog.
The document ID of a document in this keyspace must be the full path of the bucket, scope, and collection. 

Each attribute in the document represents a particular granular configuration. 
The following are the attribute names and the configurations they represent: 

[cols="1a,4a,1a"]
|===
| Name | Description | Schema

| **enable** +
__optional__
| Indicates whether AUS is enabled for the bucket, scope, collection. +
Set it to `false` to explicitly disable AUS. 

AUS settings are hierarchical and follow the order: cluster > bucket > scope > collection. +
If AUS is disabled at higher level, it cannot be enabled at a more granular level. 
However, if AUS is enabled at a higher level, it can be disabled at a more granular level.

For example,
--
* If AUS is disabled for a bucket, it is automatically disabled for all scopes and collections within it.  
The setting cannot be overridden at the scope or collection level.
* If AUS is enabled for a bucket, it can be overridden at the scope and collection level.
--

| Boolean

| **change_percentage** +
__optional__

| The percentage of change to items within an index that must be exceeded for the statistics to be refereshed. 

The value must be an integer between `0` and `100`.

If set at a bucket level, this value applies to all scopes and collections within the bucket, unless overridden at a lower level. 

If set at a scope level, this value applies to all collections within the scope, unless overridden at a lower level.

*Example:* `30`

| Integer

| **update_statistics_timeout** +
__optional__

| The timeout period for the UPDATE STATISTICS command. 
It is a number representing a duration in seconds.

If the command does not complete within this duration, it times out. 
If omitted, a default timeout value is calculated based on the number of samples used.

If set for a keyspace, this timeout applies to every UPDATE STATISTICS statement that AUS executes for that keyspace. 

If set at a bucket level, this timeout applies to all scopes and collections withing the bucket, unless a different value is set at a lower level.

If set at a scope level, this timeout applies to all collections within the scope, unless a different value is set at a collection level.

| Number

|===

[NOTE]
====
* All SQL++ DMLs are allowed on this keyspace. 
* To execute SELECT on `system:aus_settings`, you need the `query_system_catalog` role.
* To execute UPDATE, DELETE, INSERT, and UPSERT on `system:aus_settings`, you need the `query_manage_system_catalog` role.
====

==== Example
==== 
Query to add a scope level setting that applies to all collections within the scope. 

.Query
[source,sqlpp]
----
INSERT INTO system:aus_settings ( KEY, VALUE ) 
    VALUES ({ "default:bucket1.scope1", {"change_percentage": 20 } )
----
====

== Monitor AUS Tasks

The `system:tasks_cache` catalog stores information about all recent tasks executed in a cluster, including the AUS tasks.
For each AUS task, every involved query node maintains an entry within this catalog.
// You can view the recent AUS tasks, their status, and other details by querying this catalog.
AUS task entries can be specifically identified by the `class` field, which is set to `auto_update_statistics`.

=== View Recent AUS Tasks

To view all recent AUS tasks, use the following query:

[source,sqlpp]
----
SELECT * FROM system:tasks_cache WHERE class = "auto_update_statistics";
----

This query returns all AUS entries regardless of their state (scheduled, running, completed, etc.). 
To get the details of completed tasks, see <<view_completed_aus_tasks, View Completed AUS Tasks>>.

=== Find Scheduled AUS Tasks

To identify AUS tasks that are scheduled to run, you can filter the entries using the `state` attribute.

[source,sqlpp]
----
SELECT * FROM system:tasks_cache WHERE class = "auto_update_statistics" AND state = "scheduled";
----

=== View AUS Tasks on a Particular Node
 
To view recent AUS tasks on a particular node, filter by the `node` attribute. 

[source,sqlpp]
----
SELECT * FROM system:tasks_cache WHERE class = "auto_update_statistics" 
         AND state = "scheduled" 
         AND node = "127.0.0.1:8091"; // Replace with the actual node address
----

[#view_completed_aus_tasks]
=== View Completed AUS Tasks

The entries for completed AUS tasks have information specifically about tasks that have finished execution.
These entries include details such as the task ID, start time, end time, which keyspaces had their statistics updated, and whether any errors occurred during the task execution.

==== Example
====
Sample task entry for a successful AUS task on a query node:

[source,sqlpp]
----
{
    "tasks_cache": {
        "class": "auto_update_statistics",
        "delay": "21.707164s",
        "id": "4b90bb39-ca1b-55f1-84f0-4d3137c88bf8",
        "name": "bc1ab6e9-9f33-4a8f-86ad-40d74c50af5f",
        "queryContext": "",
        "results": {
            "configuration": {
                "all_buckets": true,
                "change_percentage": 20,
                "end_time": "2024-11-19 20:00:00 +0530 IST",
                "internal_version": 1,
                "start_time": "2024-11-19 19:16:00 +0530 IST"
            },

            "keyspaces_updated": [
                "default:bucket1.scope1.customers"
            ]
        },

        "startTime": "2024-11-19T19:16:00.001+05:30",
        "state": "completed",
        "stopTime": "2024-11-19T19:16:03.154+05:30",
        "subClass": "",
        "submitTime": "2024-11-19T19:15:38.292+05:30"
    }
}
----
====

For more information about `system:tasks_cache` and its attributes, see xref:n1ql:n1ql-intro/sysinfo.adoc#sys-tasks-cache[Monitor Cached Tasks].
In addition to the attributes listed there, the AUS task entries also include the following attributes:

* `keyspaces_updated`: A list of keyspaces that had their statistics updated during the AUS task execution.
* `configuration`: The configuration with which the AUS task was executed.

== Cancel AUS Tasks

You can cancel a running AUS task by deleting its entry from the `system:tasks_cache` catalog.

To cancel all running AUS tasks, use the following DELETE statement:

[source,sqlpp]
----
DELETE FROM system:tasks_cache WHERE class = "auto_update_statistics" AND state = "running";
----

CAUTION: Use appropriate filters in the WHERE clause to be selective of which tasks to cancel or delete.
Remember to add appropriate filters in the DELETE statement so that the statement affects the intended task entry. Otherwise inadvertently other tasks can get cancelled or the task history gets deleted.


To cancel a running AUS task on a specific node, include the node's address in the WHERE clause:

[source,sqlpp]
----
DELETE FROM system:tasks_cache WHERE class = "auto_update_statistics" 
       AND state = "running" 
       AND node = "127.0.0.1:8091"; // Replace with the actual node address
----

When you delete an AUS task that is in a `scheduled` or `running` state, the task is cancelled. 


 and the next AUS task is automatically scheduled.
When the DELETE statement affects an AUS task entry in the “scheduled” or “running” state, the scheduled/ running task is cancelled and the next AUS task is automatically scheduled.



== Manage AUS Load

When the AUS task is executing, it can cause an increased load on the Query node. 
This is because of all the activity of evaluating the statistics and executing statistics refresh. 
That is why it is important that the schedule for AUS is set to best suit the workloads of the cluster.

Additionally, an attempt is made to ensure that during the scheduled window, the AUS task is not started when the load of the Query node is too high. 
If the load is too high, the task is not started and the next AUS task is scheduled.



