= Auto Update Statistics
:description: Auto Update Statistics (AUS) is a solution designed to keep the optimizer statistics up to date. 

[abstract]
{description}

== Overview

Auto Update Statistics (AUS) is a feature that helps keep the optimizer statistics up to date by automatically identifying and refreshing outdated statistics.

Optimizer statistics are used by the xref:n1ql:n1ql-language-reference/cost-based-optimizer.adoc[Cost Based Optimizer] to generate optimal query plans.
These statistics are created when you run the xref:n1ql:n1ql-language-reference/updatestatistics.adoc[] statement or build an index (available from 7.6.0 onwards). 
However, as data changes over time, the statistics can become stale, leading to sub-optimal query plans and reduced query performance.

AUS addresses this challenge by running a scheduled task on the query nodes that regularly checks for outdated statistics using expiration policies and refreshes them by executing xref:n1ql:n1ql-language-reference/updatestatistics.adoc[]. 
// This way, AUS ensures that the optimizer statistics are always up to date and the CBO has the current information. 

[NOTE]
====
* AUS is only available in Couchbase Server 8.0 and later. For more information, see <<availability, Availability>>.
* AUS only updates existing statistics; it does not create new ones.
* AUS primarily maintains statistics for expressions based on index keys, and not for expressions on non-indexed fields.
====

[#availability]
== Availability

AUS is only available on query nodes running version 8.0 and later.

* You can enable AUS in a cluster that has been fully migrated to 8.0, or in a cluster that includes both 7.6.x and 8.0 query nodes. 
In such mixed clusters, the 7.6.x query nodes will not perform any AUS tasks.   

* For clusters migrating from pre-7.6.x versions (to a configuration described above), the AUS task can only be enabled once the automatic migration of optimizer statistics to the `_query` collection in the `_system` scope of the buckets has been completed. 

== How AUS Works

AUS is an opt-in feature. 
You must explicitly enable it and configure a schedule for when it should run. 
This allows you to align the AUS task with your cluster's workloads and run it at a time that minimizes the impact on performance.

An AUS task consists of two phases: 

. **Evaluation Phase**: 
In this phase, AUS evaluates whether the exisiting statistics are stale based on the <<expiration_policy, expiration policy>>.
For every index, AUS calculates the percentage of change to measure how much the data in the index has changed since the last update of the optimizer statistics for the index key expressions. 
If this percentage exceeds the configured `change_percentage` threshold, the statistics for the index's key expressions are marked as stale and require an update.

. **Update Phase**:
After the evaluation, this phase executes the necessary xref:n1ql:n1ql-language-reference/updatestatistics.adoc[] statements to refresh the statistics identified as stale. 
The AUS system ensures that the refreshed statistics maintains the same level of details as the original statistics.

//Once the Evaluation of a collection is completed, the Update phase will be executed.

//This phase will update the statistics flagged as stale in the previous phase by executing the appropriate UPDATE STATISTICS statements.

//The statistics update performed by AUS maintains the original resolution at which the statistic was collected.

Every query node in the cluster participates in the AUS task following the same configured schedule.
During the scheduled AUS window, each query node performs the following: 

* The query node selects the specific collections to perform AUS operations on. 
This ensures that no other query node processes the same collection during this window. 

* For each selected collection, the Evaluation and Update phases are executed on the statistics gathered on expressions based on fields within that collection.

* Once the AUS operation is complete for all statistics in all buckets, the query node schedules the next AUS run.

* If the scheduled window ends before the AUS task is complete, the task is aborted and the next AUS run is scheduled.

IMPORTANT: When AUS is enabled, the very first scheduled task run might update all existing optimizer statistics, regardless of the expiration policy evaluation.
This is because the index change information might not have been recorded prior to this initial run.

__Add a flowchart here to illustrate the AUS process__

[#expiration_policy]
=== Expiration Policy

AUS uses expiration policies to determine when statistics are outdated and require an update.
The policy is based on the percentage of changes to data within an index. 
It defines the threshold for how much data in an index must change before the statistics are considered outdated.

If the percentage of changed data (since the last time the statistic was collected) exceeds the defined threshold, AUS flags the statistic as stale. 
The subsequent AUS operation then updates this statistic.

== Enable and Schedule AUS

To use AUS for your cluster, you must first enable it and configure a schedule.

AUS stores its global configurations in the `system:aus` catalog. 
You can enable AUS and set its schedule by modifying the appropraite configurations within this catalog.

=== system:aus

The `system:aus` catalog contains a single document that holds all the global configurations of AUS.
You can update this document to modify the settings. 

[NOTE]
====
* Only SELECT and UPDATE DMLs are allowed on this keyspace.
* To execute SELECT on `system:aus`, you need the `query_system_catalog` role.
* To execute UPDATE on `system:aus`, you need the `query_manage_system_catalog` role. 
====

Each attribute in the document represents a particular global configuration. 
The following are the attribute names and the configurations they represent: 

[cols="1a,3a,1a"]
|===
| Name | Description | Schema

| **enable** +
__required__
| Indicates whether AUS is enabled for the cluster or not.

Set this attribute to `true` to enable AUS. 
If set to `true`, then the `schedule` attribute must be set.

*Default:* `false`

| Boolean

| **schedule** +
__optional__

| Defines the schedule for AUS operations.

This attribute is required only if `enable` is set to `true`.

| <<aus_schedule, Schedule>> object

| **change_percentage** +
__optional__

| The percentage of change to items within an index that must be exceeded for the statistics to be refereshed. 
This is the threshold for determining whether the statistics are stale or not.

The value must be an integer between `0` and `100`.

For example, a value of `30` means that if 30% or more of the items in an index have changed, the statistics for that index will be refreshed.

*Default:* `10`

| Interger 

| **all_buckets** + 
__required__

| Indicates whether AUS should be performed on all buckets or only those buckets whose metadata information is loaded on the query node.

*Default:* `false`

| Boolean

|===


[[aus_schedule]]
==== Schedule  
[cols="1a,4a,1a"]
|===
| Name | Description | Schema

| **start_time** +
__required__

| The start time of the AUS schedule in “HH:MM” format.
The `start_time` must be at least 30 minutes earlier than the `end_time`.

*Example:* `“01:30”`

| String

| **end_time** +
__required__

| The end time of the AUS schedule in “HH:MM” format. 

The `end_time` must be at least 30 minutes later than the `start_time`.

*Example:* `“05:30”`
| String

| **days** +
__required__

| An array of strings specifying the days on which the AUS schedule runs. 
Valid values include: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday. 

*Example:* `[“Saturday”, “Sunday”]`

| String array

| **timezone** +
__optional__

| The timezone that applies to the schedule's start and end times. 
The value must be a valid IANA timezone string.

*Default:* `“UTC”`

*Example:* `US/Pacific”`

| String

|===

When changing the global configurations, consider the following: 

* *Enabling AUS*: If AUS was previously not enabled, and now enabled, then the next AUS task is scheduled.
* *Re-scheduling AUS*: Cancel any scheduled AUS task. Schedule a new AUS task accordingly. No running AUS tasks will be cancelled. 
* *Other Setting Changes*: If the other global settings i.e. all_buckets, change_percentage is changed, From the next scheduled AUS run, the new values of the settings will be used.

==== Example
====
Using UPDATE Statement to enable AUS and set a schedule with some customizations:

.Query
[source,sqlpp]
----
UPDATE system:aus SET enable = true, change_percentage = 20,
schedule = { "start_time": "01:30", 
             "end_time": "04:30", 
             "timezone": "Asia/Calcutta", 
             "days": ["Monday", "Friday"] 
        };
----
====

=== system:aus_settings

The system also provides mechanisms to customize certain AUS configurations at the bucket, scope and collection level. The system:aus_settings maintains these more granular configurations.

The document id of a document in this keyspace must be the full path of the bucket/ scope/ collection name. 

All SQL++ DMLs are allowed on this keyspace.

NOTE: To execute SELECT on system:aus_settings, the query_system_catalog is required.
To execute UPDATE, DELETE, INSERT, UPSERT  on system:aus_settings, the query_manage_system_catalog is required.

By default, this keyspace has no documents. The configurations of AUS for all keyspaces by default are what is set at the global level.

A settings document must be explicitly inserted to customize AUS for the keyspace.

In the settings document, each attribute represents a particular granular configuration. The attribute names and the corresponding configuration that they represent are as follows:

[cols="1a,3a,1a"]
|===
| Name | Description | Schema

| **enable** +
__optional__
| Whether AUS is enabled for the bucket/scope/collection or not.
Set to “false” to explicitly disable. 

If AUS is disabled at the global/ cluster level, then it cannot be enabled at the bucket/scope/collection level.
If AUS is disabled at a higher level, it cannot be overridden at a more granular level.
But, if AUS is enabled at a higher level, it can be overridden at a more granular level.

Example to illustrate this:

If AUS is disabled for a bucket - it is disabled for all scopes and collections within it.  It cannot be overridden at the scope or collection level.
If AUS is enabled for a bucket - it can be overridden at the scope and collection level.

| Boolean

| **change_percentage** +
__optional__

| The percentage of changes to the items in an index that must be exceeded to trigger a   statistic to be refreshed.
Integer between 0 and 100.

If set at a bucket-level, this is the change percentage value considered for all scopes and collections within the bucket, unless overridden at a lower level.
If set at a scope-level, this is the change percentage value considered for all collections within the scope unless overridden at a lower level.

*Example:* `30`

| Integer

| **update_statistics_timeout** +
__optional__

| A number representing a duration in seconds. 
The command times out when this timeout period is reached. If omitted, a default timeout value is calculated based on the number of samples used.

If set for a keyspace, this would be set as the timeout for every UPDATE STATISTICS statement executed by AUS for that keyspace. 

If set at a bucket-level, this is the update_statistics_timeout value considered for all scopes and collections within the bucket, unless overridden at a lower level.

If set at a scope-level, this is the update_statistics_timeout value considered for all collections within the scope unless overridden at a lower level.

| Number

|===

==== Example
==== 
A sample query to add a scope-level setting. These settings would apply to all collections within the scope unless overridden at a collection level. particular collection would look like this:

.Query
[source,sqlpp]
----
INSERT INTO system:aus_settings ( KEY, VALUE ) 
    VALUES ({ "default:bucket1.scope1", {"change_percentage": 20 } )
----
====

== Scheduling AUS Tasks
When AUS is enabled and a schedule set, every Query node in the cluster participates in AUS. As a result, each Query node will have its own AUS task assigned, and this task will perform AUS operations on that specific node. 

The system:tasks_cache catalog keeps a record of recent tasks including the AUS tasks across all Query nodes.

== Viewing AUS Tasks
The system:tasks_cache catalog maintains the list of recent tasks. For every AUS task, each Query node will have an entry in the system:tasks_cache. View all recent AUS tasks by querying the system:tasks_cache keyspace.

The AUS task entries have the “class” field set to “auto_update_statistics”. 

View all recent AUS tasks:
[source,sqlpp]
----
SELECT * FROM system:tasks_cache WHERE class = "auto_update_statistics";
----
 
To find the next scheduled AUS tasks:
[source,sqlpp]
----
SELECT * FROM system:tasks_cache WHERE class = "auto_update_statistics" AND state = "scheduled";
----
 
To view the recent AUS tasks on a particular node, filter by the ”node” attribute:
[source,sqlpp]
----
SELECT * FROM system:tasks_cache WHERE class = "auto_update_statistics" AND state = "scheduled" and node = "127.0.0.1:8091";
----

The entries for completed AUS tasks will have information about the AUS task, which keyspaces had their statistics updated, if any errors occurred, etc.

=== Example
====
Sample task entry for a successful AUS task on a query node:

.Query
[source,sqlpp]
----
{
    "tasks_cache": {
        "class": "auto_update_statistics",
        "delay": "21.707164s",
        "id": "4b90bb39-ca1b-55f1-84f0-4d3137c88bf8",
        "name": "bc1ab6e9-9f33-4a8f-86ad-40d74c50af5f",
        "queryContext": "",
        "results": {
            "configuration": {
                "all_buckets": true,
                "change_percentage": 20,
                "end_time": "2024-11-19 20:00:00 +0530 IST",
                "internal_version": 1,
                "start_time": "2024-11-19 19:16:00 +0530 IST"
            },

            "keyspaces_updated": [
                "default:bucket1.scope1.customers"
            ]
        },

        "startTime": "2024-11-19T19:16:00.001+05:30",
        "state": "completed",
        "stopTime": "2024-11-19T19:16:03.154+05:30",
        "subClass": "",
        "submitTime": "2024-11-19T19:15:38.292+05:30"
    }
}
----
====

Attributes: --> Should this be added to the system:tasks_cache doc? 
* keyspaces_updated: A list of keyspaces that had statistics that had to be updated.
* configuration: the task configuration with which this task was executed.

For more information about system:tasks_cache and its attributes, see xref:n1ql:n1ql-intro/sysinfo.adoc#sys-tasks-cache[].

== Aborting a Running AUS Task
To cancel the execution of a running AUS task, execute an appropriate DELETE statement against the system:tasks_cache.

To cancel all running AUS tasks:

[source,sqlpp]
----
DELETE FROM system:tasks_cache WHERE class = "auto_update_statistics" AND state = "running";
----
 
Use appropriate filters in the WHERE clause to be selective of which tasks to cancel or delete. To cancel the running AUS task only only on a particular node:

[source,sqlpp]
----
DELETE FROM system:tasks_cache WHERE class = "auto_update_statistics" AND state = "running" AND node = "127.0.0.1:8091";
----

When the DELETE statement affects an AUS task entry in the “scheduled” or “running” state, the scheduled/ running task is cancelled and the next AUS task is automatically scheduled.

Remember to add appropriate filters in the DELETE statement so that the statement affects the intended task entry. Otherwise inadvertently other tasks can get cancelled or the task history gets deleted.

== Managing AUS Load

When the AUS task is executing, it can cause an increased load on the Query node. 
This is because of all the activity of evaluating the statistics and executing statistics refresh. 
That is why it is important that the schedule for AUS is set to best suit the workloads of the cluster.

Additionally, an attempt is made to ensure that during the scheduled window, the AUS task is not started when the load of the Query node is too high. 
If the load is too high, the task is not started and the next AUS task is scheduled.



