= Comparison Functions
:description: Comparison functions determine the greatest or least value from a set of values.
:page-topic-type: reference

[abstract]
{description}

== GREATEST 

=== Description

Determines the largest non-NULL, non-MISSING value from a list of expressions.

The function requires at least two expressions and ignores `NULL` and `MISSING` values when evaluating the greatest value.

=== Syntax

[subs=normal]
....
GREATEST (expression1, expression2, ...)
....

==== Arguments

expression1, expression2, ...::
The expressions to compare.
You must specify at least two expressions.

=== Return Value

The function returns:

* The largest value among the provided expressions. 
* `NULL` if all expressions are `NULL` or `MISSING`.

=== Example

.Find the highest rating across all review categories for a hotel
====

.Query
[source,sqlpp]
----
SELECT GREATEST(
    reviews[0].ratings.Service,
    reviews[0].ratings.Cleanliness,
    reviews[0].ratings.Overall,
    reviews[0].ratings.Location,
    reviews[0].ratings.Rooms
) AS highest_rating
FROM `travel-sample`.`inventory`.hotel
WHERE id = 10025;
----

.Result
[source,json]
----
[
  {
    "highest_rating": 5
  }
]
----
====

.Find the greatest value among different types
====

.Query
[source,sqlpp]
----
SELECT GREATEST(42, "Hotel", "2025-12-01T00:00:00Z") AS greatest_value;
----

.Result
[source,json]
----
[
  {
    "greatest_value": "Hotel"
  }
]
----
The function returns `"Hotel"` because strings have a higher precedence than numbers and dates.
====

== LEAST

=== Description

Determines the smallest non-NULL, non-MISSING value from a list of expressions.

The function requires at least two expressions and ignores `NULL` and `MISSING` values when evaluating the least value.

=== Syntax

[subs=normal]
....
LEAST (expression1, expression2, ...)
....

==== Arguments

expression1, expression2, ...::
The expressions to compare.
You must specify at least two expressions.

=== Return Value

The function returns:

* The smallest value among the provided expressions.
* `NULL` if all expressions are `NULL` or `MISSING`.

=== Example

.Find the least rating across all review categories for a hotel
====

.Query
[source,sqlpp]
----
SELECT LEAST(
    reviews[0].ratings.Service,
    reviews[0].ratings.Cleanliness,
    reviews[0].ratings.Overall,
    reviews[0].ratings.Location,
    reviews[0].ratings.Rooms
) AS highest_rating
FROM `travel-sample`.`inventory`.hotel
WHERE id = 10025;
----

.Result
[source,json]
----
[
  {
    "lowest_rating": 3
  }
]
----
====

.Find the least value among different types
====

.Query
[source,sqlpp]
----
SELECT LEAST(42, "Hotel", "2025-12-01T00:00:00Z") AS least_value;
----

.Result
[source,json]
----
[
  {
    "least_value": 42
  }
]
----
The function returns `42` because numbers have a lower precedence than strings and dates.
====

