= Conditional Functions for Numbers
:description: Conditional functions evaluate expressions to determine if the values and formulas meet the specified condition.
:page-topic-type: reference


[abstract]
{description}

== IFINF

=== Description

Returns the first non-missing, non-infinite number (Inf or -Inf) from a list of expressions. 
Inf is positive infinity, whereas -Inf is negative infinity.

If the function encounters a non-number input first, it returns NULL.

=== Syntax

[subs=normal]
....
IFINF(expression1, expression2, ...)
....

==== Arguments

expression1, expression2, ...::
A list of valid expressions to evaluate. 

=== Return Value

The function returns:

* The first non-MISSING, non-Inf number. 
* MISSING or NULL if a non-number input is encountered first.

=== Examples

.Find a non-infinite number from a list of numbers
====

.Query
[source,sqlpp]
----
SELECT IFINF(MISSING, Inf, -Inf, 42, 100) AS result
----
.Result
[source,json]
----
{
  "result": 42
}
----
====






IFINF(expression1, expression2, \...)

Returns first non-MISSING, non-Inf number.
Returns MISSING or NULL if a non-number input is encountered first.

IFNAN(expression1, expression2, \...)

Returns first non-MISSING, non-NaN number.
Returns MISSING or NULL if a non-number input is encountered first.

IFNANORINF(expression1, expression2, \...)

Returns first non-MISSING, non-Inf, or non-NaN number.
Returns MISSING or NULL if a non-number input is encountered first.

NANIF(expression1, expression2)

Returns NaN if expression1 = expression2, otherwise returns expression1.
Returns MISSING or NULL if either input is MISSING or NULL.

NEGINFIF(expression1, expression2)

Returns NegInf if expression1 = expression2, otherwise returns expression1.
Returns MISSING or NULL if either input is MISSING or NULL.

POSINFIF(expression1, expression2)

Returns PosInf if expression1 = expression2, otherwise returns expression1.
Returns MISSING or NULL if either input is MISSING or NULL.
