= Conditional Functions for Unknowns
:page-topic-type: reference
:example-caption!:
:description: Conditional functions evaluate expressions to determine if the values and formulas meet the specified condition.

{description}

[[decode,DECODE()]]
== DECODE

Compares an expression to one or more search values, and returns the corresponding result of the first match.

=== Syntax

....
DECODE(expression, search1, result1 [, search2, result2, ...] [, default])
....

The function evaluates the expression against a sequence of search-result pairs in linear order.

* The function works by comparing the expression to the first search value.
* If they are equal, the function returns the corresponding result.
* If they are not equal, the function ignores that result and moves to the next search argument. 
* This process repeats until a match is found or all pairs are exhausted.
* If no match is found, the function returns the value of the default argument if it is specified.
* If no default argument is specified and no matches occur, the function returns NULL.

[NOTE]
====
The function determines whether a default value is present based on the total number of arguments.

* Even number of arguments: The last argument is the default.
* Odd number of arguments: Every argument after the expression is part of a search-result pair, and there is no default.
====

==== Arguments

expression:: [Required] Any valid expression to compare.
search1, search2, ...:: [Required] The value to compare against the expression.
At least one search value is required, and each search value must have a corresponding result value.
result1, result2, ...:: [Required] The value to return if the corresponding search value matches the expression.
At least one result value is required, and each result value must have a corresponding search value.
default:: [Optional] The value to return if no search matches the expression. 


=== Return Value

Returns the result for the first search value that matches the expression.

If there are no matches:

* Returns `default` if it is specified.
* Returns `NULL` if `default` is not specified.

=== Example

====
Find the UTC offset of all airports in the United States whose altitude is greater than 1000:

[source,sqlpp]
----
SELECT a.airportname AS Airport,
DECODE(a.tz, "Pacific/Honolulu", "-10:00",
             "America/Anchorage", "-09:00",
             "America/Los_Angeles", "-08:00",
             "America/Denver", "-07:00",
             "America/Chicago", "-06:00",
             "America/New_York", "-05:00", a.tz) AS UTCOffset
FROM airport a
WHERE a.country = "United States" AND a.geo.alt > 1000
LIMIT 5;
----

.Results
[source,json]
----
[
  {
    "Airport": "Indian Mountain Lrrs",
    "UTCOffset": "-09:00"
  },
  {
    "Airport": "Sparrevohn Lrrs",
    "UTCOffset": "-09:00"
  },
  {
    "Airport": "Bicycle Lake Aaf",
    "UTCOffset": "-08:00"
  },
  {
    "Airport": "Twentynine Palms Eaf",
    "UTCOffset": "-0:800"
  },
  {
    "Airport": "Grants Milan Muni",
    "UTCOffset": "-07:00"
  }
]
----
====

[[if_missing,IFMISSING()]]
== IFMISSING

Returns the first value in a list that is not MISSING. 
If all values are MISSING, the function returns NULL.

=== Syntax

....
IFMISSING(expression1, expression2, ...)
....

==== Arguments

expression1, expression2, ...:: [Required] Two or more valid expressions.

=== Return Value

Returns the first non-MISSING value.

Returns NULL if all values are MISSING.

=== Example
====
[source,sqlpp]
----
SELECT IFMISSING(101, 102, "abc"), 
       IFMISSING(MISSING, 101, 102),
       IFMISSING(NULL, MISSING, 101, "abc"), 
       IFMISSING(MISSING, MISSING);
----

.Results
[source,json]
----
[
  {
    "$1": 101,
    "$2": 101,
    "$3": null,
    "$4": null
  }
]
----
====

[[if_missing_or_null,IFMISSINGORNULL()]]
== IFMISSINGORNULL

Returns the first value in a list that is neither MISSING nor NULL.

This function has an alias `COALESCE`.

=== Syntax

....
IFMISSINGORNULL(expression1, expression2, ...)
....

==== Arguments

expression1, expression2, ...:: [Required] Two or more valid expressions.

=== Return Value

Returns first non-NULL, non-MISSING value.

Returns NULL if all values are MISSING or NULL.

=== Example
====
[source,sqlpp]
----
SELECT IFMISSINGORNULL(101, 102, "abc"),
       IFMISSINGORNULL(MISSING, 101, 102),
       IFMISSINGORNULL(NULL, MISSING, 101, "abc"),
       IFMISSINGORNULL(NULL, NULL),
       IFMISSINGORNULL(MISSING, MISSING);
----

.Results
[source,json]
----
[
  {
    "$1": 101,
    "$2": 101,
    "$3": 101,
    "$4": null,
    "$5": null
  }
]
----
====

[[if_null,IFNULL()]]
== IFNULL

Returns the first value in a list that is not NULL.
Returns NULL if all values are NULL.

=== Syntax

....
IFNULL(expression1, expression2, ...)
....

==== Arguments

expression1, expression2, ...:: [Required] Two or more valid expressions.

=== Return Value

Returns the first non-NULL value.

Returns NULL if all values are NULL.

=== Example
====
[source,sqlpp]
----
SELECT IFNULL(101, 102, "abc"), 
       IFNULL(NULL, 101, 102),
       IFNULL(NULL, NULL);
----

.Results
[source,json]
----
[
  {
    "$1": 101,
    "$2": 101,
    "$3": null
  }
]
----
====

[[missing_if,MISSINGIF()]]
== MISSINGIF

Compares two expressions and returns MISSING if they are equal.
If the expressions are not equal, the function returns the first expression.

=== Syntax

....
MISSINGIF(expression1, expression2)
....

==== Arguments

expression1, expression2:: [Required] Two valid expressions to compare.

=== Return Value

Returns one of the following:

* MISSING if `expression1` = `expression2`.
* `expression1` if `expression1` != `expression2`.
* MISSING if either input is MISSING or if both inputs are MISSING.
* NULL if either input is NULL or if both inputs are NULL.

=== Example
====
[source,sqlpp]
----
SELECT MISSINGIF("abc", 101),
       MISSINGIF("abc", "abc"),
       MISSINGIF(MISSING, "abc");
----

.Results
[source,json]
----
[
  {
    "$1": "abc"
  }
]
----
====

[[null_if,NULLIF()]]
== NULLIF

Compares two expressions and returns NULL if they are equal.
If the expressions are not equal, the function returns the first expression.

=== Syntax

....
NULLIF(expression1, expression2)
....

=== Arguments

expression1, expression2:: [Required] Two valid expressions to compare.

=== Return Value

Returns one of the following:

* NULL if `expression1` = `expression2`.
* `expression1` if `expression1` != `expression2`.
* MISSING if either input is MISSING or if both inputs are MISSING.
* NULL if either input is NULL or if both inputs are NULL.

=== Example
====
[source,sqlpp]
----
SELECT NULLIF("abc", 123) AS Different,
       NULLIF("abc", "abc") AS Same;
----

.Results
[source,json]
----
[
  {
    "Different": "abc",
    "Same": null
  }
]
----
====

[[nvl,NVL()]]
== NVL

Returns the first value in a list that is not MISSING or NULL.
Returns NULL if all values are MISSING or NULL.

=== Syntax

....
NVL(expression1, expression2)
....

==== Arguments

expression1, expression2:: [Required] Two valid expressions to compare.

=== Return Value

Returns one of the following:

* `expression1` if `expression1` is not MISSING or NULL.
* `expression2` if `expression1` is MISSING or NULL and `expression2` is not MISSING or NULL.
* NULL if both `expression1` and `expression2` are MISSING or NULL.

=== Example

include::ROOT:partial$query-context.adoc[tag=section]

====
[source,sqlpp]
----
SELECT name as Name, NVL(iata, "n/a") as IATA
FROM airline 
LIMIT 5;
----

.Results
[source,json]
----
[
  {
    "IATA": "Q5",
    "Name": "40-Mile Air"
  },
  {
    "IATA": "TQ",
    "Name": "Texas Wings"
  },
  {
    "IATA": "A1",
    "Name": "Atifly"
  },
  {
    "IATA": "n/a",
    "Name": "Jc royal.britannica"
  },
  {
    "IATA": "ZQ",
    "Name": "Locair"
  }
]
----
====

[[nvl2,NVL2()]]
== NVL2

Returns `value1` if `expression` is not MISSING or NULL, and returns `value2` if `expression` is MISSING or NULL.

=== Syntax

....
NVL2(expression, value1, value2)
....

==== Arguments

expression:: [Required] Any valid expression.
value1, value2:: [Required] Values to return based on whether `expression` is MISSING or NULL.

=== Return Value

Returns `value1` if `expression` is not MISSING or NULL.
Returns `value2` if `expression` is MISSING or NULL.

=== Example

include::ROOT:partial$query-context.adoc[tag=section]

====
[source,sqlpp]
----
SELECT name as Name, NVL2(directions, "Yes", "No") as DirectionsAvailable
FROM hotel
LIMIT 5;
----

.Results
[source,json]
----
[
  {
    "DirectionsAvailable": "No",
    "Name": "Medway Youth Hostel"
  },
  {
    "DirectionsAvailable": "No",
    "Name": "The Balmoral Guesthouse"
  },
  {
    "DirectionsAvailable": "Yes",
    "Name": "The Robins"
  },
  {
    "DirectionsAvailable": "Yes",
    "Name": "Le Clos Fleuri"
  },
  {
    "DirectionsAvailable": "Yes",
    "Name": "Glasgow Grand Central"
  }
]
----
====

== Aliases

* `COALESCE` is an alias for `IFMISSINGORNULL`.
