= Conditional Functions for Unknowns
:page-topic-type: reference
:example-caption!:
:description: Conditional functions evaluate expressions and return a value based on conditional logic.

{description}

[[decode,DECODE()]]
== DECODE

Compares an expression to one or more search values and returns the corresponding result of the first match.

The function evaluates the expression against a sequence of search-result pairs in linear order.

* The function works by comparing the expression to the first search value.
* If they are equal, the function returns the corresponding result.
* If they are not equal, the function ignores that result and moves to the next search argument. 
* This process repeats until a match is found or all pairs are exhausted.
* If no match is found, the function returns the value of the default argument if it is specified.
* If no default argument is specified and no matches occur, the function returns NULL.


=== Syntax

....
DECODE(expression, search1, result1 [, search2, result2, ...] [, default])
....

[NOTE]
====
The function determines whether a default value is present based on the total number of arguments.

* Even number of arguments: The last argument is the default.
* Odd number of arguments: Every argument after the expression is part of a search-result pair, and there is no default.
====

==== Arguments

expression:: [Required] Any valid expression to compare.
search1, search2, ...:: [Required] The value to compare against the expression.
At least one search value is required, and each search value must have a corresponding result value.
result1, result2, ...:: [Required] The value to return if the corresponding search value matches the expression.
At least one result value is required, and each result value must have a corresponding search value.
default:: [Optional] The value to return if no search matches the expression. 


=== Return Value

Returns one of the following:

* The result for the first search value that matches the expression.
* `default` if no match is found and `default` is specified.
* `NULL` if no match is found and `default` is not specified.

=== Example

====
.Query
[source,sqlpp]
----
SELECT flight, 
DECODE(flight, 101, "London", 
         202, "Paris", 
         303, "Tokyo", 
         404, "New York", 
         "Unknown Destination")
AS Destination
FROM [
  {"flight": 101},
  {"flight": 303},
  {"flight": 999},
  {"flight": null}] 
AS flights;
----

.Result
[source,json]
----
[
  {
    "flight": 101,
    "Destination": "London"
  },
  {
    "flight": 303,
    "Destination": "Tokyo"
  },
  {
    "flight": 999,
    "Destination": "Unknown Destination"
  },
  {
    "flight": null,
    "Destination": "Unknown Destination"
  }
]
----
====

[[if_missing,IFMISSING()]]
== IFMISSING

Returns the first value in a list that is not `MISSING`.

=== Syntax

....
IFMISSING(expression1, expression2, ...)
....

==== Arguments

expression1, expression2, ...:: [Required] Two or more valid expressions.

=== Return Value

Returns one of the following:

* The first non-MISSING value.
* `NULL` if all values are MISSING.

=== Example
====
.Query
[source,sqlpp]
----
SELECT IFMISSING(101, 102, "abc"), 
       IFMISSING(MISSING, 101, 102),
       IFMISSING(NULL, MISSING, 101, "abc"), 
       IFMISSING(MISSING, MISSING);
----

.Result
[source,json]
----
[
  {
    "$1": 101,
    "$2": 101,
    "$3": null,
    "$4": null
  }
]
----
====

[[if_missing_or_null,IFMISSINGORNULL()]]
== IFMISSINGORNULL

Returns the first value in a list that is neither `MISSING` nor `NULL`.

This function has an alias `COALESCE`.

=== Syntax

....
IFMISSINGORNULL(expression1, expression2, ...)
....

==== Arguments

expression1, expression2, ...:: [Required] Two or more valid expressions.

=== Return Value

Returns one of the following:

* The first non-NULL, non-MISSING value.
* `NULL` if all values are `MISSING` or `NULL`.

=== Example

====
.Query
[source,sqlpp]
----
SELECT IFMISSINGORNULL(101, 102, "abc"),
       IFMISSINGORNULL(MISSING, 101, 102),
       IFMISSINGORNULL(NULL, MISSING, 101, "abc"),
       IFMISSINGORNULL(NULL, NULL),
       IFMISSINGORNULL(MISSING, MISSING);
----

.Result
[source,json]
----
[
  {
    "$1": 101,
    "$2": 101,
    "$3": 101,
    "$4": null,
    "$5": null
  }
]
----
====

[[if_null,IFNULL()]]
== IFNULL

Returns the first value in a list that is not `NULL`.

=== Syntax

....
IFNULL(expression1, expression2, ...)
....

==== Arguments

expression1, expression2, ...:: [Required] Two or more valid expressions.

=== Return Value

Returns one of the following:

* The first non-NULL value.
* `NULL` if all values are `NULL`.

=== Example

====
.Query
[source,sqlpp]
----
SELECT IFNULL(101, 102, "abc"), 
       IFNULL(NULL, 101, 102),
       IFNULL(NULL, NULL);
----

.Result
[source,json]
----
[
  {
    "$1": 101,
    "$2": 101,
    "$3": null
  }
]
----
====

[[missing_if,MISSINGIF()]]
== MISSINGIF

Compares two expressions and returns `MISSING` if they are equal.
If the expressions are not equal, the function returns the first expression.

=== Syntax

....
MISSINGIF(expression1, expression2)
....

==== Arguments

expression1, expression2:: [Required] Two valid expressions to compare.

=== Return Value

Returns one of the following:

* `MISSING` if `expression1` = `expression2`.
* `expression1` if `expression1` != `expression2`.
* `MISSING` if either input is `MISSING` or both inputs are `MISSING`.
* `NULL` if either input is `NULL` or both inputs are `NULL`.

=== Example

====
.Query
[source,sqlpp]
----
SELECT MISSINGIF("abc", 101),
       MISSINGIF("abc", "abc"),
       MISSINGIF(MISSING, "abc");
----

.Result
[source,json]
----
[
  {
    "$1": "abc"
  }
]
----
====

[[null_if,NULLIF()]]
== NULLIF

Compares two expressions and returns `NULL` if they are equal.
If the expressions are not equal, the function returns the first expression.

=== Syntax

....
NULLIF(expression1, expression2)
....

=== Arguments

expression1, expression2:: [Required] Two valid expressions to compare.

=== Return Value

Returns one of the following:

* `NULL` if `expression1` = `expression2`.
* `expression1` if `expression1` != `expression2`.
* `MISSING` if either input is `MISSING` or both inputs are `MISSING`.
* `NULL` if either input is `NULL` or both inputs are `NULL`.

=== Example

====
.Query
[source,sqlpp]
----
SELECT NULLIF("abc", 123),
       NULLIF("abc", "abc");
----

.Result
[source,json]
----
[
  {
    "$1": "abc",
    "$2": null
  }
]
----
====

[[nvl,NVL()]]
== NVL

Evaluates two expressions and returns the first expression if it is not `MISSING` or `NULL`. 

If the first expression is `MISSING` or `NULL`, the function returns the second expression.

=== Syntax

....
NVL(expression1, expression2)
....

==== Arguments

expression1, expression2:: [Required] Two valid expressions to compare.

=== Return Value

Returns one of the following:

* `expression1` if `expression1` is not `MISSING` or `NULL`.
* `expression2` if `expression1` is `MISSING` or `NULL` and `expression2` is not `MISSING` or `NULL`.
* `NULL` if both `expression1` and `expression2` are `MISSING` or `NULL`.

=== Example

====
.Query
[source,sqlpp]
----
SELECT NVL(15, 0),
       NVL(NULL, 100),
       NVL(MISSING, -1);
----

.Result
[source,json]
----
[
  {
    "$1": 15,
    "$2": 100,
    "$3": -1
  }
]
----
====

[[nvl2,NVL2()]]
== NVL2

Evaluates an expression to determine if it is `MISSING` or `NULL`, and returns a value based on the result.

=== Syntax

....
NVL2(expression, value1, value2)
....

==== Arguments

expression:: [Required] Any valid expression.
value1:: [Required] The value to return if `expression` is not `MISSING` or `NULL`.
value2:: [Required] The value to return if `expression` is `MISSING` or `NULL`.

=== Return Value

Returns one of the following:

* `value1` if `expression` is not `MISSING` or `NULL`.
* `value2` if `expression` is `MISSING` or `NULL`.

=== Example

====
.Query
[source,sqlpp]
----
SELECT NVL2(15, "Not missing or null", "Missing or null"),
       NVL2(NULL, "Not missing or null", "Missing or null"),
       NVL2(MISSING, "Not missing or null", "Missing or null");
----

.Result
[source,json]
----
[
  {
    "$1": "Not missing or null",
    "$2": "Missing or null",
    "$3": "Missing or null"
  }
]
----
====

== Aliases

* `COALESCE` is an alias for <<if_missing_or_null,IFMISSINGORNULL>>.
