= Conditional Functions for Numbers
:description: Conditional functions evaluate expressions to determine if the values and formulas meet the specified condition.
:page-topic-type: reference


[abstract]
{description}

== IFINF (`expr1`, `expr2`, ...)

This function has a synonym `IF_INF()`.

=== Description

Evaluates a list of expressions and returns the first non-infinite number.

The function skips `MISSING` and infinite values such as `Inf` and `-Inf`.
If it encounters `NULL` or any other non-number before finding a finite number, the function returns `NULL`.

=== Arguments

expr1, expr2, ...::
A list of valid expressions to evaluate. 
You must specify at least 2 expressions.

=== Return Value

* A finite number. 
* `NULL` if the function encounters a non-number input before finding a finite number.

=== Example

.Find a non-infinite number from a list of numbers
====

.Query
[source,sqlpp]
----
SELECT IFINF(5, 10, 20),
       IFINF(10, NULL, 20),
       IFINF(NULL, 10, 20),
       IFINF(MISSING, 20, NULL),
       IFINF(MISSING, NULL, 10, 20),
       IFINF(1e400, -1e400, 10, 20);
----

.Result
[source,json]
----
[
  {
    "$1": 5,
    "$2": 10,
    "$3": null,
    "$4": 20,
    "$5": null,
    "$6": 10
  }
]
----
In SQL++, `1e400` is equivalent to `Inf` (positive infinity) and `-1e400` is equivalent to `-Inf` (negative infinity).
====

== IFNAN(`expr1`, `expr2`, ...)

This function has a synonym `IF_NAN()`.

=== Description

Evaluates a list of expressions and returns the first non-NaN (Not a Number).

The function skips `MISSING` values. 
If it encounters `NULL` or any other non-number before finding a valid number, the function returns `NULL`. 

=== Arguments

expr1, expr2, ...::
A list of valid expressions to evaluate.
You must specify at least 2 expressions.

=== Return Value
* A valid number that is not `NaN`.
* `NULL` if the function encounters a non-number input before finding a valid number.

=== Example
.Find a non-NaN number from a list of numbers
====
.Query
[source,sqlpp]
----
SELECT IFNAN(3.14, 2.71, NaN),
         IFNAN(NaN, NULL, 2.71),
            IFNAN(NULL, 3.14, NaN),
                IFNAN(MISSING, NaN, NULL),
                    IFNAN(MISSING, NULL, 3.14, NaN),
                        IFNAN(NaN, NaN, 2.71, 3.14);
----
.Result
[source,json]
----
[
    {
        "$1": 3.14,
        "$2": 2.71,
        "$3": null,
        "$4": null,
        "$5": null,
        "$6": 2.71
    }
]
----
In SQL++, `NaN` represents a value that is "Not a Number".
====
