= JSON Functions
:description: JSON functions perform various encoding, decoding, and measuring operations on JSON values.
:page-topic-type: reference

[abstract]
{description}

== DECODE_JSON(`expression`)

Converts a JSON-encoded string into a {sqlpp} value.

An empty string is treated as MISSING, and a NULL string is treated as NULL.


=== Arguments

expression:: A string expression that evaluates to a JSON-encoded string.

=== Return Value

The {sqlpp} value.
This can be any valid JSON value, including an array, object, string, number, boolean, or NULL.

MISSING is returned if the input string is empty or if the input is not a valid JSON string.

=== Example

.Decode a JSON string into a {sqlpp} value
[source,n1ql]
----

----    





ENCODE_JSON(expression)

Marshals the {sqlpp} value into a JSON-encoded string.
MISSING becomes the empty string.

ENCODED_SIZE(expression)

Number of bytes in an uncompressed JSON encoding of the value.
The exact size is implementation-dependent.
Always returns an integer, and never MISSING or NULL.
Returns 0 for MISSING.

POLY_LENGTH(expression)

Returns length of the value after evaluating the expression.
The exact meaning of length depends on the type of the value:

* MISSING: MISSING
* NULL: NULL
* String: The length of the string.
* Array: The number of elements in the array.
* Object: The number of name/value pairs in the object
* Any other value: NULL
