= JSON Functions
:description: Functions for encoding, decoding, and evaluating JSON values.
:page-topic-type: reference
:example-caption!:

[abstract]
{description}

== DECODE_JSON

Converts a JSON-encoded string into a {sqlpp} value.

=== Syntax

....
DECODE_JSON(`expression`)
....

==== Arguments

expression:: [Required] An expression that represents a JSON-encoded string.

=== Return Value

Returns one of the following:

* A {sqlpp} value.
* `NULL` if the input is NULL or not a valid JSON value.
* `MISSING` if the input is empty.

=== Example

.Decode a JSON string into a {sqlpp} value
====

.Query
[source,sqlpp]
----
SELECT DECODE_JSON(
    "{\"airline\":
        { \"callsign\": \"Mile-Air\",
          \"country\": \"United States\", 
          \"iata\": \"Q5\", 
          \"id\": 10, 
          \"name\": \"40-mile Air\", 
          \"type\": \"airline\"
        }
    }"
) as decoded_value;
----    

.Result
[source,json]
----
[
  {
    "decoded_value": {
      "airline": {
        "callsign": "Mile-Air",
        "country": "United States",
        "iata": "Q5",
        "id": 10,
        "name": "40-mile Air",
        "type": "airline"
      }
    }
  }
]
----
====

== ENCODE_JSON

Converts a {sqlpp} value into a JSON-encoded string.

=== Syntax

....
ENCODE_JSON(`expression`)
....

==== Arguments

expression:: [Required] A {sqlpp} expression to be encoded.

=== Return Value

Returns one of the following:

* A JSON encoded string.
* `NULL` if the input is `NULL`.
* `MISSING` if the input is `MISSING`.

=== Example

.Encode a {sqlpp} value into a JSON string
====

.Query
[source,sqlpp]
----
SELECT ENCODE_JSON(
    {
        "airline": {
            "callsign": "Mile-Air",
            "country": "United States",
            "iata": "Q5",
            "id": 10,
            "name": "40-mile Air",
            "type": "airline"
        }
    }
) as encoded_value;
----

.Result
[source,json]
----
[
  {
    "encoded_value":
        "{ \"airline\":
             { \"callsign\":\"Mile-Air\",
               \"country\":\"United States\",
               \"iata\":\"Q5\",
               \"id\":10,
               \"name\":\"40-mile Air\",
               \"type\":\"airline\"
            }
        }"
  }
]
----
====

== ENCODED_SIZE

Returns the number of bytes in an uncompressed JSON encoding of a value.
The exact size depends on the implementation and may vary. 

=== Syntax

....
ENCODED_SIZE(`expression`)
....

==== Arguments

expression:: [Required] An expression to evaluate.

=== Return Value

An integer representing the size in bytes. 

The function never returns `NULL` or `MISSING`. 
If the input value is `MISSING`, the function returns `0`.

=== Example

.Calculate the size of a JSON-encoded value
====

.Query
[source,sqlpp]
----
SELECT ENCODED_SIZE(
    {
        "airline": {
            "callsign": "Mile-Air",
            "country": "United States",
            "iata": "Q5",
            "id": 10,
            "name": "40-mile Air",
            "type": "airline"
        }
    }
) as encoded_size;
----

.Result
[source,json]
----
[
  {
    "encoded_size": 119
  }
]
----
====

== POLY_LENGTH

Evaluates an expression and returns the length of the resulting value.
The definition of length depends on the type of the evaluated value. 
For more information, see the <<poly-length-return-value>> section.

=== Syntax

....
POLY_LENGTH(`expression`)
....

==== Arguments

expression:: [Required] An expression to evaluate.

[[poly-length-return-value]]
=== Return Value

Returns a value based on the data type of the result: 

* String: Returns the number of characters in the string.
* Array: Returns the number of elements in the array.
* Object: Returns the number of name/value pairs in the object.
* MISSING: Returns `MISSING`.
* NULL: Returns `NULL`.
* Any other value: Returns `NULL`.

=== Example

.Find the length of a string, array, and object
====

.Query
[source,sqlpp]
----
SELECT 
    POLY_LENGTH("Flight 101") as string_length,
    POLY_LENGTH(["Flight 101", "Flight 202", "Flight 303"]) as array_length,
    POLY_LENGTH({
        "flight": 101, 
        "airline": "Mile-Air", 
        "destination": "United States"
    }) as object_length;
----

.Result
[source,json]
----
[
  {
    "string_length": 10,
    "array_length": 3,
    "object_length": 3
  }
]
----
====