= Miscellaneous Utility Functions
:page-topic-type: reference
:page-partial:
:example-caption!:
:description: Miscellaneous utility functions enable you to perform tasks beyond the usual evaluation and transformation of data.

{description}
For example, there are functions to retrieve information about a document or item, perform base64 encoding and decoding, generate UUIDs, and control the flow of a query.

[[abort,ABORT()]]
== ABORT(`expression`)

=== Description

Generates an error.
The error message contains the text specified by the given [.var]`expression`.

This function is useful for flow control when xref:n1ql:n1ql-language-reference/createfunction.adoc[creating inline user-defined functions].
You can use xref:n1ql:n1ql-language-reference/conditionalops.adoc[conditional operators] to check the parameters, and use this function to generate an error if something is wrong.

=== Arguments

expression:: An expression resolving to a string.

=== Return Value

The function does not return a return value.

If this function is executed in a query, it causes the query to halt with an error code 5011.
The error message contains the text specified by the given [.var]`expression`.

When this function is executed by a user-defined function, it causes the query to halt with an error code 10109.
The error message shows the name of the user-defined function and contains the text specified by the given [.var]`expression`.

=== Examples

[[abort-ex1,ABORT() Example 1]]
.Abort a query
====

.Query
[source,sqlpp]
----
SELECT ABORT("Something went wrong");
----

.Result
[source,json]
----
[
  {
    "code": 5011,
    "msg": "Abort: \"Something went wrong\". - cause: \"Something went wrong\""
  }
]
----
====

[[abort-ex2,ABORT() Example 2]]
.User-defined function with error checking
====

.Function
[source,sqlpp]
----
CREATE OR REPLACE FUNCTION rstr(vString, vLen) LANGUAGE INLINE AS
CASE
  WHEN NOT IS_STRING(vString)
    THEN ABORT("Search string is not a string")
  WHEN NOT IS_NUMBER(vLen)
    THEN ABORT("Substring length is not a number")
  WHEN vLen > LENGTH(vString)
    THEN ABORT("Substring longer than search string")
  ELSE SUBSTR(vString, LENGTH(vString) - vLen, vLen)
END;
----

.Test invalid string argument
[source,sqlpp]
----
EXECUTE FUNCTION rstr(100, 4);
----

.Result
[source,json]
----
[
  {
    "code": 10109,
    "msg": "Error executing function rstr : \"Search string is not a string\" - cause: \"Search string is not a string\""
  }
]
----

.Test invalid number argument
[source,sqlpp]
----
EXECUTE FUNCTION rstr("Couchbase", "foo");
----

.Result
[source,json]
----
[
  {
    "code": 10109,
    "msg": "Error executing function rstr : \"Substring length is not a number\" - cause: \"Substring length is not a number\""
  }
]
----

.Test out-of-range value
[source,sqlpp]
----
EXECUTE FUNCTION rstr("Couchbase", 10);
----

.Result
[source,json]
----
[
  {
    "code": 10109,
    "msg": "Error executing function rstr : \"Substring longer than search string\" - cause: \"Substring longer than search string\""
  }
]
----

.Test with valid arguments
[source,sqlpp]
----
EXECUTE FUNCTION rstr("Couchbase", 4);
----

.Result
[source,json]
----
[
  "base"
]
----
====

[[base64,BASE64()]]
== BASE64(`expression`)

_Alias_: <<base64-encode>>

=== Description

Returns the https://en.wikipedia.org/wiki/Base64[base64^] encoding of the given [.var]`expression`.

=== Arguments

expression:: An expression representing any supported {sqlpp} datatype.

=== Return Value

A string representing the base64 encoding of the input expression.
If the input expression is `missing`, the return value is also `missing`.

=== Example

[[base64-ex,BASE64() Example]]
====
.Query
[source,sqlpp]
----
SELECT BASE64([1, 2, 3, 4]) AS `array`,
       BASE64(false) AS `boolean`,
       BASE64(missing) AS `missing`,
       BASE64(null) AS `null`,
       BASE64(1234) AS `number`,
       BASE64( {"a": 1, "b": 2, "c": [1, 2, 3]} ) AS `object`,
       BASE64("Couchbase") AS `string`;
----

.Result
[source,json]
----
[
  {
    "array": "WzEsMiwzLDRd",
    "boolean": "ZmFsc2U=",
    "null": "bnVsbA==",
    "number": "MTIzNA==",
    "object": "eyJhIjoxLCJiIjoyLCJjIjpbMSwyLDNdfQ==",
    "string": "IkNvdWNoYmFzZSI="
  }
]
----
====

[[base64-encode,BASE64_ENCODE()]]
== BASE64_ENCODE(`expression`)

Alias of <<base64>>.

[[base64-decode,BASE64_DECODE()]]
== BASE64_DECODE(`expression`)

=== Description

Reverses the encoding done by the <<base64>> or <<base64-encode>> functions.

=== Arguments

expression:: An expression representing a valid base64-encoded string.

=== Return Value

The decoded value of the input expression.
If the input expression is `missing`, the return value is also `missing`.

=== Example

[[base64-decode-ex,BASE64_DECODE() Example]]
====
.Query
[source,sqlpp]
----
SELECT BASE64_DECODE("WzEsMiwzLDRd") AS `array`,
       BASE64_DECODE("ZmFsc2U=") AS `boolean`,
       BASE64_DECODE(missing) AS `missing`,
       BASE64_DECODE("bnVsbA==") AS `null`,
       BASE64_DECODE("MTIzNA==") AS `number`,
       BASE64_DECODE("eyJhIjoxLCJiIjoyLCJjIjpbMSwyLDNdfQ==") AS `object`,
       BASE64_DECODE("IkNvdWNoYmFzZSI=") AS `string`;
----

.Result
[source,json]
----
[
  {
    "array": [
      1,
      2,
      3,
      4
    ],
    "boolean": false,
    "null": null,
    "number": 1234,
    "object": {
      "a": 1,
      "b": 2,
      "c": [
        1,
        2,
        3
      ]
    },
    "string": "Couchbase"
  }
]
----
====

[[current-users]]
== CURRENT_USERS()

=== Description

Returns the authenticated users for the current statement.

=== Arguments

None.

=== Return Value

An array of strings, each representing a user name.

=== Example

[[current-users-ex,CURRENT_USERS() Example]]
====
.Query
[source,sqlpp]
----
SELECT CURRENT_USERS() as current_users;
----

.Results
[source,json]
----
[
  {
    "current_users": [
      "builtin:Administrator"
    ]
  }
]
----
====

[[ds-version]]
== DS_VERSION()

=== Description

Returns the Couchbase Server version.

=== Arguments

None.

=== Return Value

Returns string containing the Couchbase Server version.

=== Example

[[ds-version-ex,DS_VERSION() Example]]
====
.Query
[source,sqlpp]
----
SELECT DS_VERSION() as server_version;
----

.Results
[source,json]
----
[
  {
    "server_version": "7.6.0-1886-enterprise"
  }
]
----
====

[[finderr,FINDERR()]]
== FINDERR(`expression`)

ifeval::['{page-component-version}' == '7.6'] 
[.status]#Couchbase Server 7.6.4#
endif::[]

=== Description

Returns the full details of any Query service or cbq shell error.

=== Arguments

expression:: One of the following:
+
--
* A number representing an error code.
In this case, the function returns the full details of the error matching the error code.

* A string.
In this case, the function searches for the target string in all of the error message fields except for `user_error`, and returns the full details of any errors that match the string.

* A regular expression.
In this case, the function searches for the regular expression in all of the error message fields except for `user_error`, and returns the full details of any errors that match the pattern.
--

=== Return Value

The return value is an array of one or more objects, each of which contains the details of an error that matches the find expression.

For each error, the function returns the following fields.

[options="header", cols="~a,~a,~a"]
|===
|Name|Description|Schema

|**applies_to** +
__required__
|One of the following:

* `cbq-shell`: The error applies to the cbq shell.
* `Server`: The error applies to the server.
|enum (cbq-shell, Server)

|**code** +
__required__
|A number representing the error.
|Integer

|**description** +
__required__
|Message describing why the error occurred.
|String

|**reason** +
__optional__
|List of possible causes of the error.
|String array

|**user_action** +
__optional__
|List of possible steps a user can take to mitigate the error.
|String array

|**user_error** +
__optional__
|One of the following:

* `Yes`: The error was caused by the user.
* `No`: The error was caused by other services, or was internal to the server.
* `Maybe`: A combination of both.
|enum (Yes, No, Maybe)
|===

NOTE: The error details also include a `symbol` field, which contains a representation string for the error.
This field is for internal use only, and is not shown in the results.
However, the FINDERR function does search this field when the find expression is a string or a regular expression.

=== Examples

[[finderr-ex1,FINDERR() Example 1]]
.Find error details by code number
====
.Query
[source,sqlpp]
----
SELECT FINDERR(5011);
----

.Results
[source,json]
----
[
  {
    "$1": [
      {
        "applies_to": "Server",
        "code": 5011,
        "description": "Abort: «reason»",
        "reason": [
          [
            "The SQL++ abort() function was called in the statement.",
            "e.g. SELECT abort('An example cause')"
          ]
        ],
        "user_error": "Yes"
      }
    ]
  }
]
----
====

[[finderr-ex2,FINDERR() Example 2]]
.Find error details by matching a string
====
.Query
[source,sqlpp]
----
SELECT FINDERR("A semantic error is present in the statement.");
----

.Results
[source,json]
----
[
  {
    "$1": [
      {
        "applies_to": "Server",
        "code": 3100,
        "description": "A semantic error is present in the statement.",
        "reason": [
          "The statement includes portions that violate semantic constraints."
        ],
        "user_action": [
          "The cause will contain more detail on the violation; revise the statement and re-submit."
        ],
        "user_error": "Yes"
      }
    ]
  }
]
----
====

[[finderr-ex3,FINDERR() Example 3]]
.Find multiple error details by matching a string
====
.Query
[source,sqlpp]
----
SELECT FINDERR("semantic");
----

.Results
[source,json]
----
[
  {
    "$1": [
      {
        "applies_to": "Server",
        "code": 3100,
        "description": "A semantic error is present in the statement.",
        "reason": [
          "The statement includes portions that violate semantic constraints."
        ],
        "user_action": [
          "The cause will contain more detail on the violation; revise the statement and re-submit."
        ],
        "user_error": "Yes"
      },
      {
        "applies_to": "Server",
        "code": 3220,
        "description": "«name» window function «clause» «reason»",
        "reason": [
          "A violation of the window function semantic restrictions was present in the statement."
        ],
        "user_action": [
          "Revise the statement to remove the violation."
        ],
        "user_error": "Yes"
      },
      {
        "applies_to": "Server",
        "code": 3300,
        "description": "recursive_with semantics: «cause»",
        "reason": [
          "The statement specifies restricted syntax in a recursive common table expression definition."
        ],
        "user_action": [
          "Revise the statement removing the restricted syntax."
        ],
        "user_error": "Yes"
      }
    ]
  }
]
----
====

[[finderr-ex4,FINDERR() Example 4]]
.Find multiple error details by matching a regular expression
====
.Query
[source,sqlpp]
----
SELECT FINDERR("[IU][NP]SERT");
----

.Results
[source,json]
----
[
  {
    "$1": [
      {
        "applies_to": "Server",
        "code": 3150,
        "description": "MERGE with ON KEY clause cannot have document key specification in INSERT action.",
        "reason": [
          [
            "A lookup merge statement specified a document key.",
            "e.g. MERGE INTO default USING [{},{}] AS source ON KEY 'aaa' WHEN NOT MATCHED THEN INSERT ('key',{})"
          ]
        ],
        "user_action": [
          "Refer to the documentation for lookup merge statements."
        ],
        "user_error": "Yes"
      },
// ...
      {
        "applies_to": "Server",
        "code": 5072,
        "description": "No UPSERT key for «value»",
        "user_action": [
          "Contact support."
        ]
      },
// ...
      {
        "applies_to": "Server",
        "code": 15005,
        "description": "No keys to insert «details»"
      }
    ]
  }
]
----
====

=== See Also

* The xref:cli:finderr.adoc[finderr] command line tool
* xref:n1ql:n1ql-language-reference/n1ql-error-codes.adoc[]

[[flatten_keys,FLATTEN_KEYS()]]
== FLATTEN_KEYS(`expr1` [ `modifiers` ], `expr2` [ `modifiers` ], ...)

=== Description

This function can only be used when defining an index key for an xref:n1ql:n1ql-language-reference/indexing-arrays.adoc[array index].

If you need to index multiple fields within an array, this function enables you to _flatten_ the specified expressions, and index them as if they were separate index keys.
All subsequent index keys are accordingly moved to the right.
Queries will be xref:n1ql-language-reference/selectintro.adoc#index-selection[sargable] and will generate spans.

=== Arguments

expr1, expr2, ...:: [At least 1 and at most 32 argument-values are required]
Each argument is an expression over a field within an array, which constitutes an array index key.

modifiers:: [Optional]
Arguments can be modified with `ASC` or `DESC` to specify the xref:n1ql:n1ql-language-reference/createindex.adoc#index-order[sort order] of the index key.
If this modifier is omitted, the default sort order is `ASC`.
+
The first argument may be also modified with `IGNORE MISSING`.
This modifier may only be used when the function is being used in the definition of the leading index key.
If this modifier is present, documents which do not contain the specified field are indexed anyway.
If this modifier is omitted, documents which do not contain the specified field are not indexed.
+
When the `IGNORE MISSING` modifier and the `ASC` or `DESC` modifier are used together, the order of the modifiers does not matter.

Note that `FLATTEN_KEYS()` cannot be used recursively.

=== Return Value

The return value is a flattened list of array elements for use in an array index key.

=== Examples

For examples, refer to xref:n1ql:n1ql-language-reference/indexing-arrays.adoc#examples[Array Indexing Examples].

[[formalize,FORMALIZE()]]
== FORMALIZE(`statement` [ `,query_context` ])

ifeval::['{page-component-version}' == '7.6'] 
_(Introduced in Couchbase Server 7.6)_ 
endif::[]

=== Description

Fully expands all references within a query, using the specified query context.

This function has a synonym FORMALISE().

=== Arguments

statement:: A string containing the statement to formalize.

query_context:: [ Optional ]
A string query context value for the function to use when formalizing.

=== Return Value

Returns a query with all references fully specified.

=== Examples

[[formalize-ex1,FORMALIZE() Example 1]]
.Formalize a query
====
.Query
[source,sqlpp]
----
SELECT formalize("SELECT * FROM landmark WHERE country = 'United Kingdom'","default:`travel-sample`.inventory")
----
.Results
[source,json]
----
[
  {
    "$1": "select self.* from `default`:`travel-sample`.`inventory`.`landmark` where ((`landmark`.`country`) = \"United Kingdom\")"
  }
]
----
====

[[formalize-ex2,FORMALIZE() Example 2]]
.Formalize recently completed requests
====
.Query
[source,sqlpp]
----
SELECT statement,
       NVL(queryContext,"") AS queryContext,
       formalize(statement, queryContext) AS formalized 
FROM system:completed_requests;

----
.Results
[source,json]
----
[
  {
      "statement": "select * from `travel-sample`.inventory.landmark where country = 'United Kingdom' limit 1;",
      "queryContext": "",
      "formalized": "select self.* from `default`:`travel-sample`.`inventory`.`landmark` where ((`landmark`.`country`) = \"United Kingdom\") limit 1"
  },
  {
      "statement": "select * from landmark where country = 'United Kingdom' limit 1;",
      "queryContext": "`travel-sample`.inventory",
      "formalized": "select self.* from `default`:`travel-sample`.`inventory`.`landmark` where ((`landmark`.`country`) = \"United Kingdom\") limit 1"
  },
  // ...
]
----
====

[[len,LEN()]]
== LEN(`expression`)

=== Description

A general function to return the length of an item.

=== Arguments

expression:: An expression representing any supported {sqlpp} datatype.

=== Return Value

The return value is usually a number, depending on the datatype of the input expression.

[cols="1,3"]
|===
| Input Expression | Return Value

| String
| The number of code points in the string -- equivalent to xref:n1ql-language-reference/stringfun.adoc#fn-str-length[LENGTH()].

| Object
| The field count -- equivalent to xref:n1ql-language-reference/objectfun.adoc#fn-obj-length[OBJECT_LENGTH()].

| Array
| The number of elements -- equivalent to xref:n1ql-language-reference/arrayfun.adoc#fn-array-length[ARRAY_LENGTH()].

| Binary
| The size of the binary object.

| Boolean
| `1`

| Number
| The number of characters in the number's text representation.

| MISSING
| `missing`

| NULL
| `null`
|===

For any item not listed above, the return value is `null`.

=== Example

[[len-ex,LEN() Example]]
====
.Query
[source,sqlpp]
----
SELECT LEN([1, 2, 3, 4]) AS `array`,
       LEN(false) AS `boolean`,
       LEN(missing) AS `missing`,
       LEN(null) AS `null`,
       LEN(1234) AS `number`,
       LEN( {"a": 1, "b": 2, "c": [1, 2, 3]} ) AS `object`,
       LEN("Couchbase") AS `string`;
----

.Result
[source,json]
----
[
  {
    "array": 4,
    "boolean": 1,
    "null": null,
    "number": 4,
    "object": 3,
    "string": 9
  }
]
----
====

[[meta,META()]]
== META( {startsb} `keyspace_expr` {endsb} ) {startsb} .`property` {endsb}

=== Description

This function returns the xref:learn:data/data.adoc#metadata[metadata] for the document or keyspace specified by [.var]`keyspace_expr`.
The metadata is returned as a JSON object.

To return a single property from the metadata, you must use a xref:n1ql-language-reference/nestedops.adoc#field-selection[nested expression] containing the `META()` function and the required property, for example `META().id`.
The supported metadata properties are described below.

You can use the `META()` function with a property to xref:n1ql-language-reference/indexing-meta-info.adoc[index metadata information].
Only certain metadata properties are indexable; these are indicated in the description below.

You can also use the `META()` function with a property in the predicate of an xref:n1ql:n1ql-language-reference/join.adoc#section_ek1_jnx_1db[ANSI JOIN Clause].

If your database is running Couchbase Server version 7.6.2 and later, use the `META()` function with the xref:searchfun.adoc[SEARCH() function] when you want to return XATTRs data through the Search Service and do not have a suitable Search index for your query. 

=== Arguments

keyspace_expr::
[Optional.
Default is current keyspace.]
+
String or an expression that results in a keyspace or a document.
This argument is not required when creating an index, since the `META()` function implicitly uses the keyspace being indexed.

property::
[Optional] The name of a single metadata property.
The property name must be separated from the `META()` function by a dot (`.`) and may be one of the following:

cas:::
// tag::metadata-cas[]
Value representing the current state of an item which changes every time the item is modified.
For details, refer to xref:java-sdk:howtos:concurrent-document-mutations.adoc[Concurrent Document Mutations].
// end::metadata-cas[]
+
This property is indexable.

expiration:::
// tag::metadata-expiration[]
Value representing a document's expiration date.
A value of 0 (zero) means no expiration date.
For details, refer to xref:java-sdk:howtos:kv-operations.adoc#document-expiration[KV Operations].
// end::metadata-expiration[]
+
This property is indexable.

flags:::
Value set by the SDKs for non-JSON documents.
For details, refer to xref:java-sdk:howtos:transcoders-nonjson.adoc[Non-JSON Documents].
+
This property is not indexable.
If you attempt to build an index on this property, an error is returned.

id:::
// tag::metadata-id[]
Value representing a document's unique ID number.
// end::metadata-id[]
+
This property is indexable.

type::: Value for the type of document; currently only `json` is supported.
+
This property is not indexable.
If you attempt to build an index on this property, an error is returned.

=== Return Value

The bare function returns a JSON object containing the specified document's metadata.
When the function is used with a property as part of a nested expression, the expression returns the JSON value of the property.

=== Examples

include::ROOT:partial$query-context.adoc[tag=section]

[[meta-ex1,META() Example 1]]
.Return all metadata
====
.Query
[source,sqlpp]
----
SELECT META() AS metadata
FROM airline
LIMIT 3;
----

.Results
[source,json]
----
[
  {
      "metadata": {
          "cas": 1583859008179798016,
          "expiration": 0,
          "flags": 33554432,
          "id": "airline_10",
          "type": "json"
      }
  },
  {
      "metadata": {
          "cas": 1583859008180846592,
          "expiration": 0,
          "flags": 33554432,
          "id": "airline_10123",
          "type": "json"
      }
  },
  {
      "metadata": {
          "cas": 1583859008181895168,
          "expiration": 0,
          "flags": 33554432,
          "id": "airline_10226",
          "type": "json"
      }
  }
]
----
====

[[meta-ex2,META() Example 2]]
.Return a single metadata property
====
.Query
[source,sqlpp]
----
SELECT META().id AS id
FROM airline
LIMIT 3;
----

.Results
[source,json]
----
[
  {
    "id": "airline_10"
  },
  {
    "id": "airline_10123"
  },
  {
    "id": "airline_10226"
  }
]
----
====

[[meta-ex3,META() Example 3]]
.Return a single metadata property for a specified keyspace
====
.Query
[source,sqlpp]
----
SELECT META(route).id AS id -- <1>
FROM route
JOIN airport
ON route.sourceairport = airport.faa
WHERE airport.city = "Paris"
LIMIT 3;
----

<1> You must specify a keyspace for the `META()` function because there is more than one FROM term.

.Results
[source,json]
----
[
  {
    "id": "route_10136"
  },
  {
    "id": "route_10137"
  },
  {
    "id": "route_10138"
  }
]
----
====

For examples showing how to index metadata information, refer to xref:n1ql-language-reference/indexing-meta-info.adoc[Indexing Meta Info].

For examples showing how to use metadata information in the predicate of an ANSI JOIN clause, refer to xref:n1ql:n1ql-language-reference/join.adoc[JOIN Clause].

[[node-name]]
== NODE_NAME()

=== Description

Returns the name of the node on which the query is running.

=== Arguments

None.

=== Return Value

A string representing a node name.

=== Example

[[node-name-ex,NODE_NAME() Example]]
====
.Query
[source,sqlpp]
----
SELECT NODE_NAME() AS node_name;
----

.Results
[source,json]
----
[
  {
    "node_name": "127.0.0.1:8091"
  }
]
----
====

[[node-uuid,NODE_UUID()]]
== NODE_UUID(`expression`)

=== Description

Returns the UUID of a node.

=== Arguments

expression::
A string, or an expression resolving to a string, representing a node name.
To get the UUID of the node on which the query is running, use the empty string `""`.

=== Return Value

A string representing the node UUID.

If the input expression is not a string, the return value is `null`.

If the input expression is `missing`, the return value is also `missing`.

=== Example

[[node-uuid-ex,NODE_UUID() Example]]
====
.Query
[source,sqlpp]
----
SELECT NODE_UUID("") AS from_empty_string,
       NODE_UUID("127.0.0.1:8091") AS from_node_name,
       NODE_UUID(NODE_NAME()) AS from_node_name_function;
----

.Result
[source,json]
----
[
  {
    "from_empty_string": "<redacted UUID>",
    "from_node_name": "<redacted UUID>",
    "from_node_name_function": "<redacted UUID>"
  }
]
----
====

[[pairs,PAIRS()]]
== PAIRS(`obj`)

=== Description

This function generates an array of arrays of {startsb}[.var]``field_name``, ``value``{endsb} pairs of all possible fields in the given JSON object [.var]`obj`.

NOTE: Nested sub-object fields are explored recursively.

=== Arguments

obj:: An expression resolving to an object.

=== Return Value

Array of {startsb}[.var]``field_name``, ``value``{endsb} arrays for each field in the input object [.var]`obj`.

* If [.var]`obj` has nested objects, then fields of such nested sub-objects are also explored and corresponding inner-array elements are produced.
* If [.var]`obj` is an array, then each element of the array is explored and corresponding inner-array elements are produced.
* If [.var]`obj` is a primitive data type of integer or string, then it returns NULL, as they don't have a name.
* If [.var]`obj` is an array of primitive data types, then it returns an empty array `[]`.
* If [.var]`obj` is an array of objects, then it returns an array of objects.

[TIP]
====
If you wrap an array of primitive data types in an xref:n1ql-language-reference/constructionops.adoc#object-construction[object constructor], it's treated as an object and returns an array; without the object constructor, it's treated as an array of primitive data types and returns `[]`.
For example, in <<pairs-example2>>:

* `PAIRS(public_likes)` returns `[]`
* `+PAIRS({public_likes})+` returns an array
====

=== Examples

include::ROOT:partial$query-context.adoc[tag=section]

[[pairs-example1,PAIRS() Example 1]]
.Input value of a nested object
====
.Query
[source,sqlpp]
----
SELECT t        AS orig_t,
       PAIRS(t) AS pairs_t
FROM   airport t
LIMIT  1;
----

.Result
[source,json]
----
[
  {
    "orig_t": {
      "airportname": "Calais Dunkerque",
      "city": "Calais",
      "country": "France",
      "faa": "CQF",
      "geo": {
        "alt": 12,
        "lat": 50.962097,
        "lon": 1.954764
      },
      "icao": "LFAC",
      "id": 1254,
      "type": "airport",
      "tz": "Europe/Paris"
    },
    "pairs_t": [
      [
        "id",
        1254
      ],
      [
        "city",
        "Calais"
      ],
      [
        "faa",
        "CQF"
      ],
      [
        "geo",
        {
          "alt": 12,
          "lat": 50.962097,
          "lon": 1.954764
        }
      ],
      [
        "lon",
        1.954764
      ],
      [
        "alt",
        12
      ],
      [
        "lat",
        50.962097
      ],
      [
        "type",
        "airport"
      ],
      [
        "tz",
        "Europe/Paris"
      ],
      [
        "airportname",
        "Calais Dunkerque"
      ],
      [
        "country",
        "France"
      ],
      [
        "icao",
        "LFAC"
      ]
    ]
  }
]
----
====

[[pairs-example2,PAIRS() Example 2]]
.Input value of an array
====
.Query
[source,sqlpp]
----
SELECT public_likes          AS orig_t,
       PAIRS(public_likes)   AS pairs_array_t,
       PAIRS({public_likes}) AS pairs_obj_t
FROM   hotel
LIMIT  1;
----

.Result
[source,json]
----
[
  {
    "orig_t": [
      "Julius Tromp I",
      "Corrine Hilll",
      "Jaeden McKenzie",
      "Vallie Ryan",
      "Brian Kilback",
      "Lilian McLaughlin",
      "Ms. Moses Feeney",
      "Elnora Trantow"
    ],
    "pairs_array_t": [],
    "pairs_obj_t": [
      [
        "public_likes",
        [
          "Julius Tromp I",
          "Corrine Hilll",
          "Jaeden McKenzie",
          "Vallie Ryan",
          "Brian Kilback",
          "Lilian McLaughlin",
          "Ms. Moses Feeney",
          "Elnora Trantow"
        ]
      ],
      [
        "public_likes",
        "Julius Tromp I"
      ],
      [
        "public_likes",
        "Corrine Hilll"
      ],
      [
        "public_likes",
        "Jaeden McKenzie"
      ],
      [
        "public_likes",
        "Vallie Ryan"
      ],
      [
        "public_likes",
        "Brian Kilback"
      ],
      [
        "public_likes",
        "Lilian McLaughlin"
      ],
      [
        "public_likes",
        "Ms. Moses Feeney"
      ],
      [
        "public_likes",
        "Elnora Trantow"
      ]
    ]
  }
]
----
====

[[pairs-example3a,PAIRS() Example 3a]]
.Input value of a primitive (field document string) data type
====
.Query
[source,sqlpp]
----
SELECT country        AS orig_t,
       PAIRS(country) AS pairs_t
FROM   airport
LIMIT  1;
----

.Result
[source,json]
----
[
  {
    "orig_t": "France",
    "pairs_t": null
  }
]
----
====

[[pairs-example3b,PAIRS() Example 3b]]
.Input value of a primitive (constant) data type
====
.Query
[source,sqlpp]
----
SELECT PAIRS("N1QL")             AS constant_string,
       PAIRS(4)                  AS constant_int,
       PAIRS([1,2,3])            AS constant_int_array,
       PAIRS({"name" : 3})       AS object_constant_int,
       PAIRS({"name" : [1,2,3]}) AS object_constant_int_array;
----

.Result
[source,json]
----
[
  {
    "constant_int": null,
    "constant_int_array": [],
    "constant_string": null,
    "object_constant_int": [
      [
        "name",
        3
      ]
    ],
    "object_constant_int_array": [
      [
        "name",
        [
          1,
          2,
          3
        ]
      ],
      [
        "name",
        1
      ],
      [
        "name",
        2
      ],
      [
        "name",
        3
      ]
    ]
  }
]
----
====

[[pairs-example4,PAIRS() Example 4]]
.Input value of an array of objects
====
.Query
[source,sqlpp]
----
SELECT reviews[*].ratings,
       PAIRS({reviews[*].ratings}) AS pairs_t
FROM   hotel
LIMIT  1;
----

.Result
[source,json]
----
[
  {
    "pairs_t": [
      [
        "ratings",
        [
          {
            "Cleanliness": 5,
            "Location": 4,
            "Overall": 4,
            "Rooms": 3,
            "Service": 5,
            "Value": 4
          },
          {
            "Business service (e.g., internet access)": 4,
            "Check in / front desk": 4,
            "Cleanliness": 4,
            "Location": 4,
            "Overall": 4,
            "Rooms": 3,
            "Service": 3,
            "Value": 5
          }
        ]
      ],
      [
        "ratings",
        {
          "Cleanliness": 5,
          "Location": 4,
          "Overall": 4,
          "Rooms": 3,
          "Service": 5,
          "Value": 4
        }
      ],
      [
        "ratings",
        {
          "Business service (e.g., internet access)": 4,
          "Check in / front desk": 4,
          "Cleanliness": 4,
          "Location": 4,
          "Overall": 4,
          "Rooms": 3,
          "Service": 3,
          "Value": 5
        }
      ],
      [
        "Cleanliness",
        5
      ],
      [
        "Location",
        4
      ],
      [
        "Overall",
        4
      ],
      [
        "Rooms",
        3
      ],
      [
        "Service",
        5
      ],
      [
        "Value",
        4
      ],
      [
        "Cleanliness",
        4
      ],
      [
        "Location",
        4
      ],
      [
        "Rooms",
        3
      ],
      [
        "Value",
        5
      ],
      [
        "Business service (e.g., internet access)",
        4
      ],
      [
        "Check in / front desk",
        4
      ],
      [
        "Overall",
        4
      ],
      [
        "Service",
        3
      ]
    ],
    "ratings": [
      {
        "Cleanliness": 5,
        "Location": 4,
        "Overall": 4,
        "Rooms": 3,
        "Service": 5,
        "Value": 4
      },
      {
        "Business service (e.g., internet access)": 4,
        "Check in / front desk": 4,
        "Cleanliness": 4,
        "Location": 4,
        "Overall": 4,
        "Rooms": 3,
        "Service": 3,
        "Value": 5
      }
    ]
  }
]
----
====

[[unnest-pos,UNNEST_POS()]]
== UNNEST_POS(`expr`)

You can use the `UNNEST_POS()` function with the xref:n1ql-language-reference/unnest.adoc[UNNEST Clause] to return the position of each element in an unnested array. 

This function has a synonym <<unnest-position>>.

=== Description

The `UNNEST_POS` function takes an unnested array and returns the position value of each element in the array.

=== Arguments

expr:: [Required] The alias of the unnested array from an xref:n1ql-language-reference/unnest.adoc[UNNEST Clause]. 

=== Return Values

The `UNNEST_POS` function returns the position of each element in the unnested array, `expr`, as an integer. It returns each position value as a separate row in JSON format. The first element in the array is at position `0`. 

In all other cases, the `UNNEST_POS` function returns `NULL` or `MISSING`.

=== Example

====
In the following example, the `UNNEST_POS` function takes the result of an `UNNEST` Clause on a given array, `a1`. The `UNNEST` function returns the position of each element in the unnested `a1` array , `u`, as the `upos` value. 

[source,N1QL]
----
include::example$functions/unnest-pos.n1ql[]
----

.Results
[source,json]
----
include::example$functions/unnest-pos.jsonc[]
----
====

=== Related Clauses

- xref:n1ql-language-reference/unnest.adoc[UNNEST Clause]
- xref:n1ql-language-reference/from.adoc[FROM Clause]

[[unnest-position,UNNEST_POSITION()]]
== UNNEST_POSITION(`expr`)

Synonym of <<unnest-pos>>.

[[uuid]]
== UUID()

=== Description

Generates a universally unique identifier (UUID) according to https://www.ietf.org/rfc/rfc4122.txt[RFC 4122^].

=== Arguments

None.

=== Return Value

A string representing a version 4 UUID.

=== Example

[[uuid-ex,UUID() Example]]
====
This query will return a different UUID each time you run it.

.Query
[source,sqlpp]
----
SELECT UUID() AS uuid;
----

.Results
[source,json]
----
[
  {
    "uuid": "2ca78bd8-0a28-4d68-995f-0da5e20e0964"
  }
]
----
====

For further examples using `UUID()`, refer to the xref:n1ql-language-reference/insert.adoc[INSERT] and xref:n1ql-language-reference/merge.adoc[MERGE] statements.

[[version]]
== VERSION()

=== Description

Returns {sqlpp} version.

=== Arguments

None.

=== Return Value

Returns string containing the {sqlpp} version.

=== Example

[[version-ex,VERSION() Example]]
====
.Query
[source,sqlpp]
----
SELECT VERSION() as language_version;
----

.Results
[source,json]
----
[
  {
    "language_version": "7.6.0-N1QL"
  }
]
----
====
