= Number Functions
:description: Number functions are functions that are performed on a numeric field.
:page-topic-type: reference

[abstract]
{description}

== ABS(expr)

Returns the absolute value of the number.

Absolute value of a number is the non-negative value of that number. 

=== Arguments

expr:: [Required] A valid numeric expression.

=== Return Value

The function returns 1 of the following:

* A number representing the absolute value.
* `NULL` if the input is a non-numeric value or `NULL`.

=== Example

.Absolute value of a number
====

.Query
[source,sql]
----
SELECT ABS(-15) AS absValue_1,
       ABS(15) AS absValue_2,
       ABS(POWER(-2,5)) AS absValue_3, 
       ABS(NULL) AS absValue_4;
----

.Result
[source,json]
----
[
  {
    "absValue_1": 15,
    "absValue_2": 15,
    "absValue_3": 32,
    "absValue_4": null
  }
]
----
====

ACOS(expression)

Returns arccosine in radians.

ASIN(expression)

Returns arcsine in radians.

ATAN(expression)

Returns arctangent in radians.

ATAN2(expression1, expression2)

Returns arctangent of expression2/expression1.

CEIL(expression)

Returns smallest integer not less than the number.

COS(expression)

Returns cosine.

DEGREES(expression)

Returns radians to degrees.

E()

Base of natural logarithms.

EXP(expression)

Returns e^expression^.

LN(expression)

Returns log base e.

LOG(expression)

Returns log base 10.

FLOOR(expression)

Largest integer not greater than the number.

PI()

Returns PI.

POWER(expression1, expression2):

Returns expression1^expression2^.

RADIANS(expression)

Returns degrees to radians.

RANDOM([ expression ])

Returns pseudo-random number with optional seed.

ROUND(expression [, digits ])

Rounds the value to the given number of integer digits to the right of the decimal point (left if digits is negative).
Digits is 0 if not given.

SIGN(expression)

Valid values:  -1, 0, or 1 for negative, zero, or positive numbers respectively.

SIN(expression)

Returns sine.

SQRT(expression)

Returns square root.

TAN(expression)

Returns tangent.

TRUNC(expression [, digits ])

Truncates the number to the given number of integer digits to the right of the decimal point (left if digits is negative).
Digits is 0 if not given.

Example

----
SELECT
    AVG(reviews.rating) / 5 AS normalizedRating,
    ROUND((avg(reviews.rating) / 5), 2) AS roundedRating,
    TRUNC((avg(reviews.rating) / 5), 3) AS truncRating
    FROM reviews AS reviews
    WHERE reviews.customerId = "customer62"
----

Returns

----
{
   "results": [
     {
       "normalizedRating": 0.42000000000000004,
       "roundedRating": 0.42,
       "truncRating": 0.42
     }
   ]
 }
----
