= Object Functions
:description: You can use object functions to evaluate objects, perform computations on attributes in an object, and to return a new object based on a transformation.
:page-topic-type: reference
:example-caption!:

{description}

[[fn-obj-add,OBJECT_ADD()]]
== OBJECT_ADD

This function adds new attributes and values to a given object.

=== Syntax

....
OBJECT_ADD(object, new_attr_key, new_attr_value)
....

==== Arguments

object:: An expression representing the object that you want to add to.
new_attr_key:: The name of the attribute to add.
new_attr_value:: The value of the attribute to add.

=== Return Value

The updated object.

* This function does not perform key substitution.
* If you add a duplicate attribute (that is, if the key is found), it returns an error or NULL object.
* If `new_attr_key` or `new_attr_value` is MISSING, or if `new_attr_key` is NULL, it returns the `object` unmodified.
* If object` is not an object or NULL, it returns a NULL value object.

=== Example

[[obj-add-ex,OBJECT_ADD() Example]]
====
.Query
[source,sqlpp]
----
WITH route AS ([{
  "id": "R1",
  "schedule": [
    {"day": 0, "flight": "AF198", "utc": "10:13:00"},
    {"day": 2, "flight": "AF200", "utc": "15:30:00"}
  ]
}])
SELECT route[0].schedule[0] AS original,
       OBJECT_ADD(route[0].schedule[0], "day_new", 1) AS output;
----

.Result
[source,json]
----
[
  {
    "original": {
      "day": 0,
      "flight": "AF198",
      "utc": "10:13:00"
    },
    "output": {
      "day": 0,
      "day_new": 1,
      "flight": "AF198",
      "utc": "10:13:00"
    }
  }
]
----
====

[[fn-obj-concat,OBJECT_CONCAT()]]
== OBJECT_CONCAT

This function concatenates the input objects and returns a new object.
It requires a minimum of two input objects.

NOTE: All input objects must be plain objects; arrays of objects are not supported.
If you need to concatenate arrays of objects, use <<fn-obj-concat2,OBJECT_CONCAT2()>> instead.

=== Syntax

....
OBJECT_CONCAT(expr, expr, ...)
....

==== Arguments

expr:: An expression representing an object. 
There must be at least two expressions, and all must be plain objects (not arrays).

=== Return Value

An object constructed by concatenating all the input objects.
If any of the input objects contain the same attribute name, the attribute from the last relevant object in the input list is copied to the output; similarly-named attributes from earlier objects in the input list are ignored.

=== Examples

[[obj-concat-ex,OBJECT_CONCAT() Example]]
====
.Query
[source,sqlpp]
----
SELECT OBJECT_CONCAT({"flight": "AF198"}, 
    {"utc": "4:44:44"},
    {"code": "green"}, 
    {"code": "yellow"},
    {"passengers": ["Corrine Hill", "Vallie Ryan"]}
);       
----

.Result
[source,json]
----
[
  {
    "$1": {
      "flight": "AF198",
      "utc": "4:44:44",
      "code": "yellow",
      "passengers": [
        "Corrine Hill",
        "Vallie Ryan"
      ]
    }
  }
]
----
====

[[fn-obj-concat2,OBJECT_CONCAT2()]]
== OBJECT_CONCAT2

This function concatenates multiple input objects into a single new object, and requires at least two input objects to work. 
Unlike <<fn-obj-concat>>, this function supports both plain objects and arrays of objects as arguments. 

=== Syntax

....
OBJECT_CONCAT2(expr, expr, ...)
....

==== Arguments

expr:: An expression representing an object or an array of objects. 
There must be at least two expressions.
The first argument must be a plain object and cannot be an array. 

=== Return Value

An object constructed by concatenating all the input objects.
If any of the input objects contain the same attribute name, the attribute from the last relevant object in the input list is copied to the output; similarly-named attributes from earlier objects in the input list are ignored.

=== Example

[[obj-concat2-ex,OBJECT_CONCAT2() Example]]
====
.Query
[source,sqlpp]
----
SELECT OBJECT_CONCAT2(
    {"flight": "AF198"},
    [ {"utc": "4:44:44"},
      {"code": "green"},
      {"airline": "Air France"},
      {"airline": "Delta"}
    ]
);
----

.Result
[source,json]
----
[
  {
    "$1": {
      "flight": "AF198",
      "utc": "4:44:44",
      "code": "green",
      "airline": "Delta"
    }
  }
]
----
====

[[fn-obj-field,OBJECT_FIELD()]]
== OBJECT_FIELD

This function returns the value of the specified field within the given object.
A field in this context may be any attribute or element, nested at any level within the object.

=== Syntax

....
OBJECT_FIELD(expr, field)
....

==== Arguments

expr:: An expression representing an object.

field:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, representing the path to a field within the object.
+
You can use xref:n1ql-language-reference/nestedops.adoc[nested operators] to specify the path to a nested attribute or element.
If any attribute names within the field path contain special characters, they must be escaped using backticks (`{backtick}{backtick}`).

=== Return Value

The value of the specified field.
If the object does not exist, or the field cannot be found within the object at the specified location, the function returns NULL.

=== Example

include::ROOT:partial$query-context.adoc[tag=section]

[[obj-field-ex1,OBJECT_FIELD() Example 1]]
.Top-Level Fields
====
This example returns the complete values of the specified attributes at the top level of the object.

.Query
[source,sqlpp]
----
SELECT OBJECT_FIELD(hotel, "public_likes") AS `array`,
       OBJECT_FIELD(hotel, "vacancy") AS `boolean`,
       OBJECT_FIELD(hotel, "id") AS `number`,
       OBJECT_FIELD(hotel, "geo") AS `object`,
       OBJECT_FIELD(hotel, "name") AS `string`
FROM hotel
LIMIT 1;
----

.Result
[source,json]
----
[
  {
    "array": [
      "Julius Tromp I",
      "Corrine Hilll",
      "Jaeden McKenzie",
      "Vallie Ryan",
      "Brian Kilback",
      "Lilian McLaughlin",
      "Ms. Moses Feeney",
      "Elnora Trantow"
    ],
    "boolean": true,
    "number": 10025,
    "object": {
      "accuracy": "RANGE_INTERPOLATED",
      "lat": 51.35785,
      "lon": 0.55818
    },
    "string": "Medway Youth Hostel"
  }
]
----
====

[[obj-field-ex2,OBJECT_FIELD() Example 2]]
.Nested Fields
====
This example specifies a nested array element and a nested object attribute at different depths in the hierarchy.
In the path to the nested object attribute, the final attribute name is escaped, as it contains special characters.

.Query
[source,sqlpp]
----
SELECT
  OBJECT_FIELD(hotel, "reviews[1]")
    AS array_element,
  OBJECT_FIELD(hotel, "reviews[1].ratings.`Business service (e.g., internet access)`")
    AS object_attribute
FROM hotel
LIMIT 1;
----

.Result
[source,json]
----
[
  {
    "array_element": {
      "author": "Barton Marks",
      "content": "We found the hotel de la Monnaie through Interval ...",
      "date": "2015-03-02 19:56:13 +0300",
      "ratings": {
        "Business service (e.g., internet access)": 4,
        "Check in / front desk": 4,
        "Cleanliness": 4,
        "Location": 4,
        "Overall": 4,
        "Rooms": 3,
        "Service": 3,
        "Value": 5
      }
    },
    "object_attribute": 4
  }
]
----
====


[[fn-obj-filter,OBJECT_FILTER()]]
== OBJECT_FILTER

This function extracts and returns nested fields from an input object that match a specified pattern, while retaining their original hierarchical path structure in the output. 
This is particularly useful when working with complex objects, as it allows you to filter fields based on patterns using either regular expressions or exact matches.

=== Syntax

....
OBJECT_FILTER(expression [, options])
....

==== Arguments
expression:: An expression representing an object.

options:: [Optional] A JSON object specifying options for the function.

==== Options

[options="header", cols="1a,3a,1a"]
|===
| Name | Description | Schema

| **pattern** +
__optional__

| The pattern to match. 
This can be a regular expression or a simple string, depending on the `regex` parameter.
| String

| **regex** +
__optional__
| If `TRUE`, the pattern is treated as a regular expression.

If `FALSE`, the pattern is treated as a simple string.

*Default:* `TRUE`
| Boolean

| **arraysubscript** +
__optional__
| Specifies whether array subscripts are included in field names before applying the filter.

If `TRUE`, array subscripts are included. 

If `FALSE`, array subscripts are replaced by `*`.

*Default:* `TRUE`

| Boolean

| **composites** +
__optional__
| Specifies whether the pattern should match field names that contain values requiring further processing, such as nested objects or arrays.

If `TRUE`, the pattern is matched against every level of nested fields. 

If `FALSE`, the pattern is matched only against the deepest level of nested fields. 

*Default:* `TRUE`
| Boolean

| **patternspace** +
__optional__
| A string literal with two possible values. 

`"field"`: The pattern is matched against individual field names. 

`"path"`: The pattern is matched against composite path names.

*Default:* `"path"`
| String

| **exact** +
__optional__
| Specifies whether the provided pattern must be an exact match for the field or path (as determined by the `patternspace` parameter). 

This is a short-cut for the regular expression start (^) and end ($) anchors, and can be used even when `regex` is set to `false`.

If `TRUE`, the pattern must be an exact match.

If `FALSE`, the pattern does not need to be an exact match.

*Default:* `FALSE`
| Boolean

| **ignorecase** +
__optional__
| If `TRUE`, the pattern matching is case-sensitive.

If `FALSE`, the pattern matching ignores case. 

*Default:* `FALSE`
| Boolean
|===

=== Return Value
An object containing only the fields that match the specified pattern.
Non-matching fields are excluded from the output.

=== Examples

[[obj-filter-ex1,OBJECT_FILTER() Example 1]]  
.Filtering by field name
====
.Query
[source,sqlpp]
----
SELECT OBJECT_FILTER(t, {"pattern":"Business service"})  
FROM `travel-sample`.`inventory`.`hotel` t 
WHERE type = 'hotel' 
LIMIT 2;
----
.Result
[source,json]
----
[
  {
    "$1": {
      "reviews": [
        {
          "ratings": {
            "Business service (e.g., internet access)": 4
          }
        }
      ]
    }
  },
  {
    "$1": null
  }
]
----
====

[[obj-filter-ex2,OBJECT_FILTER() Example 2]]
.Filtering by full path
You can use <<fn-obj-paths,OBJECT_PATHS()>> to generate the full path to a field, and then use that path in the `pattern` parameter. 
====
.Query
[source,sqlpp]
----
SELECT OBJECT_FILTER(t, { "pattern": "reviews[1].ratings.Service", "regex": false }) 
FROM `travel-sample`.`inventory`.`hotel` t 
WHERE type = 'hotel' 
LIMIT 1;
----
.Result
[source,json]
----
[
  {
    "$1": {
      "reviews": [
        {
          "ratings": {
            "Service": 3
          }
        }
      ]
    }
  }
]
----
====


[[fn-obj-inner-pairs,OBJECT_INNER_PAIRS()]]
== OBJECT_INNER_PAIRS

This function returns an array of objects, containing the names and values of each attribute in the input object.
It is particularly useful when iterating over multiple objects in an array, as it collates the values from similarly-named attributes into a single nested array.

In this case, the function does not return a value from any object which does not contain the shared attribute name, rather like an INNER JOIN.
For an illustration, refer to the examples below.

=== Syntax

...
OBJECT_INNER_PAIRS(expression)
...

==== Arguments

expression:: An expression representing an object.

=== Return Value

An array of objects, each containing two attributes:

name:: The name of an attribute in the source object.

val:: The value of an attribute in the source object; or an array, containing the collated values of similarly-named attributes in the source objects.

The objects in the array are sorted by attribute name, in {sqlpp} collation order.

=== Examples

[[obj-inner-pairs-ex1,OBJECT_INNER_PAIRS() Example 1]]
.Single object
====
.Query
[source,sqlpp]
----
SELECT OBJECT_INNER_PAIRS({"flight": "AI444", "utc": "4:44:44", "codename": "green"})
    AS inner_pairs;
----

.Result
[source,json]
----
[
  {
    "inner_pairs": [
      {
        "name": "codename",
        "val": "green"
      },
      {
        "name": "flight",
        "val": "AI444"
      },
      {
        "name": "utc",
        "val": "4:44:44"
      }
    ]
  }
]
----
====

[[obj-inner-pairs-ex2,OBJECT_INNER_PAIRS() Example 2]]
.Iterating over objects in an array
====
In this example, notice that where the source objects have similarly-named attributes, the values from each of those attributes are collated into a single array in the output.

.Query
[source,sqlpp]
----
WITH special_flights AS ([{"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                          {"flight": "AI333", "utc": "3:33:33", "alert": "red"},
                          {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}])
SELECT OBJECT_INNER_PAIRS(special_flights[*]) AS inner_pairs;
----

.Result
[source,json]
----
[
  {
    "inner_pairs": [
      {
        "name": "alert",
        "val": "red"
      },
      {
        "name": "codename",
        "val": [
          "green",
          "yellow"
        ]
      },
      {
        "name": "flight",
        "val": [
          "AI444",
          "AI333",
          "AI222"
        ]
      },
      {
        "name": "utc",
        "val": [
          "4:44:44",
          "3:33:33",
          "2:22:22"
        ]
      }
    ]
  }
]
----
====

[[fn-obj-inner-values,OBJECT_INNER_VALUES()]]
== OBJECT_INNER_VALUES

This function returns an array, containing the values of each attribute in the input object.
It is particularly useful when iterating over multiple objects in an array, as it collates the values from similarly-named attributes into a single nested array.

In this case, the function does not return a value from any object which does not contain the shared attribute name, rather like an INNER JOIN.
For an illustration, refer to the examples below.

=== Syntax

....
OBJECT_INNER_VALUES(expression)
....

==== Arguments

expression:: An expression representing an object.

=== Return Value

An array of the values contained within the source object.
The values in the array are sorted by the corresponding attribute names in the source object, in {sqlpp} collation order.

=== Examples

[[obj-inner-values-ex1,OBJECT_INNER_VALUES() Example 1]]
.Single object
====
.Query
[source,sqlpp]
----
SELECT OBJECT_INNER_VALUES({"flight": "AI444", "utc": "4:44:44", "codename": "green"})
    AS inner_values;
----

.Result
[source,json]
----
[
  {
    "inner_values": [
      "green",
      "AI444",
      "4:44:44"
    ]
  }
]
----
====

[[obj-inner-values-ex2,OBJECT_INNER_VALUES() Example 2]]
.Iterating over objects in an array
====
In this example, notice that where the source objects have similarly-named attributes, the values from each of those attributes are collated into a single array in the output.

.Query
[source,sqlpp]
----
WITH special_flights AS ([{"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                          {"flight": "AI333", "utc": "3:33:33", "alert": "red"},
                          {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}])
SELECT OBJECT_INNER_VALUES(special_flights[*]) AS inner_values;
----

.Result
[source,json]
----
[
  {
    "inner_values": [
      "red",
      [
        "green",
        "yellow"
      ],
      [
        "AI444",
        "AI333",
        "AI222"
      ],
      [
        "4:44:44",
        "3:33:33",
        "2:22:22"
      ]
    ]
  }
]
----
====

[[fn-obj-length,OBJECT_LENGTH()]]
== OBJECT_LENGTH

This function returns the number of name-value pairs in the object.
It only counts the top-level attributes and does not recurse into nested objects.

Equivalent to xref:n1ql-language-reference/arrayfun.adoc#len[LEN()]. 

=== Syntax

....
OBJECT_LENGTH(expression)
....

==== Arguments

expression:: An object or an expression that evaluates to an object.

=== Return Value

An integer.

If the input expression is not an object, the function returns `null`; if the input expression is `missing`, the function returns `missing`.

=== Example

[[obj-length-ex,OBJECT_LENGTH() Example]]
====
.Query
[source,sqlpp]
----
SELECT OBJECT_LENGTH({"abc": 1, "def": 2, "ghi": {"uvw": 3, "xyz": 4}});
----

.Result
[source,json]
----
[
    {
        "$1": 3
    }
]
----
====

[[fn-obj-names,OBJECT_NAMES()]]
== OBJECT_NAMES

This function returns an array, containing the names of each attribute in the input object.
It is particularly useful when iterating over multiple objects in an array, as it collates similar attribute names.

=== Syntax

....
OBJECT_NAMES(expression)
....

==== Arguments

expression:: An expression representing an object.

=== Return Value

An array of the attribute names contained within the source object.
The attribute names are sorted in {sqlpp} collation order.

=== Examples

[[obj-names-ex1,OBJECT_NAMES() Example 1]]
.Single object
====
.Query
[source,sqlpp]
----
SELECT OBJECT_NAMES({"flight": "AI444", "utc": "4:44:44", "codename": "green"})
    AS names;
----

.Result
[source,json]
----
[
  {
    "names": [
      "codename",
      "flight",
      "utc"
    ]
  }
]
----
====

[[obj-names-ex2,OBJECT_NAMES() Example 2]]
.Iterating over objects in an array
====
.Query
[source,sqlpp]
----
WITH special_flights AS ([{"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                          {"flight": "AI333", "utc": "3:33:33", "alert": "red"},
                          {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}])
SELECT OBJECT_NAMES(special_flights[*]) AS names;
----

.Result
[source,json]
----
[
  {
    "names": [
      "alert",
      "codename",
      "flight",
      "utc"
    ]
  }
]
----
====

[[fn-obj-pairs,OBJECT_PAIRS()]]
== OBJECT_PAIRS

This function returns an array of objects, containing the names and values of each attribute in the input object. 
It also provides an option to return attribute types instead of values. 

The function is particularly useful when iterating over multiple objects in an array, as it collates the values from similarly-named attributes into a single nested array. 
However, if an object does not contain a shared attribute name, it returns a null entry, similar to an OUTER JOIN.

For an illustration, refer to the examples below.

This function has an alias `OBJECT_OUTER_PAIRS`. 

=== Syntax

....
OBJECT_PAIRS(expression [, options])
....

==== Arguments

expression:: An expression representing an object.

options:: [Optional]
A JSON object specifying options for the function.


==== Options

[options="header", cols="1a,3a,1a"]
|===
| Name | Description | Schema

| **types** +
__required__
| Determines whether to return attribute types or values.

If TRUE, the function returns the name and type of each attribute.

If FALSE, the function returns the name and value of each attribute.

*Default:* `FALSE`
| Boolean
|===

=== Return Value

An array of objects, each containing the following attributes:

[options="header", cols="1a,3a,1a"]
|===
| Name | Description | Schema

| **name** +
| The name of an attribute in the source object.
| String

| **val** +
| The value of an attribute in the source object; or an array, containing the collated values of similarly-named attributes in the source objects.
| Depends on the value returned. It can be a string, number, boolean, or others. 

| **type** +
| The type of an attribute in the source object. Returned only when the `types` parameter is set to `TRUE`. 
| String
|===

NOTE: Each returned object will have either **val** or **type** (depending on the specified options), and not both. 
Also, the objects in the array are sorted by attribute name, in {sqlpp} collation order.

=== Examples

[[obj-pairs-ex1,OBJECT_PAIRS() Example 1]]
.A single input object returning names and values
====
.Query
[source,sqlpp]
----
SELECT OBJECT_PAIRS({"flight": "AI444", "utc": "4:44:44", "codename": "green"})
    AS outer_pairs;
----

.Result
[source,json]
----
[
  {
    "outer_pairs": [
      {
        "name": "codename",
        "val": "green"
      },
      {
        "name": "flight",
        "val": "AI444"
      },
      {
        "name": "utc",
        "val": "4:44:44"
      }
    ]
  }
]
----
====

[[obj-pairs-ex2,OBJECT_PAIRS() Example 2]]
.A single input object returning names and types
====
.Query
[source,sqlpp]
----
SELECT OBJECT_PAIRS({"flight": "AI444", "utc": "4:44:44", "codename": "green"},{"types":TRUE})
    AS outer_pairs;
----

.Result
[source,json]
----
[
  {
    "outer_pairs": [
      {
        "name": "codename",
        "type": "string"
      },
      {
        "name": "flight",
        "type": "string"
      },
      {
        "name": "utc",
        "type": "string"
      }
    ]
  }
]
----
====

[[obj-pairs-ex3,OBJECT_PAIRS() Example 3]]
.Iterating over objects in an array
====
In this example, notice that where the source objects have similarly-named attributes, the values from each of those attributes are collated into a single array in the output.

.Query
[source,sqlpp]
----
WITH special_flights AS ([{"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                          {"flight": "AI333", "utc": "3:33:33", "alert": "red"},
                          {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}])
SELECT OBJECT_PAIRS(special_flights[*]) AS outer_pairs;
----

.Result
[source,json]
----
[
  {
    "outer_pairs": [
      {
        "name": "alert",
        "val": [
          null,
          "red",
          null
        ]
      },
      {
        "name": "codename",
        "val": [
          "green",
          null,
          "yellow"
        ]
      },
      {
        "name": "flight",
        "val": [
          "AI444",
          "AI333",
          "AI222"
        ]
      },
      {
        "name": "utc",
        "val": [
          "4:44:44",
          "3:33:33",
          "2:22:22"
        ]
      }
    ]
  }
]
----
====


[[fn-obj-pairs-nested,OBJECT_PAIRS_NESTED()]]
== OBJECT_PAIRS_NESTED

Similar to <<fn-obj-pairs>>, this function returns an array of objects, containing the names and values of each field in the input object. 
It also provides an option to return field types instead of values. 
A field in this context may be any attribute or element, nested at any level within the object. 

This function may be useful when iterating over multiple objects in an array, as it collates and unnests the values from similarly-named fields across all objects in the input array.
However, if an object does not contain a shared field name, it returns a null entry, similar to an OUTER JOIN.

For an illustration, refer to the examples below.

=== Syntax

....
OBJECT_PAIRS_NESTED(object [, options])
....

==== Arguments

object:: An expression representing an object.

options:: [Optional] A JSON object specifying options for the function. 

==== Options

[options="header", cols="1a,3a,1a"]
|===
| Name | Description | Schema

| **composites** +
__optional__
| If TRUE, every level of every nested field is displayed.

If FALSE, only the deepest possible nested fields are returned.

*Default:* `FALSE`
| Boolean

| **types** +
__optional__
| Determines whether to return field types or values.

If TRUE, the function returns the name and type of each field.

If FALSE, the function returns the name and value of each field.

*Default:* `FALSE`
| Boolean

| **pattern** +
__optional__
| The pattern used to filter the returned paths.

It can be a regular expression or a simple string, depending on the `regex` parameter.

| String

| **regex** +
__optional__
| If `TRUE`, the pattern is treated as a regular expression.

If `FALSE`, the pattern is treated as a simple string.

*Default:* `TRUE`
| Boolean

| **patternspace** +
__optional__
| A string literal with two possible values. 

`"field"`: The pattern is matched against individual field names. 

`"path"`: The pattern is matched against composite path names.

*Default:* `"path"`
| String

| **exact** +
__optional__
| Determines whether the provided pattern must be an exact match for the field or path (as determined by the `patternspace` parameter). 

This is a short-cut for the regular expression start (^) and end ($) anchors, and can be used even when `regex` is set to `false`.

If `TRUE`, the pattern must be an exact match.

If `FALSE`, the pattern does not need to be an exact match.

*Default:* `FALSE`
| Boolean

| **ignorecase** +
__optional__
| If `TRUE`, the pattern matching is case-sensitive.

If `FALSE`, the pattern matching ignores case. 

*Default:* `FALSE`
| Boolean

| **report** +
__optional__

| Controls the output of the `name` field, allowing selection between the full path or the final field name.

Possible values are:

`"field"`: Outputs only the final field name. 

`"path"`: Outputs the full path to the field. 

*Default:* `"path"`

| String
|===

=== Return Value

An array of objects, each containing the following attributes:

[options="header", cols="1a,3a,1a"]
|===
| Name | Description | Schema

| **name** +
| The full path to every possible field within the source object, subject to the specified options. +

The result uses xref:n1ql-language-reference/nestedops.adoc[nested operators] to specify the path to all nested attributes or elements.
If any attribute names within a field path contain special characters, they are escaped using backticks (`{backtick}{backtick}`).

| String

| **val** +
| The value of a field in the source object; or an array, containing the collated values of similarly-named fields in the source objects.
| Depends on the value returned. It can be a string, number, boolean, or others. 

| **type** +
| The type of a field in the source object. Returned only when the 'types' parameter is set to 'TRUE'.
| String
|===

NOTE: Each returned object will have either **val** or **type** (depending on the specified options), and not both. 
Also, the objects in the array are sorted by field name, in {sqlpp} collation order.

=== Examples

[[obj-pairs-nested-ex1,OBJECT_PAIRS_NESTED() Example 1]]
.Single object
====
.Query
[source,sqlpp]
----
WITH input AS ({
    "attribute": {"flight-name": "AI444", "flight-number": 737}
  })
SELECT OBJECT_PAIRS_NESTED(input) AS nested_pairs,
       OBJECT_PAIRS_NESTED(input, {"composites": true}) AS nested_pairs_comp,
       OBJECT_PAIRS_NESTED(input, {"pattern": "name"}) AS nested_pairs_pattern,
       OBJECT_PAIRS_NESTED(input, {"types": true}) AS nested_pairs_types,
       OBJECT_PAIRS_NESTED(input, {"pattern": "number", "patternspace":"field"}) AS filtered_fields,
       OBJECT_PAIRS_NESTED(input, {"pattern": "-name$", "patternspace":"field", "regex":true}) 
                                   AS filtered_fields_regex;
----

.Result
[source,json]
----
[
  {
    "nested_pairs": [
      {
        "name": "attribute.flight-name",
        "val": "AI444"
      },
      {
        "name": "attribute.flight-number",
        "val": 737
      }
    ],
    "nested_pairs_comp": [
      {
        "name": "attribute",
        "val": {
          "flight-name": "AI444",
          "flight-number": 737
        }
      },
      {
        "name": "attribute.flight-name",
        "val": "AI444"
      },
      {
        "name": "attribute.flight-number",
        "val": 737
      }
    ],
    "nested_pairs_pattern": [
      {
        "name": "attribute.flight-name",
        "val": "AI444"
      }
    ],
    "nested_pairs_types": [
      {
        "name": "attribute.flight-name",
        "type": "string"
      },
      {
        "name": "attribute.flight-number",
        "type": "number"
      }
    ],
    "filtered_fields": [
      {
        "name": "attribute.flight-number",
        "val": 737
      }
    ],
    "filtered_fields_regex": [
      {
        "name": "attribute.flight-name",
        "val": "AI444"
      }
    ]
  }
]
----
====

[[obj-pairs-nested-ex2,OBJECT_PAIRS_NESTED() Example 2]]
.Iterating over objects in an array
====
In this example, notice that where the source objects have similarly-named attributes, the values from each of those attributes are collated into a single array in the output.
Each collated array is then unnested to show the name and value of its elements.

.Query
[source,sqlpp]
----
WITH special_flights AS ([{"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                          {"flight": "AI333", "utc": "3:33:33", "alert": "red"},
                          {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}])
SELECT OBJECT_PAIRS_NESTED(special_flights[*], {"composites": true}) AS nested_pairs;
----

.Result
[source,json]
----
[
  {
    "nested_pairs": [
      {
        "name": "alert",
        "val": [
          null,
          "red",
          null
        ]
      },
      {
        "name": "alert[0]",
        "val": null
      },
      {
        "name": "alert[1]",
        "val": "red"
      },
      {
        "name": "alert[2]",
        "val": null
      },
      {
        "name": "codename",
        "val": [
          "green",
          null,
          "yellow"
        ]
      },
      {
        "name": "codename[0]",
        "val": "green"
      },
      {
        "name": "codename[1]",
        "val": null
      },
      {
        "name": "codename[2]",
        "val": "yellow"
      },
      {
        "name": "flight",
        "val": [
          "AI444",
          "AI333",
          "AI222"
        ]
      },
      {
        "name": "flight[0]",
        "val": "AI444"
      },
      {
        "name": "flight[1]",
        "val": "AI333"
      },
      {
        "name": "flight[2]",
        "val": "AI222"
      },
      {
        "name": "utc",
        "val": [
          "4:44:44",
          "3:33:33",
          "2:22:22"
        ]
      },
      {
        "name": "utc[0]",
        "val": "4:44:44"
      },
      {
        "name": "utc[1]",
        "val": "3:33:33"
      },
      {
        "name": "utc[2]",
        "val": "2:22:22"
      }
    ]
  }
]
----

Compare this example with <<obj-pairs-ex3>>.
====

[[fn-obj-paths,OBJECT_PATHS()]]
== OBJECT_PATHS

This function returns the paths to all the fields within an object.
A field in this context may be any attribute or element, nested at any level within the object.

=== Syntax

....
OBJECT_PATHS(object [, options])
....

==== Arguments

object:: An expression representing an object.

options:: [Optional] An object containing the following possible parameters. 

==== Options

[options="header", cols="1a,3a,1a"]
|===
| Name | Description | Schema

| **composites** +
__optional__
| If `TRUE`, every level of every nested field is displayed. 

If `FALSE`, only the deepest possible nested fields are returned.
 
*Default:* `TRUE`
| Boolean

| **arraysubscript** +
__optional__
| If `TRUE`, array subscripts are returned. 

If `FALSE`, array subscripts are replaced by `*`.

*Default:* `TRUE`
| Boolean

| **unique** +
__optional__
| If `TRUE`, duplicate field names are collapsed to single unique field name. 

If `FALSE`, all duplicate field names are returned.

Typically used when arrays are expanded and array subscripts are not returned.

*Default:* `TRUE`
| Boolean

| **pattern** +
__optional__
| A regular expression used to filter the returned paths. 
Used in conjunction with the `patternspace` setting.

| String

| **patternspace** +
__optional__

| A string literal with two possible values.

`"field"`: The pattern is matched against individual field names.

`"path"`: The pattern is matched against composite path names.

*Default:* `"path"`

| String

| **exact** +
__optional__
| Determines whether the provided pattern must be an exact match for the field or path (as determined by the `patternspace` parameter). 

This is a short-cut for the regular expression start (^) and end ($) anchors, and can be used even when `regex` is set to `false`.

If `TRUE`, the pattern must be an exact match.

If `FALSE`, the pattern does not need to be an exact match.

*Default:* `FALSE`
| Boolean

| **ignorecase** +
__optional__
| If `TRUE`, the pattern matching is case-sensitive.

If `FALSE`, the pattern matching ignores case. 

*Default:* `FALSE`
| Boolean

|===

=== Return Value

An array containing the full path to every possible field within the source object, subject to the specified options.

The result uses xref:n1ql-language-reference/nestedops.adoc[nested operators] to specify the path to all nested attributes or elements.
If any attribute names within a field path contain special characters, they are escaped using backticks (`{backtick}{backtick}`).

* If `object` is MISSING, the function returns a MISSING value.
* If `object` is not an object, the function returns a NULL value.
* If `options` is not an object, the function returns a NULL value.

=== Examples

[[obj-paths-ex1,OBJECT_PATHS() Example 1]]
.Composite paths
====
.Query
[source,sqlpp]
----
WITH input AS ({
  "attribute": {"first-part": 1, "second-part": 2}
})
SELECT OBJECT_PATHS(input, {"composites": true}) AS composite,
       OBJECT_PATHS(input, {"composites": false}) AS non_composite;
----

.Result
[source,json]
----
[
  {
    "composite": [
      "attribute",
      "attribute.first-part",
      "attribute.second-part"
    ],
    "non_composite": [
      "attribute.first-part",
      "attribute.second-part"
    ]
  }
]
----
====

[[obj-paths-ex2,OBJECT_PATHS() Example 2]]
.Array subscripts and unique field names
====
.Query
[source,sqlpp]
----
WITH input AS ({
  "attribute": [ { "name": "elem1"}, {"name": "elem2"}]
})
SELECT
  OBJECT_PATHS(input, {"arraysubscript": true})
    AS subscripts,
  OBJECT_PATHS(input, {"arraysubscript": false, "unique": false})
    AS no_subscripts_not_unique,
  OBJECT_PATHS(input, {"arraysubscript": false, "unique": true})
    AS no_subscripts_unique;
----

.Result
[source,json]
----
[
  {
    "no_subscripts_not_unique": [
      "attribute",
      "attribute[*].name",
      "attribute[*].name"
    ],
    "no_subscripts_unique": [
      "attribute",
      "attribute[*].name"
    ],
    "subscripts": [
      "attribute",
      "attribute[0].name",
      "attribute[1].name"
    ]
  }
]
----
====

[[obj-paths-ex3,OBJECT_PATHS() Example 3]]
.Pattern matching and pattern space
====
This example searches for strings beginning with "n" and also fields that exactly match "name". 

.Query
[source,sqlpp]
----
WITH input AS ({
  "attribute": {"name": "elem1"}
})
SELECT
  OBJECT_PATHS(input)
    AS all_paths,
  OBJECT_PATHS(input, {"pattern": "^n", "patternspace": "field"})
    AS field_starts_with_n,
  OBJECT_PATHS(input, {"pattern": "^n", "patternspace": "path"})
    AS path_starts_with_n,
  OBJECT_PATHS(input, {"pattern": "name", "patternspace": "field", "exact": true})
    AS exact_field_name; 
----

.Result
[source,json]
----
[
  {
    "all_paths": [
      "attribute",
      "attribute.name"
    ],
    "field_starts_with_n": [
      "attribute.name"
    ],
    "path_starts_with_n": [],
    "exact_field_name": [
      "attribute.name"
    ]
  }
]
----
====

[[obj-paths-ex4,OBJECT_PATHS() Example 4]]
.Complex example
====
include::ROOT:partial$query-context.adoc[tag=example]

.Query
[source,sqlpp]
----
SELECT OBJECT_PATHS(hotel, {"composites": false, "arraysubscript": false}) AS paths
FROM hotel
LIMIT 1;
----

.Result
[source,json]
----
[
  {
    "paths": [
      "address",
      "alias",
      "checkin",
      "checkout",
      "city",
      "country",
      "description",
      "directions",
      "email",
      "fax",
      "free_breakfast",
      "free_internet",
      "free_parking",
      "geo.accuracy",
      "geo.lat",
      "geo.lon",
      "id",
      "name",
      "pets_ok",
      "phone",
      "price",
      "public_likes",
      "reviews[*].author",
      "reviews[*].content",
      "reviews[*].date",
      "reviews[*].ratings[*].Cleanliness",
      "reviews[*].ratings[*].Location",
      "reviews[*].ratings[*].Overall",
      "reviews[*].ratings[*].Rooms",
      "reviews[*].ratings[*].Service",
      "reviews[*].ratings[*].Value",
      "reviews[*].ratings[*].`Business service (e.g., internet access)`",
      "reviews[*].ratings[*].`Check in / front desk`",
      "state",
      "title",
      "tollfree",
      "type",
      "url",
      "vacancy"
    ]
  }
]
----
====

[[fn-obj-put,OBJECT_PUT()]]
== OBJECT_PUT

This function adds new or updates existing attributes and values to a given object.

=== Syntax

....
OBJECT_PUT(object, attr_key, attr_value)
....

==== Arguments

object:: An expression representing an object.

attr_key:: The name of the attribute to insert or update.

attr_value:: The value of the attribute.

=== Return Value

The updated object.

* If `attr_key` is found in the object, it replaces the corresponding attribute value by `attr_value`.
* If `attr_value` is MISSING, it deletes the corresponding existing key (if any), like <<fn-obj-remove>>.
* If `attr_key` is MISSING, it returns a MISSING value.
* If `attr_key` is not an object, it returns a NULL value.

=== Example

include::ROOT:partial$query-context.adoc[tag=section]

[[obj-put-ex,OBJECT_PUT() Example]]
====
.Query
[source,sqlpp]
----
SELECT schedule[0] AS original,
       OBJECT_PUT(schedule[0], "day", 1) AS output
FROM route
LIMIT 1;
----

.Result
[source,json]
----
[
  {
    "original": {
      "day": 0,
      "flight": "AF198",
      "utc": "10:13:00"
    },
    "output": {
      "day": 1,
      "flight": "AF198",
      "utc": "10:13:00"
    }
  }
]
----
====

[[fn-obj-rename,OBJECT_RENAME()]]
== OBJECT_RENAME

Renames the attribute `old_field` to `new_field` in the JSON input object `input_obj`.

=== Syntax

....
OBJECT_RENAME(input_obj, old_field, new_field)
....

==== Arguments

input_obj:: Any JSON object, or {sqlpp} expression that can evaluate to a JSON object, representing the search object.

old_field:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, representing the old (original) attribute name inside the JSON object `input_obj`.

new_field:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, representing the new attribute name to replace `old_field` inside the JSON object `input_obj`.

=== Return Value

The input object with the new attribute name.
Note that if the new attribute name already exists in the input object, the original attribute with that name is replaced.

=== Example

include::ROOT:partial$query-context.adoc[tag=section]

[[obj-rename-ex,OBJECT_RENAME() Example]]
.Changing a field name
====
.Query
[source,sqlpp]
----
SELECT t AS original,
       OBJECT_RENAME(t, "name", "new_name") AS output
FROM airline AS t
LIMIT 1;
----

.Result
[source,json]
----
[
  {
    "original": {
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "name": "40-Mile Air",
      "type": "airline"
    },
    "output": {
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "new_name": "40-Mile Air",
      "type": "airline"
    }
  }
]
----
====

[[fn-obj-remove,OBJECT_REMOVE()]]
== OBJECT_REMOVE

This function removes the specified attribute and corresponding values from the given object.

=== Syntax

....
OBJECT_REMOVE(object, attr_key)
....

==== Arguments

object:: An expression representing an object.

attr_key:: The name of the attribute to remove.

=== Return Value

The input object without the removed attribute.

* If the `attr_key` is MISSING, it returns a MISSING value.
* If the `attr_key` is not an object, it returns a NULL value.

=== Examples

[[obj-remove-ex1,OBJECT_REMOVE() Example 1]]
====
include::ROOT:partial$query-context.adoc[tag=example]

.Query
[source,sqlpp]
----
SELECT schedule[0] AS original,
       OBJECT_REMOVE(schedule[0], "day") AS output
FROM route
LIMIT 1;
----

.Result
[source,json]
----
[
  {
    "original": {
      "day": 0,
      "flight": "AF198",
      "utc": "10:13:00"
    },
    "output": {
      "flight": "AF198",
      "utc": "10:13:00"
    }
  }
]
----
====

[[obj-remove-ex2,OBJECT_REMOVE() Example 2]]
====
.Query
[source,sqlpp]
----
SELECT OBJECT_REMOVE({"abc": 1, "def": 2, "ghi": 3}, "def");
----

.Result
[source,json]
----
[
  {
    "$1": {
      "abc": 1,
      "ghi": 3
    }
  }
]
----
====

[[fn-obj-replace,OBJECT_REPLACE()]]
== OBJECT_REPLACE

Replaces all occurrences of the value `value_old` to `value_new` in the JSON input object `input_obj`.

=== Syntax

...
OBJECT_REPLACE(input_obj, old_value, new_value)
...

==== Arguments

input_obj:: Any JSON object, or {sqlpp} expression that can evaluate to a JSON object, representing the search object.

old_value:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, representing the old (original) value name inside the JSON object `input_obj`.

new_value:: A string, or any valid xref:n1ql-language-reference/index.adoc[expression] which evaluates to a string, representing the new value name to replace `old_value` inside the JSON object `input_obj`.

=== Return Value

The JSON object `input_obj` with replaced values.

=== Example

include::ROOT:partial$query-context.adoc[tag=section]

[[obj-replace-ex,OBJECT_REPLACE() Example]]
.Replace any occurrences of "airline" with "airplane"
====
.Query
[source,sqlpp]
----
SELECT t AS original,
       OBJECT_REPLACE(t, "airline", "airplane") AS output
FROM airline AS t
LIMIT 1;
----

.Result
[source,json]
----
[
  {
    "original": {
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "name": "40-Mile Air",
      "type": "airline"
    },
    "output": {
      "callsign": "MILE-AIR",
      "country": "United States",
      "iata": "Q5",
      "icao": "MLA",
      "id": 10,
      "name": "40-Mile Air",
      "type": "airplane"
    }
  }
]
----
====

[[fn-obj-type,OBJECT_TYPES()]]
== OBJECT_TYPES

This function returns the data type of every field in the supplied object, as reported by the xref:n1ql-language-reference/typefun.adoc#fn-type-type[TYPE()] function.

=== Syntax

...
OBJECT_TYPES(expression)
...

=== Arguments

expression:: An expression representing an object.

=== Return Value

An object with the same fields as the input object, but with all values replaced by their corresponding data types. 

=== Example

[[obj-type-ex,OBJECT_TYPES() Example]]
====
.Query
[source,sqlpp]
----
SELECT OBJECT_TYPES({"flight": "AI444",
                     "duration": 180,
                     "gate": NULL,
                     "aircraft": {"model": "Boeing 737"}}) 
    AS object_types;
----

.Result
[source,json]
----
[
    {
        "object_types":{
            "flight":"string",
            "duration":"number",
            "gate":"null",
            "aircraft":"object"
        }
    }
]
----
====

[[fn-obj-types-nested,OBJECT_TYPES_NESTED()]]
== OBJECT_TYPES_NESTED

This function returns the data type of every non-composite field in the supplied object, as reported by the xref:n1ql-language-reference/typefun.adoc#fn-type-type[TYPE()] function.
Additionally, all composite type fields (ARRAYs and OBJECTs) are recursively processed in the same way, returning the data types of all nested values. 

=== Syntax

...
OBJECT_TYPES_NESTED(expression)
...

==== Arguments

expression:: An expression representing an object.

=== Return Value

An object with the same fields as the input object, but with all values replaced by their corresponding non-composite data types. 

=== Example

[[obj-type-nested-ex,OBJECT_TYPES_NESTED() Example]]
====
.Query
[source,sqlpp]
----
SELECT OBJECT_TYPES_NESTED({"flight":"AI444",
                            "crewMembers": ["Alice Bobson",
                                            "John Flo",
                                            true],
                            "gate": NULL,
                            "aircraft": {"model": "Boeing 737",
                                         "capacity":200}}) 
    AS object_types_nested;
----

.Result
[source,json]
----
[
  {
    "object_types_nested": {
      "flight": "string",
      "crewMembers": [
        "string",
        "string",
        "boolean"
      ],
      "gate": "null",
      "aircraft": {
        "model": "string",
        "capacity":"number"
      }
    }
  }
]
----
====


[[fn-obj-unwrap,OBJECT_UNWRAP()]]
== OBJECT_UNWRAP

This function enables you to unwrap an object without knowing the name of the attribute.

=== Syntax

...
OBJECT_UNWRAP(expression)
...

==== Arguments

expression:: An expression representing an object.

=== Return Value

If the argument is an object with exactly one attribute, this function returns the value in the attribute.
If the argument is MISSING, it returns MISSING.
For all other cases, it returns NULL.

=== Example

[[obj-unwrap-ex,OBJECT_UNWRAP() Example]]
====
.Query
[source,sqlpp]
----
SELECT OBJECT_UNWRAP({"name": "value"}) AS single,
       OBJECT_UNWRAP({"name": MISSING}) AS `missing`,
       OBJECT_UNWRAP({"name": "value", "name2": "value2"}) AS multiple,
       OBJECT_UNWRAP("some-string") AS `string`;
----

.Result
[source,json]
----
[
  {
    "missing": null,
    "multiple": null,
    "single": "value",
    "string": null
  }
]
----
====

[[fn-obj-values,OBJECT_VALUES()]]
== OBJECT_VALUES

This function returns an array, containing the values of each attribute in the input object.
It is particularly useful when iterating over multiple objects in an array, as it collates the values from similarly-named attributes into a single nested array.

In this case, the function returns a null entry from any object which does not contain the shared attribute name, rather like an OUTER JOIN.
For an illustration, refer to the examples below.

This function has an alias `OBJECT_OUTER_VALUES`.

=== Syntax

...
OBJECT_VALUES(expression)
...

==== Arguments

expression:: An expression representing an object.

=== Return Value

An array of the values contained within the source object.
The values in the array are sorted by the corresponding attribute names in the source object, in {sqlpp} collation order.

=== Examples

[[obj-values-ex1,OBJECT_VALUES() Example 1]]
.Single object
====
.Query
[source,sqlpp]
----
SELECT OBJECT_VALUES({"flight": "AI444", "utc": "4:44:44", "codename": "green"})
    AS outer_values;
----

.Result
[source,json]
----
[
  {
    "outer_values": [
      "green",
      "AI444",
      "4:44:44"
    ]
  }
]
----
====

[[obj-values-ex2,OBJECT_VALUES() Example 2]]
.Iterating over objects in an array
====
In this example, notice that where the source objects have similarly-named attributes, the values from each of those attributes are collated into a single array in the output.

.Query
[source,sqlpp]
----
WITH special_flights AS ([{"flight": "AI444", "utc": "4:44:44", "codename": "green"},
                          {"flight": "AI333", "utc": "3:33:33", "alert": "red"},
                          {"flight": "AI222", "utc": "2:22:22", "codename": "yellow"}])
SELECT OBJECT_VALUES(special_flights[*]) AS outer_values;
----

.Result
[source,json]
----
[
  {
    "outer_values": [
      [
        null,
        "red",
        null
      ],
      [
        "green",
        null,
        "yellow"
      ],
      [
        "AI444",
        "AI333",
        "AI222"
      ],
      [
        "4:44:44",
        "3:33:33",
        "2:22:22"
      ]
    ]
  }
]
----
====

== Aliases

* `OBJECT_OUTER_PAIRS` is an alias for <<fn-obj-pairs,OBJECT_PAIRS>>.
* `OBJECT_OUTER_VALUES` is an alias for <<fn-obj-values,OBJECT_VALUES>>.
