= Pattern-Matching Functions
:description: Pattern-matching functions allow you to find regular expression patterns in strings or attributes.
:page-topic-type: reference
:example-caption!:

{description}
Regular expressions can formally represent various string search patterns using different special characters to indicate wildcards, positional characters, repetition, optional or mandatory sequences of letters, etc.
{sqlpp} functions are available to find matching patterns, find position of matching pattern, or replace a pattern with a new string.

For more information about all supported REGEX patterns, see https://golang.org/pkg/regexp/syntax[Regexp Syntax^].

NOTE: From Couchbase Server 5.0, {sqlpp} supports regular expressions supported by The Go Programming Language version 1.8.

[[section_regex_contains]]
== REGEXP_CONTAINS

Checks whether a string contains a substring that matches a regular expression pattern.

This function has an alias `REGEX_CONTAINS`.

=== Syntax

....
REGEXP_CONTAINS(expression, pattern)
....

==== Arguments

expression:: String, or any {sqlpp} expression that evaluates to a string.

pattern:: String representing a supported regular expression.

=== Return Value

Returns `TRUE` if the string value contains any sequence that matches the regular expression pattern.

=== Example

====
.Query
[source,sqlpp]
----
SELECT name
FROM [
  {"name": "Beijing Inn"},
  {"name": "Sportsman Inn"},
  {"name": "Downtown Cafe"},
  {"name": "Central Bakery"}
] AS landmark
WHERE REGEXP_CONTAINS(name, "In+.*");
----

.Results
[source,json]
----
[
  {
    "name": "Beijing Inn"
  },
  {
    "name": "Sportsman Inn"
  }
]
----
====

[[section_regex_like]]
== REGEXP_LIKE

Checks whether a string exactly matches a regular expression pattern.

This function has an alias `REGEX_LIKE`.

=== Syntax

....
REGEXP_LIKE(expression, pattern)
....

==== Arguments

expression:: String, or any {sqlpp} expression that evaluates to a string.

pattern:: String representing a supported regular expression.

=== Return Value

Returns `TRUE` if the string value exactly matches the regular expression pattern.

=== Example

====
.Query
[source,sqlpp]
----
SELECT name
FROM [
  {"name": "Inverness Castle"},
  {"name": "Beijing Inn"},
  {"name": "International Petroleum Exchange"},
  {"name": "Central Bakery"}
] AS landmark
WHERE REGEXP_LIKE(name, "In+.*");
----

.Results
[source,json]
----
[
  {
    "name": "Inverness Castle"
  },
  {
    "name": "International Petroleum Exchange"
  }
]
----
====

[[section_regex_matches]]
== REGEXP_MATCHES

Returns all substrings in a string that match a regular expression pattern.

// This function has no alias

=== Syntax

....
REGEXP_MATCHES(expression, pattern)
....

==== Arguments

expression:: String, or any {sqlpp} expression that evaluates to a string.

pattern:: String representing a supported regular expression.

=== Return Value

Returns an array of all substrings matching the expression `pattern` within the input string `expression`.
Returns an empty array if no match is found.

=== Examples

.REGEXP_MATCHES() Example 1
====
The following query finds all words beginning with upper or lower case B.

.Query
[source,sqlpp]
----
SELECT REGEXP_MATCHES("So, 'twas better Betty Botter bought a bit of better butter",
                      "\\b[Bb]\\w+"); -- <1>
----

<1> The backslash that introduces an escape sequence in the regular expression must itself be escaped by another backslash in the {sqlpp} query.
So `\b` (word boundary) must be entered as `\\b` and `\w` (word character) must be entered as `\\w`.

.Results
[source,json]
----
[
  {
    "$1": [
      "better",
      "Betty",
      "Botter",
      "bought",
      "bit",
      "better",
      "butter"
    ]
  }
]
----
====

.REGEXP_MATCHES() Example 2
====
The following query finds sequences of two words beginning with upper or lower case B.

.Query
[source,sqlpp]
----
SELECT REGEXP_MATCHES("So, 'twas better Betty Botter bought a bit of better butter",
                      "\\b[Bb]\\w+ \\b[Bb]\\w+");
----

.Results
[source,json]
----
[
  {
    "$1": [
      "better Betty",
      "Botter bought", // <1>
      "better butter"
    ]
  }
]
----

<1> This example does not find `Betty Botter` because the first match already found `Betty`.
====

[[section_regex_position]]
== REGEXP_POSITION

Returns the position of the first substring in a string that matches a regular expression pattern.

This function has an alias `REGEX_POSITION`.

=== Syntax

....
REGEXP_POSITION(expression, pattern)
....

==== Arguments

expression:: String, or any {sqlpp} expression that evaluates to a string.

pattern:: String representing a supported regular expression.

=== Return Value

Returns first position of the occurrence of the regular expression `pattern` within the input string `expression`.
Returns `-1` if no match is found.
Position counting starts from zero.

=== Example

====
The following query finds positions of first occurrence of vowels in each word of the `name` attribute.

.Query
[source,sqlpp]
----
SELECT name, ARRAY REGEXP_POSITION(x, "[aeiou]") FOR x IN TOKENS(name) END
FROM [
  {"name": "Medway Youth Hostel"},
  {"name": "The Balmoral Guesthouse"}
] AS hotel;
----

.Results
[source,json]
----
[
  {
    "$1": [
      1,
      1,
      1
    ],
    "name": "Medway Youth Hostel"
  },
  {
    "$1": [
      2,
      1,
      1
    ],
    "name": "The Balmoral Guesthouse"
  }
]
----

The order of tokens in the second result may be different.
====

[[section_regex_replace]]
== REGEXP_REPLACE

Replaces substrings that match a regular expression pattern with a specified string.

This function has an alias `REGEX_REPLACE`.

=== Syntax

....
REGEXP_REPLACE(expression, pattern, repl [, n])
....

==== Arguments

expression:: String, or any {sqlpp} expression that evaluates to a string.

pattern:: String representing a supported regular expression.

repl:: String, or any {sqlpp} expression that evaluates to a string.

n:: [Optional] The maximum number of times to find and replace the matching pattern.

=== Return Value

Returns new string with occurrences of pattern replaced with `repl`.

* If you provide `n`, the function performs at most `n` replacements.
* If you do not provide `n`, the function replaces all matching occurrences.

=== Examples

.REGEXP_REPLACE() Example 1
====
.Query
[source,sqlpp]
----
SELECT REGEXP_REPLACE("Sql++ is sql for NoSql", "[sS][qQ][lL]", "SQL"),
       REGEXP_REPLACE("Winning innings Inn", "[Ii]n+", "Hotel", 6),
       REGEXP_REPLACE("Winning innings Inn", "[IiNn]+g", upper("inning"), 2);
----

.Results
[source,json]
----
[
  {
    "$1": "SQL++ is SQL for NoSQL",
    "$2": "WHotelHotelg HotelHotelgs Hotel",
    "$3": "WINNING INNINGs Inn"
  }
]
----
====

.REGEXP_REPLACE() Example 2
====
In this example, the query replaces the pattern of repeating `n` with emphasized `NNNN` in each name.

.Query
[source,sqlpp]
----
SELECT name, REGEXP_REPLACE(name, "n+", "NNNN") AS new_name
FROM [
  {"name": "40-Mile Air"},
  {"name": "Texas Wings"},
  {"name": "Atifly"},
  {"name": "Jc royal.britannica"}
] AS airline;
----

.Results
[source,json]
----
[
  {
    "name": "40-Mile Air",
    "new_name": "40-Mile Air"
  },
  {
    "name": "Texas Wings",
    "new_name": "Texas WiNNNNgs"
  },
  {
    "name": "Atifly",
    "new_name": "Atifly"
  },
  {
    "name": "Jc royal.britannica",
    "new_name": "Jc royal.britaNNNNica"
  }
]
----
====

[[section_regex_split]]
== REGEXP_SPLIT

Splits a string into an array of substrings using a regular expression pattern as the delimiter.

// This function has no alias

=== Syntax

....
REGEXP_SPLIT(expression, pattern)
....

==== Arguments

expression:: String, or any {sqlpp} expression that evaluates to a string.

pattern:: String representing a supported regular expression.

=== Return Value

Returns an array of all the substrings created by splitting the input string `expression` at each occurrence of the expression `pattern`.
Returns an empty array if no match is found.

=== Example

====
.Query
[source,sqlpp]
----
SELECT REGEXP_SPLIT("C:\\Program Files\\couchbase\\server\\bin", "[\\\\]") AS Windows, -- <1>
REGEXP_SPLIT("/opt/couchbase/bin", "/") AS Unix;
----

<1> The regular expression `[\\\\]` matches the escaped backslash `\\`.

.Results
[source,json]
----
[
  {
    "Unix": [
      "", // <1>
      "opt",
      "couchbase",
      "bin"
    ],
    "Windows": [
      "C:",
      "Program Files",
      "couchbase",
      "server",
      "bin"
    ]
  }
]
----

<1> The `REGEXP_SPLIT` function returns any zero-length matches that occur at the start of the `expression` string, except when the split pattern is zero-length.
Otherwise, it returns any zero-length matches immediately after a previous match.
====

[[aliases]]
== Aliases

Some pattern-matching functions have an alias whose name begins with `REGEX_`.

* `REGEX_CONTAINS` is an alias for <<section_regex_contains>>.
* `REGEX_LIKE` is an alias for <<section_regex_like>>.
* `REGEX_POSITION` is an alias for <<section_regex_position>>.
* `REGEX_REPLACE` is an alias for <<section_regex_replace>>.
