= {sqlpp} Support for Couchbase Transactions
:page-topic-type: concept
:imagesdir: ../../assets/images
:description: {sqlpp} offers full support for Couchbase ACID transactions.
:tabs:
:page-partial:

// N1QL cross-references
:insert: xref:n1ql:n1ql-language-reference/insert.adoc
:upsert: xref:n1ql:n1ql-language-reference/upsert.adoc
:delete: xref:n1ql:n1ql-language-reference/delete.adoc
:update: xref:n1ql:n1ql-language-reference/update.adoc
:merge: xref:n1ql:n1ql-language-reference/merge.adoc
:select: xref:n1ql:n1ql-language-reference/selectintro.adoc
:execfunction: xref:n1ql:n1ql-language-reference/execfunction.adoc
:prepare: xref:n1ql:n1ql-language-reference/prepare.adoc
:execute: xref:n1ql:n1ql-language-reference/execute.adoc

// Learn cross-references
:transactions: xref:server:learn:data/transactions.adoc
:roles: xref:server:learn:security/roles.adoc

// Manage cross-references
:install-sample-buckets: xref:clusters:data-service/import-data-documents.adoc#import-overview
:sys-transactions: xref:server:manage:monitor/monitoring-n1ql-query.adoc#sys-transactions

// Tools cross-references
:query-workbench: xref:clusters:query-service/query-workbench.adoc
:cbq-shell: xref:server:tools:cbq-shell.adoc
:n1ql-rest-api: xref:n1ql:n1ql-rest-api/index.adoc

// Settings cross-references
:txid: xref:settings:query-settings.adoc#txid
:tximplicit: xref:settings:query-settings.adoc#tximplicit
:txstmtnum: xref:settings:query-settings.adoc#txstmtnum
:kvtimeout: xref:settings:query-settings.adoc#kvtimeout
:txtimeout_req: xref:settings:query-settings.adoc#txtimeout_req
:txtimeout-srv: xref:settings:query-settings.adoc#txtimeout-srv
:queryTxTimeout: xref:settings:query-settings.adoc#queryTxTimeout
:atrcollection_req: xref:settings:query-settings.adoc#atrcollection_req
:atrcollection-srv: xref:settings:query-settings.adoc#atrcollection-srv
:cleanupclientattempts: xref:settings:query-settings.adoc#cleanupclientattempts
:cleanuplostattempts: xref:settings:query-settings.adoc#cleanuplostattempts
:cleanupwindow: xref:settings:query-settings.adoc#cleanupwindow
:queryCleanupClientAttempts: xref:settings:query-settings.adoc#queryCleanupClientAttempts
:queryCleanupLostAttempts: xref:settings:query-settings.adoc#queryCleanupLostAttempts
:queryCleanupWindow: xref:settings:query-settings.adoc#queryCleanupWindow
:numatrs_req: xref:settings:query-settings.adoc#numatrs_req
:numatrs-srv: xref:settings:query-settings.adoc#numatrs-srv
:queryNumAtrs: xref:settings:query-settings.adoc#queryNumAtrs
:scan_consistency: xref:settings:query-settings.adoc#scan_consistency
:durability_level: xref:settings:query-settings.adoc#durability_level
:transactional-scan-consistency: xref:settings:query-settings.adoc#transactional-scan-consistency

// Related links
:begin-transaction: xref:n1ql-language-reference/begin-transaction.adoc
:set-transaction: xref:n1ql-language-reference/set-transaction.adoc
:savepoint: xref:n1ql-language-reference/savepoint.adoc
:commit-transaction: xref:n1ql-language-reference/commit-transaction.adoc
:rollback-transaction: xref:n1ql-language-reference/rollback-transaction.adoc

[abstract]
{sqlpp} offers full support for Couchbase ACID transactions.

Couchbase Capella {sqlpp} offers full support for Couchbase ACID transactions based on optimistic concurrency.
Refer to {transactions}[Transactions] for an overview of Couchbase transactions.

include::partial$n1ql-language-reference/transaction-restrictions.adoc[]

== Statements

{sqlpp} provides the following statements in support of Couchbase transactions.
Refer to the documentation for each statement for more information and examples.

* To begin a transaction, refer to {begin-transaction}[BEGIN TRANSACTION].
* To specify transaction settings, refer to {set-transaction}[SET TRANSACTION].
* To set a savepoint, refer to {savepoint}[SAVEPOINT].
* To rollback a transaction, refer to {rollback-transaction}[ROLLBACK TRANSACTION].
* To commit a transaction, refer to {commit-transaction}[COMMIT TRANSACTION].


ifdef::flag-query-settings[]
== Settings and Parameters

The Query service provides settings and parameters in support of Couchbase transactions.
Refer to the documentation for each parameter for more information and examples.

|===
| Setting{nbsp}/ Parameter | Description

| {txid}[txid] request-level parameter
| Specifies the transaction to which a statement belongs.

| {tximplicit}[tximplicit] request-level parameter
| Specifies that a statement is a single transaction.

| {txstmtnum}[txstmtnum] request-level parameter
| Specifies the transaction statement number.

| {kvtimeout}[kvtimeout] request-level parameter
| Specifies the maximum time to spend on a KV operation within a transaction before timing out.

| {durability_level}[durability_level] request-level parameter
| Specifies the transactional durability level.

| {txtimeout_req}[txtimeout] request-level parameter +
{txtimeout-srv}[txtimeout] node-level setting +
{queryTxTimeout}[queryTxTimeout] cluster-level setting
| Specify the maximum time to spend on a transaction before timing out.

| {atrcollection_req}[atrcollection] request-level parameter +
{atrcollection-srv}[atrcollection] node-level setting
| Specify where the active transaction record is stored.

| {cleanupclientattempts}[cleanupclientattempts] node-level setting +
{queryCleanupClientAttempts}[queryCleanupClientAttempts] cluster-level setting

{cleanuplostattempts}[cleanuplostattempts] node-level setting +
{queryCleanupLostAttempts}[queryCleanupLostAttempts] cluster-level setting
| Specify how expired transactions are cleaned up.

| {cleanupwindow}[cleanupwindow] node-level setting +
{queryCleanupWindow}[queryCleanupWindow] cluster-level setting
| Specify how frequently active transaction records are checked for cleanup.

| {numatrs_req}[numatrs] request-level parameter +
{numatrs-srv}[numatrs] node-level setting +
{queryNumAtrs}[queryNumAtrs] cluster-level setting
| Specify the total number of active transaction records.
|===

In addition, the {scan_consistency}[scan-consistency] request-level parameter is used to specify the transactional scan consistency.
Refer to {transactional-scan-consistency}[Transactional Scan Consistency] for details.
endif::flag-query-settings[]

ifndef::flag-devex-command-line[]
== Query Tools

To create a Couchbase transaction using {sqlpp}, you can use the {query-workbench}[Query Workbench].
endif::flag-devex-command-line[]


ifdef::flag-devex-command-line[]
== Query Tools

To create a Couchbase transaction using {sqlpp}, you can use any of the tools that you use to run a {sqlpp} query: the {query-workbench}[Query Workbench], the {cbq-shell}[cbq shell], or the {n1ql-rest-api}[Query REST API].
There are slight differences in the way these tools operate when creating Couchbase transactions.
These are explained in the sections below.

Note that some Couchbase SDKs provide APIs to support Couchbase transactions.
For further details, refer to {transactions}[Transactions].

endif::flag-devex-command-line[]

=== Couchbase Transactions with the Query Workbench

* To execute a transaction containing multiple statements, compose the sequence of statements in the Query Editor.
Each statement must be terminated with a semicolon.
// NOTE: SHift+Enter to start a newline does not work in Elixir as of 2023/04/13 (SURF-5251)
//After each statement, you must press kbd:[Shift+Enter] to start a new line _without_ executing the query.
Then switch the *transaction* toggle on and click btn:[Run Query]

* To execute a single statement as a transaction, switch the *transaction* toggle on, enter the statement in the Query Editor and click btn:[Run Query].

In either case, you do not need to specify the `txid` parameter or the `tximplicit` parameter.
If you need to specify any other parameters for the Couchbase transaction, you can use the query run-time preferences window.

ifdef::flag-devex-command-line[]
 Couchbase Transactions with the cbq shell

* To execute a transaction containing multiple statements, you can create the transaction one statement at a time.
Once you have started a transaction, all statements within the cbq shell session are assumed to be part of the same transaction until you rollback or commit the transaction.
In this case, you don't need to set the `txid` parameter.
footnote:[You must be using cbq shell version 2.0 or above to use the automatic transaction ID functionality.]

* Alternatively, you can use the `tximplicit` parameter to run a single statement as a transaction.
In this case, you do not need to specify the `txid` parameter either.

* You can specify parameters for the Couchbase transaction using the `\SET` command.

=== Couchbase Transactions with the Query REST API

* To execute a transaction containing multiple statements, you can create the transaction one statement at a time.
Once you have started the transaction, you must set the `txid` parameter to specify the transaction to which each subsequent statement belongs.

* Alternatively, you can use the `tximplicit` parameter to run a single statement as a transaction.
In this case, you do not need to specify the `txid` parameter.

* You can specify parameters for the Couchbase transaction as body parameters or query parameters alongside the query statement.

endif::flag-devex-command-line[]


== Monitoring

You can monitor active Couchbase transactions using the `system:transactions` catalog.
For more information, refer to {sys-transactions}[system:transactions].

ifdef::flag-devex-command-line[]

== Permissions

When developing a transaction with an SDK, the transaction may contain a mixture of key-value operations and query statements.

include::learn:partial$transaction-privileges.adoc[]

endif::flag-devex-command-line[]


== Worked Example

This worked example guides you through a complete Couchbase transaction session using {sqlpp}.

[[preparation]]
=== Preparation

.Keyspace

Create a new keyspace for the transaction to run in:

====
. Next to your bucket in the Data Insights sidebar, click the *More Options* (⋮) button, then btn:[Add Scope]. The Create Scope window now appears.
. Enter the name "tenants" in the *Scope Name* field, then click the btn:[Create Scope] button.
. Next to the new tenants scope, click the *More Options* (⋮) button, then btn:[Add Collection]. The Create Collection now appears.
. Enter the name "users" in the *Collection Name* field, set the TTL to 0, then click the btn:[Create Collection] button.
. Create another collection in the `tenants` scope called `bookings`, with the TTL also set to 0.

Set the query context to the new `tenants` scope.
For more information, see xref:select.adoc#query-context[Setting the Query Context].
====

.Index
For the purposes of this worked example, you must create a primary index in the new bookings collection.

====
Create a primary index on `bookings`, so that you can query and update the documents in this keyspace.

[source,sqlpp]
----
include::example$transactions/multiple.n1ql[tag=index]
----
====

.Parameters
If necessary, set the transaction parameters for this worked example.
In particular, you will turn off durability for the purposes of this example, in order to make sure that there are no problems meeting the transaction durability requirements.

[{tabs}]
====
Query Workbench::
+
--
To specify parameters for a Couchbase transaction, use the Query Options window.

. To display the Query Options window, click btn:[options].

. To specify the transaction scan consistency, open the *Scan Consistency* drop-down list and select an option.

. To specify the transaction timeout, enter a value in seconds in the *Transaction Timeout* box.

. To specify any other parameters, click the btn:[+] button in the corresponding *Named Parameters* or *Positional Parameters* section.
** For named parameters, enter the name in the *name* box and a value in the *value* box.
** For positional parameters, enter the value in the *value* box.

. To save your preferences and return to the Query Workbench, click btn:[Save Settings] 
--
ifdef::flag-devex-command-line[]

CBQ Shell::
+
--
Enter the following parameters.

[source,sqlpp]
----
include::example$transactions/multiple.n1ql[tag=settings]
----

<.> The transaction timeout.
<.> The transaction scan consistency.
No scan consistency is set for individual statements within the transaction; they inherit from the transaction scan consistency.
<.> Durability level of all the mutations within the transaction.
--
endif::flag-devex-command-line[]
====

=== Transaction

[[ex-1]]

ifndef::flag-devex-command-line[]
.Transaction using the Query Workbench
====
endif::flag-devex-command-line[]

ifdef::flag-devex-command-line[]
.Transaction using the Query Workbench or cbq shell
====
Copy the entire sequence below and paste it into either the {query-workbench}[Query Workbench] or the {cbq-shell}[cbq shell].
Note that you must be using cbq shell version 2.0 or above.
endif::flag-devex-command-line[]

ifndef::flag-devex-command-line[]
Copy the entire sequence below and paste it into the {query-workbench}[Query Workbench].
endif::flag-devex-command-line[]


.Transaction
[source,sqlpp]
----
include::example$transactions/multiple.n1ql[tags=transaction;!begin-mark;!set-mark;!savepoint-mark;!rollback-mark;!commit-mark]
----


The results of running the transaction in the Query Workbench are shown below.
ifdef::flag-devex-command-line[]
If you are using the cbq shell, the results are formatted differently, but contain the same information.
endif::flag-devex-command-line[]

.Results
[source,json]
----
include::example$transactions/results.jsonc[tags=!ellipsis]
----

<.> Beginning a transaction returns a transaction ID.
<.> Before setting the second savepoint, the booking document has user `"0"`, name `"Maurice Moss"`.
<.> After setting the second savepoint and performing an update, the booking document has user `"1"`, name `"Jen Barber"`.
<.> After rolling back to the second savepoint, the booking document again has user `"0"`, name `"Maurice Moss"`.
====
ifdef::flag-devex-command-line[]

[[ex-2]]
.Check the results of <<ex-1>>
====
Check the result of committing the transaction.

.Query
[source,sqlpp]
----
include::example$transactions/multiple.n1ql[tag=check-3]
----

.Results
[source,json,indent=0]
----
include::example$transactions/results.jsonc[tag=check-3]
----

<.> The booking document has been added with the attributes that were present when the transaction was committed.
====

.Transaction using the Query REST API
====
For reference, this example shows the equivalent of <<ex-1>> using the Query REST API.

.Begin transaction and set parameters
[source,console]
----
include::example$transactions/multiple.sh[tag=begin]
----

.Specify transaction settings
[source,console]
----
include::example$transactions/multiple.sh[tag=set]
----

.Create a booking document
[source,console]
----
include::example$transactions/multiple.sh[tag=upsert]
----

.Set a savepoint
[source,console]
----
include::example$transactions/multiple.sh[tag=savepoint-1]
----

.Update the booking document to include a user
[source,console]
----
include::example$transactions/multiple.sh[tag=update-1]
----

.Check the content of the booking and user
[source,console]
----
include::example$transactions/multiple.sh[tag=check-1]
----

.Set a second savepoint
[source,console]
----
include::example$transactions/multiple.sh[tag=savepoint-2]
----

.Update the booking documents to change the user
[source,console]
----
include::example$transactions/multiple.sh[tag=update-2]
----

.Check the content of the booking and user
[source,console]
----
include::example$transactions/multiple.sh[tag=check-2]
----

.Roll back the transaction to the second savepoint
[source,console]
----
include::example$transactions/multiple.sh[tag=rollback]
----

.Check the content of the booking and user again
[source,console]
----
include::example$transactions/multiple.sh[tag=check-3]
----

.Commit the transaction
[source,console]
----
include::example$transactions/multiple.sh[tag=commit]
----

<.> After beginning the transaction, each subsequent statement in the transaction must specify the transaction ID that was generated when the transaction began.
====
endif::flag-devex-command-line[]

== Related Links

* Blog post: https://blog.couchbase.com/transactions-n1ql-couchbase-distributed-nosql/[Couchbase Transactions: Elastic, Scalable, and Distributed^].
