= User-Defined Functions
:description: You can call a user-defined function in any expression where you can call a built-in function.
:page-topic-type: reference
:imagesdir: ../../assets/images
:page-partial:

[abstract]
{description}

== Description

When you have created a user-defined function, you can call it in any expression, just like a built-in function.
User-defined functions have the same syntax as built-in functions, with parentheses `()` to contain any arguments.

The name of the function is usually an unqualified identifier, such as `func1` or `{backtick}func-1{backtick}`.
In this case, the path to the function is determined by the current xref:n1ql:n1ql-intro/queriesandresults.adoc#query-context[query context].

To call a global function in a particular namespace, the function name must be a qualified identifier with a namespace, such as `default:func1`.
Similarly, to call a scoped function in a particular scope, the function name must be a qualified identifier with the full path to a scope, such as `default:{backtick}travel-sample{backtick}.inventory.func1`.
For more information, see xref:n1ql-language-reference/createfunction.adoc#context[Global Functions and Scoped Functions].

NOTE: The name of a user-defined function is case-sensitive, unlike that of a built-in function.
You must call the user-defined function using the same case that was used when it was created.

It's not possible to call a user-defined function in an expression if the function has side effects, such as performing mutations.
When you do this, an error is generated.

== Prerequisites

To manage user-defined functions, your client must have specific privileges depending on your xref:clusters:cluster-rbac.adoc#cluster-access-credential-types[cluster access credential type] and whether the function is global or scoped.

[cols="1a,1,1a", options="header"]
|===
| Credential Type | Function Type | Privilege 
| Basic
| Global or scoped
| xref:clusters:cluster-rbac.adoc#basic-access-credentials[`Write`]
| Advanced
| Global
| xref:clusters:cluster-rbac.adoc#privileges-for-advanced-access-credentials[`Global Function Manage`] 
| Advanced
| Scoped
| xref:clusters:cluster-rbac.adoc#privileges-for-advanced-access-credentials[`Query Manage`]
|===

== Arguments

A user-defined function has zero, one, or more arguments, separated by commas, just like a built-in function.
Each argument is a {sqlpp} expression required by the function.

If the function was created with named parameters, you must supply all the arguments that were specified when the function was created.
If the function was created without named parameters, you cannot supply an argument.
If the function is variadic, you can supply as many arguments as needed, or none.

include::partial$n1ql-language-reference/udf-output.adoc[]

== Examples

See xref:n1ql-language-reference/createfunction.adoc[CREATE FUNCTION] for details on creating user-defined functions.

For simplicity, none of these examples implement any data validation or error checking.
If necessary, you can use xref:n1ql:n1ql-language-reference/conditionalops.adoc[conditional operators] to check the parameters of a user-defined function, and the xref:n1ql:n1ql-language-reference/metafun.adoc#abort[ABORT()] function to generate an error if something is wrong.

include::ROOT:partial$query-context.adoc[tag=section]

.Inline function with expression
====
The following statement creates a function called `to_meters`, which converts feet to meters.

[source,sqlpp]
----
CREATE FUNCTION to_meters(feet) { feet * 0.3048 };
----

The following query uses the `to_meters` function to express the elevation of the selected airports in meters above mean sea level (mamsl).
The built-in ROUND function is used to round the output to zero decimal places.

.Query
[source,sqlpp]
----
SELECT airportname, ROUND(to_meters(geo.alt)) AS mamsl
FROM airport
LIMIT 5;
----

.Result
[source,json]
----
[
  {
    "airportname": "Calais Dunkerque",
    "mamsl": 4
  },
  {
    "airportname": "Peronne St Quentin",
    "mamsl": 90
  },
  {
    "airportname": "Les Loges",
    "mamsl": 130
  },
  {
    "airportname": "Couterne",
    "mamsl": 219
  },
  {
    "airportname": "Bray",
    "mamsl": 111
  }
]
----
====

.Inline function with subquery
====
The following statement creates a function called `locations`, which selects name and address information from all documents with the specified activity in the `landmark` keyspace.

[source,sqlpp]
----
include::example$n1ql-language-reference/udf-locations-define.n1ql[]
----

The following query uses the `locations` function as the FROM term in a SELECT query.
Compare this query with the example xref:n1ql-language-reference/from.adoc#ex-subquery-1[A `SELECT` clause inside a `FROM` clause] in FROM Subquery.

.Query
[source,sqlpp]
----
include::example$n1ql-language-reference/udf-locations-query.n1ql[]
----

.Result
[source,json]
----
include::example$n1ql-language-reference/udf-locations-query.jsonc[]
----
====

.External functions
====
For this example, it's assumed that you have created two external functions:

. A function called `geohash`, which depends on the JavaScript `encodeGeoHash` function in the `geohash-js` library;
. A function called `adjacent`, which depends on the JavaScript `calculateAdjacent` function in the `geohash-js` library.

For more information, see the example xref:n1ql-language-reference/createfunction.adoc#ex-external[External functions] in CREATE FUNCTION.

The following query uses the `geohash` and `adjacent` functions to find the 9-figure geohash of the selected hotel, and the geohashes immediately to the north, south, west, and east.

.Query
[source,sqlpp]
----
SELECT area,
       adjacent(area, "top") AS north,
       adjacent(area, "bottom") AS south,
       adjacent(area, "left") AS west,
       adjacent(area, "right") AS east
FROM hotel
LET area = SUBSTR(geohash(geo.lat, geo.lon), 0, 9)
WHERE name = "Sachas Hotel";
----

.Result
[source,json]
----
[
  {
    "area": "gcw2m05h1",
    "east": "gcw2m05h4",
    "north": "gcw2m05h3",
    "south": "gcw2m055c",
    "west": "gcw2m05h0"
  }
]
----

To view any of these geohashes on a map, go to https://www.movable-type.co.uk/scripts/geohash.html[Geohashes^] and enter the string in the *Geohash* box.
At the latitude of the selected hotel, each geohash represents an area of approximately 3 𐄂 5 meters.
====

== Related Links

* For an introduction to user-defined functions, see xref:guides:javascript-udfs.adoc[].
* For more information about JavaScript functions, see xref:javascript-udfs:javascript-functions-with-couchbase.adoc[].
* To create user-defined functions, see xref:n1ql-language-reference/createfunction.adoc[].
* To execute a user-defined function, see xref:n1ql-language-reference/execfunction.adoc[].
* To see the execution plan for a user-defined function, see xref:n1ql-language-reference/explainfunction.adoc[].
* To monitor user-defined functions, see xref:n1ql:n1ql-intro/sysinfo.adoc#sys-functions[Monitor Functions].
* To drop a user-defined function, see xref:n1ql-language-reference/dropfunction.adoc[].
