= Vector Functions
:description: Vector functions enable you to work with vector values.
:page-topic-type: reference
:page-status: Couchbase Server 7.6.6
:page-partial:
:example-caption!:
:keywords: similarity

[abstract]
{description}

Vector functions are supported in Couchbase Server 7.6.6 and later.

[[vector_distance,VECTOR_DISTANCE()]]
== VECTOR_DISTANCE(`vec`, `queryvec`, `metric`)

// no alias

=== Description

Finds the exact distance between a provided vector and the content of a specified field that contains vector embeddings.

=== Arguments

vec:: The name of a field that contains vectors.
The field must contain an array of 32-bit floating point numbers.

queryvec:: An array of 32-bit floating point numbers representing the vector value to search for in the vector field.
The array must have the same dimensions as the vector field.

metric:: A string representing the distance metric to use when comparing the vectors.
+
[horizontal.compact]
COSINE;; xref:vector-index:vectors-and-indexes-overview.adoc#cosine[Cosine Similarity]
DOT;; xref:vector-index:vectors-and-indexes-overview.adoc#dot[Dot Product]
L2;;
EUCLIDEAN;; xref:vector-index:vectors-and-indexes-overview.adoc#euclidean[Euclidean Distance]  
L2_SQUARED;;
EUCLIDEAN_SQUARED;; xref:vector-index:vectors-and-indexes-overview.adoc#euclidean-squared[Euclidean Squared Distance]

=== Return Value

Returns a numeric value representing the vector distance.
If the vector value is missing, returns MISSING.
If the vector value is null, returns NULL.

=== Examples

[#vector_distance_ex_simple]
.VECTOR_DISTANCE() Example
====
The following query finds the exact vector distance between a query vector and three different embedded vectors.

.Query
[source,sqlpp]
----
WITH data AS ([
  {"vector": [1, 2, 3, 4], "similarity": "identical"},
  {"vector": [1, 2, 3, 5], "similarity": "close"},
  {"vector": [6, 7, 8, 9], "similarity": "distant"}
])
SELECT
  similarity,
  VECTOR_DISTANCE(vector, [1, 2, 3, 4], "COSINE") AS cosine,
  VECTOR_DISTANCE(vector, [1, 2, 3, 4], "DOT") AS dot,
  VECTOR_DISTANCE(vector, [1, 2, 3, 4], "L2") AS l2,
  VECTOR_DISTANCE(vector, [1, 2, 3, 4], "L2_SQUARED") AS l2_squared
FROM data;
----

The results show how the distance changes as the similarity decreases.

.Results
[source,json]
----
[
    {
        "similarity": "identical",
        "cosine": 0,
        "dot": -30,
        "l2": 0,
        "l2_squared": 0
    },
    {
        "similarity": "close",
        "cosine": 0.00600091145203363,
        "dot": -34,
        "l2": 1,
        "l2_squared": 1
    },
    {
        "similarity": "distant",
        "cosine": 0.0369131753138463,
        "dot": -80,
        "l2": 10,
        "l2_squared": 100
    }
]
----
====
