@startuml

skinparam componentStyle rectangle

left to right direction

[Run {sqlpp} statement] --> [Transform JSON data] : {item1, item2, item3}
[Transform JSON data] -->  return  : {item1, item3}

@enduml
