@startuml

frame Namespace {

    frame "global library" as globalLibrary #white {
    
        component function3 #Ivory [
                        
function globalUKHoliday(... args) {
    ...       
}
        
        ]
    
        component function4 #Ivory [
                        
function globalUSHoliday(... args) {
    ...       
}
        
        ]
    }

    database "Bucket" {
        
        node "Scope" #White {
          
            frame "my-library" #White {
                    
             component function1 #Ivory [
                            
function add(x, y) {
    ...       
}
            
            ]
                   
        }     
    }
}

@enduml
