= Configure Plan Stability
:page-topic-type: concept
:page-status: Couchbase Server 8.5
:page-edition: Enterprise Edition
:description: Learn how to configure Query Plan Stability for your cluster and for individual queries.  

[abstract]
{description}

You can configure plan stability in the following ways:

* At the cluster level, <<using-the-web-console, using the Couchbase Server Web Console>>.
* For individual queries, <<using-the-prepare-statement, using the `PREPARE` statement>>.

== Using the Web Console

Use the Couchbase Server Web Console to configure Plan Stability settings at the cluster level. 
These settings automatically apply to every query node in your cluster.  

To configure Plan Stability: 

. In the Couchbase Server Web Console, go to menu:Settings[Query].
. From the *Plan Stability* list, select a mode. 
+
--
* *Off*: Does not save execution plans to disk. 
Prepared statements remain in memory only and are cleared if the query node restart or upgrades. 
* *On Prepared Statements*: Automatically saves execution plans to disk for all `PREPARE` statements. 
* *On All Statements*: Automatically saves execution plans to disk for all queries, including `PREPARE` statements and ad-hoc queries. 
--
. From the *Plan Stability Error Policy* list, select an error policy. 
+
--
* *Strict*: Stops execution and returns the error to the application.
* *Moderate*: Generates a new plan to execute the statement, but keeps the original saved plan.
* *Flexible*: Generates a new plan to execute the statement and overwrites the saved plan with the new one.
--
For more information, see xref:n1ql:n1ql-manage/query-plan-stability.adoc#error-policies[].

. Click btn:[Save].

== Using the PREPARE Statement

When you use the `PREPARE` statement, you can explicitly specify which plans to persist using `SAVE` keyword. 

* With `SAVE`: Saves the execution plan to disk. 
* Without `SAVE`: Keeps the execution plan in memory only. 

The following example shows the usage of the `SAVE` keyword: 

[source,sqlpp]
----
PREPARE SAVE get_route_by_airline FROM
SELECT * FROM route
WHERE airline = "FL";
----

For more information, see the xref:n1ql:n1ql-language-reference/prepare.adoc[PREPARE] statement.

== Managing Saved Plans


