= Administer Queries and Indexes
:page-role: tiles -toc
:!sectids:

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

include::ROOT:partial$component-signpost.adoc[]

== Get System Information

{sqlpp} has a system namespace that stores metadata about data containers.
You can query the system namespace to get information about the data containers.

* xref:n1ql:n1ql-intro/sysinfo.adoc[]

== Manage Queries

You can monitor and manage queries using {sqlpp}.

* xref:n1ql:n1ql-manage/monitoring-n1ql-query.adoc[]

== Manage Primary and Secondary Indexes

You can monitor and manage primary and secondary indexes using the Couchbase Capella UI.

* xref:clusters:index-service/manage-indexes.adoc[]

== Settings and Parameters

You can configure the Query service using
ifdef::flag-devex-rest-api[]
cluster-level query settings, node-level query settings, and
endif::flag-devex-rest-api[]
request-level query parameters.

* xref:n1ql:n1ql-manage/query-settings.adoc[]
