= Administer Queries and Indexes
:page-role: tiles -toc
:page-aliases: tools:tools-ref.adoc
:!sectids:

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

include::ROOT:partial$component-signpost.adoc[]

== Get System Information

{sqlpp} has a system namespace that stores metadata about data containers, the Query service, and the system as a whole.
You can query the system namespace to get this information.

* xref:n1ql:n1ql-intro/sysinfo.adoc[]

== Manage Queries

You can monitor and manage queries using the Couchbase Web Console, the command line interface, or the REST API.

* xref:tools:query-monitoring.adoc[]
* xref:n1ql:n1ql-manage/monitoring-n1ql-query.adoc[]

== Manage Primary and Secondary Indexes

You can monitor and manage primary and secondary indexes using the Couchbase Web Console, the command line interface, or the REST API.

* xref:manage:monitor/monitoring-indexes.adoc[]
* xref:manage:manage-indexes/manage-indexes.adoc[]

== Settings and Parameters

You can configure the Query service using cluster-level query settings, node-level query settings, and request-level query parameters.

* xref:n1ql:n1ql-manage/query-settings.adoc[]
