= Encryption at Rest for Query Service
:description: Learn how the Query Service encrypts data at rest and the types of data it can encrypt.
:page-topic-type: concept
:page-edition: Enterprise Edition
// :page-status: Couchbase Server <version>

[abstract]
{description}

== Overview

In the next major release of Couchbase Server and later, the Query Service provides xref:learn:security/native-encryption-at-rest-overview.adoc[Encryption at Rest] to protect data written to disk.
This includes data such as temporary spill files, First Failure Data Capture (FFDC) files, and archived request files.

By default, encryption at rest is turned off. 
To use this feature, you must explicitly enable it in your cluster settings and select the encryption types you want to apply.
You can enable encryption through the Couchbase Server Web Console or REST API.
For more information, see xref:manage:manage-security/encrypt-data-at-rest.adoc[Encrypt Data at Rest].

NOTE: The Query Service uses data encryption keys (DEKs) to encrypt data.
Therefore, before enabling encryption, you must configure a Key Encryption Key (KEK) or Key Management System (KMS) to manage the DEKs.
For more information, see xref:learn:security/encryption-at-rest-keys.adoc[Encryption-at-Rest Keys].

== Supported Encryption Types

Depending on the encryption types you enable, the Query Service encrypts different types of data. 

The following table describes the supported encryption types and the data they protect:

[cols="1,2,3", options="header"]
|===
| Encryption Type | Query Service Data | Description

.2+| Log Encryption 

| First Failure Data Capture (FFDC) files
| Encrypts diagnostic files that the Query Service creates when it detects incidents or potential failures. 
This includes files containing information about xref:n1ql-manage:monitoring-n1ql-query.adoc#sys-active-examples[active requests], xref:n1ql-manage:monitoring-n1ql-query.adoc#sys-completed-get[completed requests], and xref:n1ql-manage:monitoring-n1ql-query.adoc#sys-vital-examples[system vitals].

| Archived Request Files
| Encrypts files that store completed requests.
The Query Service creates these files only when streaming of completed requests is enabled.

For more information, see xref:n1ql-manage:monitoring-n1ql-query.adoc#sys-history[Streaming Completed Requests].

.2+| Bucket Encryption
| Index scan backfill files
| Encrypts temporary files created during index scans on a bucket. 
The Query Service creates these files when scan results exceed the capacity of the buffered channel between the Index Service client and the Query Service.

For more information, see xref:indexes:storage-modes.html#encryption-at-rest[Encryption at Rest for GSI].


| Sequential Scan Files
| Encrypts temporary files that the Query Service creates during sequential scans on a bucket.

For more information, see xref:indexes:storage-modes.html#encryption-at-rest[Encryption at Rest for GSI].


| Other Encryption
| Transient query files
| Encrypts temporary spill files that store transient data during query processing, such as files created for spilled sorting operations. 
|===

For more information about the various encryption types, see xref:learn:security/native-encryption-at-rest-overview.adoc#what-encryption-at-rest-protects[What Encryption at Rest Protects].

== Get Encryption Status

To check the encryption status on the Query Service, use the xref:n1ql-rest-admin:index.adoc#encryption_at_rest[Encryption-at-Rest REST API].
The API returns an object that lists the data encryption keys (DEKs) currently in use to encrypt data. 

== Decrypt Encrypted Files

To decrypt First Failure Data Capture (FFDC) files and archived request files, use the xref:cli:cbcat.adoc[cbcat] command line tool.