= Query Plan Stability
:page-topic-type: concept
// :page-status: Couchbase Server 8.1
:page-edition: Enterprise Edition
:description: The Query Plan Stability feature enables you to save and reuse query plans across upgrades.


[abstract]
{description}

Query Plan Stability is feature that preserves execution plans for your queries across Couchbase Server upgrades and node restarts. 

By default, the query optimizer generates a new plan for a query each time the plan isn't already cached. 
When you upgrade, the optimizer in the new version can generate a different plan for the same query than it did in the previous version.
Query Plan Stability prevents this by saving execution plans to persistent storage before an upgrade and reapplying those exact plans after the upgrade. 

== Key Benefits

Some of the key benefits of using Query Plan Stability are: 

* Ensures consistent query execution behavior across upgrades.
* Minimizes the risk of performance degradation caused by changes in new versions.
* Protects applications tuned around specific query plans from unexpected changes.

== How Plan Stability Works

. Before an upgrade: 
    * You enable Plan Stability by selecting which queries to target. 
    * You can choose to save plans for prepared statements, ad-hoc queries, or both.
    For more information about how to enable Plan Stability, see xref:n1ql:n1ql-manage/configure-plan-stability.adoc[].
    
    * The Query Service saves the generated plans for those queries to persistent storage.
. After an upgrade: 
    * When the Query Service receives a query, it checks the persistent storage for a matching saved plan.
    ** If a saved plan is found, the Query Service executes the query using that plan.
    ** If no saved plan is found, the Query optimizer generates a new plan for the query. 

== Plan Stability Modes

Plan stability can be enabled in two modes:

. Automatic Mode
. Managed Mode

=== Automatic Mode

You can control which query plans to save by using a cluster-level setting. 

The following modes are available:

* *Off*: Plan Stability is turned off. The Query Service generates a new plan for each query, and no plans are saved.
* *On Prepared Statements*: Only plans for prepared statements are saved. The Query Service generates a new plan for ad-hoc queries.
* *On All Statements*: All plans including both prepared statements and ad-hoc queries are saved. 
The Query Service generates a new plan only if no saved plan is found.

You can also set various levels of error policy for plan stability.

For more information about how to change this setting, see xref:n1ql:n1ql-manage/configure-plan-stability.adoc[].

=== Manual Mode

== Storage 

When you enable Plan Stability, the query service saves the plans to persistent storage. 
The plans are stored in a system keyspace called `system:plan_stability`. 

user-level bucket  called QUERY_METADATA for storage. This bucket will be automatically created when:
plan stability mode is set to “prepared_only”, “ad_hoc” or “ad_hoc_read_only”
a PREPARE statement is issued with the SAVE option

A user with admin privileges can drop the bucket. If the bucket is dropped, errors may be returned on various operations. The next time plan stability mode is set to anything other than “off”, or a PREPARE statement with SAVE option is issued, the bucket will be automatically created again.

== Error Policies

Before executing a saved query plan, the Query Service verifies if the plan is still valid.

A saved plan can become invalid over time. 
For example, if a index used in the plan is dropped, the plan becomes invalid and cannot run. 
When plan verification fails, the Query Plan Stability error policy determines how the service responds.

It supports the following error policies:

[cols ="1,3", options="header"]
|===
| Error Policy | Description

| Strict 
| Stops statement execution and returns an error to the application. 

| Moderate
| Reprepares the statement to generate and execute a new plan. 
The original saved plan remains unchanged. 

This policy is useful when an index becomes temporarily unavailable. 
Statement executions may use a sub-optimal plan while the index is down, but the saved plan stays intact and can be used again once the index is available. 

| Flexible
| Reprepares the statement to generate a new plan and replaces the saved plan with the new one.  

This behavior is similar to the standard prepared statement handling.
|===

== See Also

* xref:n1ql:n1ql-manage/configure-plan-stability.adoc[]
* xref:n1ql:n1ql-manage/manage-saved-plans.adoc[]

Prepared statements only: You explicitly create a prepared statement for each query whose plan you want to save. Only plans for these statements are saved.
Ad-hoc statements: The system automatically prepares all ad-hoc queries (auto-prepare) and saves their plans. Use this approach if you don't want to modify application code to use prepared statements explicitly.