= Encryption at Rest for Query Service
:description: Encryption at Rest for Query Service
:page-topic-type: concept


[abstract]
{description}

== Overview

== Types of Encryption 

== View Encryption Status

You can use the xref:link[Query Admin REST API] to check the encryption status of a Query Service node. 

The API returns an object that lists the data encryption keys (DEKs) currently in use to encrypt data. 
Each DEK is identified by a unique DEK ID. 

The DEK list indicates the encryption state:

* Encryption enabled: The list includes one or more non-empty DEK IDs. 
* Unencrypted files present: The list includes the special key ID `""` (an empty string).

//TODO: Add a link to the Query Admin REST API endpoint and include an example here.

== Decrypt Encrypted Files

You can decrypt encrypted FFDC and archived request files using the `cbcat` CLI tool.

For more information, see the xref:cli:cbcat.adoc[cbcat CLI reference page].

//TODO: Add a link to the cbcat tool and also include a few lines the possible options and how to use them to decrypt files.
