= Encryption at Rest for Query Service
:description: Learn how the Query Service protects data using encryption at rest and the types of data it can encrypt.
:page-topic-type: concept

[abstract]
{description}

== Overview

In Couchbase Server 8.1 and later, the Query Service provides xref:link[Encryption at Rest] to protect data written to disk.
This includes temporary spill files, First Failure Data Capture (FFDC) files, and archived request files.

To use encryption, you must explicitly enable it in your cluster configuration and select the encryption types you want to apply.
By default, this feature is turned off. 
You can enable it through the Couchbase Server Web Console or REST API.
For more information about how to enable encryption, see the xref:link[Enabling Encryption].

// TODO: Add a link to the relevant doc. 

When enabled, the Query Service generates a unique Data Encryption Key (DEK) for each data type and uses it to encrypt that data before writing it to disk.
For more information about DEKs, see the xref:link[Data Encryption Key].

// TODO: Add a link to the relevant doc.

== Supported Encryption Types

Depending on the encryption types you enable, the Query Service encrypts different types of data. 

The following table describes the supported encryption types and the data they protect:

[cols="1,2,3", options="header"]
|===
| Encryption Type | Query Service Data | Description

.2+| Log Encryption 

| First Failure Data Capture (FFDC) files
| Encrypts diagnostic files that the Query Service creates when it detects incidents or potential failures. 
This includes files containing information about xref:n1ql-manage:monitoring-n1ql-query.adoc#sys-active-examples[active requests], xref:n1ql-manage:monitoring-n1ql-query.adoc#sys-completed-get[completed requests], and xref:n1ql-manage:monitoring-n1ql-query.adoc#sys-vital-examples[system vitals].


| Archived Request Files
| Encrypts files that store completed requests.
The Query Service creates these files only when streaming of completed requests is enabled.
For more information, see xref:n1ql-manage:monitoring-n1ql-query.adoc#sys-history[Streaming Completed Requests].

.2+| Bucket Encryption
| Index scan backfill files
| Encrypts temporary files created during index scans associated with a bucket. 
These files are created when scan results exceed the capacity of the buffered channel between the Index Service client and the Query Service.
For more information, see xref:link[Encryption at Rest for GSI].

| Sequential Scan Files
| Encrypts temporary files created during sequential scans over a bucket.

| Other Encryption
| Transient query files
| Encrypts temporary spill files used to store transient data during query processing.
For example, files created for spilled sorting operation. 
|===

== View Encryption Status

You can use the xref:link[Query Admin REST API] to check the encryption status of a Query Service node. 

The API returns an object that lists the data encryption keys (DEKs) currently in use to encrypt data. 
Each DEK is identified by a unique DEK ID. 

The DEK list indicates the encryption state:

* Encryption enabled: The list includes one or more non-empty DEK IDs. 
* Unencrypted files present: The list includes the special key ID `""` (an empty string).

//TODO: Add a link to the Query Admin REST API endpoint and include an example here.

== Decrypt Encrypted Files

You can decrypt encrypted FFDC and archived request files using the `cbcat` CLI tool.

For more information, see the xref:cli:cbcat.adoc[cbcat CLI reference page].

//TODO: Add a link to the cbcat tool. Also include a few lines about the possible options. 
