= Build Mobile Apps
:page-role: tiles -toc
:description: Use App Services in Capella, in combination with Couchbase Lite embedded NoSQL database, to develop mobile apps.
:no-escape-hatch:
:!sectids:

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title,
  div.contributor-list-box,
  div#preamble,
  nav.pagination {
    flex-basis: 100%;
  }
</style>
++++
endif::[]

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

Couchbase Mobile consists of Couchbase Lite -- an embedded, offline-first database for edge devices -- synced peer-to-peer, or synchronized to your Couchbase Cluster via App Services
(or Sync Gateway, if you're using self-managed Couchbase Server instead of Capella).

For the easiest way to start building mobile apps with Couchbase,
follow the steps to xref:cloud:get-started:configuring-app-services.adoc[set up an App Services trial], creating your endpoint, and getting your connection string.
Then head to the getting started section of your chosen platform in the xref:couchbase-lite::introduction.adoc[Couchbase Lite Docs].


== App Services

App Services synchronizes data between the Couchbase Capella cluster and your mobile apps.

* xref:cloud:app-services:index.adoc[]

== Couchbase Lite

The Couchbase Lite documentation contains resources to help you develop mobile apps on all major operating systems and platforms.

* xref:couchbase-lite::introduction.adoc[Go to Couchbase Lite Docs]
