== TOKENS

This function tokenizes, or splits, an input string into meaningful segments based on the delimiters and other options you specify.
For a JSON value, it recursively extracts every token and returns them as an array of JSON atomic values.

=== Syntax

....
TOKENS(in_str, options)
....

==== Arguments
in_str:: [Required]
The JSON value to tokenize.
It can be a constant literal, a scalar value, a key name, or an entire document.
+
The following table lists the rules for each JSON type:
+
|===
| JSON Type | Return Value

| MISSING
| []

| NULL
| [NULL]

| false
| [false]

| true
| [true]

| number
| [number]

| string
| SPLIT(string)

| array
| FLATTEN(TOKENS(element)) for each element in the array (concatenation of element tokens)

| object
| For each name-value pair, name + TOKENS(value)
|===

options::
A JSON object indicating the options passed to the function.
For more information, see <<options>>.

==== Options

Options can take the following options, and each invocation of `TOKENS()` can choose one or more of the options:

[cols="1,3,1"]
|===
|Name |Description |Schema

|`name` +
__optional__
a| Determines whether to include field names in the tokenization.

* If `true`, includes field names.
* If `false`, excludes field names.

*Default:* `true`
|Boolean

|`case` +
__optional__
a| Converts characters for case folding.
Supported values are `lower` and `upper`.

By default, the function preserves the original casing.

|String

|`specials` +
__optional__
a| Determines whether to preserve strings with special characters, such as email addresses, URLs, and hyphenated phone numbers, as single tokens.

* If `true`, keeps strings with special characters as single tokens (for example, `user@example.com`).
* If `false`, splits strings on special characters (for example, `user`, `example`, `com`).

*Default:* `false`
+
NOTE: The `specials` option preserves special characters except at the end of a word.

|Boolean
|===

=== Return Value
An array of strings containing all of the tokens obtained from the input string.

=== Examples
NOTE: By default, for speed, the results are randomly ordered.
To make the difference more clear between the first two example queries, the `ARRAY_SORT()` function is used.

.List the tokens of an array where `specials` is FALSE
====
[source,sqlpp]
----
SELECT ARRAY_SORT(
  TOKENS( ['jim@example.com, kim@example.com, http://example.com/, 408-555-1212'],
          {'specials': false} ));
----

[source,json]
----
[
  {
    "$1": [
      "1212",
      "408",
      "555",
      "abc",
      "com",
      "http",
      "jim",
      "kim"
    ]
  }
]
----
====

.List the tokens of an array where `specials` is TRUE
====
[source,sqlpp]
----
SELECT ARRAY_SORT(
  TOKENS( ['jim@example.com, kim@example.com, http://example.com/, 408-555-1212'],
          {'specials': true} ));
----

[source,json]
----
[
  {
    "$1": [
      "1212",
      "408",
      "408-555-1212",
      "555",
      "abc",
      "com",
      "http",
      "http://example.com",
      "jim",
      "jim@example.com",
      "kim",
      "kim@example.com"
    ]
  }
]
----
====

.Convert all of the URL data into UPPER case and adds the full URL to the delimited words
====
include::ROOT:partial$query-context.adoc[tag=example]

[source,sqlpp]
----
SELECT ARRAY_SORT( TOKENS(url) ) AS defaulttoken,
       ARRAY_SORT( TOKENS(url, {"specials":true, "case":"UPPER"}) ) AS specialtoken
FROM hotel
LIMIT 1;
----

[source,json]
----
[
  {
    "defaulttoken": [
      "http",
      "org",
      "uk",
      "www",
      "yha"
    ],
    "specialtoken": [
      "HTTP",
      "HTTP://WWW.YHA.ORG.UK",
      "ORG",
      "UK",
      "WWW",
      "YHA"
    ]
  }
]
----
====

You can also use `{"case":"lower"}` or `{"case":"upper"}` to have case sensitive search.
Index creation and querying can use this and other parameters in combination.
These parameters should be passed within the query predicates as well.
The parameters and values must match exactly for {sqlpp} to pick up and use the index correctly.

.Create an index with `case` and use it your application
====
include::ROOT:partial$query-context.adoc[tag=example]

[source,sqlpp]
----
CREATE INDEX idx_url_upper_special ON hotel(
    DISTINCT ARRAY v FOR v IN
        TOKENS(url, {"specials":true, "case":"UPPER"})
    END );
----

[source,sqlpp]
----
SELECT name, address, url
FROM hotel
WHERE ANY v IN TOKENS(url, {"specials":true, "case":"UPPER"})
      SATISFIES v = "HTTP://WWW.YHA.ORG.UK"
      END;
----

[source,json]
----
{
    "results": [
        {
            "address": "Capstone Road, ME7 3JE",
            "name": "Medway Youth Hostel",
            "url": "http://www.yha.org.uk"
        }
    ]
}
----
====

