////
The libraries and scope section can be reused in the guides section
////
[#libraries-and-scopes]
= Libraries and Scopes

JavaScript functions are stored inside a _library_.
A library can contain one or more functions, and can also be assigned to a scope, which allows libraries to be partitioned for logical grouping.

// tag::scoping-diagram[]
.Javascript UDFs Structure
[plantuml#javascript-scopes,javascript-scopes,svg]
....
include::partial$diagrams/javascript-scopes.puml[]
....

As shown in xref:javascript-scopes[xrefstyle=short], a JavaScript function library can exist as:

* A global library accessible across the cluster.
* A library accessible within a scope.
// end::scoping-diagram[]

NOTE: You can find an introduction to scopes in our xref:tutorials:buckets-scopes-and-collections.adoc#scopes_and_collections[Couchbase Tutorials].

Furthermore, access restrictions can be applied to scopes, so that only certain groups of users will be able to access collections and libraries within that scope.

.Scopes for JavaScript Libraries
[plantuml#scopes-for-udf,udf-scopes-diagram,svg,subs=attributes]
....
include::partial$diagrams/udf-scopes-diagram.puml[]
....

You do not call a JavaScript function directly -- for example, `getBusinessDays(startDate, endDate)` as shown here.
Instead, you must define a {sqlpp} User-Defined Function to act as a reference caller to the JavaScript function.

In Couchbase terminology, you would set the query context to `travel-sample.inventory` in order to run the functions in `my-library`.