= Create a Synonym Collection and Documents
:page-topic-type: guide
:page-status: Couchbase Server 8.0
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Create a synonym collection and documents to define synonym mappings for search terms in a Search index.
:page-toclevels: 3

[abstract]
{description}

== Prerequisites

* Your user account has the xref:projects:project-roles.adoc#project-owner-role[`Project Owner`] or xref:projects:project-roles.adoc#project-cluster-manager-role[`Cluster Manager`] role for the project that contains your cluster.

* You have created a bucket and scope where you want to store your Search index and its synonym collections.
For more information, see xref:clusters:data-service/manage-buckets.adoc[] and xref:clusters:data-service/scopes-collections.adoc[].

== Procedure

To define the synonym mappings for a Search index, you must: 

. <<create-collection,>>
. <<create-documents,>>

[#create-collection]
=== Create a Synonym Collection

You can create a synonym collection like any other collection in {page-product-name}.
Create synonym collections to divide your synonyms based on language or other sorting criteria.

NOTE: You must create your synonym collections in the same bucket and scope where you want to create your Search index.

For more information about how to create a new collection, see xref:clusters:data-service/scopes-collections.adoc#create-collection[Create a Collection].

[#create-documents]
=== Create Synonym Documents

You can create the following types of synonym documents for use with the Search Service:

* <<uni,Unidirectional synonym documents>>
* <<bi,Bidirectional synonym documents>>

[#uni]
==== Create a Unidirectional Synonym Document 

Unidirectional synonym documents define a one-way synonym relationship.

A unidirectional synonym document contains an `input` array and a `synonyms` array.
Any search for a term in `input` can return any term in `synonyms`.

For example, a unidirectional synonym document for synonyms of the terms `happy`, `joyful`, and `cheerful` can be defined as: 

[source,json]
----
include::example$synonyms/unidirectional-synonym.jsonc[]
----

A search for `happy` could return results for `content`, `delighted`, `elated`, `glad`, or `pleased`.
A search for `cheerful` would not return results for `happy`. 

NOTE: You can only include a single `input` and `synonyms` array per unidirectional synonym document.

To insert a new document into your cluster with a command line tool or SDK, see xref:guides:creating-data.adoc[].

To import multiple documents into your cluster at one time with the Couchbase {page-ui-name}, command line tools, or an SDK, see xref:guides:load.adoc[].

[#bi]
==== Create a Bidirectional Synonym Document

Bidirectional synonym documents define a two-way synonym relationship.
All terms are contained in a single `synonyms` array. 
Any search for a term in the `synonyms` array can return any other term in the array.

For example, a bidirectional synonym document for synonyms of the word `happy` could be defined as:

[source,json]
----
include::example$synonyms/bidirectional-synonym.jsonc[]
----

A search for `cheerful`, `happy`, or 1 of the other terms in the array could return results for any other term.

NOTE: You can only include a single `synonyms` array per bidirectional synonym document.

To insert a new document into your cluster with a command line tool or SDK, see xref:guides:creating-data.adoc[].

To import multiple documents into your cluster at one time with the Couchbase {page-ui-name}, command line tools, or an SDK, see xref:guides:load.adoc[].

== Next Steps
To use your defined synonyms in a Search index, see xref:synonyms/add-synonym-source.adoc[].