= Add Course Enrollments
:description: Add enrollment information to the student records using the Couchbase SDK.
:page-topic-type: tutorial
:page-pagination: full
:page-toclevels: 2
:imagesdir: ../../images

[abstract]
{description}

== Prerequisites

* You have created a Capella operational free tier cluster.
For more information, see xref:get-started:create-account.adoc#getting-started[Create and Deploy Your Free Tier Operational Cluster].

* You have created the required bucket, scope, and collections.
For more information, see xref:buckets-scopes-and-collections.adoc[].

* You have installed the Java Software Development Kit (version 8, 11, 17, or 21).
** The recommended version is the latest Java LTS release.
Make sure to install the highest available patch for the LTS version. 

* You have installed https://maven.apache.org/[Apache Maven^] (version 3+).

* You have connected the Java SDK to your free tier cluster.
For more information, see xref:install-couchbase-java-sdk.adoc[].

* You have created student and course records on your cluster.
For more information, see xref:java-tutorial/create-records.adoc[].

== Add Enrollment Details

To add enrollment details to a student record:

. In your `java` directory, create a new file called `AddEnrollments.java`.
. Paste the following code block into your `AddEnrollments.java` file:
+
[source, java]
----
include::example$AddEnrollments.java[]
----
+
NOTE: Because this is a tutorial, you do not need to add an error check to make sure that your collection has returned an item.
In a live application, error checks must be made to prevent errors and keep the application running.
+
. In the `AddEnrollments.java` file, replace the `\<<connection-string>>`, `\<<username>>`, and `\<<password>>` placeholders with your cluster's public connection string, and the username and password from your cluster access credentials.
. Run the command `mvn install` to pull in all the dependencies and rebuild your application.
. Run the following command to insert the student record into the collection:
+
[source, sh]
----
mvn exec:java -Dexec.mainClass="AddEnrollments" -Dexec.cleanupDaemonThreads=false
----
+
. From the Capella UI, go to your free tier operational cluster.
. Go to the `student-record-collection` and click the document ID to see the new information you just added to Hilary's student record.

If you come across errors in your console, see xref:java-tutorial/tutorial-troubleshooting.adoc[].

== Next Steps

Explore more of Capella operational in the xref:develop:intro.adoc[developer documentation].