= Configure the Cluster Connection 
:description: Learn how to obtain the connection string and set up the cluster connection for the student cluster. 
:page-pagination: full
:page-topic-type: tutorial

[abstract]
{description}

== Cluster Connection

This tutorial uses a Java SDK to connect to your cluster. Before you can establish this connection, you must obtain the connection string, add an allowed IP address, and configure the cluster access credentials.  

To configure the connection: 

. On the *Operational Clusters* page, select *student-cluster*.

. Go to menu:Connect[SDKs].

. Note the public connection string. This is required to connect to the cluster.

. Add an allowed IP address. 

.. Go to the *Allowed IP Addresses* page from the link provided on the screen.

.. Click btn:[Add Allowed IP].

.. On the *Add Allowed IP* page, select btn:[Add Current IP Address] to automatically populate your public IP address. 

.. Click btn:[Add Allowed IP].  

. Create cluster access credentials.

.. Go to the *Cluster Access* page from the link provided on the screen.

.. Click btn:[Create Cluster Access].

.. Enter the access name. A sample name can be `administrator`.

.. Enter the password. A sample password can be `Password123#`. 

.. Under *Bucket Level Access*, select *student-bucket* and *art-school-scope*. 

.. Select access as *Read/Write*. 

== Next Steps

After implementing the data model, you can xref:java-tutorial/install-couchbase-java-sdk.adoc[set up a Couchbase SDK and connect it to your cluster to write your first application].