= Create Student and Course Records
:description: Learn how to use the SDK to create student and course records.
:page-pagination: full
:page-topic-type: tutorial

[abstract]
{description}

== Prerequisites

* You have created a Capella operational free tier cluster.
For more information, see xref:get-started:create-account.adoc#getting-started[Create and Deploy Your Free Tier Operational Cluster].

* You have created the required bucket, scope, and collections.
For more information, see xref:buckets-scopes-and-collections.adoc[].

* You have installed the Java Software Development Kit (version 8, 11, 17, or 21).
** The recommended version is the latest Java LTS release.
Make sure to install the highest available patch for the LTS version. 

* You have installed https://maven.apache.org/[Apache Maven^] (version 3+).

* You have connected the Java SDK to your free tier cluster.
For more information, see xref:java-tutorial/install-couchbase-java-sdk.adoc[].

== Create a Student Record

After connecting to your cluster, you can create a student record in the form of a JSON document inserted into the `student-record-collection`.

To create a student record:

. In your `java` directory, create a new file called `InsertStudent.java`.
. Paste the following code block into your `InsertStudent.java` file:
+
[source, java]
----
include::example$InsertStudent.java[]
----
+
. In the `InsertStudent.java` file, replace the `\<<connection-string>>`, `\<<username>>`, and `\<<password>>` placeholders with your cluster's public connection string, and the username and password from your cluster access credentials.
. Open a terminal window and navigate to your `student` directory.
. Run the command `mvn install` to pull in all the dependencies and rebuild your application.
. Run the following command to insert the student record into the collection:
+
[source, sh]
----
mvn exec:java -Dexec.mainClass="InsertStudent" -Dexec.cleanupDaemonThreads=false
----
+
. From the Capella UI, go to your free tier operational cluster and check the `student-record-collection` for the new student record you just added:
.. Go to menu:Data Tools[Documents].
.. Under *Get documents from*, select `student-bucket`, `art-school-scope`, and `student-record-collection`.
.. Click btn:[Get Documents].

You should see the document in the list of documents in the `student-record-collection`.

== Create Course Records

Creating course records is similar to creating student records.
To create course records:

. In your `java` directory, create a new file called `InsertCourses.java`.
. Paste the following code block into your `InsertCourses.java` file:
+
[source, java]
----
include::example$InsertCourses.java[]
----
+
. In the `InsertCourses.java` file, replace the `\<<connection-string>>`, `\<<username>>`, and `\<<password>>` placeholders with your cluster's public connection string, and the username and password from your cluster access credentials.
. Open a terminal window and navigate to your `student` directory.
. Run the command `mvn install` to pull in all the dependencies and rebuild your application.
. Run the following command to insert the student record into the collection:
+
[source, sh]
----
mvn exec:java -Dexec.mainClass="InsertCourses" -Dexec.cleanupDaemonThreads=false
----
+
. From the Capella UI, go to your free tier operational cluster and check the `course-record-collection` for the new course records you just added.

If you come across errors in your console, see xref:java-tutorial/tutorial-troubleshooting.adoc[].

== Next Steps

After adding course and student records to your cluster, you can xref:java-tutorial/retrieving-documents.adoc[retrieve documents from your cluster] with {sqlpp}.











