= Set Up and Connect the Couchbase Java SDK
:description: Learn how to configure the cluster connection and set up the Couchbase Java SDK to connect and interact with your student cluster.
:page-pagination: full
:page-topic-type: tutorial

[abstract]
{description}

== Prerequisites

* You have created a Capella operational free tier cluster.
For more information, see xref:get-started:create-account.adoc#getting-started[Create and Deploy Your Free Tier Operational Cluster].

* You have created the required bucket, scope, and collections.
For more information, see xref:buckets-scopes-and-collections.adoc[].

* You have installed the Java Software Development Kit (version 8, 11, 17, or 21).
** The recommended version is the latest Java LTS release.
Make sure to install the highest available patch for the LTS version.

* You have installed https://maven.apache.org/[Apache Maven^] (version 3+).

[TIP]
====
The easiest way to install and manage Java SDKs and Maven on your machine is through https://sdkman.io/install[SDKMan^].

After following the instructions to install SDKMan, open a terminal window and run the commands `sdk install java` and `sdk install maven` to install the latest versions of Java and Maven. 
====

For more information about the Java SDK installation, see the xref:java-sdk:project-docs:sdk-full-installation.adoc[full installation page].

== Configure Your Cluster Connection

Before you can establish a connection to your cluster, you must obtain the public connection string, add an allowed IP address, and configure cluster access credentials.

To configure your connection: 

. On the *Operational Clusters* page, click the name of your free tier operational cluster.

. Go to menu:Connect[SDKs].

. Make a note of the *Public Connection String*.
You'll need this to connect to the cluster.

. Add your current IP address as an allowed IP on your cluster. 
For more information, see xref:clusters:allow-ip-address.adoc[].

. Create new cluster access credentials.
+
Make sure to save the username and password for your credentials and give the credentials *Read/Write* access to the *student-bucket* and *art-school-scope*.
+
For more information, see xref:clusters:manage-database-users.adoc#create-database-credentials[Create Cluster Access Credentials].

You can now set up the Couchbase Java SDK and connect it to your cluster.

== Set Up the Java SDK

To set up the Java SDK:

. Create the following directory structure on your computer:
+
....
📂 ~ (your home directory)
  📂 student
    📂 src
      📂 main
        📂 java
....
+
. In the `student` directory, create a new file called `pom.xml`.
+
....
📂 ~ (your home directory)
  📂 student
    📃 pom.xml ⬅ here!
    📂 src
      📂 main
        📂 java
....
+
. Paste the following code block into your `pom.xml` file:
+
[source, xml]
----
include::example$pom.xml[]
----
+
. Open a terminal window and navigate to your `student` directory.
. Run the command `mvn install` to pull in all the dependencies and finish your SDK setup.

Next, connect the Java SDK to your cluster.


[#connect-to-the-cluster]
== Connect the SDK to Your Cluster

To connect to the cluster:

. In your `java` directory, create a new file called `ConnectStudent.java`.
+
....
📂 ~ (your home directory)
  📂 student
    📃 pom.xml
    📂 src
      📂 main
        📂 java
          📃 ConnectStudent.java ⬅ here!
....
+
. Paste the following code block into your `ConnectStudent.java` file:
+
[source, java]
----
include::example$ConnectStudent.java[]
----

. In the `ConnectStudent.java` file, replace the `\<<connection-string>>`, `\<<username>>`, and `\<<password>>` placeholders with your cluster's public connection string, and the username and password from your cluster access credentials.
+
[IMPORTANT]
====
You must re-run `mvn install` in your `student` directory whenever you make a change to a Java file to rebuild your application. 
====
+
. Open a terminal window and navigate to your `student` directory.
. Run the command `mvn install` to pull in all the dependencies and rebuild your application.
. Run the following command to check that the connection works:
+
[source, sh]
----
mvn exec:java -Dexec.mainClass="ConnectStudent" -Dexec.cleanupDaemonThreads=false
----
+
If the connection is successful, the collection name outputs in the console log.

If you come across errors in your console, see xref:java-tutorial/tutorial-troubleshooting.adoc[].


== Next Steps

After setting up and connecting the Java SDK, you can xref:java-tutorial/create-records.adoc[add student and course records to your cluster].