= Set Up the Couchbase Java SDK
:description: Set Up the Couchbase Java SDK to interact with your student database.
:page-topic-type: tutorial
:page-pagination: full

[abstract]
{description}

== Prerequisites

Before continuing the tutorial, you must first install the following:

* Java Software Development Kit (version {minimum-jdk-version})
* Apache Maven (version {minimum-maven-version})

[TIP]
====
The easiest way to install and manage Java SDKs and Maven on your machine is through https://sdkman.io/install[SDKMan^].

After following the instructions to install SDKMan, open a terminal window and run the commands `sdk install java` and `sdk install maven` to install the latest versions of Java and Maven. 
====


== Set Up the Java SDK

To set up the Java SDK:

. Create the following directory structure on your computer:
+
....
📂 ~ (your home directory)
  📂 student
    📂 src
      📂 main
        📂 java
....
+
. In the `student` directory, create a new file called `pom.xml`.
+
....
📂 ~ (your home directory)
  📂 student
  📃 pom.xml ⬅ here!
  📂 src
    📂 main
      📂 java
....
+
. Paste the following code block into your `pom.xml` file:
+
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>couchbase-java</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>16</maven.compiler.source>
        <maven.compiler.target>16</maven.compiler.target>
        <encoding>UTF-8</encoding>
        <project.build.sourceEncoding>${encoding}</project.build.sourceEncoding>
        <project.reporting.outputEncoding>${encoding}</project.reporting.outputEncoding>
        <project.resources.sourceEncoding>${encoding}</project.resources.sourceEncoding>
        <archetype.encoding>${encoding}</archetype.encoding>
    </properties>

    <dependencies> <!--1-->   
        <dependency>
            <groupId>com.couchbase.client</groupId>
            <artifactId>java-client</artifactId>
            <version>3.6.0</version>
        </dependency>
    </dependencies>

</project>
----
+
<1> The `<dependencies>` section of the code block lists all the libraries required to build your application.
In the case of the student record tutorial, you only need the Couchbase client SDK. 
+
. Open a terminal window and navigate to your `student` directory.
. Run the command `mvn install` to pull in all the dependencies and finish your SDK setup.


== Next Steps

After setting up the Java SDK, you can xref:java-tutorial/connect-to-database.adoc[use the SDK to connect to your Couchbase database].