= Retrieve Records
:description: Retrieve records or documents from your collections using {sqlpp}, Couchbase's SQL-based query language.
:page-topic-type: tutorial
:page-pagination: full
:page-toclevels: 2
:imagesdir: ../../images

[abstract]
{description}
You can retrieve your records using the <<#retrieve-with-query-editor,query editor>> or the <<#retrieve-with-sdk,SDK>>.

== Prerequisites

* You have created a Capella operational free tier cluster.
For more information, see xref:get-started:create-account.adoc#getting-started[Create and Deploy Your Free Tier Operational Cluster].

* You have created the required bucket, scope, and collections.
For more information, see xref:buckets-scopes-and-collections.adoc[].

* You have installed the Java Software Development Kit (version 8, 11, 17, or 21).
** The recommended version is the latest Java LTS release.
Make sure to install the highest available patch for the LTS version. 

* You have installed https://maven.apache.org/[Apache Maven^] (version 3+).

* You have connected the Java SDK to your free tier cluster.
For more information, see xref:java-tutorial/install-couchbase-java-sdk.adoc[].

* You have created student and course records on your cluster.
For more information, see xref:java-tutorial/create-records.adoc[].

[#retrieve-with-query-editor]
== With the Query Editor

To retrieve the records with the query editor, you must first define an index.

=== Define an Index

Before you can retrieve your records with the query editor, you must first define an index in your bucket.
The index helps your cluster find specific data when you run a query.

To define an index:

. In the navigation breadcrumbs in the Capella UI, do 1 of the following: 

.. Click your organization name and go to menu:Operational[]. 
.. Click your current project name or search for a project and go to menu:Operational[].
.. Expand the cluster breadcrumb and search for your free cluster.

. Click the name of your free tier operational cluster.

. Go to menu:Data Tools[Query]. 

. xref:clusters:query-service/query-workbench.adoc#specify-bucket-and-scope-context[Set your bucket and scope context] to the `student-bucket` and `art-school-scope`.

. Enter the following query into your query editor:
+
[source, sqlpp]
----
create primary index course_idx on `course-record-collection`
----
+
. Click btn:[Run] to create a single index called `course_idx` in your `course-record-collection`.

=== Retrieve Your Records

You can use the query editor to retrieve all course records at once, or narrow your search to retrieve records based on specific criteria.

==== Retrieve All Course Records

To retrieve all of your course records:

. Enter the following query into your query editor:
+
[source, sqlpp]
----
select crc.* from `course-record-collection` crc
----
+
. Click btn:[Run] to retrieve all course records.
+
[source, json]
----
[
  {
    "course-name": "art history",
    "credit-points": 100,
    "faculty": "fine art"
  },
  {
    "course-name": "fine art",
    "credit-points": 50,
    "faculty": "fine art"
  },
  {
    "course-name": "graphic design",
    "credit-points": 200,
    "faculty": "media and communication"
  }
]
----

==== Retrieve Course Records with Less than 200 Credits

You can expand your query to narrow your search further.
To retrieve only courses with less than 200 `credit-points`:

. Enter the following query into your query editor:
+
[source, sqlpp]
----
select crc.* from `course-record-collection` crc where crc.`credit-points` < 200
----
+
. Click btn:[Run] to retrieve all courses with less than 200 credits.
+
[source, json]
----
[
  {
    "course-name": "art history",
    "credit-points": 100,
    "faculty": "fine art"
  },
  {
    "course-name": "fine art",
    "credit-points": 50,
    "faculty": "fine art"
  }
]
----

=== Retrieve Record IDs

The `id` field is not automatically returned when you retrieve all of your course information.

The `id` is part of a document's meta structure, and to retrieve it you must adjust your {sqlpp} query and run it again:

. Enter the following query into your query editor:
+
[source, sqlpp]
----
select META().id, crc.* from `course-record-collection` crc where crc.`credit-points` < 200
----
+
The `META()` function call returns any property contained inside the document's metadata, including the ID.
+
. Click btn:[Run] to retrieve course records and their IDs.
+
[source, json]
----
[
  {
    "course-name": "art history",
    "credit-points": 100,
    "faculty": "fine art",
    "id": "ART-HISTORY-000001"
  },
  {
    "course-name": "fine art",
    "credit-points": 50,
    "faculty": "fine art",
    "id": "FINE-ART-000002"
  }
]
----


[#retrieve-with-sdk]
== With the SDK

You can also use {sqlpp} queries to retrieve your records with the SDK.
Unlike the query editor, you must include the name of the bucket and the scope to fully qualify the name of the collection in the {sqlpp} statement in your application. 
For example:

[source, sqlpp]
----
select crc.* from `student-bucket`.`art-school-scope`.`course-record-collection` crc
----

=== Retrieve Your Records

You can use the SDK to retrieve all course records at once, or narrow your search to retrieve records based on specific criteria.

==== Retrieve All Course Records

To retrieve all of your course records using the Java SDK:

. In your `java` directory, create a new file called `ArtSchoolRetriever.java`.
. Paste the following code block into your `ArtSchoolRetriever.java` file:
+
[source, java]
----
include::example$ArtSchoolRetrieverAll.java[]
----
+
. In the `ArtSchoolRetriever.java` file, replace the `\<<connection-string>>`, `\<<username>>`, and `\<<password>>` placeholders with your cluster's public connection string, and the username and password from your cluster access credentials.
. Open a terminal window and navigate to your `student` directory.
. Run the command `mvn install` to pull in all the dependencies and rebuild your application.
. Run the following command to retrieve all course records:
+
[source, sh]
----
mvn exec:java -Dexec.mainClass="ArtSchoolRetriever" -Dexec.cleanupDaemonThreads=false
----
+
If the retrieval is successful, the course information outputs in the console log.

==== Retrieve Course Records with Less than 200 Credits

You can set parameters in your code to narrow your search further.
To retrieve only courses with less than 200 `credit-points` using the Java SDK:

. In your `java` directory, create a new file called `ArtSchoolRetrieverParameters.java`.
. Paste the following code block into your `ArtSchoolRetrieverParameters.java` file:
+
[source, java]
----
include::example$ArtSchoolRetriever.java[]
----
+
. In the `ArtSchoolRetrieverParameters.java` file, replace the `\<<connection-string>>`, `\<<username>>`, and `\<<password>>` placeholders with your cluster's public connection string, and the username and password from your cluster access credentials.
. Open a terminal window and navigate to your `student` directory.
. Run the command `mvn install` to pull in all the dependencies and rebuild your application.
. Run the following command to retrieve all course records:
+
[source, sh]
----
mvn exec:java -Dexec.mainClass="ArtSchoolRetrieverParameters" -Dexec.cleanupDaemonThreads=false
----
+
If the retrieval is successful, the course information with your parameters outputs in the console log.

If you come across errors in your console, see xref:java-tutorial/tutorial-troubleshooting.adoc[].


== Next Steps

After retrieving student and course records, you can xref:java-tutorial/adding-course-enrollments.adoc[add enrollment details to the student records using the SDK].
