= Troubleshooting
:description: This page addresses errors you might come across when following the Student Record System tutorial.
:page-topic-type: tutorial

[abstract]
{description}

**Authentication error**

If you get an authentication error when running Maven commands in your console, confirm that the username and password in your Java file matches the username and password you used when setting up the Capella Operational cluster in your browser.

If they do not match, you can edit the Java file to add the correct username or password and try compiling and running the Maven command again.

// **IP address error**

// If you get a `DnsSrvLookupFailedEvent` error to specify your IP address in your console, go to your Java file and replace `localhost` with the IP address of your local Couchbase cluster in your browser. 

**SLF4J: Failed to load StaticLoggerBinder**

If you get a `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"` error, add an SLF4J binding to enable logging by including the following dependencies in your `pom.xml` file. 

[source, xml]
----
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>2.0.9</version>
</dependency>
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>2.0.9</version>
</dependency>
----

**Other build errors**

For any other build errors in your console, run `mvn install` and try the original command again.