[mermaid]
.Search Engine Architecture
----
flowchart LR
    jsons@{ shape: docs, label: "JSON documents" }
    subgraph engine [Search Engine]
        analyzer@{shape: process, label: "Text Analyzer"}
        index@{shape: flip-tri, label: "Inverted\nindex"}
        database@{shape: lin-cyl, label: "Databases"}
    end
    jsons --> analyzer
    analyzer --> index
    index --> database
----