// tag::dict[]
A `dict_compound` token filter uses a wordlist to find subwords inside an input token. 
If the token filter finds a subword inside a compound word, it turns it into a separate token. 

// tag::dict_example[]
[source,json]
----
include::example$complex-search-index-payload.jsonc[tag=dict_compound]
----
// end::dict_example[]

For example, if you had a wordlist that contained `play` and `jump`, the token filter converts `playful jumping` into two tokens: `play` and `jump`.

[plantuml,dict,svg]
....
@startuml

(playful jumping) as Start <<Input Token>>
(play) <<Output>>
(jump) <<Output>>
rectangle wordlist {
    usecase "play" as WL1
    usecase "jump" as WL2
}

Start --> (play) 
Start --> (jump)
@enduml
....
// end::dict[]

// tag::edge[]
An `edge_ngram` token filter uses a specified range to create new tokens. 
You can also choose whether to create the new token from the start or backward from the end of the input token. 

// tag::edge_example[]
[source,json]
----
include::example$complex-search-index-payload.jsonc[tag=edge_ngram]
----
// end::edge_example[]

For example, if you had a miminum of four and a maximum of five with an input token of `breweries`, the token filter creates the tokens `brew` and `brewe`.

[plantuml,edge,svg]
....
@startuml

(breweries) as Start <<Input Token>>
(brew) <<Output>>
(brewe) <<Output>>
rectangle range {
    usecase "min: 4" as R1
    usecase "max: 5" as R2
}

Start --> (brew) 
Start --> (brewe)
@enduml
....
// end::edge[]

// tag::elision[]
An `elision` token filter removes elisions from input tokens. 

// tag::elision_example[]
[source,json]
----
include::example$complex-search-index-payload.jsonc[tag=elision]
----
// end::elision_example[]

For example, if you had the `stop_fr` wordlist in an elision token filter, the token `je m'appelle John` becomes the tokens `je`, `appelle`, and `John`.

[plantuml,elision,svg]
....
@startuml

(je m'appelle John) as Start <<Input Token>>
(je) <<Output>>
(appelle) <<Output>>
(John) <<Output>>
rectangle wordlist {
    usecase "stop_fr" as WL1
}

Start --> (je) 
Start --> (appelle)
Start --> (John)
@enduml
....
// end::elision[]

// tag::keyword[]
A `keyword_marker` token filter finds keywords in an input token and turns them into tokens. 

// tag::keyword_example[]
[source,json]
----
include::example$complex-search-index-payload.jsonc[tag=keyword_marker]
----
// end::keyword_example[]

For example, if you had a wordlist that contained the keyword `beer`, the token `beer and breweries` becomes the token `beer`.

[plantuml,keyword,svg]
....
@startuml

(beer and breweries) as Start <<Input Token>>
(beer) <<Output>>
rectangle wordlist {
    usecase "beer" as WL1
}

Start --> (beer) 
@enduml
....
// end::keyword[]

// tag::length[]
A `length` token filter removes tokens that are shorter or longer than a set character length. 

// tag::length_example[]
[source,json]
----
include::example$complex-search-index-payload.jsonc[tag=length]
----
// end::length_example[]

For example, if you had a range with a minimum of two and a maximum of four, the token `beer and breweries` becomes the tokens `beer` and `and`.

[plantuml,length,svg]
....
@startuml

(beer and breweries) as Start <<Input Token>>
(beer) <<Output>>
(and) <<Output>>

Start --> (beer)
Start --> (and)
@enduml
....
// end::length[]

// tag::ngram[]
An `ngram` token filter uses a specified character length to split an input token into new tokens. 

// tag::ngram_example[]
[source,json]
----
include::example$complex-search-index-payload.jsonc[tag=ngram]
----
// end::ngram_example[]

For example, if you had a range with a minimum of four and a maximum of five, the token `beers` becomes the tokens `beer`, `beers`, and `eers`.

[plantuml,ngram,svg]
....
@startuml

(beers) as Start <<Input Token>>
(beer) <<Output>>
(beers) <<Output>>
(eers) <<Output>>

Start --> (beer)
Start --> (beers)
Start --> (eers) 
@enduml
....
// end::ngram[]

// tag::normalize[]
A `normalize_unicode` token filter uses a specified Unicode Normalization form to create new tokens. 

// tag::normalize_example[]
[source,json]
----
include::example$complex-search-index-payload.jsonc[tag=normalize_unicode]
----
// end::normalize_example[]
// end::normalize[]

// tag::shingle[]
A `shingle` token filter uses a specified character length and separator to create new tokens.

// tag::shingle_example[]
[source,json]
----
include::example$complex-search-index-payload.jsonc[tag=shingle]
----
// end::shingle_example[]

For example, if you use a xref:search:default-tokenizers-reference.adoc#whitespace[whitespace tokenizer], a range with a minimum of two and a maximum of three, and a space as a separator, the token `abc def` becomes `abc`, `def`, and `abc def`.

[plantuml,shingle,svg]
....
@startuml

(abc def) as Start <<Input Token>>

(abc) <<Output>>
(def) <<Output>>
(abc def) <<Output>>

Start --> (abc)
Start --> (def)
Start --> (abc def) 
@enduml
....
// end::shingle[]

// tag::stop[]
A `stop_tokens` token filter uses a wordlist to remove specific tokens from input. 

// tag::stop_example[]
[source,json]
----
include::example$complex-search-index-payload.jsonc[tag=stop_tokens]
----
// end::stop_example[]

For example, if you have a wordlist that contains the word `and`, the token `beers and breweries` becomes `beers` and `breweries`.

[plantuml,stop,svg]
....
@startuml

(beers and breweries) as Start <<Input Token>>
(beers) <<Output>>
(breweries) <<Output>>

rectangle wordlist {
    usecase "and" as WL1
}

Start --> (beers)
Start --> (breweries)
@enduml
....
// end::stop[]

// tag::truncate[]
A `truncate_token` token filter uses a specified character length to shorten any input tokens that are too long. 

// tag::truncate_example[]
[source,json]
----
include::example$complex-search-index-payload.jsonc[tag=truncate_token]
----
// end::truncate_example[]

For example, if you had a `length` of four, the token `beer and breweries` becomes `beer`, `and`, and `brewe`.

[plantuml,truncate,svg]
....
@startuml

(beer and breweries) as Start <<Input Token>>
(beer) <<Output>>
(and) <<Output>>
(brewe) <<Output>>

rectangle length {
    usecase "4" as L1
}

Start --> (beer)
Start --> (and)
Start --> (brewe)
@enduml
....
// end::truncate[]