:imagesdir: ../assets/images

=== Couchbase Clients

// tag::body[]
Clients access data by connecting to a Couchbase cluster over the network.
The most common type of client is a Couchbase SDK, which is a full programmatic API that enables applications to take the best advantage of Couchbase.
This developer guide focuses on the most commonly-used SDKs, but full explanations and reference documentation for all SDKs is available.

The Couchbase Shell (cbsh) also provides a quick and streamlined interface for simple access, and is suitable if you just want to access an item without writing any code.
Note that the Couchbase Shell is currently in preview and is not covered by support.

// tag::refs[]
Read the following for further information about the clients available:

* https://couchbase.sh/docs/[Couchbase Shell (cbsh)] -- preview
* xref:home::sdk.adoc[SDK Clients]
// end::refs[]

// tag::refs-ui[]
It is also possible to access document data via the Couchbase Capella UI.
// end::refs-ui[]
// end::body[]
