/* Data Control Language */

dcl-statement ::= grant
                | revoke

/* tag::grant[] */
grant ::= grant-user | grant-group
/* end::grant[] */

/* tag::grant-user[] */
grant-user ::= 'GRANT' role ( ',' role )* ( 'ON' keyspace-ref ( ',' keyspace-ref )* )?
          'TO' ('USER' | 'USERS')? user ( ',' user )*
/* end::grant-user[] */

/* tag::grant-group[] */
grant-group ::= 'GRANT' role ( ',' role )* ( 'ON' keyspace-ref ( ',' keyspace-ref )* )?
          'TO' ('GROUP'|'GROUPS') group ( ',' group )*          
/* end::grant-group[] */          

/* tag::revoke[] */
revoke ::= 'REVOKE' role ( ',' role )* ( 'ON' keyspace-ref ( ',' keyspace-ref )* )?
           'FROM' user ( ',' user )*
/* end::revoke[] */

role ::= identifier
user ::= identifier