/* Hints */

/* tag::hint-comment[] */
hint-comment ::= block-hint-comment | line-hint-comment
/* end::hint-comment[] */

/* tag::block-hint-comment[] */
block-hint-comment ::= '/*+' hints '*/'
/* end::block-hint-comment[] */

/* tag::line-hint-comment[] */
line-hint-comment ::= '--+' hints
/* end::line-hint-comment[] */

/* tag::hints[] */
hints ::= simple-hint-sequence | json-hint-object
/* end::hints[] */

/* tag::simple-hint-sequence[] */
simple-hint-sequence ::= simple-hint+
/* end::simple-hint-sequence[] */

/* tag::simple-hint[] */
simple-hint ::= ordered-hint-simple
              | gsi-hint-simple
              | gsi-all-hint-simple
              | fts-hint-simple
              | hash-hint-simple
              | nl-hint-simple
              | no-gsi-hint-simple
              | no-fts-hint-simple
              | no-hash-hint-simple
              | no-nl-hint-simple
/* end::simple-hint[] */

/* tag::ordered-hint-simple[] */
ordered-hint-simple ::= 'ORDERED'
/* end::ordered-hint-simple[] */

/* tag::gsi-hint-simple[] */
gsi-hint-simple ::= 'INDEX' '(' keyspace index* ')'
/* end::gsi-hint-simple[] */

/* tag::gsi-all-hint-simple[] */
gsi-all-hint-simple ::= 'INDEX_ALL' '(' keyspace index* ')'
/* end::gsi-all-hint-simple[] */

/* tag::fts-hint-simple[] */
fts-hint-simple ::= 'INDEX_FTS' '(' keyspace index* ')'
/* end::fts-hint-simple[] */

/* tag::nl-hint-simple[] */
nl-hint-simple ::= 'USE_NL' '(' ( keyspace )+ ')'
/* end::nl-hint-simple[] */

/* tag::hash-hint-simple[] */
hash-hint-simple ::= 'USE_HASH' '(' ( keyspace ( '/' ( 'BUILD' | 'PROBE' ) )? )+ ')'
/* end::hash-hint-simple[] */

/* tag::no-gsi-hint-simple[] */
no-gsi-hint-simple ::= ( 'NO_INDEX' | 'AVOID_INDEX' ) '(' keyspace index* ')'
/* end::no-gsi-hint-simple[] */

/* tag::no-fts-hint-simple[] */
no-fts-hint-simple ::= ( 'NO_INDEX_FTS' | 'AVOID_INDEX_FTS' ) '(' keyspace index* ')'
/* end::no-fts-hint-simple[] */

/* tag::no-hash-hint-simple[] */
no-hash-hint-simple ::= ( 'NO_USE_HASH' | 'AVOID_HASH' ) '(' ( keyspace ( '/' ( 'BUILD' | 'PROBE' ) )? )+ ')'
/* end::no-hash-hint-simple[] */

/* tag::no-nl-hint-simple[] */
no-nl-hint-simple ::= ( 'NO_USE_NL' | 'AVOID_NL' ) '(' ( keyspace )+ ')'
/* end::no-nl-hint-simple[] */

/* tag::json-hint-object[] */
json-hint-object ::= '{' json-hint (',' json-hint )* '}'
/* end::json-hint-object[] */

/* tag::json-hint[] */
json-hint ::= ordered-hint-json
             | gsi-hint-json
             | gsi-all-hint-json
             | fts-hint-json
             | hash-hint-json
             | nl-hint-json
             | no-gsi-hint-json
             | no-fts-hint-json
             | no-hash-hint-json
             | no-nl-hint-json
/* end::json-hint[] */

/* tag::ordered-hint-json[] */
ordered-hint-json ::= '"ordered"' ':' 'true'
/* end::ordered-hint-json[] */

/* tag::gsi-hint-json[] */
gsi-hint-json ::= '"index"' ':' ( index-array | index-object )
/* end::gsi-hint-json[] */

/* tag::gsi-all-hint-json[] */
gsi-all-hint-json ::= '"index"' ':' ( index-array | index-object )
/* end::gsi-all-hint-json[] */

/* tag::fts-hint-json[] */
fts-hint-json ::= '"index_fts"' ':' ( index-array | index-object )
/* end::fts-hint-json[] */

/* tag::nl-hint-json[] */
nl-hint-json ::= '"use_nl"' ':' ( keyspace-array | keyspace-object )
/* end::nl-hint-json[] */

/* tag::hash-hint-json[] */
hash-hint-json ::= '"use_hash"' ':' ( hash-array | hash-object )
/* end::hash-hint-json[] */

/* tag::no-gsi-hint-json[] */
no-gsi-hint-json ::= ( '"no_index"' | '"avoid_index"' ) ':' ( index-array | index-object )
/* end::no-gsi-hint-json[] */

/* tag::no-fts-hint-json[] */
no-fts-hint-json ::= ( '"no_index_fts"' | '"avoid_index_fts"' ) ':' ( index-array | index-object )
/* end::no-fts-hint-json[] */

/* tag::no-nl-hint-json[] */
no-nl-hint-json ::= ( '"no_use_nl"' | '"avoid_nl"') ':' ( keyspace-array | keyspace-object )
/* end::no-nl-hint-json[] */

/* tag::no-hash-hint-json[] */
no-hash-hint-json ::= ( '"no_use_hash"' | '"avoid_hash"' ) ':' ( hash-array | hash-object )
/* end::no-hash-hint-json[] */

/* tag::index-array[] */
index-array ::= '[' index-object ( ',' index-object )* ']'
/* end::index-array[] */

/* tag::index-object[] */
index-object ::= '{' keyspace-property ',' indexes-property '}'
/* end::index-object[] */

/* tag::indexes-property[] */
indexes-property ::= '"indexes"' ':' ( 'null'
                                     | '"' index '"'
                                     | '[' '"' index '"' ( ',' '"' index '"' )* ']' )
/* end::indexes-property[] */

/* tag::keyspace-array[] */
keyspace-array ::= '[' keyspace-object ( ',' keyspace-object )* ']'
/* end::keyspace-array[] */

/* tag::keyspace-object[] */
keyspace-object ::= '{' keyspace-property '}'
/* end::keyspace-object[] */

/* tag::keyspace-property[] */
keyspace-property ::= ( '"keyspace"' | '"alias"' ) ':' '"' keyspace '"'
/* end::keyspace-property[] */

/* tag::hash-array[] */
hash-array ::= '[' hash-object ( ',' hash-object )* ']'
/* end::hash-array[] */

/* tag::hash-object[] */
hash-object ::= '{' keyspace-property ( "," option-property )? '}'
/* end::hash-object[] */

/* tag::option-property[] */
option-property ::= '"option"' ':' ( '"build"' | '"probe"' | 'null' )
/* end::option-property[] */
