= Create a Custom Word List 
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Create a custom word list with the Couchbase {page-ui-name} to use with a custom token filter.

[abstract]
{description}

A custom xref:customize-index.adoc#wordlists[word list] gives greater control over the input you want to remove from xref:customize-index.adoc#tokenizers[tokenizer] results.
xref:customize-index.adoc#token-filters[Token filters] work with tokenizers to add, remove, or transform tokens for Search.

Only specific custom token filter types can use custom word lists: 

* xref:create-custom-token-filter.adoc#dict-compound[dict_compound]
* xref:create-custom-token-filter.adoc#elision[elision]
* xref:create-custom-token-filter.adoc#keyword-marker[keyword_marker]
* xref:create-custom-token-filter.adoc#stop-tokens[stop_tokens]

For more information about how to create a custom token filter, see xref:create-custom-token-filter.adoc[].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].
 
* You have logged in to the Couchbase {page-ui-name}. 

* You have started to create or already created an index in xref:create-search-indexes.adoc#advanced-mode[Advanced Mode Editing].

* You have already created or started to create a xref:create-custom-analyzer.adoc[custom analyzer] and xref:custom-token-filter.adoc[custom token filter] that can use a custom word list in your Search index.

== Procedure 

To create a custom word list with the {page-ui-name} in Advanced Mode: 

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create or use a token filter, custom analyzer, and custom word list.
. (Optional) If you did not create your index with Advanced Mode, select *Enable Advanced Options*.
. Expand *Global Index Settings*.
. Do one of the following: 
.. To create a new custom analyzer, click btn:[Add Custom Analyzer].
.. To edit the configuration on an existing custom analyzer, expand the *Default Analyzer* list, and next to your custom analyzer, click btn:[Edit].
. Do one of the following: 
.. To create a new custom token filter and word list, 
.. To create a new custom word list on an existing token filter, expand the *Token Filters* list, and next to your custom token filter, click btn:[Edit]. 
. Click btn:[Add Word list].
. In the *Name* field, enter a name for the word list. 
. In the *New Word* field, enter a word you want to add to the word list. 
. Click btn:[Add].
. (Optional) To add more words to the word list, repeat the previous steps. 
. Click btn:[Submit].

== Next Steps

After you create a custom word list, you can use it with xref:create-custom-token-filter.adoc[a custom token filter].

To continue customizing your Search index, you can also: 

* xref:set-advanced-settings.adoc[]
* xref:set-type-identifier.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[].