= Create a Child Mapping
:page-topic-type: guide
:description: Create a child mapping with the Couchbase Capella UI to add or remove a field that contains a JSON object from a Search index.

[abstract]
{description}

== Prerequisites 

* You've created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You've created a type mapping. 
For more information about how to create a type mapping on an index, see xref:create-type-mapping.adoc[].

* You've logged in to the Couchbase Capella UI. 

== Procedure 

To create a child mapping with the Capella UI:

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a child mapping.
. Under *Type Mappings*, next to an existing type mapping, go to menu:More Options (&vellip;)[Insert Child Mapping].
. In the *Name* field, enter the name of a field in a document that contains a JSON object. 
. (Optional) To set a different analyzer for the child mapping, in the *Analyzer* list, select an analyzer.
+
You can select a xref:default-analyzers-reference.adoc[default analyzer] or xref:create-custom-analyzer.adoc[create your own].  
. (Optional) To only index the fields you add to the child mapping, clear *Index all contained fields*. 
. Click btn:[Submit].
. Click btn:[Update Index].

== Next Steps

After you create a child mapping, you can choose to add or remove fields in the JSON object from your Search index. 

Both child mappings and type mappings use child fields to add and remove fields from a Search index. 

For more information about how to add or remove fields from a mapping, see xref:create-child-field.adoc[].

To continue customizing your Search index, you can also:

* xref:set-advanced-settings.adoc[]
* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].