= Create a Search Index 
:page-topic-type: concept 
:description: Create a Search index to get started with the Search Service in your database. 

[abstract]
{description}

You can create a Search index with: 

* The <<ui,Couchbase Capella UI>>. 
* With <<sdks,Couchbase SDKs>>.
* The <<api,Search Service REST API>>. 

TIP: If you're new to developing with the Search Service, xref:create-search-index-ui.adoc[create a Search index with the UI]. 
You can copy the JSON payload from the UI to create your index with the REST API. 

[#ui]
== Creating a Search Index with the Capella UI

To xref:create-search-index-ui.adoc[create a basic Search index], simply provide the following information:

* The desired index name. 
* The desired collection (or set of collections) under a single bucket and scope in your database.
//* The bucket, scope and collection where you want to create the index.
//* A xref:customize-index.adoc#type-mappings[type mapping] for the documents that you want to add to the index.

Once the index is created, the system streams data from the chosen collection(s) plus all subsequent mutations into the index builder.

Search indexes can be editied and further customized or modified to enhance search results and performance. For more details on customizing a Search Index using the Capella UI, refer to xref:customize-index.adoc[Customize a Search Index with the Capella UI].

[#sdks]
== Creating a Search Index with Couchbase SDKs

You can create a Search index with Couchbase SDKs.

For an example of directly using the Java SDK to create a Search index, see *NEED_NEW_EXAMPLE_PAGE*

For more information about Search in the various Couchbase SDKs, see *SDK_INTRO_PAGE*.

[#api]
== Creating a Search Index with the REST API

You can create a Search index with the REST API through a JSON payload.

Most properties in the JSON payload correspond to the settings found in the Capella UI. However, certain items remain fixed due to legacy and compatibility considerations.

For an example of directly using the REST API to create a Search index, see xref:create-search-index-rest-api.adoc[Create a Search Index with the REST API].

For more information about the available properties for a Search index, see xref:search-index-params.adoc[Search Index JSON Properties].
