= Create a Custom Date/Time Parser 
:page-topic-type: guide 
:description: Create a custom date/time parser with the Couchbase Server Web Console to tell the Search Service how to process a new date/time format.

[abstract]
{description}

If you store date data in a format other than RFC-3339 (ISO-8601), then you need to create a date/time parser.

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You have logged in to the Couchbase Server Web Console. 

== Procedure 

To create a custom date/time parser with the Couchbase Server Web Console: 

. Go to *Search*.
. Click the Search index where you want to create a custom date/time parser.
. Click btn:[Edit].
. Expand menu:Customize Index[Date/Time Parsers]. 
. Click btn:[Add Date/Time Parser]
. In the *Name* field, enter a name for the date/time parser. 
. In the *Layout to be added* field, enter a date/time layout with Go syntax. 
+
For more information, see the documentation about the https://pkg.go.dev/time#pkg-constants[Go Programming Language Time Package's Layout Constant^].
. Click btn:[Add]. 
. (Optional) To add an additional layout, repeat the previous steps. 
. Click btn:[Save].

== Next Steps

After you create a custom date/time parser, you can xref:set-advanced-settings.adoc#date-time[set it as the default date/time parser] for your Search index.

To continue customizing your Search index, you can also: 

* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:set-advanced-settings.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].