= Create a Search Index with the REST API and curl/HTTP 
:page-topic-type: guide
:description: You can create a Search index with the Search Service API. 

[abstract]
{description}

You must create a Search index before you can xref:simple-search-rest-api.adoc[run a search] with the Search Service.

== Prerequisites 

* You have the Search Service enabled on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* Your user account has the *Search Admin* role for the bucket where you want to create the index. 

* You've installed the Couchbase command-line tool (CLI).

* You have the hostname or IP address for your database. 

== Procedure 

To create a Search index with the REST API:

. In your command-line tool, enter a `curl` command with the `XPUT` verb. 
. Set your header content to include `Content-Type: application/json`.
. Enter your username, password, and the Search Service endpoint on port `8094` with the name of the index you want to create: 
+
[source,console]
----
include::example$create-search-index-header.sh[]
----
. Enter the JSON payload for the settings you want in your index. 
+
TIP: You can copy the Index Definition from the Couchbase Capella UI to use in your REST API call.
For more information about how to create an index with the UI, see xref:create-search-index-ui.adoc[].  
Additionally, make sure neither "uuid" nor "sourceUUID" are present, as this prevents the system from interpreting your action as an update and allows for index portability to a new cluster.
+
In the following example, the JSON payload creates a simple index named `landmark-content-index` on the `travel-sample` bucket. It creates a type mapping for the `inventory.landmark` collection, with a child field, `content`:
+
[source,console]
----
include::example$create-search-index-payload.sh[]
----
+
For more information about the available JSON properties for a Search index, see xref:search-index-params.adoc[].

== Next Steps

After you create a Search index, you can xref:simple-search-rest-api.adoc[] to test your Search index. 

You can also xref:simple-search-ui.adoc[] or with one of the Couchbase SDKs: 

include::partial$sdks-fts-links.adoc[]
