= Create a Custom Character Filter
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Create a custom character filter with the Couchbase {page-ui-name} to remove unwanted characters from a Search query or the contents of a Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].
 
* You have logged in to the Couchbase {page-ui-name}. 

* You have started to create or already created an index in xref:create-search-index-ui.adoc[Advanced Mode].

== Procedure 

To create a custom character filter with the {page-ui-name} in Advanced Mode:

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a custom character filter.
. Under *Advanced Settings*, expand *Custom Filters*. 
+
NOTE: Make sure you use *Advanced Mode*. 
. Click btn:[Add Character Filter].
. In the *Name* field, enter a name for the character filter. 
. In the *Regular Expression* field, enter the regular expression for the character filter. 
. (Optional) In the *Replacement* field, enter a string that replaces any matches for the regular expression. 
. Click btn:[Submit].

== Next Steps

After you create a custom character filter, you can use it with xref:create-custom-analyzer.adoc[a custom analyzer]. 

To continue customizing your Search index, you can also: 

* xref:set-advanced-settings.adoc[]
* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].