= Create a Child Mapping with the Web Console
:page-topic-type: guide

== Prerequisites 

* You've created an index.
For more information, see xref:search/create-search-index-ui.adoc[].

* You've created a type mapping. 
For more information about how to create a type mapping on an index, see xref:search/create-type-mapping.adoc[].

* You've logged in to the Couchbase Server Web Console. 

== Procedure 

To create a child mapping: 

. Go to *Search*.
. Click the index where you want to create a child mapping.
. Click btn:[Edit].
. Expand *Customize Index*. 
. Expand *Mappings*. 
. Point to an existing mapping and click btn:[+].
. Click *insert child mapping*. 
. In the *{}* field, enter the name of a JSON object field in your database's documents. 
. (Optional) To only index the fields you add to the child mapping, select *only index specified fields*. 
. (Optional) To set a different analyzer for the child mapping, in the *Analyzer* list, select an analyzer.
+
For more information about the available default analyzers, see xref:search/default-analyzers-reference.adoc[]. 
. Click btn:[OK].