= Create a Search Index 
:page-topic-type: concept 
:description: Create a Search index to get started with the Search Service in your database. 

[abstract]
{description}

You can create a Search index with: 

* The <<ui,Couchbase Capella UI>>. 
// * The <<sdks,Couchbase SDKs>>.
* The <<api,Search Service REST API>>. 

TIP: If you're new to developing with the Search Service, <<ui,create a Search index with the UI>>. 
You can export the Search index definition JSON payload from the UI to create your index xref:create-search-index-rest-api.adoc[with the REST API], or xref:import-search-index.adoc[]. 

[#ui]
== Creating a Search Index with the Capella UI

Couchbase Capella supports two editing modes for the Search Service: 

* xref:create-quick-index.adoc[Quick Mode]
* xref:create-search-index-ui.adoc[Advanced Mode]

[NOTE]
====
For indexes created with Couchbase Server version 7.6 and later, index names must be unique inside a bucket and scope.
You cannot have 2 indexes with the same name inside the same bucket and scope on a Capella database running version 7.6.

The Capella UI marks indexes as scoped or not scoped to a specific bucket and scope.

Indexes created with a previous version of Couchbase Server are not scoped. 
==== 

Use Quick Mode for a streamlined editing experience. 
Use Advanced Mode to fully customize your Search index with advanced settings and features.

After you create a Search index, the Search Service streams data from your chosen collection or collections, and any document mutations, into the index builder.
Before your index finishes building, you can run a search and return partial results. 

You can also customize a Search index to improve search results and performance. 
For more information about how you can customize a Search index with the Capella UI, see xref:customize-index.adoc[]. 

//[#sdks]
//== Creating a Search Index with Couchbase SDKs

//You can create a Search index with Couchbase SDKs.

//For an example of directly using the Java SDK to create a Search index, see *NEED_NEW_EXAMPLE_PAGE*

//For more information about Search in the various Couchbase SDKs, see *SDK_INTRO_PAGE*.

[#api]
== Creating a Search Index with the REST API

You can create a Search index with the REST API through a JSON payload.

Most properties in the JSON payload correspond to settings in the Capella UI. 
You can also copy the Search index definition JSON payload from a Search index in the Capella UI to use in a REST API call. 

[NOTE]
====
Use the scoped name for an index with the xref:rest-api:rest-fts.adoc[Search Service REST API] for any endpoints that do not include the bucket and scope in their path. 
For example, you must use `bucket.scope.index_name` as the format for your index name with the `analyzeDoc` endpoint, but not with the new 7.6 `query` endpoint.
====

For more information about how to use the REST API to create a Search index, see xref:create-search-index-rest-api.adoc[].

For more information about the available properties for a Search index, see xref:search-index-params.adoc[Search Index JSON Properties].

== See Also 

* xref:customize-index.adoc[]
* xref:index-aliases.adoc[]
* xref:run-searches.adoc[]
