= Create a Basic Search Index in Advanced Mode
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use Advanced Mode to create a Search index in the Couchbase {page-ui-name} with full customization and advanced features.

[abstract]
{description}

Use xref:create-quick-index.adoc[Quick Mode] if you do not need full customization or advanced settings to quickly create a Search index and xref:customize-index.adoc#type-mappings[type mappings].

You must create a Search index before you can xref:simple-search-ui.adoc[run a search] with the Search Service.

== Prerequisites

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your database. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have logged in to the Couchbase {page-ui-name}.

== Procedure 

To use Advanced Mode in Couchbase {page-product-name} to create a Search index:

. On the *Databases* page, select the database where you want to create a Search index. 
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
. Click btn:[Advanced Mode].
. In the *Index Name* field, enter a name for the Search index. 
+
[NOTE]
====
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

For Couchbase Server version 7.6 and later, your index name must be unique inside your selected bucket and scope. You cannot have 2 indexes with the same name inside the same bucket and scope.
====
 
. Under *Type Mappings*, in the *Bucket* list, select the bucket where you want to create your Search index.
. In the *Scope* list, select the scope where you want to create your Search index.
. Click btn:[Add Mapping].
. In the *Collection* list, select a collection for the type mapping.
. (Optional) To switch from a xref:customize-index.adoc#type-mappings[dynamic to a static type mapping], click *Index only specified fields*.
. Click btn:[Submit].
. (Optional) Do any of the following: 
.. If you created a xref:customize-index.adoc#type-mappings[static type mapping], then you should xref:create-child-field.adoc[add a child field] or xref:create-child-mapping.adoc[add a child mapping] to your type mapping to specify the documents you want to include in your index. 
.. Add additional features to your Search index to improve performance and search results.
For more information, see xref:customize-index.adoc[].
. Click btn:[Create Index].

== Next Steps 

If you did not create a static type mapping, this basic index includes all documents from the collection you selected. 
You can run a search against this index, but it's recommended that you customize your index to improve performance and reduce the index size. 
 
For more information about the different features you can add to your Search index to improve performance and search results, see xref:customize-index.adoc[].

For more information about how to run a search, see xref:simple-search-ui.adoc[].
