= Create a Search Index Alias with the Web Console
:page-topic-type: guide
:description: Use a Search index alias to run a Search query across multiple buckets, scopes, or Search indexes. 

[abstract]
{description}

For more information about Search index aliases, see xref:index-aliases.adoc[].

== Prerequisites

* You have created at least one Search index.
For more information, see xref:create-search-index-ui.adoc[].

* You have logged in to the Couchbase Server Web Console. 

== Procedure

To create a Search index alias with the Couchbase Server Web Console: 

. Go to *Search*.
. Click btn:[Add Alias].
. In the *Index Name* field, enter a name for your Search index alias. 
. In the *Target Indexes* list, use kbd:[CTRL] + click to select each Search index that you want to add to the index alias. 
. Click btn:[Create Index Alias].

== Next Steps

To customize a Search index, see xref:customize-index.adoc[].

To run a search and test the contents of your Search index or Search index alias, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].