= Create a Custom Analyzer 
:page-topic-type: guide
:description: Create a custom analyzer with the Couchbase Capella UI's Advanced Mode to modify the input text from a Search query or Search index and improve search results.

[abstract]
{description}

NOTE: You must use Advanced Mode to add a custom analyzer to your Search index.
For more information, see xref:create-search-index-ui.adoc[].

For more information, see xref:customize-index.adoc#analyzers[Search Index Features].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have created an index with xref:create-search-index-ui.adoc[Advanced Mode].

* You have logged in to the Couchbase Capella UI. 

== Procedure 

To create a custom analyzer with the Capella UI in Advanced Mode:

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a custom analyzer.
. Under *Advanced Settings*, expand *Analyzers*. 
+
NOTE: Make sure you use *Advanced Mode*. 
. Click btn:[Add Analyzer].
. In the *Name* field, enter a name for the new custom analyzer. 
. To remove specific characters from search input before tokenizing, in the *Character Filters* list, do one of the following:
.. To add a character filter to your analyzer, click a character filter. 
You can select a default character filter or create your own.
+
For more information, see xref:default-character-filters-reference.adoc[] or xref:create-custom-character-filter.adoc[].
.. To remove a character filter from your analyzer, click the *x* on a character filter.
. In the *Tokenizer* list, click the tokenizer you want to use to create tokens from Search input.
You can select a default tokenizer or create your own. 
+
For more information, see xref:default-tokenizers-reference.adoc[] or xref:create-custom-tokenizer.adoc[].
. To modify the tokens created by the tokenizer, in the *Token Filters* list, do one of the following: 
.. To add a token filter to your analyzer, click a token filter. 
You can select a default token filter or create your own. 
+
For more information, see xref:default-token-filters-reference.adoc[] or xref:create-custom-token-filter.adoc[].
.. To remove a token filter from your analyzer, click the *x* on a token filter.
. Click btn:[Submit].

== Next Steps

After you create a custom analyzer, you can xref:set-advanced-settings.adoc#default-analyzer[set it as the default analyzer] for your Search index. 

You can also use the custom analyzer when you xref:create-type-mapping.adoc[create a type mapping with Advanced Mode],  xref:create-child-mapping.adoc[a child mapping] or xref:create-child-field.adoc[a child field]. 

To continue customizing your Search index, you can also: 

* xref:set-advanced-settings.adoc[]
* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].