= Create a Search Index with the Quick Editor 
:page-topic-type: guide
:description: Use the Quick Index editor in Couchbase Server's Web Console to create a Search index.

[abstract]
{description}

The Quick Index editor lets you select the fields that you want to add to a Search index with a document in your database.

== Prerequisites 

* You have the Search Service enabled on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* Your user account has the *Search Admin* role for the bucket where you want to create the index. 

* You've logged in to the Couchbase Server Web Console. 

== Procedure 

To use the Couchbase Server Web Console's Quick Editor to create a Search index:

. Go to *Search*. 
. Click btn:[Quick Index].
. In the *Index Name* field, enter a name for the index. 
. In the first *Keyspace* list, select the bucket where you want to create the index. 
. In the second *Keyspace* list, select the scope where you want to create the index. 
. In the third *Keyspace* list, select the collection where you want to create the index. 
. In the *Select Fields* box, click a field in the document that you want to add to the index. 
. In the *Type* list, select the field's data type. 
+
For more information about the available data types, see xref:field-data-types-reference.adoc[].
. Set the field's options. 
+
For more information about the available field options, see xref:quick-index-field-options.adoc[].
. Click btn:[Add]. 
. (Optional) Repeat Steps 7-10 for each field you want to add to the Search index. 
. Click btn:[Create Index].  

== Next Steps 

You can xref:customize-index.adoc[customize your index] with the standard Search index editor to improve your Search index's performance and the quality of your search results. 

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].