= Create a Search Index 
:page-topic-type: concept 
:description: Create a Search index to get started with the Search Service in your database. 

[abstract]
{description}

You can create a Search index with: 

* The Couchbase Server Web Console. 
* The Search Service REST API. 

TIP: If you're new to developing with the Search Service, xref:create-search-index-ui.adoc[create a Search index with the UI]. 
You can copy the JSON payload from the UI to create your index with the REST API. 

== Creating a Search Index with the Web Console

To xref:create-search-index-ui.adoc[create a basic Search index], you only need to provide the following information: 

* The name of the index. 
* The bucket where you want to create the index. 

If you want to restrict the documents you add to an index, you can also: 

* xref:create-type-mapping.adoc[]. 
* xref:create-child-field.adoc[Add child fields] to add or remove document fields from the index. 

For more information about how you can customize a Search index, see xref:customize-index.adoc[].

The Web Console also has a xref:create-quick-index.adoc[Quick Index editor]. 
Use the Quick Index editor to create a Search index with a document from your database.
