= Create an XATTRs Mapping
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use the {page-ui-name} to create a mapping for Extended Attributes (XATTRs) and search for them with the Search Service.

[abstract]
{description}

You must add an XATTRs mapping to your Search index to use and search for XATTRs metadata in your documents. 

== Prerequisites

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You have created a type mapping for a collection. 
For more information about how to create a type mapping on an index, see xref:create-type-mapping.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 


== Procedure

To add an XATTRs mapping to your Search index from the {page-ui-name}:

. Go to *Search*.
. Click the index where you want to create an XATTRs mapping.
. Click btn:[Edit].
. Expand menu:Customize Index[Mappings].
. Point to an existing collection type mapping and click btn:[+].
. Click *insert xattrs mapping*. 
. (Optional) To only index the fields you add to the XATTRs mapping, select *only index specified fields*.
+
Otherwise, your XATTRs mapping is a xref:customize-index.adoc#type-mappings[dynamic mapping] that includes all child fields from your documents' metadata. 
. (Optional) To set a different analyzer for the XATTRs mapping, in the *Analyzer* list, select an analyzer.
+
You can select a xref:default-analyzers-reference.adoc[default analyzer] or xref:create-custom-analyzer.adoc[create your own]. 
. Click btn:[OK]. 

== Next Steps

After you create a XATTRs mapping, you can choose to add or remove fields in your document metadata from your Search index. 

XATTRs mappings, child mappings, and type mappings use child fields to add and remove fields from a Search index. 

For more information about how to add or remove fields from a mapping, see xref:create-child-field.adoc[].

To continue customizing your Search index, you can also:

* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:set-advanced-settings.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].