= Create a Search Index with the Quick Editor 
:page-topic-type: guide
:description: Use the Quick Index editor in Couchbase Server's Web Console to create a Search index.

[abstract]
{description}

The Quick Index editor lets you select the fields that you want to add to a Search index with a document in your database.

The Quick Index editor works best when you need to create a basic Search index.
If you want to have greater control over how the Search Service returns results, such as changing your xref:customize-index.adoc#analyzers[analyzer], see xref:create-search-index-ui.adoc[]. 

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have a bucket with scopes and collections in your database.
For more information about how to create a bucket, see xref:server:manage:manage-buckets/create-bucket.adoc[]. 

* Your user account has the *Search Admin* role for the bucket where you want to create the index. 

* You have logged in to the Couchbase Server Web Console. 

== Procedure 

To use the Couchbase Server Web Console's Quick Editor to create a Search index:

. Go to *Search*. 
. Click btn:[Quick Index].
. In the *Index Name* field, enter a name for the index. 
+
[NOTE]
====
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

As of version 7.6, your index name must be unique inside your selected bucket and scope.
You cannot have 2 indexes with the same name inside the same bucket and scope.
====
. In the first *Keyspace* list, select the bucket where you want to create the index. 
. In the second *Keyspace* list, select the scope where you want to create the index. 
. In the third *Keyspace* list, select the collection where you want to create the index. 
. In the *Select Fields* box, click a field in the document that you want to add to the index. 
. In the *Type* list, select the field's data type. 
+
For more information about the available data types, see xref:field-data-types-reference.adoc[].
. Set the field's options. 
+
For more information about the available field options, see xref:quick-index-field-options.adoc[].
. Click btn:[Add]. 
. (Optional) Repeat the previous steps for each field you want to add to the Search index. 
. Click btn:[Create Index].  

== Next Steps 

You can xref:customize-index.adoc[customize your index] with the standard Search index editor to improve your Search index's performance and the quality of your search results. 

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].