= Create a Custom Analyzer 
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Create a custom analyzer with the Couchbase {page-ui-name}'s Advanced Mode to modify the input text from a Search query or Search index and improve search results.

[abstract]
{description}

NOTE: You must use Advanced Mode to add a custom analyzer to your Search index.
For more information, see xref:create-search-indexes.adoc#advanced-mode[Advanced Mode Editing].

For more information, see xref:customize-index.adoc#analyzers[Search Index Features].

== Prerequisites 

* You have the Search Service enabled on a node in your operational cluster.
For more information about how to change Services on your operational cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To create a custom analyzer with the {page-ui-name} in Advanced Mode:

. On the *Operational Clusters* page, select the operational cluster where you want to work with the Search Service. 
. Go to menu:Data Tools[Search].
. Do one of the following:
.. To work with an existing Search index, click the name of the index where you want to create a custom analyzer.
.. To create a new Search index, click btn:[Create Search Index].
. Make sure to select *Enable Advanced Options*.
. Expand *Global Index Settings*. 
. Click btn:[Add Custom Analyzer].
. In the *Analyzer Name* field, enter a name for the new custom analyzer.
. <<configure-components,Configure the components of your analyzer>>.
. Click btn:[Add Custom Analyzer].

=== Configure Analyzer Components

For more information about analyzers and their components, see xref:customize-index.adoc#analyzers[Analyzers].

Add the following components to a custom analyzer to take input text from a document or Search query and convert it into tokens: 

. <<tokenizers,Tokenizers>>
. <<character-filters,Character Filters>>
. <<token-filters,Token Filters>>

[#tokenizers]
==== Configure Tokenizers 

For more information about tokenizers, see xref:customize-index.adoc#tokenizers[Tokenizers].

To configure the tokenizer for a custom analyzer: 

. (Optional) Create a custom tokenizer. 
For more information, see xref:create-custom-tokenizer.adoc[]. 
. In the *Tokenizer* list, select a tokenizer to use in your custom analyzer. 
You can choose your custom tokenizer or xref:default-tokenizers-reference.adoc[use a default tokenizer]. 

[#character-filters]
==== Configure Character Filters

For more information about character filters, see xref:customize-index.adoc#character-filters[Character Filters].

To add a character filter or character filters to a custom analyzer: 

. (Optional) Create 1 or more custom character filters. 
For more information, see xref:create-custom-character-filter.adoc[]. 
. In the *Character Filters* list, select 1 or more character filters to use in your custom analyzer. 
You can choose your custom character filter or xref:default-character-filters-reference.adoc[use the default character filters]. 

Remove a character filter from your custom analyzer by clicking the *x* next to a listed filter.

[#token-filters]
==== Configure Token Filters

For more information about token filters, see xref:customize-index.adoc#token-filters[Token Filters].

To add a token filter or token filters to a custom analyzer: 

. (Optional) Create 1 or more custom token filters. 
For more information, see xref:create-custom-token-filter.adoc[]. 
. In the *Token Filters* list, select 1 or more token filters to use in your custom analyzer. 
You can choose your custom token filter or xref:default-token-filters-reference.adoc[use the default token filters]. 

Remove a token filter from your custom analyzer by clicking the *x* next to a listed filter.

== Next Steps

After you create a custom analyzer, you can xref:create-search-index-ui.adoc#default-analyzer[set it as the default analyzer] for your Search index. 

You can also use the custom analyzer when you create a type mapping or mapping while you xref:create-search-index-ui.adoc[]. 

To continue customizing your Search index, you can also: 

* xref:set-type-identifier.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[].