= Create a Search Index with the Capella UI
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-aliases: create-quick-index.adoc, set-advanced-settings.adoc
:description: You can create a Search index using the Couchbase {page-ui-name} to generate a properly formatted Search index definition.
:page-toclevels: 3 

[abstract]
{description}

Use Advanced Mode to create a Search index in the Couchbase {page-ui-name} with full customization and advanced features, such as xref:create-custom-analyzer.adoc[creating custom analyzers] or xref:set-type-identifier.adoc[setting a document filter].

You must create a Search index before you can xref:simple-search-ui.adoc[run a search] with the Search Service.

== Prerequisites

* You have the Search Service enabled on a node in your operational cluster.
For more information about how to change Services on your operational cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your operational cluster. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have logged in to the Couchbase {page-ui-name}.

== Procedure 

To use the {page-ui-name} to create a Search index:

. On the *Operational Clusters* page, select the operational cluster where you want to create a Search index. 
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
. (Optional) To add additional customization options to your Search index, click btn:[Enable Advanced Mode].
. In the *Index Name* field, enter a name for the Search index. 
+
[NOTE]
====
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

For Couchbase Server version 7.6 and later, your index name must be unique inside your selected bucket and scope.
You cannot have 2 indexes with the same name inside the same bucket and scope.
====
 
. In the *Bucket* and *Scope* lists, choose the bucket and scope where you want to create your Search index.
. In the *Collections* list, select the collections you want to include in your Search index, or accept the default of *All*.
+
If you select specific collections, you can only use documents from these collections in your Search index.
. In the *Choose a Collection or Document Field* panel, click a collection name.
. Click *Index everything from: $COLLECTION_NAME*.
. Click btn:[Index All Fields].
. Click btn:[Add to Index].
. (Optional) <<configure-settings,Configure Global Index settings>>.
. (Optional) Expand *Replicas & Partitions* and configure your *Number of Replicas* and *Number of Partitions*. 
+
For more information, see xref:customize-index.adoc#replica[Replica and Partition Settings].
. Click btn:[Create Index].

[#configure-settings]
=== Configure Global Search Index Settings 

To configure global settings for your Search index: 

. Expand *Global Index Settings*:
.. [[default-analyzer]]In the *Default Analyzer* list, select the xref:customize-index.adoc#analyzers[default analyzer] to assign to new xref:customize-index.adoc#type-mappings[type mappings] in your index. 
.. [[date-time]]In the *Default Date/Time Parser* list, select the xref:customize-index.adoc#date-time[default date/time parser] to use for date data in your index. 
+
TIP: If you're editing your index in xref:create-search-indexes.adoc#advanced-mode[Advanced Mode Editing], you can also choose to xref:create-custom-analyzer.adoc[] or xref:create-custom-date-time-parser.adoc[]. 
. (Advanced Mode Only) In the *Configured Type Mappings* pane, under *Choose Document Filter*, xref:set-type-identifier.adoc[configure a document filter] for your Search index. 

== Next Steps 

Your Search index will contain documents that match the collection type mapping you specified. 
You can run a search against your index, but it's recommended that you create more xref:create-type-mapping.adoc[specific type mappings] to improve performance and reduce the index size. 
 
For more information about the different features you can add to your Search index to improve performance and search results, see xref:customize-index.adoc[].

For more information about how to run a search, see xref:simple-search-ui.adoc[].
