= Create a Search Index 
:page-topic-type: concept 
:description: Create a Search index to get started with the Search Service in your database. 

[abstract]
{description}

You can create a Search index with: 

* The <<ui,Couchbase Capella UI>>. 
* The <<api,Search Service REST API>>. 

TIP: If you're new to developing with the Search Service, xref:create-search-index-ui.adoc[create a Search index with the UI]. 
You can copy the JSON payload from the UI to create your index with the REST API. 

[#ui]
== Creating a Search Index with the Capella UI

To xref:create-search-index-ui.adoc[create a basic Search index], you only need to provide the following information: 

* The name of the index. 
* The bucket where you want to create the index. 
* The scope and collection where you want to create the index.
* A xref:customize-index.adoc#type-mappings[type mapping] for the documents that you want to add to the index.

After you create a Search index, you can customize it to improve search results and performance.
For more information about how you can customize a Search index with the Capella UI, see xref:customize-index.adoc[].

[#api]
== Creating a Search Index with the REST API

You can create a Search index with the REST API through a JSON payload.
The properties in the JSON payload correspond to the settings in the Capella UI. 

For more information about the available properties for a Search index, see xref:search-index-params.adoc[].