= Create a Type Mapping With The UI 
:page-topic-type: guide

== Prerequisites 

* You've created an index.
For more information, see xref:guides:search/create-search-index-ui.adoc[].
 
* You've logged in to the Capella UI. 

== Procedure 

To create a type mapping for a Search index with the Capella UI: 

. From your organization page, select the database where you want to create a type mapping. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a type mapping. 
. Expand *Advanced Configuration*. 
. Expand *Type Mappings*. 
. Click btn:[Add Type Mapping]. 
. In the *Collection* list, select the collection where you want to create the type mapping. 
. (Optional) To use a specific analyzer for documents in the type mapping, in the *Default Analyzer* list, select an analyzer. 
+
You can xref:guides:search/default-analyzers-reference.adoc[use a default analyzer] or xref:guides:search/create-custom-analyzer.adoc[create your own].
. (Optional) To switch from a xref:guides:search/customize-index.adoc#type-mappings[dynamic type mapping to a static type mapping], clear *Index all contained fields*. 
.. To choose which fields to add or remove from the static type mapping, see xref:guides:search/create-child-field.adoc[].
. (Optional) To add a child type mapping for a document field that contains a JSON object, see xref:guides:search/create-child-mapping.adoc[].
. Click btn:[Submit].