= Create a Custom Character Filter 
:page-topic-type: guide
:description: Create a custom character filter with the Couchbase Server Web Console to remove unwanted characters from a Search query or the contents of a Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You have logged in to the Couchbase Server Web Console. 

== Procedure 

To create a custom character filter with the Couchbase Server Web Console: 

. Go to *Search*.
. Click the Search index where you want to create a custom character filter.
. Click btn:[Edit].
. Expand menu:Customize Index[Custom Filters]. 
. Click btn:[Add Character Filter].
. In the *Name* field, enter a name for the character filter. 
. In the *Regular Expression* field, enter the regular expression for the character filter. 
. (Optional) In the *Replacement* field, enter a string that replaces any matches for the regular expression. 
. Click btn:[Save].

== Next Steps

After you create a custom character filter, you can use it with xref:create-custom-analyzer.adoc[a custom analyzer]. 

To continue customizing your Search index, you can also: 

* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:set-advanced-settings.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].