= Create a Search Index Alias with the Capella UI
:page-topic-type: guide
:description: Use a Search index alias to run a Search query across multiple buckets, scopes, or Search indexes. 

[abstract]
{description}

For more information about Search index aliases, see xref:index-aliases.adoc[].

== Prerequisites

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have created at least one Search index.
For more information, see xref:create-search-index-ui.adoc[].

* You have logged in to the Couchbase Capella UI. 

== Procedure

To create a Search index alias with the Capella UI: 

. On the *Databases* page, select the database where you want to create a Search index alias.
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Alias].
. In the *Alias Name* field, enter a name for your Search index alias. 
. In the *Target Indexes* list, select each Search index that you want to add to the index alias. 
. Click btn:[Create Alias].

== Next Steps

To customize a Search index, see xref:customize-index.adoc[].

To run a search and test the contents of your Search index or Search index alias, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].