= Create a Child Field
:page-topic-type: guide
:description: Create a child field with the Couchbase Server Web Console to add or remove a specific field's content from a Search index.

[abstract]
{description}

== Prerequisites 

* You've created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You've created a type mapping. 
For more information about how to create a type mapping on an index, see xref:create-type-mapping.adoc[].

* You've logged in to the Couchbase Server Web Console. 
 

== Procedure 

To add or remove a child field from a Search index with the Couchbase Server Web Console:

. Go to *Search*.
. Click the index where you want to create a child field.
. Click btn:[Edit].
. Expand *Customize Index*. 
. Expand *Mappings*. 
. Point to an existing mapping and click btn:[+].
. Click *insert child field*. 
. In the *Field* field, enter the name of a field in your documents that you want to add or remove from the index.
+
NOTE: The field must contain either a single value or an array. If the field contains a JSON object, xref:create-child-mapping.adoc[], instead.  
. In the *Type* list, select the data type for the field: 
+
For more information about the available data types, see xref:field-data-types-reference.adoc[].

. Configure optional settings for the child field: 
+
|====
|Option |Description 

|Searchable As a|

Set a different name that you can use to search the field's contents in a query. 

The default value is the value set in *Field*.

|Analyzer a|

Choose an analyzer for the content in the child field. 

You can choose a default analyzer or a custom analyzer. 

For more information about the available default analyzers, see xref:default-analyzers-reference.adoc[].

For more information about how to create a custom analyzer, see xref:create-custom-analyzer.adoc[].

|Index a|

To include the child field in the index, select *Index*. 

To remove the child field from the index, clear *Index*. 

|[[store]]Store a|

To store the values from the field in the index and return them in search results, select *Store*.
This increases your index's size and indexing time.  

To remove the field's values from the index, clear *Store*.

|Include in _all field a|

The `_all` field is a composite field that has the content from multiple fields in an index. 
It allows searches to query the content of a field without specifying the field's name. 

To include this field in the `_all` field, select *Include in _all field*. 

To exclude this field from the `_all` field, clear *Include in _all field*. 

TIP: To change the name of the `_all` field, see xref:set-advanced-settings.adoc#all-field[Default Field].

|Include Term Vectors a|

Term vectors store the location of terms in a field for an index. 
You can use term vectors to highlighting matching search terms in search results, and perform phrase searches.
Term vectors increase your index's size and indexing time.  

To enable term vectors for this field, select *Include Term Vectors*.

To turn off term vectors, clear *Include Term Vectors*. 

NOTE: To enable term vectors, you must also enable <<store,Store>>. 

|Doc Values a|

Doc values are the value for each instance of the field in an index. 
Use doc values for Search xref:search-request-params.adoc#facets[Facets] and sorting search results. 

To store doc values, select *Doc Values*. 

To exclude doc values from the index, clear *Doc Values*. 
|==== 
. Click btn:[OK].

== Next Steps

You can continue to create child fields to add or remove the contents of a document from your Search index. 

If a field in your documents contains a JSON object, xref:create-child-mapping.adoc[], instead. 

To continue customizing your Search index, you can also:

* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:set-advanced-settings.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].