= Create a Child Mapping
:page-topic-type: guide
:description: Create a child mapping with the Couchbase Capella UI to add or remove a field that contains a JSON object from a Search index.

[abstract]
{description}

After you create a child mapping, you can choose to add or remove fields in the JSON object from your Search index. 
For more information about how to add or remove fields from a mapping, see xref:create-child-field.adoc[].

== Prerequisites 

* You've created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You've created a type mapping. 
For more information about how to create a type mapping on an index, see xref:create-type-mapping.adoc[].

* You've logged in to the Couchbase Capella UI. 

== Procedure 

To create a child mapping: 

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a child mapping.
. Expand *Advanced Configuration*. 
. Expand *Type Mappings*. 
. Next to an existing type mapping, click the *More Options* (&vellip;) menu.
. Click *Insert Child Mapping*. 
. In the *Name* field, enter the name of a JSON object field in your database's documents. 
. (Optional) To set a different analyzer for the child mapping, in the *Analyzer* list, select an analyzer.
+
For more information about the available default analyzers, see xref:default-analyzers-reference.adoc[]. 
. (Optional) To only index the fields you add to the child mapping, clear *Index all contained fields*. 
. Click btn:[Submit].
. Click btn:[Update Index].