= Create a Child Field in Advanced Mode
:page-topic-type: guide
:description: Create a child field with the Couchbase Capella UI's Advanced Mode to add or remove a specific field's content from a Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You have created a type mapping. 
For more information about how to create a type mapping on an index, see xref:create-type-mapping.adoc[].

* You have logged in to the Couchbase Capella UI. 

* You have started to create or already created an index in xref:create-search-index-ui.adoc[Advanced Mode].
 
== Procedure 

To add or remove a child field from a Search index with the Capella UI:

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a child field.
. Under *Type Mappings*, next to an existing type mapping, go to menu:More Options (&vellip;)[Insert Child Field].
. In the *Field* field, enter the name of a field in your documents that you want to add or remove from the index.
+
NOTE: The field must contain either a single value or an array. If the field contains a JSON object, xref:create-child-mapping.adoc[Create a Child Mapping], instead. 
. In the *Type* list, select the data type for the field: 
+
For more information about the available data types, see xref:field-data-types-reference.adoc[].

. Configure optional settings for the child field.
+
For more information about the available settings for child fields, see xref:child-field-options-reference.adoc[].
. Click btn:[Submit].
. Click btn:[Update Index].

== Next Steps

You can continue to create child fields to add or remove the contents of a document from your Search index. 

If a field in your documents contains a JSON object, xref:create-child-mapping.adoc[], instead. 

To continue customizing your Search index, you can also:

* xref:set-advanced-settings.adoc[]
* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].