= Create a Custom Analyzer
:page-topic-type: guide
:description: Create a custom analyzer with the Couchbase Server Web Console to modify the input text from a Search query or Search index and improve search results.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You have logged in to the Couchbase Server Web Console. 

== Procedure 

To create a custom analyzer with the Couchbase Server Web Console: 

. Go to *Search*. 
. Click the Search index where you want to create a custom analyzer.
. Click btn:[Edit].
. Expand menu:Customize Index[Analyzers]. 
. Click btn:[Add Analyzer].
. In the *Name* field, enter a name for the new custom analyzer. 
. To remove specific characters from search input before tokenizing, in the *Character Filters* list, do one of the following:
.. To add a character filter to your analyzer, select a character filter and click btn:[+ Add]. 
You can select a default character filter or create your own.
+
For more information, see xref:default-character-filters-reference.adoc[] or xref:create-custom-character-filter.adoc[].
.. To remove a character filter from your analyzer, click btn:[remove].
. In the *Tokenizer* list, click the tokenizer you want to use to create tokens from Search input.
You can select a default tokenizer or create your own. 
+
For more information, see xref:default-tokenizers-reference.adoc[] or xref:create-custom-tokenizer.adoc[].
. To modify the tokens created by the tokenizer, in the *Token Filters* list, do one of the following: 
.. To add a token filter to your analyzer, select a token filter and click btn:[+ Add]. 
You can select a default token filter or create your own. 
+
For more information, see xref:default-token-filters-reference.adoc[] or xref:create-custom-token-filter.adoc[].
.. To remove a token filter from your analyzer, click btn:[remove].
. Click btn:[Save].

== Next Steps

After you create a custom analyzer, you can xref:set-advanced-settings.adoc#default-analyzer[set it as the default analyzer] for your Search index. 

You can also use the custom analyzer when you xref:create-type-mapping.adoc[], xref:create-child-mapping.adoc[], and xref:create-child-field.adoc[]. 

To continue customizing your Search index, you can also: 

* xref:set-type-identifier.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:set-advanced-settings.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].