= Create a Search Index in Quick Mode
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use Quick Mode to create a Search index in the Couchbase {page-ui-name} with streamlined options.

[abstract]
{description}

Quick Mode works best when you need to create a basic Search index to start testing and prototyping with the Search Service.
You must use Advanced Mode to have greater control over how the Search Service returns such results, such as changing your xref:customize-index.adoc#analyzers[analyzer]. 

For more information about how to create a Search index in Advanced Mode, see xref:create-search-index-ui.adoc[].

You must create a Search index before you can xref:simple-search-ui.adoc[run a search] with the Search Service.

== Prerequisites 

* You have the Search Service enabled on a node in your cluster.
For more information about how to change Services on your cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your cluster. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To use Quick Mode in Couchbase {page-product-name} to create a Search index:

. On the *Databases* page, select the cluster where you want to create a Search index.
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
+
By default, *Quick Mode* should be on.
. In the *Index Name* field, enter a name for the index. 
+
[NOTE]
====
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

For Couchbase Server version 7.6 and later, your index name must be unique inside your selected bucket and scope.
You cannot have 2 indexes with the same name inside the same bucket and scope.
====
. Under *Type Mappings*, in the *Bucket* list, select the bucket where you want to create your Search index. 
. In the *Scope* list, select the scope where you want to create the index. 
. Choose a type mapping to add to your index: 
.. To add an entire collection as a type mapping, select a collection name.
.. To only add a single field as a type mapping, expand a collection, then select a field from your document schema.
. Configure the options for your new type mapping. 
For more information about the available options, see xref:create-type-mapping.adoc[].
. Click btn:[Add].
. (Optional) Add additional collections or field type mappings to your index. 
. Click btn:[Create Index].

== Next Steps 

If you want to add more advanced settings and customization to your Search index, you can xref:create-search-index-ui.adoc[use Advanced Mode]. 

CAUTION: If you edit your Search index in Advanced Mode, you cannot return to Quick Mode and keep any Advanced Mode settings. 

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[].