= Create a Search Index 
:page-topic-type: concept 
:description: Create a Search index to get started with the Search Service in your database. 

[abstract]
{description}

You can create a Search index with: 

* The Couchbase Capella UI. 
* The Search Service REST API. 

TIP: If you're new to developing with the Search Service, xref:create-search-index-ui.adoc[create a Search index with the UI]. 
You can copy the JSON payload from the UI to create your index with the REST API. 

== Creating a Search Index with the Capella UI

To xref:create-search-index-ui.adoc[create a basic Search index], you only need to provide the following information: 

* The name of the index. 
* The bucket where you want to create the index. 
* The scope and collection where you want to create the index.
* A xref:customize-index.adoc#type-mappings[type mapping] for the documents that you want to add to the index.
+
For more information about how to create a type mapping, see xref:create-type-mapping.adoc[].

If you want to restrict the document fields added to an index, you can also xref:create-child-field.adoc[add and remove child fields]. 

For more information about how you can customize a Search index, see xref:customize-index.adoc[].
