= Create a Type Mapping with the Capella UI
:page-topic-type: guide
:description: Create a type mapping to control what documents are included or excluded from a Search index. 

[abstract]
{description}
For more information, see xref:customize-index.adoc#type-mappings[].

== Prerequisites 

* You've created an index.
For more information, see xref:create-search-index-ui.adoc[].
 
* You've logged in to the Couchbase Capella UI. 

== Procedure 

To create a type mapping with the Capella UI: 

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a type mapping.
. Expand *Advanced Configuration*. 
. Expand *Type Mappings*. 
. Click btn:[+ Add Mapping].  
. In the *Collection* list, select the collection where you want to create the type mapping. 
. (Optional) To use a specific analyzer for documents in the type mapping, in the *Analyzer* list, select an analyzer. 
+
You can xref:default-analyzers-reference.adoc[use a default analyzer] or xref:create-custom-analyzer.adoc[create your own].
By default, the mapping inherits the default analyzer you set for the Search index.
. (Optional) To switch from a xref:customize-index.adoc#type-mappings[dynamic type mapping to a static type mapping], clear *Index all contained fields*. 
.. To choose which fields to add or remove from a static type mapping, see xref:create-child-field.adoc[].
. (Optional) To add a child mapping for any document fields that contain a JSON object, see xref:create-child-mapping.adoc[].
. Click btn:[Submit].