= Create a Custom Date/Time Parser
:page-topic-type: guide 

If you store date data in a format other than RFC-3339 (ISO-8601), then you need to create a date/time parser.

== Prerequisites 

* You've logged in to the Capella UI. 

== Procedure 

To create a custom date/time parser: 

. From your organization page, select the database where you want to create a custom date/time parser. 
. Go to menu:Data Tools[Search].
. Do one of the following: 
.. To create a custom date/time parser on an existing Search Index, click the index name.
.. To create a custom date/time parser on a new Search Index, click btn:[Add Search Index].
. Expand *Advanced Configuration*. 
. Expand *Date/Time Parsers*. 
. Click btn:[Add Date/Time Parser]
. In the *Name* field, enter a name for the date/time parser. 
. In the *New Word* field, enter a date/time layout with Go syntax. 
+
For more information, see the documentation about the https://pkg.go.dev/time#pkg-constants[Go Programming Language Time Package's Layout Constant^].
. Click btn:[Add]. 
. (Optional) To add an additional layout, repeat Steps 8-9. 
. Click btn:[Save].