= Create a Custom Wordlist 
:page-topic-type: guide
:description: Create a custom wordlist with the Couchbase Capella UI to use with a custom token filter.

[abstract]
{description}

A custom wordlist gives greater control over the input you want to remove from xref:customize-index.adoc#tokenizers[tokenizer] results. 

For more information about how to create a custom token filter, see xref:create-custom-token-filter.adoc[].

== Prerequisites 

* You've created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You've logged in to the Couchbase Capella UI. 

== Procedure 

To create a custom wordlist with the Capella UI: 

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a custom wordlist.
. Expand *Advanced Configuration*. 
. Expand *Custom Filters*. 
. Click btn:[Add Wordlist].
. In the *Name* field, enter a name for the wordlist. 
. In the *New Word* field, enter a word you want to add to the wordlist. 
. Click btn:[Add].
. (Optional) To add more words to the wordlist, repeat Steps 8-9. 
. Click btn:[Submit].

== Next Steps

After you create a custom wordlist, you can use it with xref:create-custom-token-filter.adoc[a custom token filter].

To continue customizing your Search index, you can also: 

* xref:set-advanced-settings.adoc[]
* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].