= Create a Search Index 
:page-topic-type: concept 
:description: Create a Search index to get started with the Search Service in your database. 

[abstract]
{description}

You can create a Search index with: 

* The <<ui,Couchbase Capella UI>>. 
// * The <<sdks,Couchbase SDKs>>.
* The <<api,Search Service REST API>>. 

TIP: If you're new to developing with the Search Service, xref:create-search-index-ui.adoc[create a Search index with the UI]. 
You can copy the Search index definition JSON payload from the UI to create your index xref:create-search-index-rest-api.adoc[with the REST API]. 

[#ui]
== Creating a Search Index with the Capella UI

To xref:create-search-index-ui.adoc[create a basic Search index], provide the following information:

* The name of the index. 
* The bucket, scope and collection or collections where you want to create the index.
* A xref:customize-index.adoc#type-mappings[type mapping] for the documents that you want to add to the index.

[NOTE]
====
As of version 7.6, your index name must be unique inside its bucket and scope. You cannot have 2 indexes with the same name inside the same bucket and scope.

//// 
TODO
Verify this for Capella - how can you view the scoped name?
To view the full, scoped name for an index, go to the Search tab and point to the Index Name. Use the scoped name with the Search Service REST API, for any endpoints that do not include the bucket and scope in their path.
//// 

====

After you create a Search index, the Search Service streams data from your chosen collection or collections, and any document mutations, into the index builder.
Before your index finishes building, you can run a search and return partial results. 

You can also customize a Search index to improve search results and performance. 
For more information about how you can customize a Search index with the Capella UI, see xref:customize-index.adoc[]. 

//[#sdks]
//== Creating a Search Index with Couchbase SDKs

//You can create a Search index with Couchbase SDKs.

//For an example of directly using the Java SDK to create a Search index, see *NEED_NEW_EXAMPLE_PAGE*

//For more information about Search in the various Couchbase SDKs, see *SDK_INTRO_PAGE*.

[#api]
== Creating a Search Index with the REST API

You can create a Search index with the REST API through a JSON payload.

Most properties in the JSON payload correspond to settings in the Capella UI. 
You can also copy the Search index definition JSON payload from a Search index in the Capella UI to use in a REST API call. 

For more information about how to use the REST API to create a Search index, see xref:create-search-index-rest-api.adoc[].

For more information about the available properties for a Search index, see xref:search-index-params.adoc[Search Index JSON Properties].

== See Also 

* xref:customize-index.adoc[]
* xref:index-aliases.adoc[]
* xref:run-searches.adoc[]
