= Create a Search Index 
:page-topic-type: concept
:page-ui-name: {ui-name}
:page-product-name: {product-name} 
:page-aliases: fts:fts-quickstart-guide.adoc, fts:fts-creating-indexes.adoc, fts:fts-creating-index-with-rest-api.adoc, fts:fts-creating-index-from-UI-difference-between-classic-quick-editor.adoc
:description: Create a Search index to get started with the Search Service in your cluster. 

[abstract]
{description}

You can create a Search index with: 

* The <<ui,Couchbase {page-ui-name}>>. 
* The <<api,Search Service REST API>>. 

TIP: If you're new to developing with the Search Service, <<ui,create a Search index with the UI>>. 
You can copy the Search index definition JSON payload from the UI to create your index xref:create-search-index-rest-api.adoc[with the REST API], or xref:import-search-index.adoc[].

As of Couchbase Server version 8.0, you can also add synonym collections to your cluster and Search index to run synonym searches on text fields.
For more information about synonym searches, see xref:synonyms/synonyms-search.adoc[].

[#ui]
== Creating a Search Index with the Web Console

To xref:create-search-index-ui.adoc[create a basic Search index], provide the following information: 

* The name of the index. 
* The bucket where you want to create the index. 

Many of the examples in the Search Service documentation use the `travel-sample` sample data bucket.
For more information about how to load this sample data on your own cluster, see xref:manage:manage-settings/install-sample-buckets.adoc[].

[NOTE]
====
For indexes created with Couchbase Server version 7.6 and later, index names must be unique inside a bucket and scope.
You cannot have 2 indexes with the same name inside the same bucket and scope on a Couchbase {page-product-name} cluster running version 7.6.

The Couchbase {page-ui-name} marks indexes as scoped or not scoped to a specific bucket and scope. 

Indexes created with a previous version of Couchbase Server are not scoped.

To view the full, scoped name for an index, go to the *Search* tab and point to the *Index Name*.
Use the scoped name with the xref:rest-api:rest-fts.adoc[Search Service REST API], for any endpoints that do not include the bucket and scope in their path. 
==== 

If you want to restrict the documents you add to an index, you can also: 

* xref:create-type-mapping.adoc[]. 
* xref:create-child-field.adoc[Add child fields] to add or remove document fields from the index. 

After you create a Search index, the Search Service streams data from your chosen collection or collections, and any document mutations, into the index builder.
Before your index finishes building, you can run a search and return partial results. 

You can also customize a Search index to improve search results and performance. 
For more information about how you can customize a Search index with the Web Console, see xref:customize-index.adoc[]. 

=== Creating a Search Index with the Quick Editor

The Web Console also has a Quick Index editor.

You can use the Quick Index editor to create a Search index by selecting fields from a document from your cluster.

The Quick Index editor works best when you need to create a basic Search index to start testing and prototyping with the Search Service.
If you want to have greater control over how the Search Service returns results, such as changing your xref:customize-index.adoc#analyzers[analyzer], use xref:create-search-index-ui.adoc[the standard editor]. 

You can edit an index that you created with the Quick Index editor in the standard editor later. 
You cannot edit an index that you created with the standard editor in the Quick Index editor. 

For more information about how to create an index with the Quick Index editor, see xref:create-quick-index.adoc[].

[#api]
== Creating a Search Index with the REST API

You can create a Search index with the REST API through a JSON payload. 
Most properties in the JSON payload correspond to settings in the Web Console. 
You can also copy the Search index definition JSON payload from a Search index in the Web Console to use in a REST API call. 

[NOTE]
====
Use the scoped name for an index with the xref:rest-api:rest-fts.adoc[Search Service REST API] for any endpoints that do not include the bucket and scope in their path. 
For example, you must use `bucket.scope.index_name` as the format for your index name with the `analyzeDoc` endpoint, but not with the new 7.6 `query` endpoint.
====

For more information about how to use the REST API to create a Search index, see xref:create-search-index-rest-api.adoc[].

For more information about the available properties for a Search index, see xref:search-index-params.adoc[Search Index JSON Properties].

== Updating Search Indexes

If you want to make changes to a Search index later, some of those changes might trigger a full index rebuild. 
Rebuilding an index uses the compute resources available to your Search Service nodes and can cause downtime. 

The following Search index updates require a full index rebuild: 

[cols="2,1,1"]
|====
| |How to Change Through the UI |How to Change through the REST API

|Adding additional fields or mappings to your Search index
a| xref:create-child-field.adoc[]

xref:create-child-mapping.adoc[]

xref:create-type-mapping.adoc[]

xref:create-xattrs-mapping.adoc[]

a| xref:search-index-params.adoc#scope-collection[scope.collection Objects, JSON Object Field Objects, and XATTRs Objects]

xref:search-index-params.adoc#child-fields[field_name Object]

|Changing whether a field is included in the *_all* field
| xref:child-field-options-reference.adoc#all[Include in _all field]
| xref:search-index-params.adoc#include-in-all[`include_in_all`]

|Changing a field's data type
| xref:create-child-field.adoc[]
| xref:search-index-params.adoc#field-type[`type`]

|Changing term vector storage settings for a field
| xref:child-field-options-reference.adoc#term-vectors[Include Term Vectors]
| xref:search-index-params.adoc#term-vectors[`include_term_vectors`]

|Enabling or disabling a field or mapping 
a| xref:create-child-field.adoc[]

xref:create-child-mapping.adoc[]

xref:create-type-mapping.adoc[]

xref:create-xattrs-mapping.adoc[]

a| xref:search-index-params.adoc#objects-enabled[`enabled`] (Collection, JSON Object, or XATTRs Object level)

xref:search-index-params.adoc#default-mapping-enabled[`enabled`] (Default Mapping)

xref:search-index-params.adoc#field-enabled[`enabled`] (Field level)

|Changing a text field's analyzer
| xref:child-field-options-reference.adoc#analyzer[Analyzer]
| xref:search-index-params.adoc#field-analyzer[`analyzer`]

|Changing the default analyzer for the Search index
| xref:set-advanced-settings.adoc#default-analyzer[Default Analyzer]
| xref:search-index-params.adoc#default-analyzer[`default_analyzer`]

|Changing a date/time field's date/time parser
| xref:child-field-options-reference.adoc#datetime-parser[Datetime Parser]
| xref:search-index-params.adoc#field-datetime[`date_format`]

|Changing the default date/time parser for the Search index
| xref:set-advanced-settings.adoc#date-time[Default Date/Time Parser]
| xref:search-index-params.adoc#default-date-time-parser[`default_datetime_parser`]

|Changing the dimensions, similarity metric, or optimization settings on a vector or vector_base64 field
a| xref:child-field-options-reference.adoc#dimension[Dimension]

xref:child-field-options-reference.adoc#similarity-metric[Similarity Metric]

xref:child-field-options-reference.adoc#optimized[Optimized For]

a| xref:search-index-params.adoc#dims[`dims`]

xref:search-index-params.adoc#similarity[`similarity`]

xref:search-index-params.adoc#vector-index-optimized-param[`vector_index_optimized_for`]

|Making any changes to any field that has been included in the *_all* field
| xref:create-child-field.adoc[]
| xref:search-index-params.adoc#child-fields[field_name Object]

|Changing any mapping that has been set as dynamic
a| xref:create-child-mapping.adoc[]

xref:create-type-mapping.adoc[]

xref:create-xattrs-mapping.adoc[]

| xref:search-index-params.adoc#scope-collection[scope.collection Objects, JSON Object Field Objects, and XATTRs Objects]

|Removing a defined child mapping when a parent mapping has dynamic enabled
a| xref:create-child-field.adoc#delete[Delete a Child Field Mapping]

xref:create-child-mapping.adoc#delete[Delete a Child Mapping]

xref:create-xattrs-mapping.adoc#delete[Delete an XATTRs Mapping]
| xref:search-index-params.adoc#child-fields[field_name Object]

|Making any changes to fields that share the same name ^[<<footnote-1,1>>]^
| xref:create-child-field.adoc[]
| xref:search-index-params.adoc#child-fields[field_name Object]

|Changing the Search index's document filter
| xref:set-type-identifier.adoc[]
| xref:search-index-params.adoc#doc-config[Doc_config Object]

|Changing the name of the *_all* field
| xref:set-advanced-settings.adoc#all-field[Default Field]
| xref:search-index-params.adoc#all-field[`default_field`]

////
|Changing the Search index's default type
| xref:set-advanced-settings.adoc#default-type[Default Type]
| xref:search-index-params.adoc[]
////
|====

[#footnote-1]
^[<<same-field-name,1>>]^ Fields can share the same name when you use the xref:child-field-options-reference.adoc#searchable-as[Searchable As] setting from the {page-ui-name}, change the xref:search-index-params.adoc#field-name[`name` property] in your JSON definition, or index 2 fields with the same name under 2 different xref:about-mappings.adoc#collections[collection type mappings].

== See Also 

* xref:customize-index.adoc[]
* xref:index-aliases.adoc[]
* xref:run-searches.adoc[]