= Create a Child Mapping
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Create a child mapping with the Couchbase {page-ui-name} to add or remove a field that contains a JSON object from a Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You have created a type mapping. 
For more information about how to create a type mapping on an index, see xref:create-type-mapping.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To create a child mapping with the Couchbase {page-ui-name}: 

. Go to *Search*.
. Click the index where you want to create a child mapping.
. Click btn:[Edit].
. Expand menu:Customize Index[Mappings].
. Point to an existing mapping and click btn:[+].
. Click *insert child mapping*. 
. In the *{}* field, enter the name of a field in a document that contains a JSON object. 
. (Optional) To only index the fields you add to the child mapping, select *only index specified fields*. 
. (Optional) To set a different analyzer for the child mapping, in the *Analyzer* list, select an analyzer.
+
You can select a xref:default-analyzers-reference.adoc[default analyzer] or xref:create-custom-analyzer.adoc[create your own]. 
. Click btn:[OK].

== Next Steps

After you create a child mapping, you can choose to add or remove fields in the JSON object from your Search index. 

Both child mappings and type mappings use child fields to add and remove fields from a Search index. 

For more information about how to add or remove fields from a mapping, see xref:create-child-field.adoc[].

To continue customizing your Search index, you can also:

* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:set-advanced-settings.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].