= Create a Search Index in Advanced Mode
:page-topic-type: guide
:description: Use Advanced Mode to create a Search index in Couchbase Capella with full customization and advanced features.

[abstract]
{description}

Use xref:create-quick-index.adoc[Quick Mode] if you do not need full customization or advanced settings to quickly create a Search index and xref:customize-index.adoc#type-mappings[type mappings].

You must create a Search index before you can xref:simple-search-ui.adoc[run a search] with the Search Service.

== Prerequisites

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your database. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have logged in to the Couchbase Capella UI.

== Procedure 

To use Advanced Mode in Couchbase Capella to create a Search index:

. On the *Databases* page, select the database where you want to create a Search index. 
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
. Click the btn:[Advanced Mode] toggle.
. In the *Index Name* field, enter a name for the Search index. 
+
[NOTE]
====
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

For version 7.6 and later, your index name must be unique inside your selected bucket and scope. You cannot have 2 indexes with the same name inside the same bucket and scope.
====
 
. Under *Type Mappings*, in the *Bucket* list, select the bucket where you want to create your Search index. 
. In the *Scope* list, select the scope where you want to create the index. 
. (Optional) In the *Document Filter* list, configure an optional filter to add or remove documents from your Search index. 
+
For more information about how to configure a document filter, see xref:set-type-identifier.adoc[]. 
. Add at least one mapping to your Search index: 
.. In your list of collections, click a collection name. 
.. (Optional) To index all fields from the document schema in the collection as a xref:customize-index.adoc#type-mappings[dynamic type mapping], click *Index everything from collection*. 
. Click btn:[Add].
. (Optional) If you did not configure your collection mapping as a xref:customize-index.adoc#type-mappings[dynamic type mapping]: 
.. Expand a collection, then select a field from your document schema.
.. Configure a JSON object or child field type mapping. 
.. Click btn:[Add].
. (Optional) Add additional collection mappings or type mappings to your Search index. 
. (Optional) Configure *Advanced Settings* for your Search index.
For more information, see xref:set-advanced-settings.adoc[].
. Click btn:[Create Index].

== Next Steps 
 
For more information about the different features you can add to your Search index to improve performance and search results, see xref:customize-index.adoc[].

For more information about how to run a search, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].
