= Create a Child Mapping with the Capella UI
:page-topic-type: guide

== Prerequisites 

* You've created an index.
For more information, see xref:guides:search/create-search-index-ui.adoc[].

* You've created a type mapping. 
For more information about how to create a type mapping on an index, see xref:guides:search/create-type-mapping.adoc[].

* You've logged in to the Couchbase Server Capella UI. 

== Procedure 

To create a child mapping for a Search index from the Capella UI:

. From your organization page, select the database where you want to create a child mapping. 
. Go to menu:Data Tools[Search].
. Click the name of the index where you want to create a child mapping. 
. Expand *Advanced Configuration*. 
. Expand *Type Mappings*. 
. Click the *More Options* (&vellip;) menu. 
. Click *Insert Child Mapping*. 
. In the *Name* field, enter the name of a JSON object field in your database's documents.
. (Optional) To set a different analyzer for the child mapping, in the *Default Analyzer* list, select an analyzer.
+
For more information about the available default analyzers, see xref:search/default-analyzers-reference.adoc[].
. (Optional) To only index the fields you add to the child mapping, clear *Index all contained fields*. 
. Click btn:[Submit].