= Create a Type Mapping
:page-topic-type: guide

== Prerequisites 

* You've created an index.
For more information, see xref:guides:search/create-search-index-ui.adoc[].
 
* You've logged in to the Couchbase Server Web Console. 

== Procedure 

To create a type mapping with the Couchbase Server Web Console: 

. Go to *Search*.
. Click the index where you want to create a type mapping.
. Click btn:[Edit].
. Expand *Customize Index*. 
. Expand *Mappings*. 
. Click btn:[Add Type Mapping]. 
. Do one of the following: 
.. If you selected *Use non-default scope/collection(s)*, in the *Collection* list, select the collection where you want to create the type mapping. 
.. If you cleared *Use non-default scope/collection(s)*, in the *#* field, enter the name of a type field where you want to create a type mapping. 
. (Optional) To only include documents of a specific type from a collection, in the *#* field, add the document type to the end of the collection.
+
For example, `scope.collection.document_type`.
. (Optional) To use a specific analyzer for documents in the type mapping, in the *Analyzer* list, select an analyzer. 
+
You can xref:guides:search/default-analyzers-reference.adoc[use a default analyzer] or xref:guides:search/create-custom-analyzer.adoc[create your own].
. (Optional) To switch from a xref:guides:search/customize-index.adoc#type-mappings[dynamic type mapping to a static type mapping], select *Only index specified fields*. 
.. To choose which fields to add or remove from the static type mapping, see xref:guides:search/create-child-field.adoc[].
. (Optional) To add a child type mapping for a document field that contains a JSON object, see xref:guides:search/create-child-mapping.adoc[].
. Click btn:[OK].