= Create a Quick Index 
:page-topic-type: guide
:description: Use the Quick Index editor in Couchbase Server's Web Console to create a Search index.

[abstract]
{description}

The Quick Index editor lets you select the scopes, collections, and fields that you want to add to a Search index from a document in your database.

== Prerequisites 

* You have the Search Service enabled on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* Your user account has the *Search Admin* role for the bucket where you want to create the index. 

* You've logged in to the Couchbase Server Web Console. 

== Procedure 

. Go to *Search*. 
. Click btn:[Quick Index].
. In the *Index Name* field, enter a name for the index. 
. In the first *Keyspace* list, select the bucket where you want to create the index. 
. In the second *Keyspace* list, select the scope where you want to create the index. 
. In the third *Keyspace* list, select the collection where you want to create the index. 
. In the *Select Fields* box, click a field in the document that you want to add to the index. 
. In the *Type* list, select the field's data type. 
+
For more information about the available data types, see xref:field-data-types-reference.adoc[].
. Set the field's options. 
+
For more information about the available field options, see xref:quick-index-field-options.adoc[].
. Click btn:[Add]. 
. (Optional) Repeat Steps 7-10 for each field you want to add to the index. 
. Click btn:[Create Index].  