= Create a Custom Analyzer with the Capella UI
:page-topic-type: guide
:description: Create a custom analyzer to modify the input text from a Search query or Search index and improve search results.

[abstract]
{description}

== Prerequisites 

* You've created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You've logged in to the Couchbase Capella UI. 

== Procedure 

To create a custom analyzer:

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a custom analyzer.
. Expand *Advanced Configuration*. 
. Expand *Analyzers*. 
. Click btn:[Add Analyzer].
. In the *Name* field, enter a name for the new custom analyzer. 
. To remove specific characters from search input before tokenizing, in the *Character Filters* list, do one of the following:
.. To add a character filter to your analyzer, click a character filter. 
You can select a default character filter or create your own.
+
For more information, see xref:customize-index.adoc#character-filters[Character Filters] or xref:create-custom-character-filter.adoc[].
.. To remove a character filter from your analyzer, click the *x* on a character filter.
. In the *Tokenizer* list, click the tokenizer you want to use to create tokens from Search input.
You can select a default tokenizer or create your own. 
+
For more information, see xref:customize-index.adoc#tokenizers[Tokenizers] or xref:create-custom-tokenizer.adoc[].
. To modify the tokens created by the tokenizer, in the *Token Filters* list, do one of the following: 
.. To add a token filter to your analyzer, click a token filter. 
You can select a default token filter or create your own. 
+
For more information, see xref:default-token-filters-reference.adoc[] or xref:create-custom-token-filter.adoc[].
.. To remove a token filter from your analyzer, click the *x* on a token filter.
. Click btn:[Submit].
. Click btn:[Update Index].

