= Create a Type Mapping 
:page-topic-type: guide
:description: Create a type mapping with the Couchbase Capella UI to control what documents are included or excluded from a Search index. 

[abstract]
{description}

For more information, see xref:customize-index.adoc#type-mappings[Customize a Search Index with the Capella UI].

== Prerequisites 

* You've created an index.
For more information, see xref:create-search-index-ui.adoc[].
 
* You've logged in to the Couchbase Capella UI. 

== Procedure 

To create a type mapping with the Capella UI: 

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a type mapping. 
. Under *Type Mappings*, in the *Bucket* list, select the bucket where you want to create a type mapping. 
. In the *Scope* list, select the scope where you want to create a type mapping. 
. Click btn:[Add Mapping].
. In the *Collection* list, select the collection for the type mapping.
. (Optional) Do any of the following:
.. To use a specific analyzer for documents in the type mapping, in the *Analyzer* list, select an analyzer. 
+
By default, the mapping inherits the default analyzer you set for the Search index. 
For more information about analyzers, see xref:customize-index.adoc#analyzers[Customize a Search Index with the Capella UI].
.. To switch from a xref:customize-index.adoc#type-mappings[dynamic type mapping to a static type mapping], select *Only index specified fields*. 
. Click btn:[Submit].

[TIP]
====
You can also create type mappings with the Data Insights area: 

. Expand the scope where you want to create a type mapping. 
. Next to the collection where you want to create the type mapping, go to menu:More Options (&vellip;)[Map Collection to Index]. 
. (Optional) To edit the analyzer or switch to a static type mapping, next to the type mapping, go to menu:More Options (&vellip;)[Edit].
====

== Next Steps 

After you create a static type mapping, you can xref:create-child-field.adoc[] to add or remove specific document fields from your Search index.

To add an extra filter to the documents selected by your type mapping, you can also xref:set-type-identifier.adoc[].

If you have a document field that contains a JSON object, xref:create-child-mapping.adoc[] for that field. 

To continue customizing your Search index, you can: 

* xref:set-advanced-settings.adoc[]
* xref:set-type-identifier.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-wordlist.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].