= Create a Child Field
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Create a child field with the Couchbase {page-ui-name} to add or remove a specific field's content from a Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You have created a type mapping. 
For more information about how to create a type mapping on an index, see xref:create-type-mapping.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 
 

== Procedure 

To add or remove a child field from a Search index with the Couchbase {page-ui-name}:

. Go to *Search*.
. Click the index where you want to create a child field.
. Click btn:[Edit].
. Expand menu:Customize Index[Mappings]. 
. Point to an existing mapping and click btn:[+].
. Click *insert child field*. 
. [[field]]In the *Field* field, enter the name of a field in your documents that you want to add or remove from the index.
+
NOTE: The field must contain either a single value or an array.
If the field contains a JSON object, xref:create-child-mapping.adoc[create a child mapping] instead.
Field names must not contain periods (`.`).  
. In the *Type* list, select the data type for the field. 
+
For more information about the available data types, see xref:field-data-types-reference.adoc[].

. Configure optional settings for the child field. 
+
For more information about the available settings for child fields, see xref:child-field-options-reference.adoc[].
. Click btn:[OK].

== Next Steps

You can continue to create child fields to add or remove the contents of a document from your Search index. 

If a field in your documents contains a JSON object, xref:create-child-mapping.adoc[], instead. 

To continue customizing your Search index, you can also:

* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:set-advanced-settings.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].