= Create a Search Index with the REST API and curl/HTTP 
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: You can create a Search index with the Search Service API. 

[abstract]
{description}

You must create a Search index before you can xref:simple-search-rest-api.adoc[run a search] with the Search Service.

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your database.
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[]. 

* You have the hostname for the node in your database that's running the Search Service.
+
For more information about how to find the hostname for a node in your {page-product-name} database, see xref:clouds:get-capella-host-name.adoc[].

== Procedure 

To create a Search index with the REST API:

. In your command-line tool, enter a `curl` command with the `XPUT` verb. 
. Set your header content to include `"Content-Type: application/json"`.
. Enter your username, password, and the Search Service endpoint on port `18094` with the name of the index you want to create: 
+
[source,console]
----
include::example$create-search-index-header.sh[]
----
+
[NOTE]
====
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

As of version 7.6, your index name must be unique inside your selected bucket and scope. You cannot have 2 indexes with the same name inside the same bucket and scope.
====

. Enter the JSON payload for the settings you want in your index. 
+
Do not include the xref:search-index-params.adoc#uuid[uuid] or xref:search-index-params.adoc#sourceuuid[sourceUUID] parameters. 
+
TIP: If you remove the xref:search-index-params.adoc#uuid[uuid] and xref:search-index-params.adoc#sourceuuid[sourceUUID] parameters, you can copy the Search index definition JSON payload from the Couchbase {page-ui-name} to use in your REST API call.
For more information about how to create an index with the UI, see xref:create-search-index-ui.adoc[]. 

include::partial$large-index-caution.adoc[tag=regular-search]

=== Example 

In the following example, the JSON payload creates a simple index named `landmark-content-index` on the `travel-sample` bucket. It creates a type mapping for the `inventory.landmark` collection, with a child field, `content`:

[source,console]
----
include::example$create-search-index-payload.sh[]
----

For more information about the available JSON properties for a Search index, see xref:search-index-params.adoc[].

== Next Steps

After you create a Search index, you can xref:simple-search-rest-api.adoc[] to test your Search index. 

If you want to edit your index with another REST API call, include the xref:search-index-params.adoc#uuid[uuid] parameter with the UUID the Search Service assigned to your Search index.

You can also xref:simple-search-ui.adoc[] or with one of the Couchbase SDKs: 

include::partial$sdks-fts-links.adoc[]
