= Create a Type Mapping
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Create a type mapping with the Couchbase {page-ui-name} to control what documents are included or excluded from a Search index. 

[abstract]
{description}
For more information, see xref:customize-index.adoc#type-mappings[Customize a Search Index with the Web Console].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].
 
* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To create a type mapping with the Couchbase {page-ui-name}: 

. Go to *Search*.
. Click the index where you want to create a type mapping.
. Click btn:[Edit].
. Expand menu:Customize Index[Mappings]. 
. Click btn:[Add Type Mapping]. 
. Do one of the following: 
.. If you selected *Use non-default scope/collection(s)*, in the *Collection* list, select the collection where you want to create the type mapping. 
.. If you cleared *Use non-default scope/collection(s)*, in the *#* field, enter the name of a type field where you want to create a type mapping. 
. (Optional) To only include documents of a specific type from a collection, add the document type to the end of the collection in the *#* field.
+
For example, `scope.collection.document_type`.
For more information, see xref:set-type-identifier.adoc[].
. (Optional) To use a specific analyzer for documents in the type mapping, in the *Analyzer* list, select an analyzer. 
+
You can xref:default-analyzers-reference.adoc[use a default analyzer] or xref:create-custom-analyzer.adoc[create your own].
. (Optional) To switch from a xref:customize-index.adoc#type-mappings[dynamic type mapping to a static type mapping], select *Only index specified fields*. 
.. To choose which fields to add or remove from the static type mapping, see xref:create-child-field.adoc[].
.. To add a child type mapping for a document field that contains a JSON object, see xref:create-child-mapping.adoc[].
. Click btn:[OK].

== Next Steps

After you create a static type mapping, you can xref:create-child-field.adoc[] to add or remove specific document fields from your Search index. 

To add an extra filter to the documents selected by your type mapping, you can also xref:set-type-identifier.adoc[].

If you have a document field that contains a JSON object, xref:create-child-mapping.adoc[] for that field. 

To continue customizing your Search index, you can: 

* xref:set-type-identifier.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:set-advanced-settings.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].