= Create a Basic Search Index with the Capella UI
:page-topic-type: guide
:description: You can create a Search index with the Couchbase Capella UI. 

[abstract]
{description}

You must create a Search index before you can xref:simple-search-ui.adoc[run a search] with the Search Service.

== Prerequisites

* You've deployed the Search Service on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* Your user account has the *Search Admin* role for the bucket where you want to create the index.  

* You've logged in to the Couchbase Capella UI. 

== Procedure 

To create a Search index with the Capella UI: 

. On the *Databases* page, select the database where you want to create a Search index. 
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
. In the *Index Name* field, enter a name for the Search index. 
+
NOTE: Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).
 
. In the Data Insights area, expand the scope where you want to create a type mapping. 
. Next to the collection where you want to create the type mapping, go to menu:More Options (&vellip;)[Map Collection to Index]. 
. Click btn:[Create Index].

== Next Steps 

This basic index includes all documents from the collection you selected in the Data Insights area.
You can run a search against this index, but it's recommended that you customize your index to improve performance and reduce the index size. 
 
For more information about how to customize an index, see xref:customize-index.adoc[].

For more information about how to run a search, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].
