= Create a Type Mapping in Advanced Mode
:page-topic-type: reference
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Add a type mapping to your Search index using the Couchbase {page-ui-name}'s Advanced Mode to control what documents are added to your index. 

[abstract]
{description}

For more information about type mappings, see xref:customize-index.adoc#type-mappings[Search Index Features].

== Prerequisites

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have started to create or already created a Search index in xref:create-search-index-ui.adoc[Advanced Mode].

* You have logged in to the Couchbase {page-ui-name}.

== Procedure

To create a type mapping with the {page-ui-name}:

. On the *Databases* page, select the database that has the Search index you want to edit.
. Go to menu:Data Tools[Search].
. Click the index where you want to create a type mapping.
. Under *Type Mappings*, in the Bucket list, select the bucket where you want to create a type mapping.
. In the *Scope* list, select the scope where you want to create a type mapping.
. Click btn:[Add Mapping].
. In the *Collection* list, select the collection to use for the type mapping.
. (Optional) Do any of the following:
.. To use a specific analyzer for documents added from this type mapping, in the *Analyzer* list, select an analyzer.
+
By default, the mapping inherits the default analyzer you set for the Search index. 
For more information about analyzers, see xref:customize-index.adoc#analyzers[Search Index Features].
.. To switch from a xref:customize-index.adoc#type-mappings[dynamic type mapping to a static type mapping], select *Only index specified fields*.
.. To only include documents of a specific type from a collection, in the *Name* field, add the document type to the end of the collection.
+
For example, `collection.document_type`.
For more information, see xref:set-type-identifier.adoc[].
. Click btn:[Submit].
. (Optional) To remove all documents that match the type mapping from your Search index, clear the checkbox for that type mapping. 
+
By leaving the checkbox selected, all matching documents will be included in the Search index.

== Next Steps

After you create a static type mapping, you can xref:create-child-field.adoc[] to add or remove specific document fields from your Search index.

To add an extra filter to the documents selected by your type mapping, you can also xref:set-type-identifier.adoc[].

If you have a document field that contains a JSON object, xref:create-child-mapping.adoc[] for that field.

To continue customizing your Search index, you can:

* xref:set-advanced-settings.adoc[]
* xref:set-type-identifier.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[] 
* xref:create-custom-wordlist.adoc[]


To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[].
