= Create a Custom Wordlist 
:page-topic-type: guide
:description: Create a custom wordlist with the Couchbase Server Web Console to use with a custom token filter.

[abstract]
{description}

A custom wordlist gives greater control over the input you want to remove from xref:customize-index.adoc#tokenizers[tokenizer] results. 

For more information about how to create a custom token filter, see xref:create-custom-token-filter.adoc[].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You have logged in to the Couchbase Server Web Console. 

== Procedure 

To create a custom wordlist with the Couchbase Server Web Console:  

. Go to *Search*. 
. Click the Search index where you want to create a custom wordlist.
. Click btn:[Edit].
. Expand menu:Customize Index[Custom Filters]. 
. Click btn:[Add Wordlist].
. In the *Name* field, enter a name for the wordlist. 
. In the *Word to be added* field, enter a word you want to add to the wordlist. 
. To add the word to the list, do one of the following: 
.. Click btn:[Add].
.. Press kbd:[Enter]. 
. (Optional) To add more words to the wordlist, repeat the previous steps. 
. Click btn:[Save].

== Next Steps

After you create a custom wordlist, you can use it with xref:create-custom-token-filter.adoc[a custom token filter].

To continue customizing your Search index, you can also: 

* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:set-advanced-settings.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].