= Create a Custom Date/Time Parser 
:page-topic-type: guide 
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Create a custom date/time parser with the Couchbase {page-ui-name} to tell the Search Service how to process a new date/time format.

[abstract]
{description}

If you store date data in a format other than RFC-3339 (ISO-8601), then you need to create a date/time parser.

== Prerequisites 

* You have the Search Service enabled on a node in your operational cluster.
For more information about how to change Services on your operational cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 

* You have started to create or already created an index in xref:create-search-indexes.adoc#advanced-mode[Advanced Mode Editing].

== Procedure 

To create a custom date/time parser with the {page-ui-name} in Advanced Mode: 

. On the *Operational Clusters* page, select the operational cluster where you want to work with the Search Service. 
. Go to menu:Data Tools[Search].
. Do one of the following:
.. To work with an existing Search index, click the name of the index where you want to create a custom date/time parser.
.. To create a new Search index, click btn:[Create Search Index].
. Make sure to select *Enable Advanced Options*.
. Expand *Global Index Settings*. 
. Click btn:[Add Custom Date/Time Parser]
. In the *Date/Time Parser Name* field, enter a name for the date/time parser. 
. In the *New Date and Time* field, enter a date/time layout with Go syntax. 
+
For more information, see the documentation about the https://pkg.go.dev/time#pkg-constants[Go Programming Language Time Package's Layout Constant^]. 
. (Optional) To add an additional layout, click btn:[Add] and enter a new layout. 
. Click btn:[Add Custom Date/Time Parser].

== Next Steps

After you create a custom date/time parser, you can xref:create-search-index-ui.adoc#date-time[set it as the default date/time parser] for your Search index.

To continue customizing your Search index, you can also: 

* xref:set-type-identifier.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[].