= Customize a Search Index with the Web Console
:page-topic-type: concept
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-aliases: fts:fts-configure-index-options.adoc, fts:fts-custom-filters.adoc
:description: Configure additional options for a Search index to improve performance and fine tune your search results. 

[abstract]
{description}

Some Search index options are only available when you xref:create-search-index-ui.adoc[use the standard editor].

You can add the following components and configure the following options for a Search index: 

[cols="2,1,1,4"]
|====
|Option |Quick Editor |Standard Editor |Description 

|[[type-identifiers]]Type Identifier 
|
|&check;
a|Set a type identifier to add a filter to the documents added to your Search index through a <<type-mapping,type mapping>>:

* JSON Type Field: Selects only documents that contain a specific field with a specified string value.
* Doc ID up to Separator: Selects only documents with an ID or key up to a specific substring.
* Doc ID with Regex: Selects only documents with an ID or key that matches a regular expression.
* Custom: As of Couchbase Server version 8.0, custom document filters select only documents that match a custom filter, based on the values of specific fields.

Type identifiers add a more granular filter to the documents in a type mapping.
If a type mapping has a type identifier, only documents that match the type identifier can be included in the Search index.

For more information about how to configure a type identifier, see xref:set-type-identifier.adoc[].

|[[type-mappings]]Mappings
|&check;
|&check;
a|Use a type mapping to include or exclude specific documents in a collection from an index.
For more information about the different kinds of mappings in a Search index, see xref:about-mappings.adoc[].

|[[nested]]Array of Objects Mappings
|&check;
|&check;
a|From the next major release of Couchbase Server, you can use a nested object mapping to preserve the relationships between fields when you have an array of objects in your documents.

Nested object mappings change the default field flattening process in the Search Service.
For more information, see xref:create-nested-object.adoc[].

|[[analyzers]]Analyzers 
|
|&check;
a|Use analyzers to improve and customize the search results in your index.  

Analyzers transform input text into tokens, which give you greater control over your index's text matching.  

You can use one of Couchbase's built-in analyzers or create your own. 
For more information about how to create a custom analyzer, see xref:create-custom-analyzer.adoc[].

Analyzers have different components that control how text is transformed for search. 
When you create a custom analyzer, you can choose these components. 
For more information, see <<custom-filters,>>. 

|[[custom-filters-table]]Custom Filters 
|
|&check;
a|Use custom filters to add more customization to a custom analyzer.

For more information about these filters, see the <<custom-filters,>> section.

|[[date-time]]Date/Time Parsers 
|
|&check;
a|If the documents in your index contain date and time data in a format other than RFC-3339 (ISO-8601), then you need to create a date/time parser.

A custom date/time parser tells the Search index how to interpret date data from your documents.
If any values are missing from a date/time string in your documents, the Search Service automatically fills in xref:default-date-time-parsers-reference.adoc#missing-values[default date/time values] to make it easier to compare date/time strings.

For more information about how to add a custom date/time parser, see xref:create-custom-date-time-parser.adoc[].

For more information about the available default date/time parsers, see xref:default-date-time-parsers-reference.adoc[].

|Advanced 
|
|&check;
a|Set advanced settings to change your index's default analyzer, replication, and more. 

For more information about how to change advanced settings, see xref:set-advanced-settings.adoc[].

|Synonym Sources
|&check;
|&check;
a| 

As of Couchbase Server version 8.0 and later, you can add a Synonym Source to a Search index to use synonym searches on text fields.

After you xref:synonyms/create-synonym-collection-docs.adoc[create a synonym collection and synonym documents], and xref:synonyms/add-synonym-source.adoc[add a synonym source], you can run a search for a term and return results that include terms with similar meanings. 

For example, you could run a search for `happy` and get results for `joyful`, `cheerful`, or `delighted`.

You can also xref:synonyms/add-synonym-source-quick.adoc[add Synonym Sources with the Quick Editor].

For more information about synonym search for the Search Service, see xref:synonyms/synonyms-search.adoc[] or xref:synonyms/synonyms-search-quick.adoc[], based on your preferred editor.

|====

[#custom-filters]
== Custom Filters 

Custom filters are components of a Search index <<analyzers,analyzer>>. 

Create and add these components to a custom analyzer to improve search results and performance for an index with the xref:create-search-index-ui.adoc[standard editor]. 

You can create the following custom filters: 

* <<character-filters,>>
* <<tokenizers,>>
* <<token-filters,>>
* <<wordlists,>>

[#character-filters]
=== Character Filters 

Character filters remove unwanted characters from the input for a search. 
For example, the default *html* character filter removes HTML tags from your search content. 

You can use a default character filter in an analyzer or create your own. 

For more information about the available default character filters, see xref:default-character-filters-reference.adoc[].

For more information about how to create your own custom character filter, see xref:create-custom-character-filter.adoc[].

[#tokenizers]
=== Tokenizers 

Tokenizers separate input strings into individual tokens. 
These tokens are combined into token streams. 
The Search Service takes token streams from search queries to determine matches for token streams in search results. 

You can use a default tokenizer in an analyzer or create your own. 

For more information about the available default tokenizers, see xref:default-tokenizers-reference.adoc[].

For more information about how to create your own tokenizer, see xref:create-custom-tokenizer.adoc[].

[#token-filters]
=== Token Filters 

Token filters take the token stream from a tokenizer and modify the tokens. 

A token filter can create stems from tokens to increase the matches for a search term. 
For example, if a token filter creates the stem `play`, a search can return matches for `player`, `playing`, and `playable`.

The Search Service has default tokenizers available.
For a list of all available tokenizers, see xref:default-token-filters-reference.adoc[].

You can also create your own token filters. 
Custom token filters can use <<wordlists,>> to modify their tokens. 
For more information about how to create your own token filter, see xref:create-custom-token-filter.adoc[].

[#wordlists]
=== Wordlists 

Wordlists define a list of words that you can use with a <<token-filters,token filter>> to create tokens. 

You can use a wordlist to find words and create tokens, or remove words from a tokenizer's token stream. 

When you create a custom token filter, the Search Service has a set of default wordlists. 
For more information about the available default wordlists, see xref:default-wordlists-reference.adoc[].

For more information about how to create your own wordlist, see xref:create-custom-wordlist.adoc[].

== See Also

* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:set-advanced-settings.adoc[]
* xref:synonyms/synonyms-search.adoc[]
* xref:run-searches.adoc[]
* xref:index-aliases.adoc[]
