= Default Character Filters
:page-topic-type: reference
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Character filters remove unwanted characters from your search input. 

[abstract]
{description}

You can use a xref:customize-index.adoc#character-filters[character filter] when you xref:create-custom-analyzer.adoc[create a custom analyzer].
Choose a default character filter or xref:create-custom-character-filter.adoc[create your own].

The following default character filters are available:

|====
|Character Filter |Description

|asciifolding a| 

The analyzer converts any characters that aren't in the Basic Latin Unicode block to their ASCII equivalent. 

This means the filter converts any alphabetic, numeric, or symbol characters that aren't in the first 127 ASCII characters.

For example, the character filter converts `รก` to `a`.

|html a|

The analyzer removes all HTML tags from search input. 

For example, the character filter removes the <p> tags from indexed content, but keeps the text inside the <p> tag.

|zero_width_spaces a|

The analyzer replaces zero-width non-joiner spaces with regular space characters. 

Zero-width non-joiner spaces are unicode characters that interrupt https://en.wikipedia.org/wiki/Ligature_(writing)[ligatures^](joins between characters) in text formatting.

|====