= Get a Search Index Definition from the Web Console
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use the Couchbase {page-ui-name} to copy and paste a JSON Search index definition for use in the REST API or another cluster.

[abstract]
{description}

NOTE: You cannot export a Search index definition as a downloadable file.
You can only copy the Search index definition from an existing index.

== Prerequisites

* You have the Search Service enabled on a node in your cluster.
For more information about how to deploy a new node and Services on your cluster, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have a bucket with scopes and collections in your cluster.
For more information about how to create a bucket, see xref:server:manage:manage-buckets/create-bucket.adoc[].

* Your user account has the xref:learn:security/roles.adoc#search-admin[`Search Admin`] role for the bucket where you want to export an index definition.  

* You have created a Search index. 
+
For more information about how to create a Search index, see xref:create-search-index-ui.adoc[] or xref:create-search-index-rest-api.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure

To copy a Search index definition from the {page-ui-name}:

. Go to *Search*.
. Click the name of the Search index definition you want to copy.
. Expand *Show index definition JSON*.
. Click btn:[Copy to Clipboard].

TIP: When you xref:create-search-index-ui.adoc[create a Search index with the {page-ui-name}], you can also click btn:[copy to clipboard] on the *Index Definition Preview* to copy the Search index definition.

== Next Steps

You can paste the copied definition into a new `.json` file to import it into a new cluster, or use the definition with the xref:create-search-index-rest-api.adoc[Search REST API].

To import your Search index definition into a new Couchbase Server cluster through the Web Console, see xref:server:search:import-search-index.adoc[].

To import your Search index into a Couchbase Capella cluster, see xref:cloud:search:import-search-index.adoc[].