= Export a Search Index Definition from the Capella UI
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use the Couchbase {page-ui-name} to export a JSON Search index definition for use in another cluster.

[abstract]
{description}

== Prerequisites

* You have the Search Service enabled on a node in your operational cluster.
For more information about how to change Services on your operational cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your operational cluster. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have created a Search index. 
+
For more information about how to create a Search index, see xref:create-search-index-ui.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure

To export a Search index definition from the {page-ui-name}:

. In the navigation breadcrumbs in the Capella UI, do 1 of the following: 

** Click your organization name and go to menu:Operational[]. 
** Click your current project name or search for a project and go to menu:Operational[].
** Expand the cluster breadcrumb and search for a cluster.

. Select the cluster where you want to work with the Search Service.
. Go to menu:Data Tools[Search].
. Click icon:download[].

== Next Steps

To import your Search index definition into a new Couchbase Server cluster through the Web Console, see xref:server:search:import-search-index.adoc[].

To import your Search index into a Couchbase Capella cluster, see xref:cloud:search:import-search-index.adoc[].