= Run a Geospatial Search Query with the REST API and curl/HTTP
:page-topic-type: guide
:description: Search for geospatial data in your Couchbase Capella database with a compatible Search index, the REST API and curl/HTTP.

[abstract]
{description}

== Prerequisites

* You've deployed the Search Service on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* Your user account has the *Search Admin* or *Search Reader* role. 

* You installed the Couchbase command-line tool (CLI).

* You have the hostname or IP address for your database. 

== Procedure

To run a geospatial Search query, <<geospatial-index,create a Search index with a geospatial type mapping>>. 

Then, <<geospatial-query,run a Search query from the Capella UI>>.  

[#geospatial-index]
== Create a Search Index with a Geospatial Type Mapping

To create the Search index with a geospatial type mapping: 

. xref:create-search-index-rest-api.adoc[] with the following JSON payload, replacing all values that start with a `$`: 

[source,json]
----
include::example$geospatial-search-index.jsonc[]
----

[#geospatial-query]
== Run a Geospatial Search Query

To run a Search query against the Search index: 

. In your command-line tool, enter a `curl` command with the `XPOST` verb. 
. Set your header content to include `Content-Type: application/json`.
. Enter your username, password, and the Search Service endpoint on port `8094` with the name of the index you want to query: 
+
[source,console]
----
include::example$run-search-header.sh[]
----
. Enter the JSON payload for your query.  
+
For example, the following query searches a geospatial field, `geo`, for any locations within a 100 mile radius of the coordinates `-2.235143, 53.482358`:

[source,json]
----
include::example$geospatial-search-query.jsonc[]
----

== Next Steps

You can xref:customize-index.adoc[customize your Search index] to improve search results and performance, or change the JSON payload xref:search-index-params.adoc[for your Search index] or xref:search-request-params.adoc[for your Search query].

You can also xref:search-query-auto-complete.adoc[].