= Run a Geospatial Search Query with the REST API and curl/HTTP
:page-topic-type: guide
:description: Search for geospatial data in your Couchbase Capella database with a compatible Search index, the REST API and curl/HTTP.

[abstract]
{description}

== Prerequisites

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your database. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have documents in your database that contain geospatial data.

* You have the hostname for the node in your database that's running the Search Service.
+
For more information about how to find the hostname for a node in your Capella database, see xref:clouds:get-capella-host-name.adoc[].

== Procedure

To run a geospatial Search query, <<geospatial-index,create a Search index with a geospatial type mapping>>. 

Then, <<geospatial-query,run a Search query from the Capella UI>>.  

[#geospatial-index]
=== Create a Search Index with a Geospatial Type Mapping

To create the Search index with a geospatial type mapping: 

. xref:create-search-index-rest-api.adoc[] with the following JSON payload, replacing all placeholder values that start with a `$`: 
+
[source,json]
----
include::example$geospatial-search-index.jsonc[]
----

[#geospatial-query]
=== Run a Geospatial Search Query

To run a Search query against the Search index: 

. In your command-line tool, enter a `curl` command with the `XPOST` verb. 
. Set your header content to include `"Content-Type: application/json"`.
. Enter your username, password, and the Search Service endpoint on port `18094` with the name of the index you want to query: 
+
[source,console]
----
include::example$run-search-header.sh[]
----
. Enter the JSON payload for your query.  

=== Example 

For example, the following query searches a geospatial field, `geo`, for any locations within a 100 mile radius of the coordinates `-2.235143, 53.482358`:

[source,json]
----
include::example$geospatial-search-query.jsonc[]
----

== Next Steps

You can xref:customize-index.adoc[customize your Search index] to improve search results and performance.

You can also: 

* Change the JSON payload xref:search-index-params.adoc[for your Search index].
* Change the JSON payload xref:search-request-params.adoc[for your Search query].

If you want to add autocomplete to your database's search, see xref:search-query-auto-complete.adoc[].