= Run a Geospatial Search Query with the {page-ui-name}
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Search for geospatial data in your Couchbase {page-product-name} operational cluster with a compatible Search index and the {page-ui-name}.

[abstract]
{description}

For more information about how the Search Service scores documents in search results, see xref:run-searches.adoc#scoring[Scoring for Search Queries].

== Prerequisites

* You have the Search Service enabled on a node in your operational cluster.
For more information about how to change Services on your operational cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your operational cluster. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have documents in your operational cluster that contain geospatial data. 

* You have logged in to the Couchbase {page-ui-name}.

== Procedure

To run a geospatial Search query, <<geospatial-index,create a Search index with a geospatial type mapping in Advanced Mode>>. 

Then, <<geospatial-query,run a Search query from the {page-ui-name}>>.  

[#geospatial-index]
=== Create a Search Index with a Geospatial Type Mapping

To create the Search index in the {page-ui-name} with Advanced Mode: 

. On the *Operational Clusters* page, select the operational cluster where you want to create a Search index. 
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
. In the *Index Name* field, enter a name for the Search index. 
+
[NOTE]
====
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

For Couchbase Server version 7.6 and later, your index name must be unique inside your selected bucket and scope.
You cannot have 2 indexes with the same name inside the same bucket and scope.
====
 
. In the *Bucket* and *Scope* lists, choose the bucket and scope where you want to create your Search index.
This bucket and scope should contain the collection and documents that have your geospatial data. 
. In your document schema, expand the collection that holds the documents with your geospatial data. 
. Click the name of the field that holds your geospatial data.
. In the *Type* list, select *Geopoint*. 
. Select *Include in search results*. 
. Select *Support field agnostic search*. 
. Click btn:[Add To Index].
. Click btn:[Create Index].

[#geospatial-query]
=== Run a Geospatial Search Query

To run a Search query against the Search index from the {page-ui-name}: 

. Next to your <<geospatial-index,geospatial type mapping Search index>>, click btn:[Search].
. In the *Search* field, enter a search query for geospatial data. 
+
For example, the following query searches a geospatial field, `geo`, for any locations within a 100 mile radius of the coordinates `-2.235143, 53.482358`:
+
[source,json]
----
include::example$geospatial-search-query.jsonc[]
----

== Next Steps

For more information about the different features you can add to your Search index to improve performance and search results, see xref:customize-index.adoc[].

If you want to add autocomplete to your operational cluster's search, see xref:search-query-auto-complete.adoc[].
