= Import a Search Index Definition with the Web Console
:page-topic-type: guide
:description: Use the Couchbase Server Web Console to import a JSON Search index definition or Search index alias.

[abstract]
{description}

== Prerequisites

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have a bucket with scopes and collections in your database.
For more information about how to create a bucket, see xref:server:manage:manage-buckets/create-bucket.adoc[].

* Your user account has the *Search Admin* role for the bucket where you want to create the index.  

* You have logged in to the Couchbase Server Web Console. 

== Procedure

To import a xref:create-search-indexes.adoc[Search index definition] or xref:index-aliases.adoc[Search alias] with the Couchbase Server Web Console:

. Go to *Search*.
. Do one of the following:
.. To import a Search index definition, click btn:[Add Index].
.. To import a Search index alias definition, click btn:[+ Add Alias].
. Click btn:[Import].
. In the Import Index window, paste the JSON definition of your Search index or index alias.
. Click btn:[Import].
. (Optional) Make any changes to your Search index or index alias settings. 
+
For more information, see xref:customize-index.adoc[] or xref:create-search-index-alias.adoc[].
. Click btn:[Create Index] or btn:[Create Index Alias].

== Next Steps

To change the settings for your imported Search index, see xref:customize-index.adoc[]. 

To run a search with your Search index or index alias, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].