= Import a Search Index Definition with the Capella UI
:page-topic-type: guide
:description: Use the Couchbase Capella UI to import a JSON Search index definition or Search index alias.

[abstract]
{description}

== Prerequisites

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your database. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].
 
* You have logged in to the Couchbase Capella UI. 

== Procedure

To import a xref:create-search-indexes.adoc[Search index definition] or xref:index-aliases.adoc[Search alias] with the Capella UI:

. On the *Databases* page, select the database where you want to import a Search index or index alias.
. Go to menu:Data Tools[Search].
. Do one of the following:
.. To import a Search index definition, click btn:[Import Search Index].
.. To import a Search index alias definition, click btn:[Import Search Alias].
. In the *Index Name* or *Alias Name* field, enter a name for your new Search index or alias. 
. Upload a JSON file smaller than 40 MB that contains your Search index or alias definition.
. Click btn:[Import Search Index] or btn:[Import Search Alias].
//. (Optional) Make any changes to your Search index or index alias settings. 
//+
//For more information, see xref:customize-index.adoc[] or xref:create-search-index-alias.adoc[].
//. Click btn:[Create Index] or btn:[Create Index Alias].

== Next Steps

To change the settings for your imported Search index, see xref:create-quick-index.adoc[] or xref:create-search-index-ui.adoc.

To run a search with your Search index or index alias, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].