= Import a Search Index Definition with the {page-ui-name}
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use the Couchbase {page-ui-name} to import a JSON Search index definition or Search index alias.

[abstract]
{description}

== Prerequisites

* You have the Search Service enabled on a node in your cluster.
For more information about how to change Services on your cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your cluster. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have a Search index or Search index alias definition saved as a JSON file.
For more information about the properties you can include in a Search index or index alias definition, see xref:search-index-params.adoc[].
+
NOTE: Your JSON file must be smaller than 40 MB. 
 
* You have logged in to the Couchbase {page-ui-name}. 


== Import a Search Index Definition 

To import a full xref:search-index-params.adoc[Search index definition] with the {page-ui-name}: 

. On the *Operational Clusters* page, select the cluster where you want to import a JSON Search index definition.
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
. Click btn:[Advanced Mode].
. Click btn:[Index Definition].
. Click btn:[Import from File].
. Upload a JSON file that contains your Search index definition.
+
For example:
+
[source,json]
----
include::example$short-search-index.jsonc[]
----
. (Optional) Make changes to your Search index settings. 
+
For more information, see xref:customize-index.adoc[] or xref:create-search-index-ui.adoc[].
. Click btn:[Create Index].

== Import a Search Index Alias Definition 

To import a xref:index-aliases.adoc[Search alias] with the {page-ui-name}:

. On the *Operational Clusters* page, select the cluster where you want to import a JSON Search index alias.
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Alias].
. Click btn:[Alias Definition].
. Click btn:[Import from File]. 
. Upload a JSON file that contains your Search alias definition.
+
For example:
+
[source,json]
----
include::example$search-index-alias.jsonc[]
----
. (Optional) Make changes to your Search index alias settings. 
+
For more information, see xref:create-search-index-alias.adoc[].
. Click btn:[Create Alias].

== Next Steps

To add additional features to your imported Search index, see xref:customize-index.adoc[].

To run a search with your Search index or index alias, see xref:simple-search-ui.adoc[].