= Create Search Index Aliases
:page-topic-type: concept
:description: A Search index alias lets you run a Search query against a Search index without using the original Search index name.

[abstract]
{description}

You can also use a Search index alias to run a Search query across multiple buckets, scopes, or Search indexes. 
The Search Service runs the Search query on each Search index in the alias, and returns a merged set of results. 

Search index aliases are useful when you need to update an existing Search index. 

For example, say you had a Search index, `old-index`, and an alias, `my-alias`.

If you wanted to make updates to `old-index`, you could add it to the alias `my-alias`. 
If you created a clone of `old-index`, then made your updates, you could replace `old-index` in the alias `my-alias`. 

Using a Search index alias lets you edit `old-index` without any downtime. 

For more information about how to create a Search index alias, see xref:create-search-index-alias.adoc[].

== See Also

* xref:create-search-index-alias.adoc[]
* xref:import-search-index.adoc[]

