= Manage Search Result Pagination
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use offset-based or cursor-based pagination with the Search Service to manage large result sets from a Search query.
:page-toclevels: 3

[abstract]
{description}

The Search Service supports 2 approaches to pagination:

* <<offset,Offset-based pagination>> with the `size` and `from` properties.
* <<cursor,Cursor-based pagination>>, also called deep pagination, with the `search_after` and `search_before` properties.

Offset-based pagination is best for paginating the first few pages of your search results.
Switch to cursor-based pagination for deeper pagination to reduce memory usage.

Cursor-based pagination also lets you choose a specific document to use as the start of your search results.

== Prerequisites

* You have the Search Service enabled on a node in your cluster.
For more information about how to deploy a new node and Services on your cluster, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have created a Search index.
+
For more information, see xref:create-search-indexes.adoc[].
+
[NOTE]
====
Depending on the type of field you want to use for pagination, you might not be able to use xref:about-mappings.adoc#dynamic[dynamic mappings] in your index:

* If you want to use a numeric or geospatial data field to paginate your search results, you must include these fields in your Search index as a xref:about-mappings.adoc#static[static mapping].
* If you want to use a datetime field to paginate your search results, you must include this field as a xref:about-mappings.adoc#static[static mapping] and explicitly define a xref:customize-index.adoc#date-time[date/time parser] for that mapping.
====

* Your user account has the xref:learn:security/roles.adoc#search-admin[`Search Admin`] or xref:learn:security/roles.adoc#search-reader[`Search Reader`] role for the bucket that contains the Search index you want to query.

* You installed the Couchbase command-line tool (CLI).

* You have the hostname or IP address for the node in your cluster where you're running the Search Service.
For more information about where to find the IP address for your node, see xref:server:manage:manage-nodes/list-cluster-nodes.adoc[].

* If you want to paginate using a numeric, date, or geospatial field, all the nodes in your cluster must be running Couchbase Server version 8.5 or later. 

== Procedure

To paginate results from a Search query:

. In your command-line tool, enter a `curl` command with the `XPOST` verb. 
. Set your header content to include `"Content-Type: application/json"`.
. Enter your username, password, and the Search Service endpoint on port `8094` with the name of the index you want to query: 
+
[source,console]
----
include::example$run-search-header.sh[]
----
+
To use SSL, use the `https` protocol in the Search Service endpoint URL and port `18094`. 
. Enter the JSON payload for your query. 
+
You can follow 1 of the following examples, based on the type of pagination or sort criteria you want to use for your documents: 

* <<offset,>>
* <<paginate-forward,Return Search Results After a Specific Document>>
* <<paginate-backward,Return Results Before a Specific Document>>
* <<non-textual,Paginate with Numeric, Date, or Geo Fields>>

NOTE: You cannot <<paginate-forward,paginate forward>> and <<paginate-backward,paginate backward>> in the same Search query.

[#offset]
=== Paginate Using Offset-Based Pagination 

To return a page of results from a Search query using offset-based pagination:

. Set the xref:search-request-params.adoc#size-limit[`size`] property to the number of results you want to return on a page.
. Set the xref:search-request-params.adoc#size-limit[`from`] property to the number of results to skip before the page starts.
+
For example, set your `size` to `5` and `from` to `10` to return results 11 through 15:
+
[source,json]
----
include::example$pagination/pagination-from-size-example.jsonc[]
----

To return a page using offset-based pagination, the Search Service processes and skips over every result that comes before it.
Offset-based pagination uses more heap memory.
For deeper pages, use <<paginate-forward,cursor-based pagination>>, instead.

[#paginate-forward]
=== Return Search Results After a Specific Document

To use the results from a previous Search query to paginate and return the next page of results, or return the results after a specific document:

. Run your Search query with a `sort` array and the `size` property set to your desired page size.
+
TIP: Make sure that your `sort` array forces a final order on your search results.
Try to always set your document ID values as the final sort criteria in any `sort` array.
+
For example, the following query returns the first 3 results for a conjunct query with the terms `food` and `view`, sorted by `score`, and then by the documents' `id` values:
+
[source,json]
----
include::example$pagination/pagination-queries-example.jsonc[tag=first_page]
----
. From your results, copy the values from the `sort` array of the last document on the page.
+
NOTE: If your `sort` array contains numeric, date, or geo fields, you must copy the values from the document's `decoded_sort` array instead of its `sort` array.
For more information, see <<non-textual,Paginate on Numeric, Date, or Geo Fields>>.
+
For example, from the previous query, the object in your search results for the last result on the page could be similar to the following: 
+
[source,json]
----
include::example$pagination/pagination-decoded-sort.jsonc[tag=simple_sort]
----
. Add the values from the copied `sort` array to the xref:search-request-params.adoc#search_after[`search_after`] array, in the same order as the `sort` array for your query.
+
For example, the following query uses `search_after` to return only the next 3 results after the document with the `id` value `hotel_3629`:
+
[source,json]
----
include::example$pagination/pagination-queries-example.jsonc[tag=next_page]
----
. Run the query to return the results for the next page in your search.

[#paginate-backward]
=== Return Results Before a Specific Document

To use the results from a previous Search query to paginate and return the previous page of results, or return the results before a specific document:

. Run your Search query with a `sort` array and the `size` property set to your desired page size.
+
TIP: Make sure that your `sort` array forces a final order on your search results.
Try to always set your document ID values as the final sort criteria in any `sort` array.
+
For example, the following query returns the first 3 results for a conjunct query with the terms `food` and `view`, sorted by `score`, and then by the documents' `id` values:
+
[source,json]
----
include::example$pagination/pagination-queries-example.jsonc[tag=first_page]
----
. From your results, copy the values from the `sort` array of the first document on the page.
+
NOTE: If your `sort` array contains numeric, date, or geo fields, copy the values from the document's `decoded_sort` array instead of its `sort` array.
For more information, see <<non-textual,Paginate on Numeric, Date, or Geo Fields>>.

. Add the copied values to the xref:search-request-params.adoc#search_before[`search_before`] array, in the same order as your `sort` array.
+
For example, the following query uses `search_before` to return only the preceding 3 results from before the document with the `id` value `hotel_21850`:
+
[source,json]
----
include::example$pagination/pagination-queries-example.jsonc[tag=previous_page]
----
. Run the query to return the results from the previous page in your search.

[#non-textual]
=== Paginate with Numeric, Date, or Geo Fields

[.status]#Couchbase Server 8.5#

As of Couchbase Server version 8.5 and later, you can add numeric, date, or geospatial data fields to your `sort` array for cursor-based pagination.

IMPORTANT: Make sure all nodes in your cluster are running Couchbase Server version 8.5 or later before trying to paginate on numeric, date, or geospatial data fields.
Mixed version clusters might return inconsistent results.

To use cursor-based based pagination with numeric, date, or geospatial data fields:

. Run your Search query with a `sort` array and the `size` property set to your desired page size.
+
For example, the following query returns the first 10 results for a conjunct query with the terms `food` and `view`, sorted by `reviews.ratings.Overall`, `reviews.date`, `geo_distance` from a set of coordinates, and then by the documents' `id` values:
+
[source,json]
----
include::example$pagination/pagination-queries-example.jsonc[tag=complex_sort]
----
. Continue with <<paginate-forward,Return the Next Page of Results>> or <<paginate-backward,Return the Previous Page of Results>>, using the `decoded_sort` values for these fields in your `search_after` or `search_before` array.
+
For example, a document sorted by the `sort` object in the previous query could return the following `sort` and `decoded_sort` arrays in your search results:
+
[source,json]
----
include::example$pagination/pagination-decoded-sort.jsonc[tag=complex_sort]
----
+
The `sort` array contains the encoded data from the `reviews` object, the encoded geo distance, and the document's ID value.
The `decoded_sort` array contains the readable values for `reviews.ratings.Overall`, `reviews.date`, `geo_distance` and the same document ID.
+
If you wanted to return the next 5 results after `hotel_21851`, your query could look like the following: 
+
[source,json]
----
include::example$pagination/pagination-queries-example.jsonc[tag=complex_next]
----

== Next Steps

* xref:run-searches.adoc[]
* xref:search-request-params.adoc[]
* xref:simple-search-rest-api.adoc[]
* xref:geo-search-rest-api.adoc[]
