= Quick Index Mapping and Field Options 
:page-topic-type: reference
:description: When you create a Search index with Quick Mode in the Capella UI, you must set options for each field or type mapping you add to the index. 

[abstract]
{description}

You can create the following types of type mappings in Quick Mode: 

* <<quick-collection,>>
* <<quick-field,>>

TIP: Indexing an entire collection in Quick Mode creates a dynamic type mapping for that collection. 
Indexing a field creates a static type mapping for the parent collection.
For more information about static and dynamic type mappings, see xref:customize-index.adoc#type-mappings[Search Index Features].

For more information about how to create a Search index with Quick Mode, see xref:create-quick-index.adoc[]. 

[#quick-collection]
== Quick Collection Type Mapping Options 

Configure an entire collection in Quick Mode to add or remove all documents in that collection from your Search index.

You can configure the following settings in Quick Mode for a type mapping that uses an entire collection: 

|====
|Option |Description 

| Index everything from collection: "`$COLLECTION_NAME`" a|

You must select *Index everything from collection* to add a collection type mapping in Quick Mode. 

| Index text fields as identifiers a|

To index any *Text* type fields with the xref:default-analyzers-reference.adoc#keyword[keyword analyzer], select *Index text fields as identifiers*. 

To use other analyzers or settings on text fields, clear *Index text fields as identifiers*. 

For more information about analyzers, see xref:customize-index.adoc#analyzers[Search Index Features].

|Analyzer/Language a|

Select the language for the content inside any *Text* fields. 

The Search Service automatically applies an xref:customize-index.adoc#analyzers[analyzer] to the field's contents based on the selected language. 

For more information about the available language options, see xref:quick-index-supported-languages.adoc[].

|====

[#quick-field]
== Quick Field Type Mapping Options 

Configure a single field in Quick Mode to add or remove it from your Search index.

You can configure the following settings in Quick Mode for a type mapping that uses a single field: 

|====
|Option |Description 

|Index this field as an identifier (Text Only) a|

To index this field with the xref:default-analyzers-reference.adoc#keyword[keyword analyzer], select *Index this field as an identifier*. 

To use other analyzers or settings on this text field, clear *Index this field as an identifier*. 

For more information about analyzers, see xref:customize-index.adoc#analyzers.adoc[Search Index Features].

|Language (Text Only) a|

Select the language for the content inside a text field. 

The Search Service automatically applies an xref:customize-index.adoc#analyzers[analyzer] to the field's contents based on the selected language. 

For more information about the available language options, see xref:quick-index-supported-languages.adoc[].

|Include in search results a|

To include content from the field in search results, select *Include in search results*. 

To exclude the field's content from search results, clear *Include in search results*. 

|Support highlighting a|

The Search Service can highlight matching search terms in search results from an index. 

To enable highlighting in search results, select *Support highlighting*. 

To turn off highlighting in search results, clear *Support highlighting*. 

NOTE: To enable *Support highlighting*, you must also enable *Include in search results*. 

|Support phrase matching a|

To support searches for whole phrases, select *Support phrase matching*. 

To turn off phrase matching, clear *Support phrase matching*. 

|Support field agnostic search a|

To search the field's contents without specifying the field name in a search query, select *Support field agnostic search*. 

To turn off field agnostic search, clear *Support field agnostic search*. 

|Support sorting and faceting a|

To sort search results and use xref:search-request-params.adoc#facets[facets] with the field's contents, select *Support sorting and faceting*. 

To turn off sorting and facets, clear *Support sorting and faceting*. 

|Searchable As a|

Set a different name that you can use to search the field's contents in a query. 

The default value is the field's name.

|====