= Run a Search With a Search Index
:page-topic-type: concept
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-aliases: fts:fts-perform-searches.adoc, fts:fts-searching-full-text-indexes-aliases.adoc, fts:fts-searching-with-sdk.adoc
:description: Run a Search query to search and return the contents of a Search index.

[abstract]
{description}

If you use the default search result xref:search-request-params.adoc#sort[sorting] of `_score`, a document's <<scoring,score>> determines where it appears in your search results. 

NOTE: You must xref:create-search-indexes.adoc[create a Search index] before you can run a search with the Search Service.

You can run a search against a Search index with: 

* The <<ui,Couchbase {page-ui-name}>>. 
* The <<api,Search Service REST API with curl and HTTP>>.
* A <<sql,{sqlpp} query>>. 
* The Couchbase SDKs: 
+
include::partial$sdks-fts-links.adoc[]

To run a Search query against multiple Search indexes at once, xref:create-search-index-alias.adoc[].

[#scoring]
== Scoring for Search Queries 

As of Couchbase Server version 8.0, you can choose between 2 scoring algorithms for your Search index: 

* <<tf-idf,tf-idf>>
* <<bm25,bm25>>

For more information about how to set your scoring model, see xref:set-advanced-settings.adoc#scoring_model[Set Search Index Advanced Settings].

[TIP]
====
Scoring can also change based on whether you're using:

* xref:synonyms/synonyms-search.adoc#run-synonym-search[Synonyms and synonym searches] in your Search index.
* xref:custom-scripts/custom-script-queries.adoc[Custom script queries].
====

[#tf-idf]
=== tf-idf Search Scoring

To determine a document's score in search results, the Search Service can use the https://en.wikipedia.org/wiki/Tf%E2%80%93idf[tf-idf^] algorithm. 
`tf-idf` increases the score of a document based on term frequency, or the number of times a term occurs in a document divided by the total number of terms in the document. 
It penalizes document frequency, or how often a term appears across all documents. 

The `tf-idf` score is calculated at a partition level in a Search index. 

The Search Service uses `tf-idf` to calculate the hit score for a document, multiplied by any xref:search-request-params.adoc#boost[boost] parameters applied to each query inside the xref:search-request-params.adoc#query-object[query object]: 

----
hit_score = (query_1_boost * query_1_hit_score) + (query_2_boost * query_2_hit_score)
----

If one of your Search queries is a xref:vector-search:vector-search.adoc[Vector Search query], the calculation changes to: 

----
hit_score = (query_1_boost * query_1_hit_score) + (knn_boost * knn_distance)
----

When running a hybrid search with the <<ui,{page-ui-name}>> or <<api,REST API>>, the Search Service displays results as a disjunct (`OR`) between your regular Search and Vector Search queries. 

TIP: When running a hybrid Search query and the `tf-idf` algorithm, you should add a `boost` value to your regular Search query to level the `tf-idf` score with the knn distance.
Otherwise, you might see unexpected search results.
This is because of the differences in the scoring algorithms between the 2 query types.

[#bm25]
=== bm25 Search Scoring

As of Couchbase Server version 8.0, you can choose to use the https://en.wikipedia.org/wiki/Okapi_BM25[bm25^] algorithm instead of `tf-idf` for your Search index.

`bm25` ranks documents based on the query terms that appear in each document, regardless of proximity.
It calculates the number of times a term occurs in a document, with penalties for more common terms like `tf-idf`, but also includes: 

* Diminishing returns for a term that continues to frequently appear in documents, based on a saturation parameter (`k1`).
* An adjustment to the resulting score, based on the total length of the current document field, divided by a normalized average length of the field across all documents (`b`).

The value of `k1` limits just how much a single query term's frequency can affect the scoring of a document.
`k1` reduces the effect of term repetition and the risk of documents with excessively repeated content inflating your relevance scores.
For example, spam or clickbait content would have reduced scores in `bm25` over the same document sentence being scored with `tf-idf`.

The Search Service chooses reasonable defaults for the value of `k1` and `b`.

Unlike `tf-idf`, `bm25` rewards term frequency, but penalizes document frequency.

The calculation for a basic Search query is still based on the document's score for a query multiplied by any xref:search-request-params.adoc#boost[boost] parameters: 

----
hit_score = (query_1_boost * query_1_hit_score) + (query_2_boost * query_2_hit_score)
----

The calculation when running a hybrid Search query, that includes xref:vector-search:vector-search.adoc[a Vector Search query], is still: 

----
hit_score = (query_1_boost * query_1_hit_score) + (knn_boost * knn_distance)
----

When running a hybrid search with the <<ui,{page-ui-name}>> or <<api,REST API>>, the Search Service displays results as a disjunct (`OR`) between your regular Search and Vector Search queries. 

`bm25` supports better hybrid search results and richer result rankings. 
It also gives more stable result ordering across Search index partitions, when xref:search-request-params.adoc#global_scoring[`global_scoring`] is enabled.

[#ui]
== Run a Search with the {page-ui-name}

You can use the {page-ui-name} to test your Search index before you integrate search into your application. 

You can enter a basic search query in the {page-ui-name}, or use a xref:search-request-params.adoc#query[query object] and other JSON properties for a more complex search.
If your cluster is running Couchbase Server version 7.6.2 and later, the {page-ui-name} lets you generate a command-line curl example or edit the JSON for your query using a built-in code editor.

For more information about how to run a search with the {page-ui-name}, see xref:simple-search-ui.adoc[].

For more information about how to configure a Search index and search for geospatial data, see xref:geo-search-ui.adoc[].

[#api]
== Run a Search with the REST API 

You can also use the REST API, curl, and HTTP to run a search.

Use a xref:search-request-params.adoc[Search request JSON payload] to control how the Search Service returns results. 

For more information about how to run a search with the REST API, see xref:simple-search-rest-api.adoc[].

For more information about how to configure a Search index and search for geospatial data, see xref:geo-search-rest-api.adoc[].

[#sql]
== Run a Search with a {sqlpp} Query 

Use the xref:tools:query-workbench.adoc[Query tab] to search using natural-language search and {sqlpp} features in the same query. 

When using {sqlpp} with a hybrid xref:vector-search:vector-search.adoc[Vector Search] query, you have more flexibility in how you choose to display your search results. 
When running a hybrid search with the <<ui,{page-ui-name}>> or <<api,REST API>>, the Search Service displays results as a disjunct (`OR`) between your 2 search queries. 
For example: 

----

{ 
    "query": 
    {
        "match_phrase": "my regular query"
    } 
}

OR 

{
    "knn": [
        "k": 5,
        "field": "vector_field",
        "vector": [0, 0, 128]
    ]
}
----

{sqlpp} allows you to choose whether to return search results as a conjunct (`AND`) or a disjunct (`OR`) between for hybrid search queries.

As a conjunct, the Search Service: 

* Returns matches that score highly for both the regular Search query and the Vector Search query. 
* Excludes matches that only match the Vector Search query.

For example: 

[source,sqlpp]
----

SELECT meta().id FROM <key_space>
WHERE text = "content"
AND SEARCH(<key_space>, {"query": {"match": "content", "field": "text"}, "knn": {"vector": <vector_embedding>", "field": "vector_field", "k": 5}});

----

As a disjunct, the Search Service: 

* Returns matches for the regular Search query, followed by matches for the Vector Search query.

As a result, you could see matches for the Vector Search query that do not contain matches for the regular Search query. 

For example: 

[source,sqlpp]
----

SELECT meta().id FROM <key_space>
WHERE SEARCH (<key_space>, {"query": {"match": "content", "field": "text"}, "knn": {"vector": <vector_embedding>", "field": "vector_field", "k": 5}});

----

For more information about how to use the Search Service from a {sqlpp} query, see xref:n1ql:n1ql-language-reference/searchfun.adoc[].

== See Also 

* xref:create-search-indexes.adoc[]
* xref:customize-index.adoc[]
* xref:index-aliases.adoc[]
* xref:search-facets.adoc[]
* xref:custom-scripts/custom-script-queries.adoc[]