= Run a Search With a Search Index
:page-topic-type: concept
:description: Run a Search query to search and return the contents of a Search index.

[abstract]
{description}

NOTE: You need to xref:create-search-indexes.adoc[create a Search index] before you can run a search with the Search Service.

You can run a search against a Search index with: 

* The <<ui,Couchbase Capella UI>>. 
* The <<api,Search Service REST API with curl and HTTP>>.
* The Couchbase SDKs: 
+
include::partial$sdks-fts-links.adoc[]

[#ui]
== Run a Search with the Capella UI

You can use the Capella UI to test your Search index before you integrate search into your application. 

You can enter a basic search query in the Capella UI, or use a xref:search-request-params.adoc#query[query object] and other JSON properties for a more complex search. 

For more information about how to run a search with the Capella UI, see xref:simple-search-ui.adoc[].

For more information about how to configure a Search index and search for geospatial data, see xref:geo-search-ui.adoc[].

[#api]
== Run a Search with the REST API 

You can also use the REST API, curl, and HTTP to run a search.

Use a xref:search-request-params.adoc[Search request JSON payload] to control how the Search Service returns results. 

For more information about how to run a search with the REST API, see xref:simple-search-rest-api.adoc[].

For more information about how to configure a Search index and search for geospatial data, see xref:geo-search-rest-api.adoc[].

== See Also 

* xref:create-search-indexes.adoc[]
* xref:customize-index.adoc[]
* xref:index-aliases.adoc[]