= Run a Search
:page-topic-type: concept
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-aliases: fts:fts-perform-searches.adoc, fts:fts-searching-full-text-indexes-aliases.adoc, fts:fts-searching-with-sdk.adoc
:description: Run a Search query to search and return the contents of a Search index.

[abstract]
{description}

NOTE: You must xref:create-search-indexes.adoc[create a Search index] before you can run a search with the Search Service.

You can run a search against a Search index with: 

* The <<ui,Couchbase {page-ui-name}>>. 
* The <<api,Search Service REST API with curl and HTTP>>.
* A <<sql,{sqlpp} query>>. 
* The Couchbase SDKs: 
+
include::partial$sdks-fts-links.adoc[]

To run a Search query against multiple Search indexes at once, xref:create-search-index-alias.adoc[].

[#ui]
== Run a Search with the Web Console

You can use the Web Console to test your Search index before you integrate search into your application. 

You can enter a basic search query in the Web Console, or use a xref:search-request-params.adoc#query[query object] and other JSON properties for a more complex search. 

For more information about how to run a search with the Web Console, see xref:simple-search-ui.adoc[].

For more information about how to configure a Search index and search for geospatial data, see xref:geo-search-ui.adoc[].

[#api]
== Run a Search with the REST API 

You can also use the REST API, curl, and HTTP to run a search.

Use a xref:search-request-params.adoc[Search request JSON payload] to control how the Search Service returns results. 

For more information about how to run a search with the REST API, see xref:simple-search-rest-api.adoc[].

For more information about how to configure a Search index and search for geospatial data, see xref:geo-search-rest-api.adoc[].

[#sql]
== Run a Search with a {sqlpp} Query 

Use the xref:tools:query-workbench.adoc[Query tab] to search using natural-language search and {sqlpp} features in the same query. 

For more information about how to use the Search Service from a {sqlpp} query, see xref:n1ql:n1ql-language-reference/searchfun.adoc[].

== See Also 

* xref:create-search-indexes.adoc[]
* xref:customize-index.adoc[]
* xref:index-aliases.adoc[]