= Add Autocomplete to Your Application
:description: Use autocomplete to add suggestions for a user's Search query as they type in your application. 
:page-topic-type: guide
:tabs:

[abstract]
{description}

Create and configure a Search index that supports autocomplete, then configure your application to return results from the Search Service.

== Prerequisites 

* You've deployed the Search Service on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* Your user account has the *Search Admin* role for the bucket where you want to create the index.

== Procedure 

To add autocomplete with the Search Service to your application:

. Copy the follwoing JSON Search index payload template.
JSON payload: 
+
[source,json]
----
include::example$autocomplete-search-index.jsonc[]
----
. Update the following strings in the template to create a new file (example index called "e-ngram-2-8" for keyspace *travel-sample.inventory.hotel* field *name*)
+
[cols="1,1"]
|===
| "name": "$IMDEX_NAME, | "name": "e-ngram-2-8",
| "sourceName": "$BUCKET_NAME", | "sourceName": "travel-sample",
| "$SCOPE_NAME.$COLLECTION_NAME": { | "inventory.hotel": {
| "$FIELD_NAME": { | "name": {
| "name": "$FIELD_NAME", | "name": "name",
|===
. xref:search-query-auto-complete-ui.adoc#search-index[Create an autocomplete Search index with the UI] or xref:create-search-index-rest-api.adoc[] with the file you created. 
[start=2]
. xref:simple-search-rest-api.adoc[Run a Search query] with 2-8 characters in the `query` property to test the Search index.
. Configure your application to return results from the Search Service.
+
The following examples simulate a user typing an input string and return search results for each partial string:
+
[{tabs}]
====
C#:: 
+
--
[source,csharp]
----
include::example$autocomplete-sample.cs[]
----
--
Go::
+
--
[source,go]
----
include::example$autocomplete-sample.go[]
----
--

Java::
+
--
[source,java]
----
include::example$autocomplete-sample.java[]
----
--

JavaScript::
+
--
[source,javascript]
----
include::example$autocomplete-sample.js[]
----
--

Python::
+
--
[source,python]
----
include::example$autocomplete-sample.py[]
----
--
====

== Next Steps

After you add autocomplete to your application, you can xref:customize-index.adoc[] or change the xref:search-index-params.adoc[JSON payload] for your Search index to improve your search results. 
