= Add Autocomplete to Your Application
:description: Use autocomplete to add suggestions for a user's Search query as they type in your application. 
:page-topic-type: guide
:tabs:

[abstract]
{description}

Create and configure a Search index that supports autocomplete, then configure your application to return results from the Search Service.

== Prerequisites 

* You've deployed the Search Service on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* Your user account has the *Search Admin* role for the bucket where you want to create the index.

== Procedure 

. xref:search-query-auto-complete-ui.adoc#search-index[Create an autocomplete Search index with the UI] or xref:create-search-index-rest-api.adoc[] with the following JSON payload: 
+
[source,json]
----
include::example$autocomplete-search-index.jsonc[]
----
[start=2]
. Configure your application to return results from the Search Service.
+
The following examples simulate a user typing an input string and return search results for each partial string:
+
[{tabs}]
====
C#:: 
+
--
[source,csharp]
----
include::example$autocomplete-sample.cs[]
----
--
Go::
+
--
[source,go]
----
include::example$autocomplete-sample.go[]
----
--

Java::
+
--
[source,java]
----
include::example$autocomplete-sample.java[]
----
--

JavaScript::
+
--
[source,javascript]
----
include::example$autocomplete-sample.js[]
----
--

Python::
+
--
[source,python]
----
include::example$autocomplete-sample.py[]
----
--
====

== Next Steps

