= Configure an Autocomplete Search Index
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name} 
:description: Create a Search index with the {page-ui-name} or import a JSON Search index payload to start using autocomplete with the Search Service.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your database. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have logged in to the Couchbase {page-ui-name}.
 

== Procedure 

You can create a compatible Search index with the <<ui,{page-ui-name} in Advanced Mode>> or <<import,import a JSON payload>>.  

[#ui]
=== Create an Autocomplete Search Index Manually with the {page-ui-name}

To create the Search index in the {page-ui-name} with Advanced Mode:

. On the *Databases* page, select the database where you want to create the Search index. 
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
. Click the btn:[Advanced Mode] toggle.
. In the *Index Name* field, enter a name for the Search index. 
+
[NOTE]
====
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

For Couchbase Server version 7.6 and later, your index name must be unique inside your selected bucket and scope. 
You cannot have 2 indexes with the same name inside the same bucket and scope.
====
. Under *Advanced Settings*, expand *Analyzers*. 
. xref:create-custom-analyzer.adoc[] with the following settings:
.. In the *Name* field, enter `keyword_to_lower`.
.. In the *Tokenizer* list, select *single*. 
.. In the *Token Filters* list, select and add the *to_lower* token filter. 
. Under *Advanced Settings*, expand *Custom Filters*. 
. xref:create-custom-token-filter.adoc#edge-ngram[Create a custom token filter] with the following settings: 
.. In the *Name* field, enter `edge_ngram_2_8`. 
.. In the *Type* list, select *edge_ngram*.
.. In the *Min* box, enter `2`, or the minimum number of characters you want the Search index to use for autocomplete.
.. In the *Max* box, enter `8`, or the maximum number of characters you want the Search index to use for autocomplete.
. xref:create-custom-analyzer.adoc[Create another custom analyzer] with the following settings:
.. In the *Name* field, enter `edge_ngram`.
.. In the *Tokenizer* list, select *unicode*.  
.. In the *Token Filters* list, click both the *to_lower* and your custom *edge_ngram_2_8* token filter.
. Under *Type Mappings*, in the *Bucket* list, select the bucket where you want to create your Search index. 
. In the *Scope* list, select the scope where you want to create the index.
. In the *Filter by collection or field* field, enter the name of the collection you want to search from your Search index.
.. When the collection appears, click the collection name. 
.. Clear *Index everything from collection: "$COLLECTION_NAME"*.
.. Click btn:[Add].
. In the *Filter by collection or field* field, enter the name of a field in your collection's document schema that contains the data you want to search. 
. Configure the field: 
.. In the *Analyzer/Language* list, select your *edge_ngram* analyzer. 
.. Select *Index this field*.
.. Select *Store field values*. 
.. Select *Include in _all field*.
. Expand *General Settings*. 
. In the *Default Analyzer* list, select your *keyword_to_lower* analyzer. 
. Click btn:[Create Index].

[#import]
=== Import a Search Index Payload 

. xref:import-search-index.adoc[] with the following JSON payload, replacing all placeholder values that start with a `$`:
+
[source,json]
----
include::example$autocomplete-search-index.jsonc[]
----

== Next Steps

To add an autocomplete feature to your application, see xref:search-query-auto-complete-code.adoc[] for example code. 
