= Add Autocomplete to Your Application
:description: Use autocomplete to add suggestions for a user's Search query as they type in your application. 
:page-topic-type: guide
:tabs:

[abstract]
{description}

After you xref:search-query-auto-complete-ui.adoc[create and configure a Search index that supports autocomplete], configure your application to return results from the Search Service.

== Prerequisites 

* You've deployed the Search Service on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* You've created a compatible Search index. For more information, see xref:search-query-auto-complete-ui.adoc[].

== Procedure 

To add autocomplete with the Search Service to your application:

. To test that your Search index was configured correctly, do one of the following: 
.. xref:simple-search-rest-api.adoc[Run a Search query from the REST API] with 2-8 characters in the `query` property.
.. xref:simple-search-ui.adoc[Run a Search query from the Capella UI] with 2-8 characters in the *Search* field. 

+
For example, with the `travel-sample` bucket, you could enter the strings `Be`, `Bea`, `Beau`, and `Beauf` to find a document with the text `Beaufort Hotel`.

. Configure your application to return results from the Search Service.
+
The following examples simulate a user typing an input string and return search results for each partial string:
+
[{tabs}]
====
C#:: 
+
[source,csharp]
----
include::example$autocomplete-sample.cs[]
----
Go::
+
[source,go]
----
include::example$autocomplete-sample.go[]
----

Java::
+
[source,java]
----
include::example$autocomplete-sample.java[]
----

JavaScript::
+
[source,javascript]
----
include::example$autocomplete-sample.js[]
----

Python::
+
[source,python]
----
include::example$autocomplete-sample.py[]
----
====

== Next Steps

After you add autocomplete to your application, to improve your search results, you can: 

* xref:customize-index.adoc[Customize your Search index with the Capella UI].
* Change the xref:search-index-params.adoc[JSON payload] for your Search index. 
