= Add Autocomplete to Your Application
:description: Use autocomplete to add suggestions for a user's Search query as they type in your application. 
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-topic-type: guide
:tabs:

[abstract]
{description}

After you xref:search-query-auto-complete-ui.adoc[create and configure a Search index that supports autocomplete], configure your application to return results from the Search Service.

== Prerequisites 

* You have the Search Service enabled on a node in your cluster.
For more information about how to change Services on your cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your cluster. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have the hostname for the node in your cluster that's running the Search Service.
+
Go to your cluster settings and click btn:[Nodes] to view node hostnames.

* You have created a compatible Search index.
For more information, see xref:search-query-auto-complete-ui.adoc[].

* You have created cluster access credentials that have Read/Write permissions on the bucket and scope where you created your Search index. 
For more information, see xref:clusters:manage-database-users.adoc[].

== Procedure 

To add autocomplete with the Search Service to your application:

. Test that your Search index was configured correctly by xref:simple-search-ui.adoc[running a Search query from the {page-ui-name}] with 2-8 characters in the *Search* field. 
+
For example, with the `travel-sample` bucket, you could enter the strings `Be`, `Bea`, `Beau`, and `Beauf` to find a document with the text `Beaufort Hotel`.

. Configure your application to return results from the Search Service.
+
The following examples simulate a user typing an input string and return search results for each partial string:
+
[{tabs}]
====
C#:: 
+
[source,csharp]
----
include::example$autocomplete-sample.cs[]
----
Go::
+
[source,go]
----
include::example$autocomplete-sample.go[]
----

Java::
+
[source,java]
----
include::example$autocomplete-sample.java[]
----

JavaScript::
+
[source,javascript]
----
include::example$autocomplete-sample.js[]
----

Python::
+
[source,python]
----
include::example$autocomplete-sample.py[]
----
====

== Next Steps

After you add autocomplete to your application, to improve your search results, you can: 

* xref:customize-index.adoc[Add additional features to your Search index from the UI].
* Change the xref:search-index-params.adoc[JSON payload] for your Search index. 
