= Add Search to Your Application
:page-topic-type: concept
:description: Use the Search Service to create a customizable search experience for your database and your end-user applications. 

[abstract]
{description}

The Search Service uses <<indexes,Search indexes>> and <<queries,Search queries>> to collect and return content from documents in your database. 

[#indexes]
== Search Indexes

A Search index tells the Search Service what content to use from documents in your database for <<queries,Search queries>>.
You can choose to exclude content to improve search performance and improve the relevance of search results.

A Search index can also analyze and modify the content in your Search index or Search query to improve matching and search results. 
The Search Service has default components that you can use to customize a Search index, or you can create your own. 

You need to create a Search index before you can use the Search Service to search the contents of your database from your application. 

For more information about how to create a Search index, see xref:create-search-indexes.adoc[].  

You can create a Search index:

* xref:create-search-index-ui.adoc[With the Couchbase Capella UI]
* xref:create-search-index-rest-api.adoc[From the REST API]

[#queries]
== Search Queries 

A Search query tells the Search Service what to search for in the contents of a Search index. 

Search queries use JSON objects to control how the Search Service returns search results. 

You can also choose to xref:search-query-auto-complete.adoc[add autocomplete] to your application to provide a more user-friendly search experience in your application.

For more information about how you can run a search against a Search index, see xref:run-searches.adoc[].

You can run a Search query:

* xref:simple-search-ui.adoc[With the Couchbase Capella UI] 
* xref:simple-search-rest-api.adoc[From the REST API]