= Configure and Test Autocomplete with the Capella UI
:page-topic-type: guide 
:description: Create a Search index and run a Search query with the Capella UI to test autocomplete with the Search Service.

[abstract]
{description}

== Prerequisites 

* You've deployed the Search Service on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* Your user account has the *Search Admin* role for the bucket where you want to create the index. 

* You've logged in to the Couchbase Capella UI. 
 

== Procedure 

To use autocomplete with the Search Service, you need to <<search-index,create a Search index with two custom analyzers>>.

Then, you can <<run-query,run a test Search query from the Web Console>>.  

[#search-index]
=== Create the Autocomplete Search Index

To create the Search index with the Capella UI:

. On the *Databases* page, select the database where you want to create the Search index. 
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
. In the *Index Name* field, enter a name for the Search index. 
+
NOTE: Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).
. Expand *Analyzers*. 
. xref:create-custom-analyzer.adoc[] with the following settings:
.. In the *Name* field, enter `keyword_to_lower`.
.. In the *Tokenizer* list, select *single*. 
.. In the *Token Filters* list, select and add the *to_lower* token filter. 
. Expand *Custom Filters*. 
. xref:create-custom-token-filter.adoc#edge-ngram[Create a custom token filter] with the following settings: 
.. In the *Name* field, enter `edge_ngram_2_8`. 
.. In the *Type* list, select *edge_ngram*.
.. In the *Min* box, enter `2`, or the minimum number of characters you want the Search index to use for autocomplete.
.. In the *Max* box, enter `8`, or the maximum number of characters you want the Search index to use for autocomplete.
. xref:create-custom-analyzer.adoc[Create another custom analyzer] with the following settings:
.. In the *Name* field, enter `edge_ngram`.
.. In the *Tokenizer* list, select *unicode*.  
.. In the *Token Filters* list, click both the *to_lower* and your custom *edge_ngram_2_8* token filter.
.. In the *Field* field, enter the name of a text field in a document from your selected scope and collection. 
.. In the *Analyzer* list, select your *edge_ngram* analyzer. 
.. Select *Index*.
.. Select *Store*. 
.. Select *Include in _all field*. 
. Expand *General Settings*. 
. In the *Default Analyzer* list, select your *keyword_to_lower* analyzer. 
. Click btn:[Create Index]

[#run-query]
=== Run A Search Query

To run a search query against the Search index from the Capella UI: 

. xref:simple-search-ui.adoc[Run a search] with the <<search-index,Autocomplete Search index>> and enter 2-8 characters to use to generate auto-completed search results. 

The Search Service returns documents that could autocomplete the query you entered in the *Search* field. 

== Next Steps

To add an autocomplete feature to your application, see Step 2 in xref:search-query-auto-complete-code.adoc[] for example code. 
