= Use Autocomplete with the Search Service
:page-topic-type: concept
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Add autocomplete to your application to provide a search engine-like experience for your database. 

[abstract]
{description}

Also known as auto suggest or type-ahead, autocomplete guesses potential matches for a user's search input as they type. 

Autocomplete can provide a better user experience with search in your application.

== Set Up Autocomplete 

To use autocomplete with the Search Service and your Couchbase {page-product-name} database:

. Create a compatible Search index. 
You can create the index xref:search-query-auto-complete-ui.adoc#ui[with the UI] or xref:search-query-auto-complete-ui.adoc#api[with the REST API].
. Configure your application to return autocomplete search results from the Search Service. 
For example code that you can use with your application, see xref:search-query-auto-complete-code.adoc[].

You can use the `travel-sample` dataset to test and configure autocomplete, or use your own data. 