= Add Search to Your Application
:page-topic-type: concept
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-aliases: clusters:search-service/search-service.adoc
:description: Use the Search Service to create a customizable search experience for your database and your end-user applications. 

[abstract]
{description}

The Search Service offers near real-time search capabilities for a diverse range of data types. 
For example, you can use the Search Service with: 

* Structured or unstructured text
* Dates
* Numbers
* CIDR notation
* Geospatial data 

Use a <<indexes,Search index>> to efficiently store your data, and retrieve it with a <<queries,Search query>>.

[#indexes]
== Search Indexes

A Search index tells the Search Service what content to use from the documents in your database for processing <<queries,Search queries>>. 
A Search index can use any field across multiple collections in a single scope.
If your cluster is running Couchbase Server version 7.6.2 and later, it can also include any document metadata stored in Extended Attributes (XATTRs).

You can choose to exclude content to improve search performance and improve the relevance of search results.

A Search index can also analyze and modify the content in your Search index or Search query to improve matching and search results. 
The Search Service has default components that you can use to customize a Search index, or you can create your own.

You need to create a Search index before you can use the Search Service to search the contents of your database from your application. 

For more information about how to create a Search index, see xref:create-search-indexes.adoc[].  

You can create a Search index:

* xref:create-search-index-ui.adoc[With the Couchbase {page-ui-name}]
* With a xref:search-index-params.adoc[JSON payload] that you xref:import-search-index.adoc[import through the UI].
//* With the Couchbase SDKs
//* xref:create-search-index-rest-api.adoc[From the REST API]

[#queries]
== Search Queries 

A Search query tells the Search Service what to search for in the contents of a Search index. 

Search queries use a simple string-based query syntax or JSON objects to control how the Search Service retrieves search results.

For more information about how you can run a search against a Search index, see xref:run-searches.adoc[].

You can run a Search query:

* xref:simple-search-ui.adoc[With the Couchbase {page-ui-name}]
* xref:n1ql:n1ql-language-reference/searchfun.adoc[With a SQL++ query]. 
* With the Couchbase SDKs: 
+
include::partial$sdks-fts-links.adoc[]
//* xref:simple-search-rest-api.adoc[From the REST API]

== Vector Search for AI Applications

Vector Search builds on {page-product-name}'s Search Service to provide vector index support for Retrieval Augmented Generation (RAG) with an existing Large Language Model (LLM).

Vector Search adds a new index type to the Search Service to support AI application development, known as a Vector Search index.
Using Vector Search and Couchbase {page-product-name}, you can develop applications with an existing LLM while giving context and up-to-date information from your own data. 

For more information about Vector Search, see xref:vector-search:vector-search.adoc[].

== See Also 

* xref:create-search-indexes.adoc[]
* xref:customize-index.adoc[]
* xref:index-aliases.adoc[]
* xref:run-searches.adoc[]
* xref:vector-search:vector-search.adoc[]
