= Add Search to Your Application
:page-topic-type: concept
:description: Use the Search Service to create a customizable search experience for your database and your end-user applications. 

[abstract]
{description}

The Search Service offers near real-time search capabilities for a diverse range of data types. 

This service accommodates structured or unstructured text (full-text search), dates, numbers, CIDR notation, and geospatial data. 

<<indexes,Search indexes>> are designed to efficiently store and retrieve these data types, thereby accelerating <<queries,Search queries>>.

[#indexes]
== Search Indexes

A Search index definition directs the Search Service on which specific content to extract from the documents in your database's collections for processing <<queries,Search queries>>. Each index can extract and process any field across multiple collections, provided that all the collections exist under a single scope.

While it might be straightforward for a developer to index all fields in a collection, the majority of production Search indexes are tailored to concentrate on only the essential content or a select set of fields. This strategy not only optimizes resource utilization but also ensures top-notch performance.

For the majority of use cases, the built-in defaults prove to be highly effective. However, to cater to advanced indexing scenarios, the Search Service also permits advanced customization by allowing users to create their own Type Mappings, Analyzers, Filters, and Datetime Parsers.

Before utilizing the Search Service to query your database contents from your application, you must first create a Search Index.
For more information about how to create a Search index, see xref:create-search-indexes.adoc[Create a Search Index].  

You can create a Search index:

* xref:create-search-index-ui.adoc[With the Couchbase Capella UI]
* xref:create-search-index-rest-api.adoc[From the REST API]

[#queries]
== Search Queries 

A Search query tells the Search Service what to search for in the contents of a Search index. 

Search queries employ either a simple string-based query syntax or more sophisticated and versatile JSON objects to dictate how the Search Service retrieves search results.

For more information about how you can query data using a Search index, see xref:run-searches.adoc[Query data using a Search Index].

You can run a Search query:

* xref:simple-search-ui.adoc[With the Couchbase Capella UI] 
* xref:simple-search-rest-api.adoc[From the REST API]

[#usecases]
== Common Use Cases

* Implement full-text search and highlighting in your application for efficient customer review searches.
* Integrate xref:search-query-auto-complete.adoc[autocomplete] functionality to offer a more user-friendly search experience within your application.
