= Collect Additional Information with Search Facets
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use Search facets to collect specific, additional information about the documents included in results for a specific search query.
:page-aliases: fts:fts-search-facets.adoc

[abstract]
{description}

The Search Service supports the following facet types: 

* <<term-facet,>>
* <<numeric-range-facet,>>
* <<date-range-facet,>>

[#term-facet]
== Term Facet

Use a term facet to return a count for the number of documents in your search results that have a specific term in a field.

TIP: For best results with a term facet, use the xref:search:default-analyzers-reference.adoc#keyword[keyword analyzer] on the field you want to use for the facet.

For example, the following Search request searches for the word `water` in the Search index, and calculates a term facet for the value of the `country` field: 

[source,console]
----
curl -X POST -H "Content-Type: application/json" \
http://{HOSTNAME}:8094/api/bucket/{BUCKET_NAME}/scope/{SCOPE_NAME}/index/{INDEX_NAME}/query -d \
'{
    "size": 10,
    "query": {
        "boost": 1,
        "query": "water"
     },
    "facets": {
         "type": {
             "size": 5,
             "field": "country"
         }
    }
}'
----

At the end of your search results, the Search Service would return the following object with the term facet information:

[source,json]
----
"facets": {
    "type": {
        "field": "country",
        "total": 94,
        "missing": 0,
        "other": 0,
        "terms": [
            {
                "term": "United States",
                "count": 46
            },
            {
                "term": "United Kingdom",
                "count": 42
            },
            {
                "term": "France",
                "count": 6
            }
        ]
    }
}
----

xref:search:simple-search-ui.adoc[Run a search with the {page-ui-name}] to view facet information in a table format. 

For more information about how to configure a term facet in your Search query, see xref:search-request-params.adoc#facets[facets] or xref:search-request-params.adoc#facet-name[\{facet-name} Object].

[#numeric-range-facet]
== Numeric Range Facet

Use a numeric range facet to define a numeric range and receive the number of documents with a field value that falls within that range. 

TIP: For best results with a numeric range facet, use a field with a `number` type in your documents.

For example, you could define numeric range facets to collect information about the ABV values for different beers in the `beer-sample` sample data:

* You could define a numeric range facet, `high`, for ABV values greater than 7. 
* You could define another numeric range facet, `low`, for ABV values less than 7. 

The curl request for your query and the specific facet information would be: 

[source,console]
----
curl -X POST -H "Content-Type: application/json" \
http://{HOSTNAME}:8094/api/bucket/beer-sample/scope/_default/index/beer-index/query -d \
'{
    "size": 10,
    "query": {
        "boost": 1,
        "query": "water"
    },
    "facets": {
        "abv": {
            "size": 5,
            "field": "abv",
            "numeric_ranges": [
                {
                    "name": "high",
                    "min": 7
                },
                {
                    "name": "low",
                    "max": 7
                }
             ]
        }
    }
}'
----

At the end of your search results, the Search Service would return the following object with the numeric range facet information:

[source,json]
----
"facets": {
    "abv": {
        "field": "abv",
        "total": 70,
        "missing": 21,
        "other": 0,
        "numeric_ranges": [
            {
                "name": "low",
                "max": 7,
                "count": 57
            },
            {
                "name": "high",
                "min": 7,
                "count": 13
            }
        ]
    }
}
----

xref:search:simple-search-ui.adoc[Run a search with the {page-ui-name}] to view facet information in a table format. 

For more information about how to configure a numeric range facet in your Search query, see:

* xref:search-request-params.adoc#facets[facets]
* xref:search-request-params.adoc#facet-name[\{facet-name} Object]
* xref:search-request-params.adoc#numeric[numeric_ranges Array Objects]

[#date-range-facet]
== Date Range Facet

Use a date range facet to define a date range and receive the number of documents with a date field value that falls within that range. 

TIP: For best results with a date range facet, use a field with the `datetime` type in your documents.
Make sure to use a xref:search:customize-index.adoc#date-time[date/time parser] that matches your date and time data. 

For example, you could define date range facets to collect information about the last time a document was updated in the `beer-sample` sample data:

* You could define a date range facet, `new`, for dates later than August 1st, 2010. 
* You could define another numeric range facet, `old`, for dates earlier than August 1st, 2010. 

The curl request for your query and the specific facet information would be: 

[source,console]
----
curl -X POST -H "Content-Type: application/json" \
http://{HOSTNAME}:8094/api/bucket/beer-sample/scope/_default/index/beer-index/query -d \
'{
    "query": {
        "field": "country",
        "term": "united"
    },
    "facets": {
        "types": {
            "size": 10,
            "field": "updated",
            "date_ranges": [
                {
                "name": "old",
                "end": "2010-08-01"
                },
                {
                "name": "new",
                "start": "2010-08-01"
                }
            ]
        }
    }
}'
----

At the end of your search results, the Search Service would return the following object with the date range facet information:

[source,json]
----
"facets": {
    "types": {
        "field": "updated",
        "total": 954,
        "missing": 0,
        "other": 0,
        "date_ranges": [
            {
                "name": "old",
                "end": "2010-08-01T00:00:00Z",
                "count": 934
            },
            {
                "name": "new",
                "start": "2010-08-01T00:00:00Z",
                "count": 20
            }
        ]
    }
}
----

xref:search:simple-search-ui.adoc[Run a search with the {page-ui-name}] to view facet information in a table format. 

For more information about how to configure a date range facet in your Search query, see:

* xref:search-request-params.adoc#facets[facets]
* xref:search-request-params.adoc#facet-name[\{facet-name} Object]
* xref:search-request-params.adoc#date[date_ranges Array Objects]

== Next Steps

For more information about how to structure a Search query, see xref:search:search-request-params.adoc[].