= Set Search Index Advanced Settings
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: When using the Advanced Mode editor in Couchbase {page-ui-name}, you can configure additional advanced settings for your Search index.

[abstract]
{description}

Advanced Mode adds full customization and advanced features such as xref:create-custom-analyzer.adoc[creating custom analyzers] or xref:set-type-identifier.adoc[setting a document filter].
For more information about the different settings and features available in a Search index, see xref:customize-index.adoc[].

You must create a Search index before you can xref:simple-search-ui.adoc[run a search] with the Search Service.

== Prerequisites

* You have the Search Service enabled on a node in your operational cluster.
For more information about how to change Services on your operational cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your operational cluster. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have created a basic Search index with the {page-ui-name}.
For more information, see xref:create-search-index-ui.adoc[].

* You have logged in to the Couchbase {page-ui-name}.

== Procedure

To set advanced settings for a Search index with the {page-ui-name}:

. On the *Operational Clusters* page, select the operational cluster where you created your Search index. 
. Go to menu:Data Tools[Search].
. Click the name of the index where you want to configure advanced settings.
. Click btn:[Enable Advanced Mode].
. Do any of the following: 
.. [[default-analyzer]]In the *Default Analyzer* list, select the xref:customize-index.adoc#analyzers[default analyzer] to assign to new xref:customize-index.adoc#type-mappings[type mappings] in your index.
+
You can also choose to xref:create-custom-analyzer.adoc[].
.. [[date-time]]In the *Default Date/Time Parser* list, select the xref:customize-index.adoc#date-time[default date/time parser] to use for date data in your index. 
+
You can also choose to xref:create-custom-date-time-parser.adoc[]. 
.. xref:set-type-identifier.adoc[].
.. xref:synonyms-search.adoc[Add and configure synonyms].
.. Choose the scoring model you want to use with your Search index.
For more information about scoring models, see xref:customize-index.adoc#scoring-model[Scoring Model].
.. If you're using xref:customize-index.adoc#dynamic[dynamic type mappings], choose how to handle dynamic fields in your Search index:
... To store the content of any fields added to a Search index from a dynamic type mapping, turn on *Store Dynamic Fields*. 
... To include fields or whole documents in your Search index that match a dynamic type mapping, turn on *Index Dynamic Fields*. 
. Click btn:[Update Index].

== Next Steps

You can keep adding additional features to your Search index to improve performance and search results.
For more information, see xref:customize-index.adoc[].

For more information about how to run a search, see xref:simple-search-ui.adoc[].