= Set a Search Index Document Filter 
:page-topic-type: guide 
:description: Use a document filter with a type mapping to add an extra filter to the documents you want to include in a Search index.
:page-toclevels: 3

[abstract]
{description}

For more information about document filters and type mappings, see xref:customize-index.adoc#type-identifiers[Customize a Search Index with the Capella UI].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your database. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].
 
* You have logged in to the Couchbase Capella UI. 

* You have started to create or already created an index in xref:create-search-index-ui.adoc[Advanced Mode].

== Procedure 

To set a document filter for a Search index with the Capella UI:

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a document filter
. Under *Type Mappings*, in the *Document Filter* list, choose the document filter you want to add to your Search index:   
.. <<json-type,>>
.. <<doc-id-sep,>>
.. <<doc-id-regex,>>

[#json-type]
=== Create a JSON Type Field Document Filter 

To only add documents to your Search index that contain a specific field with a specified string value: 

. In the *Field* field, enter the name of the field in your documents that you want to use to filter documents in your Search index.
+
For example, if your documents include a `type` field, you could enter `type` in the *Field* field. 
+
NOTE: You cannot use a field as a document filter if the field name contains a period (.).  
. In the *docvalue* field, enter the exact string from the document field that you want to use as a filter. 
+
For example, if you wanted your Search index to only return documents that had a `type` value of `hotel`, you could enter `hotel`.

[#doc-id-sep]
=== Create a Doc ID Up To Separator Document Filter 

To only add documents to your Search index that have IDs that match a specified prefix: 
 
. In the *Separator* field, enter the separator character from the ID prefix in your document ID values. 
+
For example, if you know all of your document ID values are prefixed by a string and an underscore (_), enter `_`.
. In the *ID prefix* field, enter the exact prefix from the document's ID value that you want to use as a filter. 
+
For example, if you wanted your Search index to only return documents that have an prefix of `landmark_`, you could enter `landmark`.

[#doc-id-regex]
=== Create a Doc ID with Regex document filter 

To only add documents to your Search index that have IDs that match a specified https://github.com/google/re2/wiki/Syntax[RE2] regular expression: 

. In the *regex* field, enter the regular expression that you want to use to filter documents in your Search index. 
+
For example, if you wanted only documents with ID values that contained `_40`, you could enter `_[3-5]0` as your regular expression.
. In the *ID prefix* field, add a match for the regular expression from the document's ID value that you want to use as a filter. 
+
For example, if you wanted your Search index to only return documents with ID values that contained `_40`, you could enter `_40`.


== Next Steps

After you set the document filter for your Search index, you can continue to customize your Search index: 

* xref:set-advanced-settings.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-wordlist.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].
