= Set a Search Index Type Identifier 
:page-topic-type: guide 
:description: Use a type identifier with a type mapping to add an extra filter to the documents you want to include in a Search index.
:page-toclevels: 3

[abstract]
{description}

For more information about type identifiers and type mappings, see xref:customize-index.adoc#type-identifiers[Search Index Features].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your database. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].
 
* You have logged in to the Couchbase Capella UI. 

* You have started to create or already created an index in xref:create-search-index-ui.adoc[Advanced Mode].

== Procedure 

To set a type identifier for a Search index with the Capella UI:

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to create a type identifier.
. Expand *General Settings*.
. Do one of the following:   
.. <<json-type,>>
.. <<doc-id-sep,>>
.. <<doc-id-regex,>>

[#json-type]
=== Create a JSON Type Field Type Identifier 

To only add documents to your Search index that contain a specific field with a specified string value: 

. Click the *JSON Type Field* tab. 
. In the *JSON Type Field* field, enter the name of the field in your documents that you want to use to filter documents in your Search index.
+
For example, if your documents include a `type` field, you could enter `type` in the *JSON Type Field* field. 
+
NOTE: You cannot use a field as a type identifier if the field name contains a period (.).  
. Under *Type Mappings*, next to the type mapping where you want to add the type identifier, go to menu:More Options (&vellip;)[Edit].
. In the *Name* field, add a period (.) to the end of the current type mapping name.
. After the period, add the exact string from the document field that you want to use as a filter.
+
For example, if you wanted your Search index to only return documents that had a `type` value of `hotel`, you could enter `hotel`.
. Click btn:[Submit].
. Click btn:[Update Index].

[#doc-id-sep]
=== Create a Doc ID Up To Separator Type Identifier 

To only add documents to your Search index that have IDs that match a specified prefix: 

. Click the *Doc ID up to Separator* tab. 
. In the *Doc ID up to Separator* field, enter the separator character from the ID prefix in your document ID values. 
+
For example, if you know all of your document ID values are prefixed by a string and an underscore (_), enter `_`.
. Under *Type Mappings*, next to the type mapping where you want to add the type identifier, go to menu:More Options (&vellip;)[Edit].
. In the *Name* field, add a period (.) to the end of the current type mapping name.
. After the period, add the exact prefix from the document's ID value that you want to use as a filter. 
+
For example, if you wanted your Search index to only return documents that have an prefix of `landmark_`, you could enter `landmark`.
. Click btn:[Submit].
. Click btn:[Update Index].

[#doc-id-regex]
=== Create a Doc ID with Regex Type Identifier

To only add documents to your Search index that have IDs that match a specified https://github.com/google/re2/wiki/Syntax[RE2] regular expression: 

. Click the *Doc ID with Regex* tab. 
. In the *Doc ID with Regex* field, enter the regular expression that you want to use to filter documents in your Search index. 
+
For example, if you wanted documents with ID values that contained `_40`, you could enter `_[3-5]0` as your regular expression.
. Under *Type Mappings*, next to the type mapping where you want to add the type identifier, go to menu:More Options (&vellip;)[Edit].
. In the *Name* field, add a period (.) to the end of the current type mapping name.
. After the period, add a match for the regular expression from the document's ID value that you want to use as a filter.
+
For example, if you wanted your Search index to only return documents with ID values that contained `_40`, you could enter `_40`.
. Click btn:[Submit].
. Click btn:[Update Index].

== Next Steps

After you set the type identifier for your Search index, you can continue to customize your Search index: 

* xref:set-advanced-settings.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-wordlist.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].
