= Set the Type Identifier for a Search Index 
:page-topic-type: guide 
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-aliases: fts:fts-type-identifiers.adoc
:description: Use a type identifier with a type mapping to add an extra filter to the documents you want to include in a Search index.
:page-toclevels: 3

[abstract]
{description}

For example, if you added a filter to your type mapping that checked if the value of a field was `true`, only documents with the value `true` for that field would be included in your Search index under that type mapping.
Based on your settings, xref:create-child-field.adoc[child fields] or xref:create-child-mapping.adoc[child mappings] that you define for documents that pass the filter on this type mapping will be returned in search results. 

You can filter based on the value of a field, or part of the value of your document IDs. 

As of Couchbase Server version 8.0, you can filter documents with custom filters based on the value of: 

* xref:search-index-params.adoc#boolean_filter[A boolean field].
* xref:search-index-params.adoc#date_range_filter[A date field, within a specific range].
* xref:search-index-params.adoc#numeric_range_filter[A numeric field, within a specific range].
* xref:search-index-params.adoc#term_filter[A term in a text field].
* A xref:search-index-params.adoc#conjunct_filter[conjunct] or xref:search-index-params.adoc#disjunct_filter[disjunct] object that combines 2 or more of the available filters.

You can add up to a maximum of 100 custom document filters on a single Search index.

For more information about type identifiers and type mappings, see xref:customize-index.adoc#type-identifiers[Customize a Search Index with the Web Console].

== Prerequisites 

* You have the Search Service enabled on a node in your cluster.
For more information about how to deploy a new node and Services on your cluster, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have a bucket with scopes and collections in your cluster.
For more information about how to create a bucket, see xref:server:manage:manage-buckets/create-bucket.adoc[]. 

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You have created at least one type mapping in your Search index. 
For more information, see xref:create-type-mapping.adoc[]. 

* Your user account has the xref:learn:security/roles.adoc#search-admin[`Search Admin`] role for the bucket where you want to edit an index. 
 
* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To set a type identifier for a Search index with the Couchbase {page-ui-name}: 

. Go to *Search*.
. Click the index where you want to set a type identifier.
. Click btn:[Edit].
. Expand *Type Identifier*. 
. Do one of the following: 
.. <<json-type,>>
.. <<doc-id-sep,>>
.. <<doc-id-regex,>>
.. (Couchbase Server version 8.0 and later) <<custom,>>

WARNING: You cannot use custom document filters with another type of type identifier on your Search index. 
If you select an option other than *Custom* after you have defined custom document filters, you'll lose any defined custom filters on your Search index.

[#json-type]
=== Create a JSON Type Field Type Identifier 

To only add documents to your Search index that contain a specific field with a specified string value: 

. Select *JSON type field*. 
. In the *JSON Type Field* field, enter the name of the field in your documents that you want to use to filter documents in your Search index.
+
For example, if your documents include a `type` field, you could enter `type` in the *JSON Type Field* field. 
+
NOTE: You cannot use a field as a type identifier if the field name contains a period (.).  
. Under *Type Mappings*, next to the type mapping where you want to add the type identifier, click btn:[Edit]. 
. In the *#* field, add a period (.) to the end of the current type mapping name. 
. After the period, add the exact string from the document field that you want to use as a filter. 
+
For example, if you wanted your type mapping to only include documents that had a value of `hotel` in the `type` field, you could enter `scope.collection.hotel` in the type mapping *#* field.
. Click btn:[OK].
. Click btn:[Update Index].

[#doc-id-sep]
=== Create a Doc ID Up To Separator Type Identifier 

To only add documents to your Search index that have IDs that match a specified prefix: 

. Select *Doc ID up to Separator*. 
. In the *Doc ID up to Separator* field, enter the ID prefix, up to the separator character, that you want to use to filter documents in your Search index.
+
For example, if you know all of your document ID values are prefixed by a string and an underscore (\_), enter `_`.
. Under *Type Mappings*, next to the type mapping where you want to add the type identifier, click btn:[Edit]. 
. In the *#* field, add a period (.) to the end of the current type mapping name. 
. After the period, add the exact prefix from the document's ID value that you want to use as a filter. 
+
For example, if you wanted your type mapping to only include documents that have an prefix of `landmark_` in their ID values, you could enter `scope.collection.landmark` in the type mapping *#* field.
. Click btn:[OK].
. Click btn:[Update Index].

[#doc-id-regex]
=== Create a Doc ID with Regex Type Identifier 

To only add documents to your Search index that have IDs that match a specified https://github.com/google/re2/wiki/Syntax[RE2] regular expression: 

. Select *Doc ID with Regex*. 
. In the *Doc ID with Regex* field, enter the regular expression that you want to use to filter documents in your Search index. 
+
For example, if you wanted only documents with ID values that contained `\_40`, you could enter `_[3-5]0` as your regular expression.
. Under *Type Mappings*, next to the type mapping where you want to add the type identifier, click btn:[Edit].
. In the *#* field, add a period (.) to the end of the current type mapping name. 
. After the period, add a match for the regular expression from the document's ID value that you want to use as a filter. 
+
For example, if you wanted your type mapping to only include documents with ID values that contained `_40`, you could enter `scope.collection._40` in the type mapping *#* field.
. Click btn:[OK].
. Click btn:[Update Index].

[#custom]
=== Create a Custom Document Filter Type Identifier

To create a new custom document filter on a Search index with the Couchbase {page-ui-name}:

. Select *Custom*. 
. Click btn:[+ Add Document Filter].
. In the *Type* field, enter a name for your new document filter.
. In the *Filter* code editor, enter a JSON object to define your document filter.
+
For more information about the properties for each document filter type, see: 
+
* xref:search-index-params.adoc#boolean_filter[Boolean Document Filters]
* xref:search-index-params.adoc#date_range_filter[Date Range Document Filters]
* xref:search-index-params.adoc#numeric_range_filter[Numeric Range Document Filters]
* xref:search-index-params.adoc#term_filter[Term Document Filters]
* xref:search-index-params.adoc#conjunct_filter[Conjunct Document Filters]
* xref:search-index-params.adoc#disjunct_filter[Disjunct Document Filters]

+
TIP: Do not add the name of your document filter to your filter definition when defining a custom document filter through the {page-ui-name}.
Define the document filter as an unnamed object with the specific properties you need for your document filter type.

+
. Click btn:[Save].
. Under *Type Mappings*, next to the type mapping where you want to add the type identifier, click btn:[Edit].
. In the *#* field, add a period (.) to the end of the current type mapping name. 
. After the period, enter the name of the custom document filter that you want to use to filter documents on this type mapping.
+
For example, if you defined a custom document filter named `free_breakfast_true`, enter `scope.collection.free_breakfast_true` in the type mapping *#* field.
. Click btn:[OK].
. Click btn:[Update Index].

== Next Steps

After you set the type identifier for your Search index, you can continue to customize your Search index: 

* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:set-advanced-settings.adoc[]
* xref:synonyms/synonyms-search.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].