= Set the Type Identifier for a Search Index 
:page-topic-type: guide 
:description: Use a type identifier with a type mapping to add an extra filter to the documents you want to include in a Search index.
:page-toclevels: 3

[abstract]
{description}

For more information about type identifiers and type mappings, see xref:customize-index.adoc#type-identifiers[Customize a Search Index with the Web Console].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have a bucket with scopes and collections in your database.
For more information about how to create a bucket, see xref:server:manage:manage-buckets/create-bucket.adoc[]. 

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].

* You have created at least one type mapping in your Search index. 
For more information, see xref:create-type-mapping.adoc[]. 

* Your user account has the *Search Admin* role for the bucket where you want to edit an index. 
 
* You have logged in to the Couchbase Server Web Console. 

== Procedure 

To set a type identifier for a Search index with the Couchbase Server Web Console: 

. Go to *Search*.
. Click the index where you want to set a type identifier.
. Click btn:[Edit]. 
. Do one of the following: 
.. <<json-type,>>
.. <<doc-id-sep,>>
.. <<doc-id-regex,>>

[#json-type]
=== Create a JSON Type Field Type Identifier 

To only add documents to your Search index that contain a specific field with a specified string value: 

. Select *JSON type field*. 
. In the *JSON Type Field* field, enter the name of the field in your documents that you want to use to filter documents in your Search index.
+
For example, if your documents include a `type` field, you could enter `type` in the *JSON Type Field* field. 
+
NOTE: You can't use a field as a type identifier if the field name contains a period (.).  
. Under *Type Mappings*, next to the type mapping where you want to add the type identifier, click btn:[Edit]. 
. In the *#* field, add a period (.) to the end of the current type mapping name. 
. After the period, add the exact string from the document field that you want to use as a filter. 
+
For example, if you wanted your Search index to only return documents that had a `type` value of `hotel`, you could enter `scope.collection.hotel` in the type mapping *#* field.
. Click btn:[OK].
. Click btn:[Update Index].

[#doc-id-sep]
=== Create a Doc ID Up To Separator Type Identifier 

To only add documents to your Search index that have IDs that match a specified prefix: 

. Select *Doc ID up to Separator*. 
. In the *Doc ID up to Separator* field, enter the ID prefix, up to the separator character, that you want to use to filter documents in your Search index.
+
For example, if you know all of your document ID values are prefixed by a string and an underscore, enter `_`.
. Under *Type Mappings*, next to the type mapping where you want to add the type identifier, click btn:[Edit]. 
. In the *#* field, add a period (.) to the end of the current type mapping name. 
. After the period, add the exact prefix from the document's ID value that you want to use as a filter. 
+
For example, if you wanted your Search index to only return documents that have an prefix of `landmark_`, you could enter `scope.collection.landmark` in the type mapping *#* field.
. Click btn:[OK].
. Click btn:[Update Index].

[#doc-id-regex]
=== Create a Doc ID with Regex Type Identifier 

To only add documents to your Search index that have IDs that match a specified https://github.com/google/re2/wiki/Syntax[RE2] regular expression: 

. Select *Doc ID with Regex*. 
. In the *Doc ID with Regex* field, enter the regular expression that you want to use to filter documents in your Search index. 
+
For example, if you wanted only documents with ID values that contained `_40`, you could enter `_[3-5]0` as your regular expression.
. Under *Type Mappings*, next to the type mapping where you want to add the type identifier, click btn:[Edit].
. In the *#* field, add a period (.) to the end of the current type mapping name. 
. After the period, add a match for the regular expression from the document's ID value that you want to use as a filter. 
+
For example, if you wanted your Search index to only return documents with ID values that contained `_40`, you could enter `scope.collection._40` in the type mapping *#* field.
. Click btn:[OK].
. Click btn:[Update Index].


== Next Steps

After you set the type identifier for your Search index, you can continue to customize your Search index: 

* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:set-advanced-settings.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].