= Set Global Search Index Settings 
:page-topic-type: guide 
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Configure global settings for your Search index with the Couchbase {page-ui-name} to change the default behavior for text analysis and date data interpretation.  

[abstract]
{description}
You can also set a xref:customize-index.adoc#type-identifiers[document filter] for your index.

== Prerequisites 

* You have the Search Service enabled on a node in your operational cluster.
For more information about how to change Services on your operational cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your operational cluster. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To set global settings for a Search index with the {page-ui-name}: 

. On the *Databases* page, select the operational cluster that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index you want to edit.
. Expand *Global Index Settings*. 
. Do any of the following: 
.. 
. Click btn:[Update Index].

== Next Steps

After you change the settings for your Search index, you can continue to customize your Search index: 

* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-wordlist.adoc[]
* xref:create-custom-date-time-parser.adoc[]

For more information about replica and partition settings, see xref:customize-index.adoc#replica[Replica and Partition Settings].

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[].