= Set a Search Index Type Identifier  
:page-topic-type: guide 
:description: Set a type identifier with the Couchbase Capella UI for a Search index to control how the Search Service sets a document's type.

[abstract]
{description}

For more information about type identifiers, see xref:customize-index.adoc#type-identifiers[Customize a Search Index with the Capella UI].

== Prerequisites 

* You've created an index.
For more information, see xref:create-search-index-ui.adoc[].
 
* You've logged in to the Couchbase Capella UI. 

== Procedure 

To set a type identifier for a Search index with the Capella UI:

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to change the type identifier.
. Expand *Advanced Configuration*. 
. Expand *General Settings*. 
. Do one of the following: 
.. To use the value of a field in the document as the document's type, select *JSON type field*.
.. To use the document's ID value, up to a given separator, as the document's type, select *Doc ID up to separator*. 
.. To use the document's ID value with a regular expression applied as the document's type, select *Doc ID with regex*.
. Enter the field name, separator, or regular expression in the corresponding field. 
. Click btn:[Update Index].

== Next Steps

After you set the type identifier for your Search index, you can continue to customize your Search index: 

* xref:set-advanced-settings.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-wordlist.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].