= Set Search Index Advanced Settings
:page-topic-type: guide 
:description: Configure advanced settings with the Couchbase Server Web Console for a Search index to improve an index's search results and performance. 

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have a bucket with scopes and collections in your database.
For more information about how to create a bucket, see xref:server:manage:manage-buckets/create-bucket.adoc[]. 

* You have created an index.
For more information, see xref:create-search-index-ui.adoc[].

* Your user account has the *Search Admin* role for the bucket where you want to edit an index. 
 
* You have logged in to the Couchbase Server Web Console. 

== Procedure 

To set advanced settings for a Search index with the Couchbase Server Web Console:  

. Go to *Search*.
. Click the index that you want to edit.
. Click btn:[Edit].
. Expand menu:Customize Index[Advanced]. 
. Configure any of the following advanced settings for your index: 
+
|====
|Option |Description 

|Default Type |Change the default type assigned to documents in the index.
The default value is `_default`.

|[[default-analyzer]]Default Analyzer a|

Change the default analyzer assigned to type mappings in the index. 

For more information about the available default analyzers, see xref:default-analyzers-reference.adoc[].

For more information about how to create your own custom analyzer, see xref:create-custom-analyzer.adoc[].

|[[date-time]]Default Date/Time Parser |Change the default date/time parser used for date data. 

|[[all-field]]Default Field a|

When you xref:create-child-field.adoc[create a mapping for a child field], you can choose to include that field in an `_all` field. 

You can add fields to the `_all` field to search their contents without specifying their field name in your search query. 

Enter a value in the *Default Field* field to change the name of this default field. 

|Store Dynamic Fields |Select *Store Dynamic Fields* to include field values in search results from a xref:customize-index.adoc#type-mappings[dynamic type mapping] in the index.

|Index Dynamic Fields |Select *Index Dynamic Fields* to include fields from a xref:customize-index.adoc#type-mappings[dynamic type mapping] in the index. 

|DocValues for Dynamic Fields |Select *DocValues for Dynamic Fields* to include the values of each field from a xref:customize-index.adoc#type-mappings[dynamic type mapping] in the index for xref:search-request-params.adoc#facets[Facets] and sorting search results.

|Index Replicas a|

Set the number of replicas that the Search Service creates for the index. 

For more information about replication and the Search Service, see xref:fts:fts-high-availability-for-search.adoc[].

|Index Type |This setting is included for compatibility only. For new indexes, this setting is always *Version 6.0 (Scorch)*.

|Index Partitions |Enter a number greater than one to divide the index into partitions across multiple nodes running the Search Service. 

|====
[start=7]
. Click btn:[Update Index].

== Next Steps

After you change the settings for your Search index, you can continue to customize your Search index: 

* xref:set-type-identifier.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-wordlist.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].