= Set a Search Index Type Identifier  
:page-topic-type: guide 
:description: Set an optional method for filtering documents to be included in a Search index:

[abstract]
{description}

For more information about type identifiers, see xref:customize-index.adoc#type-identifiers[Customize a Search Index with the Capella UI].

== Prerequisites 

* You've created an index.
For more information, see xref:create-search-index-ui.adoc[].
 
* You've logged in to the Couchbase Capella UI. 

== Procedure 

To set a Type Identifier to filter documents for a Search index with the Capella UI:

. On the *Databases* page, select the database that has the Search index you want to edit. 
. Go to menu:Data Tools[Search].
. Click the index where you want to change the type identifier.
. Expand menu:Advanced Configuration[General Settings]. 
. Do one of the following: 
.. To use  *JSON type field* to select only documents that contain a specific field with a particular string value
... Select *JSON type field*.
... In `JSON type field` text area enter the name of the field in the document you wish to filter on.
... Under *Type Mappings*, next to the type mapping you wish to filter, go to menu:More Options (&vellip;)[Edit]:
... add a period `.` and then the exact `string` (with no quotes) you wish to filter on to the end of the scope.collection.
.. To use *Doc ID up to separator* to select only documents with IDs that match a prefix up to seperator string.
... Select *Doc ID up to separator*.
... In `Doc ID up to separator` text area enter the string that the ID match will stop at.
... Under *Type Mappings*, next to the type mapping you wish to filter, go to menu:More Options (&vellip;)[Edit]:
... add a period `.` and then the `prefix` of the ID (with no quotes) you wish to filter on to the end of the scope.collection.
.. To use *Doc ID with regex* to select only documents with IDs that match a *https://github.com/google/re2/wiki/Syntax[RE2]* regular expression.
... Select *Doc ID with regex*.
... In `Doc ID with regex` text area enter the regular expresion to match the ID against.
... Under *Type Mappings*, next to the type mapping you wish to filter, go to menu:More Options (&vellip;)[Edit]:
... add a period `.` and then a `substring` of the ID (with no quotes) that the regex matches to filter on to the end of the scope.collection.
. Click btn:[Update Index].

NOTE: The Type Identifier document filtering is only active is you append a `.` and then a `substring` to the end of the scope.collection for all three of the above methods.

== Next Steps

After you set the type identifier for your Search index, you can continue to customize your Search index: 

* xref:set-advanced-settings.adoc[]
* xref:create-type-mapping.adoc[]
* xref:create-child-field.adoc[]
* xref:create-child-mapping.adoc[]
* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]
* xref:create-custom-wordlist.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[] or xref:simple-search-rest-api.adoc[].
