= Set a Document Filter
:page-topic-type: guide 
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use a document filter with a type mapping to add an extra filter to the documents you want to include in a Search index.
:page-toclevels: 3

[abstract]
{description}

For example, if you added a filter to your type mapping that checked if the value of a field was `true`, only documents with the value `true` for that field would be included in your Search index under that type mapping.
Based on your settings, xref:create-type-mapping.adoc#field[child fields] or xref:create-type-mapping.adoc#object[child mappings] that you define for documents that pass the filter on this type mapping will be returned in search results. 

You can filter based on the value of a field, or part of the value of your document IDs. 

As of Couchbase Server version 8.0, you can filter documents with custom filters based on the value of: 

* xref:search-index-params.adoc#boolean_filter[A boolean field].
* xref:search-index-params.adoc#date_range_filter[A date field, within a specific range].
* xref:search-index-params.adoc#numeric_range_filter[A numeric field, within a specific range].
* xref:search-index-params.adoc#term_filter[A term in a text field].
* A xref:search-index-params.adoc#conjunct_filter[conjunct] or xref:search-index-params.adoc#disjunct_filter[disjunct] object that combines 2 or more of the available filters.
You can add up to a maximum of 100 custom document filters on a single Search index.

For more information about document filters and type mappings, see xref:customize-index.adoc#type-identifiers[Search Index Features].

== Prerequisites 

* You have the Search Service enabled on a node in your operational cluster.
For more information about how to change Services on your operational cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your operational cluster. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have started to create or already created an index in xref:create-search-indexes.adoc#advanced-mode[Advanced Mode Editing].

* You have created at least 1 type mapping in your Search index.
For more information, see xref:create-type-mapping.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To set a document filter for a Search index with the {page-ui-name}:

. On the *Operational Clusters* page, select the operational cluster where you want to work with the Search Service. 
. Go to menu:Data Tools[Search].
. Do 1 of the following:
.. To work with an existing Search index, click the name of the index where you want to create a document filter.
.. To create a new Search index, click btn:[Create Search Index].
. Make sure to select *Enable Advanced Options*.
. Expand *Global Index Settings*. 
. Do 1 of the following:
.. <<json-type,>>
.. <<doc-id-sep,>>
.. <<doc-id-regex,>>
.. <<custom,>>

WARNING: You cannot use custom document filters with another type of type identifier on your Search index. 
If you select an option other than *Custom* after you have defined custom document filters, you'll lose any defined custom filters on your Search index.

[#json-type]
=== Create a JSON Type Field Document Filter 

To only add documents to your Search index that contain a specific field with a specified string value: 

. Under *Choose Document Filter*, click btn:[JSON Type Field] 
. In the *JSON Type Field* field, enter the name of the field in your documents that you want to use to filter documents in your Search index.
+
For example, if your documents include a `type` field, you could enter `type` in the *JSON Type Field* field. 
+
NOTE: You cannot use a field as a document filter if the field name contains a period (.).
. Under *Type Mappings*, next to the type mapping where you want to add the document filter, go to menu:More Options (&vellip;)[Edit].
. In the *Enter Document Filter* field, enter the exact string from the document field that you want to use as a filter.
+
For example, if you wanted your type mapping to only include documents that had a value of `hotel` in the `type` field, you could enter `hotel` in the filter field.
. Click btn:[Submit].
. Click btn:[Update Index].

[#doc-id-sep]
=== Create a Doc ID Up To Separator Document Filter 

To only add documents to your Search index that have IDs that match a specified prefix: 

. Under *Choose Document Filter*, click btn:[Doc ID up to Separator]. 
. In the *Doc ID up to Separator* field, enter the separator character from the ID prefix in your document ID values. 
+
For example, if you know all of your document ID values are prefixed by a string and an underscore (\_), enter `_`.
. Under *Type Mappings*, next to the type mapping where you want to add the document filter, go to menu:More Options (&vellip;)[Edit].
. In the *Enter Document Filter* field, enter the exact prefix from the document's ID value that you want to use as a filter. 
+
For example, if you wanted your type mapping to only include documents that have an prefix of `landmark_` in their ID values, you could enter `landmark` in the filter field.
. Click btn:[Submit].
. Click btn:[Update Index].

[#doc-id-regex]
=== Create a Doc ID with Regex Document Filter

To only add documents to your Search index that have IDs that match a specified https://github.com/google/re2/wiki/Syntax[RE2] regular expression: 

. Under *Choose Document Filter*, click btn:[Doc ID with Regex]. 
. In the *Doc ID with Regex* field, enter the regular expression that you want to use to filter documents in your Search index. 
+
For example, if you wanted documents with ID values that contained `\_40`, you could enter `_[3-5]0` as your regular expression.
. Under *Type Mappings*, next to the type mapping where you want to add the document filter, go to menu:More Options (&vellip;)[Edit].
. In the *Enter Document Filter* field, enter a match for the regular expression from the document's ID value that you want to use as a filter.
+
For example, if you wanted your type mapping to only include documents with ID values that contained `_40`, you could enter `_40` in the filter field.
. Click btn:[Submit].
. Click btn:[Update Index].

[#custom]
=== Create a Custom Document Filter

[.status]#Couchbase Server 8.0#

To create a new custom document filter on a Search index with the Couchbase {page-ui-name}:

. Under *Choose Document Filter*, click btn:[Custom].
. Click btn:[Add Document Filter].
. In the *Label* field, enter a name for your new document filter. 
. In the *Filter* code editor, enter a JSON object to define your document filter.
+
For more information about the properties for each document filter type, see: 
+
* xref:search-index-params.adoc#boolean_filter[Boolean Document Filters]
* xref:search-index-params.adoc#date_range_filter[Date Range Document Filters]
* xref:search-index-params.adoc#numeric_range_filter[Numeric Range Document Filters]
* xref:search-index-params.adoc#term_filter[Term Document Filters]
* xref:search-index-params.adoc#conjunct_filter[Conjunct Document Filters]
* xref:search-index-params.adoc#disjunct_filter[Disjunct Document Filters]

+
TIP: Do not add the name of your document filter to your filter definition when defining a custom document filter through the {page-ui-name}.
Define the document filter as an unnamed object with the specific properties you need for your document filter type.

+
. Click btn:[Save].
. Under *Type Mappings*, next to the type mapping where you want to add the document filter, go to menu:More Options (&vellip;)[Edit].
. In the *Select Document Filter* list, select the name of the custom document filter that you want to use to filter documents on this type mapping.
. Click btn:[Submit].
. Click btn:[Update Index].

== Next Steps

After you set the document filter for your Search index, you can continue to customize your Search index: 

* xref:create-custom-analyzer.adoc[]
* xref:create-custom-character-filter.adoc[]
* xref:create-custom-token-filter.adoc[]
* xref:create-custom-tokenizer.adoc[]

To run a search and test the contents of your Search index, see xref:simple-search-ui.adoc[].
