= Run A Simple Search with the Capella UI 
:page-topic-type: guide
:description: Run a Search query from the Couchbase Capella UI to preview the search results from a Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database. 

* Your user account has the `Search Admin` or `Search Reader` role. 

* You've created a Search index. 
+
For more information about how to create a Search index, see xref:create-search-indexes.adoc[].

* You've logged in to the Couchbase Capella UI. 

== Procedure 

To run a simple search with the Capella UI: 

. On the *Databases* page, select the database where you created your Search index. 
. Go to menu:Data Tools[Search]. 
. Next to your Search index, click the *More Options* (&vellip;) menu.
. Click btn:[Search].
. In the *Search* field, enter a search query. 
+
For example, the following query searches for the strings `view`, `food`, and `beach`:
+
[source,json]
----
include::example$run-search-payload-ui.jsonc[]
----

The query payload enables scoring explanations and term highlighting. It also returns all available fields in the index, and returns 10 results per page.