= Run A Simple Search with the Web Console 
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-aliases: fts:fts-searching-from-the-UI.adoc, fts:fts-multi-collection-behaviour.adoc
:description: Run a Search query from the Couchbase {page-ui-name} to preview the search results from a Search index.

[abstract]
{description}

For more information about how the Search Service scores documents in search results, see xref:run-searches.adoc#scoring[Scoring for Search Queries].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have a bucket with scopes and collections in your database.
For more information about how to create a bucket, see xref:server:manage:manage-buckets/create-bucket.adoc[]. 

* You have created a Search index. 
+
For more information about how to create a Search index, see xref:create-search-indexes.adoc[].

* Your user account has the *Search Admin* or *Search Reader* role. 

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To run a simple search with the Couchbase {page-ui-name}: 

. Go to *Search*.
. Click the index where you want to run a search.
. In the *Search this index* field, enter a search query. 
. Press kbd:[Enter] or click btn:[Search].
. (Optional) To view the full contents of a document returned in the search results, click one of the results. 
. (Optional) To view the results of document scoring in search results, click *Show Scoring*.

=== Example

For example, the following query searches for the strings `view`, `food`, and `beach`:

[source,json]
----
include::example$run-search-payload-ui.jsonc[]
----

The query payload enables scoring explanations and term highlighting. 
It also returns all available fields in the index, and returns 10 results per page.

TIP: Use a xref:index-aliases.adoc[Search index alias] to search multiple Search indexes in a single search query. 
Use the xref:search-request-params.adoc#collections[`collections` parameter] in your request to specify an array of collections to search from the Search index.

== Next Steps 

If you do not get the search results you were expecting, you can change the xref:search-request-params.adoc[JSON payload for your Search query].

You can also xref:customize-index.adoc[]. 