= Run A Simple Search with the {page-ui-name} 
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Run a Search query from the Couchbase {page-ui-name} to preview the search results from a Search index.

[abstract]
{description}

For more information about how the Search Service scores documents in search results, see xref:run-searches.adoc#scoring[Scoring for Search Queries].

== Prerequisites 

* You have the Search Service enabled on a node in your operational cluster.
For more information about how to change Services on your operational cluster, see xref:cloud:clusters:modify-database.adoc[]. 

* You have created a Search index. 
+
For more information about how to create a Search index, see xref:create-search-indexes.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To run a simple search with the {page-ui-name}: 

. On the *Operational Clusters* page, select the operational cluster where you created your Search index. 
. Go to menu:Data Tools[Search]. 
. Next to your Search index or xref:index-aliases.adoc[index alias], click btn:[Search].
. In the *Search* field, enter a search query. 
. Press kbd:[Enter].
. (Optional) To view a document and its source collection, click a document name in the search results list. 

=== Example: Simple Text Search

For example, the following query searches for the strings `view`, `food`, and `beach`:

[source,json]
----
include::example$run-search-payload-ui.jsonc[]
----

The query payload enables scoring explanations and term highlighting. 
It also returns all available fields in the index, and returns 10 results per page.

TIP: Use the xref:search-request-params.adoc#collections[`collections` parameter] in your request to specify an array of collections to search from the Search index. 

=== Example: Validate a Search Query

[.status]#Couchbase Server 7.6.5#

For example, the following query searches a Search index, `landmark-content-index`, using a xref:search-request-params.adoc#geopoint-queries-distance[Distance/Radius-Based Geopoint Query] on the `geo` field.
The query includes the xref:search-request-params.adoc#ctl[ctl object] with the `validate` property to validate the query:

[source,json]
----
include::example$run-search-validate-ui.jsonc[]
----

Since the `landmark-content-index` does not include a mapping for the `geo` field and the `validate` property is included in the query, the Web Console returns the following error: 

----
query_validate: field not indexed, name: geo, type: geopoint
----

== Next Steps 

If you do not get the search results you were expecting, you can change the xref:search-request-params.adoc[JSON payload for your Search query].

You can also xref:customize-index.adoc[]. 