= Run A Simple Search with the Web Console 
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-aliases: fts:fts-searching-from-the-UI.adoc, fts:fts-multi-collection-behaviour.adoc
:description: Run a Search query from the Couchbase {page-ui-name} to preview the search results from a Search index.

[abstract]
{description}

For more information about how the Search Service scores documents in search results, see xref:run-searches.adoc#scoring[Scoring for Search Queries].

== Prerequisites 

* You have the Search Service enabled on a node in your cluster.
For more information about how to deploy a new node and Services on your cluster, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have a bucket with scopes and collections in your cluster.
For more information about how to create a bucket, see xref:server:manage:manage-buckets/create-bucket.adoc[]. 

* You have created a Search index. 
+
For more information about how to create a Search index, see xref:create-search-indexes.adoc[].

* Your user account has the xref:learn:security/roles.adoc#search-admin[`Search Admin`] or xref:learn:security/roles.adoc#search-reader[`Search Reader`] role for the bucket or buckets that contain the Search indexes you want to search.

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To run a simple search with the Couchbase {page-ui-name}: 

. Go to *Search*.
. Click the index where you want to run a search.
. In the *Search this index* field, enter a search query. 
. Press kbd:[Enter] or click btn:[Search].
. (Optional) To view the full contents of a document returned in the search results, click one of the results. 
. (Optional) To view the results of document scoring in search results, click *Show Scoring*.
. (Couchbase Server version 7.6.2 and later) To directly edit the xref:search-request-params.adoc[Search request JSON payload] for your Search query and run a new search:
.. Click *show advanced query settings*. 
.. Click btn:[Edit]. 
.. Edit the JSON payload. 
For more information about the available parameters, see xref:search-request-params.adoc[].
.. Click btn:[Execute].

=== Example: Simple Text Search

For example, the following query searches for the strings `view`, `food`, and `beach`:

[source,json]
----
include::example$run-search-payload-ui.jsonc[]
----

The query payload enables scoring explanations and term highlighting. 
It also returns all available fields in the index, and returns 10 results per page.

TIP: Use a xref:index-aliases.adoc[Search index alias] to search multiple Search indexes in a single search query. 
Use the xref:search-request-params.adoc#collections[`collections` parameter] in your request to specify an array of collections to search from the Search index.

=== Example: Validate a Search Query

[.status]#Couchbase Server 7.6.4#

For example, the following query searches a Search index, `landmark-content-index`, using a xref:search-request-params.adoc#geopoint-queries-distance[Distance/Radius-Based Geopoint Query] on the `geo` field.
The query includes the xref:search-request-params.adoc#ctl[ctl object] with the `validate` property to validate the query:

[source,json]
----
include::example$run-search-validate-ui.jsonc[]
----

Since the `landmark-content-index` does not include a mapping for the `geo` field and the `validate` property is included in the query, the Web Console returns the following error: 

----
query_validate: field not indexed, name: geo, type: geopoint
----

[#nested]
=== Example: Query an Array of Objects

//[.status]#Couchbase Server 8.1#

From the next major release of Couchbase Server, you can now configure a Search index to avoid flattening xref:create-nested-object.adoc[arrays of objects] in your documents. 

If your Search index definition contains a `nested` object and you choose to return that object in your search results, the {page-ui-name} marks the nested objects on the results page.

For example, if you wanted to query the Search index definition from xref:create-search-index-rest-api.adoc#nested[Example: Search Index with a Nested Array of Objects Mapping], you could run the following query to find hotels where the reviews contain the words `location` and `nice view` and the `Overall` rating is `4` or `5`:

[source,json]
----
include::example$nested/run-search-payload-nested-ui.json[]
----

Since the query requested the contents of all available fields in the Search index, the Search Service returns the original field content of any fields or objects added and stored in the Search index.
Specifically, the Search Service marks the contents of the `reviews` object as *Nested Documents* in your search results.

== Next Steps 

If you do not get the search results you were expecting, you can change the xref:search-request-params.adoc[JSON payload for your Search query].
If your cluster is running Couchbase Server version 7.6.2 and later, you can edit the JSON payload directly in the UI by clicking *show advanced query settings*. 

Run any changes to your JSON payload by clicking btn:[Execute].

You can also xref:customize-index.adoc[]. 
