= Run A Simple Search with the {page-ui-name} 
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Run a Search query from the Couchbase {page-ui-name} to preview the search results from a Search index.

[abstract]
{description}

For more information about how the Search Service scores documents in search results, see xref:run-searches.adoc#scoring[Scoring for Search Queries].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[]. 

* You have created a Search index. 
+
For more information about how to create a Search index, see xref:create-search-indexes.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To run a simple search with the {page-ui-name}: 

. On the *Databases* page, select the database where you created your Search index. 
. Go to menu:Data Tools[Search]. 
. Next to your Search index, click btn:[Search].
. In the *Search* field, enter a search query. 
. Press kbd:[Enter].
. (Optional) To view a document and its source collection, click a document name in the search results list. 

=== Example

For example, the following query searches for the strings `view`, `food`, and `beach`:

[source,json]
----
include::example$run-search-payload-ui.jsonc[]
----

The query payload enables scoring explanations and term highlighting. 
It also returns all available fields in the index, and returns 10 results per page.

TIP: Use the xref:search-request-params.adoc#collections[`collections` parameter] in your request to specify an array of collections to search from the Search index. 

== Next Steps 

If you do not get the search results you were expecting, you can change the xref:search-request-params.adoc[JSON payload for your Search query].

You can also xref:customize-index.adoc[]. 