= Run A Simple Search with the Web Console 
:page-topic-type: guide
:description: Run a Search query from the Couchbase Server Web Console to preview the search results from a Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database. 

* Your user account has the *Search Admin* or *Search Reader* role. 

* You have created a Search index. 
+
For more information about how to create a Search index, see xref:create-search-indexes.adoc[].

* You have logged in to the Couchbase Server Web Console. 

== Procedure 

To run a simple search with the Couchbase Server Web Console: 

. Go to *Search*.
. Click the index or xref:index-alises.adoc[index alias] where you want to run a search.
. In the *Search this index* field, enter a search query. 
+
For example, the following query searches for the strings `view`, `food`, and `beach`:
+
[source,json]
----
include::example$run-search-payload-ui.jsonc[]
----
+
The query payload enables scoring explanations and term highlighting. It also returns all available fields in the index, and returns 10 results per page.
+
TIP: Use a xref:index-aliases.adoc[Search index alias] to search multiple Search indexes in a single search query. 
Use the xref:search-request-params.adoc#collections[`collections` parameter] in your request to specify an array of collections to search from the Search index. 

. Press kbd:[Enter] or click btn:[Search].
. (Optional) To view the contents of a document, click the document name in the search results list. 

== Next Steps 

If you do not get the search results you were expecting, you can change the xref:search-request-params.adoc[JSON payload for your Search query].

You can also xref:customize-index.adoc[]. 