= Run a Simple Search with the REST API and curl/HTTP 
:page-topic-type: guide 
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: You can use the REST API and a curl command to run a search against a Search index.

[abstract]
{description}

For more information about how the Search Service scores documents in search results, see xref:run-searches.adoc#scoring[Scoring for Search Queries].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* Your user account has the *Search Admin* or *Search Reader* role. 

* You installed the Couchbase command-line tool (CLI).

* You have the hostname or IP address for the node in your database where you're running the Search Service.
For more information about where to find the IP address for your node, see xref:server:manage:manage-nodes/list-cluster-nodes.adoc[].

* You have created a Search index. 
+
For more information about how to create a Search index, see xref:create-search-index-ui.adoc[] or xref:create-search-index-rest-api.adoc[].

== Procedure 

To run a simple search with the REST API: 

. In your command-line tool, enter a `curl` command with the `XPOST` verb. 
. Set your header content to include `"Content-Type: application/json"`.
. Enter your username, password, and the Search Service endpoint on port `8094` with the name of the index you want to query: 
+
[source,console]
----
include::example$run-search-header.sh[]
----
+
To use SSL, use the `https` protocol in the Search Service endpoint URL and port `18094`. 
. Enter the JSON payload for your query. 
+
TIP: You can copy the JSON for a Query Request from the Couchbase {page-ui-name} to use in your REST API call.
For more information about how to perform a search with the UI, see xref:simple-search-ui.adoc[].

=== Example

In the following example, the JSON payload queries an index named `landmark-content-index` for the strings `view`, `food`, and `beach`:

[source,console]
----
include::example$run-search-payload.sh[]
----

For more information about the available properties for a Search query JSON payload, see xref:search-request-params.adoc[].

== Next Steps 

If you do not get the search results you were expecting, you can change the JSON payload xref:search-index-params.adoc[for your Search index] or xref:search-request-params.adoc[for your Search query].

You can also xref:customize-index.adoc[].