= Run A Simple Search with the Web Console 
:page-topic-type: guide
:description: Run a Search query from the Couchbase Server Web Console to preview the search results from a Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database. 

* Your user account has the `Search Admin` or `Search Reader` role. 

* You've created a Search index. 
+
For more information about how to create a Search index, see xref:create-search-indexes.adoc[].

* You've logged in to the Couchbase Server Web Console. 

== Procedure 

To run a simple search with the Web Console: 

. Go to *Search*.
. Click the index where you want to run a search.
. In the *Search this index* field, enter a search query. 
+
For example, the following query searches for the strings `view`, `food`, and `beach`:
+
[source,json]
----
include::example$run-search-payload-ui.jsonc[]
----

The query payload enables scoring explanations and term highlighting. It also returns all available fields in the index, and returns 10 results per page.