= Run a Simple Search with the REST API and curl/HTTP 
:page-topic-type: guide 
:description: You can use the REST API and a curl command to run a search against a Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database. 

* Your user account has the `Search Admin` or `Search Reader` role. 

* You installed the Couchbase command-line tool (CLI).

* You have the hostname or IP address for your database. 

* You've created a Search index. 
+
For more information about how to create a Search index, see xref:create-search-index-ui.adoc[] or xref:create-search-index-rest-api.adoc[].

== Procedure 

To run a search with the REST API: 

. In your command-line tool, enter a `curl` command with the `XPOST` verb. 
. Set your header content to include `Content-Type: application/json`.
. Enter your username, password, and the Search Service endpoint on port `8094` with the name of the index you want to query: 
+
[source,console]
----
include::example$run-search-header.sh[]
----
. Enter the JSON payload for your query. 
+
TIP: You can copy the JSON for Query Request from the Couchbase Server or Couchbase Capella UI to use in your REST API call.
For more information about how to perform a search with the UI, see xref:simple-search-ui.adoc[].

+
In the following example, the JSON payload queries an index named `landmark-content-index` on the `travel-sample` bucket for the strings `view`, `food`, and `beach`:
+
[source,console]
----
include::example$run-search-payload.sh[]
----
+
For more information about the available properties for a Search query JSON payload, see xref:search-request-params.adoc[].

== Next Steps 

If you don't get the search results you were expecting, you can change the xref:search-request-params.adoc[JSON payload for your Search query].

You can also xref:customize-index.adoc[] or modify the xref:search-index-params.adoc[JSON payload for your Search index]. 