= Collection, Object, XATTRs, and Field Mapping Options 
:page-topic-type: reference
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-aliases: quick-index-field-options.adoc
:description: When you create a Search index in the {page-ui-name}, you must set options for each collection, object, Extended Attributes (XATTRs) object, or field mapping you add to your index. 

[abstract]
{description}

You can create the following types of mappings in the {page-ui-name}: 

* <<collection,>>
* <<object,>>
* <<xattrs,>>
* <<field,>>

TIP: Indexing an entire collection creates a dynamic type mapping for that collection. 
Indexing a field creates a static type mapping for the parent collection.
For more information about static and dynamic type mappings, see xref:customize-index.adoc#type-mappings[Search Index Features].

For more information about how to create a Search index, see xref:create-search-index-ui.adoc[]. 

[#collection]
== Collection Type Mapping Options 

Configure an entire collection type mapping to add or remove all documents in that collection from your Search index.

You can add <<object,JSON object mappings>>, an <<xattrs,Extended Attributes (XATTRs) mapping>>, or <<field,field type mappings>> for objects and fields inside your collection to change your collection type mapping from a xref:customize-index.adoc#dynamic[dynamic mapping] to a xref:customize-index.adoc#static[static mapping].

You can configure the following settings for a type mapping that uses an entire collection: 

|====
|Option |Formerly Known As |Description 

| Index everything from collection: "`$COLLECTION_NAME`" 
a| In Quick Mode: Index everything from collection: "`$COLLECTION_NAME`" 

In Advanced Mode: Leaving *Only index specified fields* unchecked
a| You must select *Index everything from collection* to add a collection type mapping. 

The Search Service adds all documents inside the selected collection to your Search index.

| Use keyword analyzer for text 
a| In Quick Mode: *Index text fields as identifiers*

In Advanced Mode: Not available
a| To index any *Text* type fields inside this collection with the xref:default-analyzers-reference.adoc#keyword[keyword analyzer], select *Use keyword analyzer for text*. 

To use other analyzers on text fields, clear *Use keyword analyzer for text*. 

For more information about analyzers, see xref:customize-index.adoc#analyzers[Search Index Features].

|Analyzer/Language 
a| In Quick Mode: *Analyzer/Language*

In Advanced Mode: *Default Analyzer*
a| If you do not select *Use keyword analyzer for text*, use the *Analyzer/Language* list to select an analyzer to use or the language of any content inside *Text* fields in the collection. 

For more information about the available language and analyzer options, see xref:default-analyzers-reference.adoc[].

|====

[#object]
== Object Mapping Options 

Configure a JSON object mapping to add or remove a JSON object from your Search index.
This JSON object does not currently have to exist in your document schema. 

You can add <<field,a field type mapping>> for any fields under a JSON object to change your JSON object mapping from a xref:customize-index.adoc#dynamic[dynamic mapping] to a xref:customize-index.adoc#static[static mapping].

You can configure the following options for a JSON object mapping: 

|====
|Option |Formerly Known As |Description

| Index everything under: "`$OBJECT_NAME`" 
a| Not available.
a| Select *Index everything under* to create a xref:customize-index.adoc#dynamic[dynamic] object mapping in your Search index. 

The Search Service adds all document fields inside the object to your Search index.

| Use keyword analyzer for text 
a| Not available.
a| To index any *Text* type fields inside this object with the xref:default-analyzers-reference.adoc#keyword[keyword analyzer], select *Use keyword analyzer for text*. 

To use other analyzers on text fields, clear *Use keyword analyzer for text*. 

For more information about analyzers, see xref:customize-index.adoc#analyzers[Search Index Features].

|Analyzer/Language 
a| In Quick Mode: *Analyzer/Language*

In Advanced Mode: *Default Analyzer*
a| If you do not select *Use keyword analyzer for text*, use the *Analyzer/Language* list to select the analyzer or language for the content inside any *Text* fields. 

For more information about the available language and analyzer options, see xref:default-analyzers-reference.adoc[].

|====

[#xattrs]
== XATTRs Mapping Options 

Configure an Extended Attributes (XATTRs) mapping to add or remove document metadata from your Search index.
The XATTRs object does not have to currently exist in your document schema.

You can add <<field,a field type mapping>> for any fields under an XATTRs mapping to change your mapping from a xref:customize-index.adoc#dynamic[dynamic mapping] to a xref:customize-index.adoc#static[static mapping].

You can only configure 1 XATTRs mapping for each collection in your Search index.

You can configure the following options for an XATTRs mapping: 

|====
|Option |Formerly Known As |Description 

| Index everything under: "`$xattrs`" 
a| In Quick Mode: Not available 

In Advanced Mode: Leaving *Only index specified fields* unchecked
a| Select *Index everything under: "$xattrs"* to create a xref:customize-index.adoc#dynamic[dynamic] XATTRs mapping in your Search index. 

The Search Service adds all metadata fields inside the XATTRs object to your Search index.

| Use keyword analyzer for text (Text Fields Only) 
a| In Quick Mode: Not available 

In Advanced Mode: Not available
a| To index this field with the xref:default-analyzers-reference.adoc#keyword[keyword analyzer], select *Use keyword analyzer for text*. 

To use other analyzers on this text field, clear *Use keyword analyzer for text*. 

For more information about analyzers, see xref:customize-index.adoc#analyzers.adoc[Search Index Features].

// |Include in search results 
// |
// a|To include content from the field in search results, select *Include in search results*. 

// To exclude the field's content from search results, clear *Include in search results*. 

// |Support field agnostic search 
// |
// a|To search the field's contents without specifying the field name in a search query, select *Support field agnostic search*. 

// To turn off field agnostic search, clear *Support field agnostic search*. 

// |Support sorting and faceting 
// |
// a|To sort search results and use xref:search-request-params.adoc#facets[facets] with the field's contents, select *Support sorting and faceting*. 

// To turn off sorting and facets, clear *Support sorting and faceting*.

// |Analyzer/Language (Text Fields Only) 
// | 
// a|If you do not select *Use keyword analyzer for text*, use the *Analyzer/Language* list to select the analyzer or language for the content inside any *Text* fields. 

// For more information about the available language and analyzer options, see xref:default-analyzers-reference.adoc[].

|====

[#field]
== Field Type Mapping Options 

Configure a single field type mapping to add or remove that field from your Search index.

You can configure the following settings for a type mapping that uses a single field: 

[cols="1,1,2"]
|====
|Option |Formerly Known As |Description 

| Type 
| In Quick Mode and Advanced Mode: *Type*
a| Set the data type of the contents of the field. 

The *Type* you choose changes the settings you have available for that field. 

For more information about the available field data types, see xref:field-data-types-reference.adoc[].

|Searchable As 
| In Quick Mode and Advanced Mode: *Searchable As*
a| Set a different name that you can use to search the field's contents in a query. 

The default value is the field's name.

| Use keyword analyzer for text (Text Fields Only) 
a| In Quick Mode: *Index this field as an identifier*

In Advanced Mode: Not available
a|To index this field with the xref:default-analyzers-reference.adoc#keyword[keyword analyzer], select *Use keyword analyzer for text*. 

To use other analyzers on this text field, clear *Use keyword analyzer for text*. 

For more information about analyzers, see xref:customize-index.adoc#analyzers.adoc[Search Index Features].

|Analyzer/Language (Text Fields Only) 
a| In Quick Mode: *Analyzer/Language*

In Advanced Mode: *Default Analyzer*
a| If you do not select *Use keyword analyzer for text*, use the *Analyzer/Language* list to select the analyzer or language for the content inside any *Text* fields. 

For more information about the available language and analyzer options, see xref:default-analyzers-reference.adoc[].

|[[dimension]]Dimension (Vector Fields Only) 
| In Quick Mode and Advanced Mode: *Dimension*
a| include::partial$vector-search-field-descriptions.adoc[tag=dimension]

|Similarity Metric (Vector Fields Only) 
| In Quick Mode and Advanced Mode: *Similarity Metric*
a| include::partial$vector-search-field-descriptions.adoc[tag=similarity_metric]

|Optimized For (Vector Fields Only) 
| In Quick Mode and Advanced Mode: *Optimized For*
a| include::partial$vector-search-field-descriptions.adoc[tag=optimized_for]

|Include in search results 
a| In Quick Mode: *Include in search results*

In Advanced Mode: *Store*
a| To include content from the field in search results, select *Include in search results*. 

To exclude the field's content from search results, clear *Include in search results*. 

// |Support highlighting 
// a| In Quick Mode: *Support highlighting*

// In Advanced Mode: *Include Term Vectors* and *Store*
// a| The Search Service can highlight matching search terms in search results from an index. 

// To enable highlighting in search results, select *Support highlighting*. 

// To turn off highlighting in search results, clear *Support highlighting*. 

// NOTE: To enable *Support highlighting*, you must also enable *Include in search results*.

|Support phrase matching 
a| In Quick Mode: *Support phrase matching*

In Advanced Mode: *Include Term Vectors*
a| To support searches for whole phrases, select *Support phrase matching*. 

To turn off phrase matching, clear *Support phrase matching*.

NOTE: To enable *Support phrase matching*, you must also enable *Include in search results*.

|Support field agnostic search 
a| In Quick Mode: *Support field agnostic search*

In Advanced Mode: *Include in _all field*
a|To search the field's contents without specifying the field name in a search query, select *Support field agnostic search*. 

To turn off field agnostic search, clear *Support field agnostic search*. 

|Support sorting and faceting 
a| In Quick Mode: *Support sorting and faceting*

In Advanced Mode: *Doc Values*
a| To support sorting search results based on this field and use xref:search-request-params.adoc#facets[facets] with the field's contents, select *Support sorting and faceting*. 

To turn off sorting and facets, clear *Support sorting and faceting*. 

|====