= Implement the Data Model
:description: Learn how to logically partition your data in Capella Operational using buckets, scopes, and collections.
:imagesdir: ../images
:page-pagination: full
:page-topic-type: tutorial

include::partial$tutorial-globals.adoc[]

[abstract]
{description}

== Buckets, Scopes, and Collections

To organize and manage your data in Couchbase, you can create buckets, scopes, and collections inside your cluster.

A bucket is equivalent to a database in a relational database management system, while scopes and collections are used to provide separation between documents of different types.
A bucket can hold any number of scopes, and a scope can hold any number of collections.

[plantuml,couchbase-hierarchy,svg]
....
include::partial$diagrams/couchbase-hierarchy.puml[]
....

[horizontal]
bucket:: Stores and retrieves data in the server.              
scope:: Stores collections. When you create a new bucket, Couchbase provides you with a default scope called `_default`.
collection:: Contains a set of documents. Couchbase provides you with a default collection called `_default`.

For more information, see xref:cloud:clusters:data-service/about-buckets-scopes-collections.adoc[Buckets, Scopes, and Collections].

== Create a Bucket, Scope, and Collection

To continue this tutorial, you must create a bucket to hold all student data, a scope to narrow down the data into only data related to an art school, and two collections to narrow it down further into art school students and art school courses.

Steps: 

. On the *Operational* tab, select *student-cluster*.

. Select the *Data Tools* tab.

. From the left pane, click btn:[+ Create].

. Under Bucket, select *New* and enter the name as *student-bucket*. 
Accept the default 100 MiB as the memory quota. 

. Under Scope, enter the name as *art-school-scope*.

. Under Collection, enter the name as *student-record-collection* for your first collection. 

. Click btn:[Create].

To create the second collection, follow the above steps but use the existing *student-bucket* and *art-school-scope*, and then create a collection with the name *course-record-collection*.

