= Install Couchbase Server
:description: Install and set up Couchbase Server to continue following the Student Record System tutorial.
:page-topic-type: tutorial
:imagesdir: ../images
:page-pagination: full
:page-toclevels: 2

:sdk-footnote: footnote:[Software Development Kit]

include::partial$tutorial-globals.adoc[]

[abstract]
{description}

== Installation

You can install and run Couchbase Server as a standalone application or as a Docker instance.

=== Standalone

To download Couchbase Server as a standalone application:

. Go to the https://www.couchbase.com/downloads/[Couchbase download page].
. Go to menu:Server[Couchbase Server Community].
. Select a **Version** and an **OS** and click btn:[Download].

After Couchbase Server is finished downloading, follow the instructions to install it on your machine.

=== Docker

To download Couchbase Server as a Docker instance:

. Download https://docs.docker.com/get-docker/[Docker^].
. Open a terminal window and run this command to provision the server image, set up the storage location, and run the server:
+
[source, sh]
----
docker run -t --name db -p 8091-8096:8091-8096 -p 11210-11211:11210-11211 \
couchbase/server:community-{current-community-version}
----


== Set Up a Cluster

Couchbase Server can run as its own cluster or join another cluster to form a multi-node system.
For this tutorial, your server runs as a single node.

To set up a cluster:

. Make sure your Couchbase Server is running.
. In your browser, go to `pass:[http://127.0.0.1:8091]` to access your server's configuration page.
. Click btn:[Setup New Cluster].
. For your cluster name, enter **student-cluster**.
. For your username, enter **username**.
. For your password, enter **password**.
. Click btn:[Next: Accept Terms].
. Accept the terms and conditions and click btn:[Finish With Defaults] to access the **Dashboard** page.


== Next Steps

After installing Couchbase Server and setting up a cluster, you can xref:buckets-scopes-and-collections.adoc[implement a data model].
