= Install Couchbase Server
:description: Install and set up Couchbase Server to continue following the Student Record System tutorial.
:page-topic-type: tutorial
:imagesdir: ../images
:page-pagination: full
:page-toclevels: 2
:page-aliases: install-couchbase-server.adoc

:sdk-footnote: footnote:[Software Development Kit]

[abstract]
{description}

== Installation

You can install and run Couchbase Server as a standalone application or as a Docker instance.

=== Standalone

To download Couchbase Server as a standalone application:

. Go to the https://www.couchbase.com/downloads/[Couchbase download page].
. Go to menu:Server[Couchbase Server Community].
. Select a **Version** and an **OS** and click btn:[Download].

After Couchbase Server is finished downloading, follow the instructions to install it on your machine.

=== Docker

To download Couchbase Server as a Docker instance:

. Download https://www.docker.com/get-started/[Docker^].
. Open a terminal window and run this command to provision the server image, set up the storage location, and run the server:
+
[source, sh]
----
docker run -t --name db -p 8091-8096:8091-8096 -p 11210-11211:11210-11211 \
couchbase/server:enterprise-{current-enterprise-version}
----


== Set Up a Cluster

Couchbase Server can run as its own cluster or join another cluster to form a multi-node system.
For this tutorial, your server runs as a single node.

To set up a cluster:

. Go to your server's configuration page.
You can access this page in any of the following ways:
* Opening your local Couchbase Server app.
* Running a Docker instance in the terminal.
* Going directly to `pass:[http://127.0.0.1:8091]` in your browser.
. Click btn:[Setup New Cluster].
. For your cluster name, enter **student-cluster**.
. Set a username and password.
. Click btn:[Next: Accept Terms].
. Accept the terms and conditions and click btn:[Finish With Defaults] to access the **Dashboard** page.


== Next Steps

After installing Couchbase Server and setting up a cluster, you can xref:tutorial-create-database.adoc[create a cluster].