= Understand Queries
:page-role: tiles -toc
:page-aliases: n1ql:tutorial.adoc
:!sectids:

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

include::ROOT:partial$component-signpost.adoc[]

== Query Concepts

An overview of common concepts that you will need to understand in order to use the Query service.

* xref:n1ql:n1ql-intro/queriesandresults.adoc[]

== Query Tools

The Query service provides the following tools for running queries:

* xref:n1ql:n1ql-intro/cbq.adoc[]
* xref:clusters:query-service/query-workbench.adoc[]

== Related Links

The interactive {sqlpp} tutorial provides web modules where you can learn about {sqlpp} without having to configure Couchbase Capella or have Couchbase Server installed in your own environment.
The modules are self-contained and let you modify and run sample queries.

* https://query-tutorial.couchbase.com/tutorial/#1[{sqlpp} Query Language Tutorial^]

ifdef::flag-devex-cheatsheet[]

== {sqlpp} Cheat Sheet

The {sqlpp} cheat sheet provides a concise summary of the basic syntax elements of {sqlpp}.

* http://docs.couchbase.com/files/Couchbase-N1QL-CheatSheet.pdf[{sqlpp} Cheat Sheet^]

endif::flag-devex-cheatsheet[]
