= Running Queries
:page-role: tiles -toc
:!sectids:

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

== Queries and Results

An overview of common concepts that you will need to understand in order to use the Query service.

* xref:n1ql:n1ql-intro/queriesandresults.adoc[]

== Getting System Information

{sqlpp} has a system catalog that stores metadata about a database.
The system catalog is a namespace called system.

* xref:n1ql:n1ql-intro/sysinfo.adoc[]

== {sqlpp} Error Codes

All of the {sqlpp} error codes, their error messages, and some tips to resolve them.

* xref:n1ql:n1ql-language-reference/n1ql-error-codes.adoc[]

== Related Links

The Query services provides the following tools for running queries:

ifdef::flag-devex-command-line[]
* xref:server:tools:cbq-shell.adoc[]
endif::flag-devex-command-line[]
* xref:clusters:query-service/query-workbench.adoc[]
