= Monitor Query Operations
:page-topic-type: concept
:description: System keyspaces provide various monitoring details and statistics about individual queries and the Query service.
:page-topic-type: task
:keywords: n1ql, sqlpp, query, result, parameter, prepared, prepared statement, consistent, consistency, monitor, keyspace

[abstract]
{description}

You can monitor and profile SQL++ queries, Query service engines, and corresponding system resources for smoother operational performance and efficiency of the system. 

There is a system keyspace for each part of the system catalog. The names are plural to avoid conflicting with SQL++ keywords.

[%header,cols="30%,70%"]
|===
| System Keyspace | Description 

| Datastores
| Datastores are similar to sites. A datastore is a database deployment, for example, a server cluster, cloud service, or mobile installation. It is analogous to a relation database instance. For information on how to query this keyspace, see <<querying-datastores,Query Datastores>>.

| Namespaces
| Namespaces are similar to pools. A namespace is a unit of authorization, resource allocation, and tenancy. It is analogous to a relational database or schema. Currently, only the `default` and `system` namespaces are available. For information on how to query this keyspace, see <<query-namspaces,Query Namespaces>>.
 

| Buckets
| A bucket is the fundamental space for storing data in Couchbase Capella. Each bucket contains at least one scope by default, and you can create more scopes as required. It is analogous to a relational database table space or file group. For information on how to query this keyspace, see <<query-buckets,Query Buckets>>.

| Scopes
| A scope is a set of one or more collections. Each scope contains at least one collection by default, and you can create more collections as required. It is analogous to a group of relational database tables. For information on how to query this keyspace, see <<query-scopes,Query Scopes>>.

| Collections
| A collection is a set of documents that may vary in structure. It is a unit of authorization and resource allocation. It is analogous to a relational database table. For information on how to query this keyspace, see <<query-collections,Query Collections>>.

| Indexes
| An index on a keyspace. It is analogous to a relational database index. Types of indexes include b-tree (ForestDB or MOI) and view indexes.For information on how to query this keyspace, see <<query-indexes,Query Indexes>>.

| Dual
| The dual keyspace has been added for evaluating constant expressions. It contains a single entry with no attributes. For information on how to query this keyspace, see <<query-dual,Query Dual>>.

|===



[#querying-datastores]
== Query Datastores

You can query datastores using the `system:datastores` keyspace as follows:

[source,sqlpp]
----
SELECT * FROM system:datastores
----

The query returns the following attributes:

[horizontal]
`id`:: (string) ID of the datastore
`url`:: (string) URL of the datastore instance

[#querying-namespaces]
== Query Namespaces

You can query namespaces using the `system:namespaces` keyspace as follows:

[source,sqlpp]
----
SELECT * FROM system:namespaces
----

The query returns the following attributes:

[horizontal]
`id`:: (string) ID of the namespace
`name`:: (string) Name of the namespace
`datastore_id`:: (string) ID of the datastore to which the namespace belongs

[#querying-buckets]
== Query Buckets

You can query buckets using the `system:buckets` keyspace as follows:

[source,sqlpp]
----
SELECT * FROM system:buckets
----

The query returns the following attributes:

[horizontal]
`datastore_id`:: (string) ID of the datastore to which the bucket belongs
`name`:: (string) Name of the bucket
`namespace`:: (string) Namespace to which the bucket belongs
`namespace_id`:: (string) ID of the namespace to which the bucket belongs
`path`:: (string) Path of the bucket

[#querying-scopes]
== Query Scopes

You can query scopes using the `system:scopes` keyspace as follows:

[source,sqlpp]
----
SELECT * FROM system:scopes
----

The query returns the following attributes:

[horizontal]
`bucket`:: (string) Bucket to which the scope belongs
`datastore_id`:: (string) ID of the datastore to which the scope belongs
`name`:: (string) Name of the scope
`namespace`:: (string) Namespace to which the scope belongs
`namespace_id`:: (string) ID of the namespace to which the scope belongs
`path`:: (string) Path of the scope

NOTE: Querying `system:scopes` only returns named scopes -- that is, non-default scopes.
To return all scopes, including the default scopes, you can query `system:all_scopes`.

[#querying-keyspaces]
== Query Collections

You can query collections using the `system:keyspaces` keyspace as follows:

[source,sqlpp]
----
SELECT * FROM system:keyspaces
----

For the default collection in the default scope, the query returns the following attributes:

[horizontal]
`datastore_id`:: (string) ID of the datastore to which the keyspace belongs
`id`:: (string) ID of the bucket to which the keyspace belongs
`name`:: (string) Bucket to which the keyspace belongs
`namespace`:: (string) Namespace to which the keyspace belongs
`namespace_id`:: (string) ID of the namespace to which the keyspace belongs
`path`:: (string) Path of the keyspace

For a named, non-default collection, the query returns the following attributes:

[horizontal]
`bucket`:: (string) Bucket to which the keyspace belongs
`datastore_id`:: (string) ID of the datastore to which the keyspace belongs
`id`:: (string) ID of the keyspace
`name`:: (string) Name of the keyspace
`namespace`:: (string) Namespace to which the keyspace belongs
`namespace_id`:: (string) ID of the namespace to which the keyspace belongs
`path`:: (string) Path of the keyspace
`scope`:: (string) Scope to which the keyspace belongs

NOTE: Querying `system:keyspaces` only returns non-system keyspaces.
To return all keyspaces, including the system keyspaces, you can query `system:all_keyspaces`.

[#querying-indexes]
== Query Indexes

You can query indexes using the `system:indexes` keyspace as follows:

[source,sqlpp]
----
SELECT * FROM system:indexes
----

For an index on the default collection in the default scope, the query returns the following attributes:

[horizontal]
`condition`:: (string) Index filter, if present
`datastore_id`:: (string) ID of the datastore to which the index belongs
`id`:: (string) ID of the index
`index_key`:: (array of strings) List of index keys
`is_primary`:: (boolean) True if the index is a primary index
`keyspace_id`:: (string) ID of the bucket to which the index belongs
`name`:: (string) Name of the index
`namespace_id`:: (string) ID of the namespace to which the index belongs
`state`:: (string) State of index, for example, online
`using`:: (string) Type of index, for example, gsi

For an index on a named, non-default collection, the query returns the following attributes:

[horizontal]
`bucket_id`:: (string) ID of the bucket to which the index belongs
`condition`:: (string) Index filter, if present
`datastore_id`:: (string) ID of the datastore to which the index belongs
`id`:: (string) ID of the index
`index_key`:: (array of strings) List of index keys
`is_primary`:: (boolean) True if the index is a primary index
`keyspace_id`:: (string) ID of the keyspace to which the index belongs
`name`:: (string) Name of the index
`namespace_id`:: (string) ID of the namespace to which the index belongs
`state`:: (string) State of index, for example, online
`using`:: (string) Type of index, for example, gsi

NOTE: Querying `system:indexes` only returns indexes on non-system keyspaces.
To return all indexes, including indexes on system keyspaces, you can query `system:all_indexes`.

[#querying-dual]
== Query Dual

You can use dual to evaluate constant expressions.

[source,sqlpp]
----
SELECT 2+5 FROM system:dual
----

The query returns the result of the expression, 7 in this case.

== Related Links

* Refer to xref:server:manage:monitor/monitoring-n1ql-query.adoc[Monitor Queries] for more information on the system namespace.