= Enable Custom Script Search Queries
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-status: Couchbase Server 8.5
:description: Before you can use custom script queries with the Search Service, you need to enable custom script queries on your cluster.

[abstract]
{description}

For more information about custom script queries, see xref:custom-scripts/custom-script-queries.adoc[].

== Prerequisites

* You have the Search Service enabled on a node in your cluster.
For more information about how to deploy a new node and Services on your cluster, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* Your user account has the xref:learn:security/roles.adoc#search-admin[`Search Admin`] role.

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure

To allow custom script queries to run on your cluster:

. Go to menu:Settings[Search].
. Under *Custom Script Query Execution*, click *Enabled*.

NOTE: Enabling custom script queries across your cluster can take about 1-2 seconds.
You can turn off this setting at any time by clearing *Enabled*, but this can cause downtime on your cluster, as the JavaScript execution engine needs to restart.

== Next Steps

After you enable custom script query execution on your cluster, you can xref:custom-scripts/run-custom-script-query.adoc[].