= Hybrid Search Using GSI with a Vector Column
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: A Composite Vector Index is a Global Secondary Index (GSI) with a single vector column that enables hybrid queries to find semantically-related content.
:stem: 
:page-toclevels: 3
:index-name: Composite Vector Index
:index-name-plural: Composite Vector Indexes

{description}
The added vector column lets your application perform a hybrid query using both the index's scalar, array, and object index entries plus a vector value. 
See xref:learn:services-and-indexes/indexes/indexes.adoc[] for an overview of GSI and other indexes.

== How the Composite Vector Index's Vector Column Works 

A Composite Vector Index has a single vector column that enables semantic and similarity searches within your {sqlpp} queries.
When creating the index, you use a `VECTOR` key attribute to designate the field that contains the embedded vectors.

When your query contains an embedded vector, the Query Service uses any non-vector predicates in the query to filter index entries.
Then it performs an index scan on the remaining index entries, using the similarity function you specify in the query to locate similar vectors. 
This behavior reduces the number of vector similarity comparisons the Query Service must do to find similar vectors.

== Prerequisites

* You must have the Index Service enabled on at least one node in your cluster. 
For more information about how to deploy a new node and Services on your database, see xref:manage:manage-nodes/node-management-overview.adoc[].

* You must have a bucket with scopes and collections in your database. 
For more information about how to create a bucket, see xref:manage:manage-buckets/create-bucket.adoc[].

* Your account must have the xref:learn:security:roles.adoc#query-manage-index[Query Manage Index] role to be able to create an index.

* You have documents in a collection that contain one or more vector embeddings.
You can add a single vector to a Composite Vector Index.
If your documents contain multiple embedded vectors, you can create multiple indexes---one for each vector attribute.
+
Embeddings can be an array of floating point numbers or a base64 encoded string.
Couchbase {product-name} does not embed vectors itself. 
You must use an external embedding model to embed vectors into your data and add them to your documents.
+
[TIP]
--
include::vector-search:partial$download-sample-partial.adoc[]
--

* You must know the number of dimensions the vector contains. 
The embedding model you use to embed the vectors may determine this value for you.
For example, OpenAI API's `text-embedding-ada-002` embedding model that embedded the sample data demonstrated later in this page creates vectors that have 1536 dimensions.

* You must decide what algorithms you want your index to use. 
These algorithms affect how much memory and processing Couchbase {product-name} uses to train and search them.
See xref:vector-index:vectors-and-indexes-overview.adoc#index-algorithms[Indexing Algorithms]

include::partial$index-algorithm-settings.adoc[]


== Create a Composite Vector Index

Creating a Composite Vector Index is similar to creating a non-vector GSI index.
See xref:guides:create-index.adoc[] for an overview of creating indexes.
In the `CREATE INDEX` statement to create the Composite Vector Index, add the `VECTOR` lead key attribute after the vector's column name to declare it as an embedded vector.

You must also use the `WITH` clause to specify some additional information for the vector column. 
The format for this clause with the most commonly used parameters is:

[source,sqlpp]
----
WITH {  "dimension":<dimensions> , "similarity":<similarity-function>, "description":<algorithm-settings>}; 
----

* `dimensions` is an integer value that sets the number of dimensions in the vector.
This value is set by the embedded model you used to embed the vectors.
* `similarity-function` is a string that sets the distance function to use when comparing vectors during index creation.
Couchbase {product-name} uses the following strings to represent the proximity functions:
+
--
** `COSINE`: xref:use-vector-indexes.adoc#cosine[Cosine Similarity]
** `DOT`: xref:use-vector-indexes.adoc#dot[Dot Product]
** `L2`, `L2_SQUARED`, `EUCLIDEAN`, or `EUCLIDEAN_SQUARED`: xref:use-vector-indexes.adoc#euclidean[Euclidean Distance]  
--
+
For the greatest accuracy, use the distance function you plan to use when querying vector data.
* `algorithm-settings` is a string containing the settings for the indexing algorithms. 
See <<#algo_settings>> earlier in this page.

For a full list of the parameters that affect a vector column in a GSI, see *FIXME:TDB*.

[#examples]
=== Examples

The following examples show you how to create two Composite Vector Index with a vector column using sample data.
They both use the data from the `color_data_2vectors.zip` file mentioned earlier. 
The data in `rgb.json` file looks like this:

[source,json]
----
[
  {
    "id": "#FFEFD5",
    "color": "papaya whip",
    "brightness": 240.82,
    "colorvect_l2": [
      255,
      239,
      213
    ],
    "wheel_pos": "other",
    "verbs": [
      "soften",
      "mellow",
      "lighten"
    ],
    "description": "Papaya whip is a soft and mellow color that can be described as a light shade of 
    peach or coral. It has a calming and soothing effect, similar to the tropical fruit it is named 
    after. This color is perfect for creating a warm and inviting atmosphere, and it pairs well with 
    other pastel shades or neutral tones. Papaya whip is a versatile color that can be used in both 
    fashion and interior design, adding a touch of elegance and sophistication to any space.",
    "embedding_model": "text-embedding-ada-002-v2",
    "embedding_vector_dot": [
      -0.014644118957221508,
      0.017003899440169334,
      -0.013450744561851025,
      0.0021356006618589163,
      0.006283756345510483,
      0.01162360142916441,
    // . . . 
    ]
 },
 // . . . 
] 
----

==== Index the RGB Values

The `rgb.json` file's `colorvect_l2` attribute defines an array containing the RGB values for the entry's color. 
While this technically is not an embedded vector, you can still create a vector index column for this array. 
The following example creates a GSI for this attribute as an embedded vector as well as the color's name and brightness.

[source,sqlpp]
----
include::vector-index:example$gsi-vector-idx-examples.sqlpp[tag=create-rgb-idx]
----

In this example:

* The number of dimensions is 3, because there are three values in the array containing the RGB value.
* The similarity function is `L2`. 
This function works well to find related vectors which are close by the search vector.
In this example, finding similar colors depends more on proximity than the magnitude or alignment of the vectors.
See xref:gsi-with-vectors.adoc##vector_similarity[Vector Similarity] for a comparison of similarity functions.
* The `description` lets Couchbase {product-name} decide the number of centroids for the IVF algorithm.
It also chooses to use Scalar Quantization with an 8-bit index, splitting each dimension into 256 bins.
This setting does not actually save any space in the index, as each of the RGB dimensions are already 8-bit values. 
However, in this example, memory use is not a concern as the dataset is small. 

The result of running example is:

[source,json]
----
[
  {
    "id": "f572fa0b1c7358ee",
    "name": "color_vectors_idx",
    "state": "online"
  }
]
----

==== Create a Composite Vector Index Using the Embedded Vectors

The `embedding_vector_dot` attribute contains the embedded vectors for the text in the `description` attribute.
The data sample shown in <<#examples>> truncated this attribute to several values.
The embedded vector contains 1536 dimensions.

The following example creates a GSI that indexes the embedded vectors in the `embedding_vector_dot` as well as indexing the scalar `color` that contains the color's name and `brightness.`
 
[source,sqlpp]
----
include::vector-index:example$gsi-vector-idx-examples.sqlpp[tag=create-vectors-idx]
----

This example uses the Dot Product similarity function. 
This function works better with the embedded text content than the Euclidean function used in the previous example. 
It also uses the same algorithms as the previous example--Couchbase {product-name} chooses the number of centroids, and uses SQ quantization with 256 bins.

If successful, Couchbase {product-name} responds with:

[source, json]
----
[
  {
    "id": "c965205718c3e4c2",
    "name": "color_desc_idx",
    "state": "online"
  }
]
----

After Couchbase {product-name} creates the index, it begins training it. 
Depending on your system, this training can take several seconds.

== Query with a Composite Vector Index Column

You query embedded vector attributes that you have indexed in a Composite Vector Index to find similar vectors and therefore similar semantic content.
To find the most similar vectors, use a `GROUP BY` clause in your query to return the most relevant vectors first. 
In this clause, call one of two functions that actually performs the vector comparisons: `APPROX_VECTOR_DISTANCE` or `VECTOR_DISTANCE`.
The first of these functions is faster, but less precise.
The second is more precise, but slower.
Which you choose depends on your use case.

You should also use a `LIMIT` clause to return just the number of vectors you need. 
The query pushes the `LIMIT` clause down into the index scan so that the scan ends after finding the required number of matches.

=== Query RGB Values

Querying the RGB values in `rgb.colorvect_l2` requires a vector with only three values.
You can just specify the vector by hand.
The following example finds colors that are similar to gray, which has an RGB value of 128, 128, 128:

[source, sqlpp]
----
include::vector-index:example$gsi-vector-idx-examples.sqlpp[tag=query-rgb-idx]
----

The query uses the `APPROX_VECTOR_DISTANCE` function to sort the results. 
You pass it the vector column to search, the vector to search for (in this case, the array `128, 128, 128`) and the distance function.

For the best accuracy, use the same distance function you specified when creating the GSI (in this case, `L2`).
The query pushes the `LIMIT` clause down into the index scan, so once it finds the 5 entries that satisfy the query, it exits.

The top result is the entry for gray. 
The other results are all shades of gray:

[source,json]
----
[{
        "color": "grey",
        "colorvect_l2": [
            128,
            128,
            128
        ],
        "brightness": 128
    },
    {
        "color": "slate gray",
        "colorvect_l2": [
            112,
            128,
            144
        ],
        "brightness": 125.04
    },
    {
        "color": "light slate gray",
        "colorvect_l2": [
            119,
            136,
            153
        ],
        "brightness": 132.855
    },
    {
        "color": "light gray",
        "colorvect_l2": [
            144,
            144,
            144
        ],
        "brightness": 144
    },
    {
        "color": "dim gray",
        "colorvect_l2": [
            105,
            105,
            105
        ],
        "brightness": 105
    }
]
----

You can also add other predicates to help reduce the workload of searching for similar vectors by excluding vectors.
The following example searches for colors similar to gray which has an RGB value of 128, 128, 128 and have a brightness greater than 128:

[source, sqlpp]
----
include::vector-index:example$gsi-vector-idx-examples.sqlpp[tag=query-rgb-idx-w-predicate]
----

The result of running this query are:

[source, json]
----
[{
        "color": "light slate gray",
        "colorvect_l2": [
            119,
            136,
            153
        ],
        "brightness": 132.855
    },
    {
        "color": "light gray",
        "colorvect_l2": [
            144,
            144,
            144
        ],
        "brightness": 144
    },
    {
        "color": "cadet blue",
        "colorvect_l2": [
            95,
            158,
            160
        ],
        "brightness": 139.391
    },
    {
        "color": "rosy brown",
        "colorvect_l2": [
            188,
            143,
            143
        ],
        "brightness": 156.455
    },
    {
        "color": "dark sea green",
        "colorvect_l2": [
            143,
            188,
            143
        ],
        "brightness": 169.415
    }
]
----

===  Query the Embedded Vectors

To query the `color_desc_idx` Composite Vector index containing the embedded vector for the description attribute, you must supply a vector.
In a production environment, your application calls the same embedding model it called to generate the embedded vectors in your documents to generate a vector for the query value.

For this example, you can use embedded vectors in the `rgb_questions.json` file that's in the `color_data_2vectors.zip` file.
This file contains a `question` attribute containing a search prompt for a particular color. 
The `couchbase_search_query.knn.vector` attribute contains the embedded vector for the `question` attribute:

[source,json]
----
[
  {
    "id": "#FFEFD5",
    "question": "What is the name of the color that is reminiscent of a tropical fruit and has a calming
     effect, often used in fashion and interior design?",
    "wanted_similar_color_from_search": "papaya whip",
    "embedding_model": "text-embedding-ada-002-v2",
    "couchbase_search_query": {
      "fields": [
        "*"
      ],
      "knn": [
        {
          "field": "embedding_vector_dot",
          "k": 3,
          "vector": [
            0.005115953739732504,
            0.004331615287810564,
            0.014279481954872608,
            // ....
          ]
        }
      ],
      "query": {
        "match_none": {}
      },
      "sort": [
        "-_score"
      ]
    }
  },
  // ...
]
----


This example queries the  `embedding_vector_dot` column. 
It appears here with most of the 1536 vectors omitted:

[source,sqlpp]
----
include::vector-index:example$gsi-vector-idx-examples.sqlpp[tag=query-vectors-idx-truncated]
----

You can expand the following section to see and copy the entire query with all the vectors:

.Show full example
[%collapsible]
====
[source,sqlpp]
----
include::vector-index:example$gsi-vector-idx-examples.sqlpp[tag=query-vectors-idx-whole]
----
====

Another option is to import the `rgb_questions.json` file into another collection in the `vector-sample` bucket's `color` scope named `rgb-questions`.
Then you can use a subquery to get the vectors for the question and use it in your query of the `rgb` collection's `embedding_vector_dot` attribute:

[source,sqlpp]
----
include::vector-index:example$gsi-vector-idx-examples.sqlpp[tag=query-vectors-idx-subquery]
----

In either case, the results of the query are the same:

[source,json]
----
[
  {
    "color": "cantalope",
    "description": "The color cantaloupe is a soft and soothing shade that evokes feelings of calmness 
    and relaxation. It is a refreshing hue that brings to mind the juicy and sweet fruit it is named 
    after. This delicate color is a pale orange with hints of pink, giving it a subtle and gentle 
    appearance. It is a perfect color for creating a peaceful and tranquil atmosphere."
  },
  {
    "color": "papaya whip",
    "description": "Papaya whip is a soft and mellow color that can be described as a light shade of 
    peach or coral. It has a calming and soothing effect, similar to the tropical fruit it is named 
    after. This color is perfect for creating a warm and inviting atmosphere, and it pairs well with 
    other pastel shades or neutral tones. Papaya whip is a versatile color that can be used in both 
    fashion and interior design, adding a touch of elegance and sophistication to any space."
  },
  {
    "color": "apricot",
    "description": "Apricot is a warm and inviting color, reminiscent of the soft glow of a sunset. It 
    has the ability to soften the harshness of other colors and enliven any space it is used in. It is a 
    delicate and soothing hue, perfect for creating a cozy and welcoming atmosphere."
  }
]
----

The second result, the color papaya whip, matches the `rgb_questions` collection's `wanted_similar_color_from_search` attribute. 

=== Adding a Scalar

Using additional scalar fields in your search can improve your results and reduce the overhead of performing a vector search.
For example, filtering on an additional scalar field reduces the number of vectors an index scan has to compare. 
Searching for scalar values requires less resources than vector searches.

The example that created the `color_desc_idx` index added fields in addition to the `embedding_vector_dot` vector field. 
The following example adds a filter based on the `brightness` field to reduce the number of vectors that get compared and also improve the results.

The version of the query that performs a subquery of the `rgb-questions` to get the vector value is:

[source,sqlpp]
----
include::vector-index:example$gsi-vector-idx-examples.sqlpp[tag=query-vectors-idx-subquery-filtered]
----

The truncated version of the query is: 

[source,sqlpp]
----
include::vector-index:example$gsi-vector-idx-examples.sqlpp[tag=query-vectors-idx-filtered-truncated]
----

You can expand the Show full example section to see and copy the entire query with all the vectors:

.Show full example
[%collapsible]
====
[source,sqlpp]
----
include::vector-index:example$gsi-vector-idx-examples.sqlpp[tag=query-vectors-idx-filtered-whole]
----
====

The results of this query moves the papaya whip entry to the top. 

[source,json]
----
[{
        "color": "papaya whip",
        "description": "Papaya whip is a soft and mellow color that can be described as a light shade of peach or coral. It has a calming and soothing effect, similar to the tropical fruit it is named after. This color is perfect for creating a warm and inviting atmosphere, and it pairs well with other pastel shades or neutral tones. Papaya whip is a versatile color that can be used in both fashion and interior design, adding a touch of elegance and sophistication to any space.",
        "brightness": 240.82
    },
    {
        "color": "pale turquoise",
        "description": "Pale turquoise is a delicate and soothing color that can be described as a soft blend of blue and green. It has a calming effect and can evoke feelings of tranquility and serenity. The color is often associated with the ocean and can bring to mind images of clear, tropical waters. It has a gentle and subtle quality, making it a popular choice for creating a peaceful and serene atmosphere.",
        "brightness": 219.163
    },
    {
        "color": "light green",
        "description": "Light green is a calming and refreshing color that evokes feelings of tranquility and new beginnings. It is a delicate shade that is often associated with nature and growth. The softness of this color can bring a sense of balance and harmony to any space, making it a popular choice for interior design. Light green is also known to have a rejuvenating effect, making it a perfect color for relaxation and self-care. Its gentle hue can bring a sense of peace and serenity to the mind, body, and soul.",
        "brightness": 199.178
    }
]
----
