= Use Scalar Columns to Filter Hyperscale Vector Index Scans
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: You can reduce the number of vectors a query that uses a Hyperscale Vector index by adding scalar values.
:stem:
:page-toclevels: 3
:index-name: Hyperscale Vector index
:index-name-plural: Hyperscale Vector indexes

[abstract]
{description}
A Hyperscale Vector index has a single column that indexes the vector.
However, you can include scalar values in the index that you can use to filter the vector search.
The index stores these included values along with the vector, but they're not indexed.

In your queries that use a Hyperscale Vector index, you add the included scalar values as predicates in the `WHERE` clause.
During the index scan, Couchbase {product-name} uses the included scalar values to filter out vectors that do not meet the filter restriction.
If the filter matches the entry, Couchbase {product-name} performs the more expensive vector comparison operation to determine the distance between the vector value and the search vector.

== Creating a Hyperscale Vector Index with Included Scalar Values

When you create a Hyperscale Vector index, you can add scalar values to the index using the `INCLUDE` clause in the `CREATE VECTOR INDEX` statement.

The following example creates a new Hyperscale Vector index for the `embedding-vector-dot` vector column from the xref:vector-index:hyperscale-vector-index.adoc#query-example[Hyperscale Vector Index Query Example].
It also includes the `brightness` key from the document.


[source,sqlpp]
----
include::vector-index:example$hyperscale-idx-examples.sqlpp[tag=create-idx-brightness]
----

This example is the same as the example from xref:vector-index:hyperscale-vector-index.adoc#examples[Create Hyperscale Vector Index Example], except that it adds the `INCLUDE` clause to add the `brightness` key.

== Querying a Hyperscale Vector Index with Included Scalar Values

When you query a Hyperscale Vector index, you can use the included scalar values as predicates in the `WHERE` clause of your query.
Couchbase {product-name} uses the predicates to filter the results before performing the vector comparison.

The following example performs the same query as the example from xref:vector-index:hyperscale-vector-index.adoc#query-with-a-hyperscale-vector-index[Query with a Hyperscale Vector Index], but adds the `brightness` key as a predicate in the `WHERE` clause:

[source,sqlpp]
----
include::vector-index:example$hyperscale-idx-examples.sqlpp[tag=query-rgb-with-brightness]
----

The result of running the query is:

[source,json]
----
include::vector-index:example$hyperscale-idx-data.json[tag=query-rgb-brightness]
----

Querying with the `brightness` attribute changes makes `sky blue` the top result compared to the results from the example in xref:vector-index:hyperscale-vector-index.adoc#query-with-a-hyperscale-vector-index[Query with a Hyperscale Vector Index].
The restriction can also make the query faster.
On a laptop running a three-node cluster in Docker containers, the query ran in 43{nbsp}ms versus 219{nbsp}ms for the query without the filter.
