= Hyperscale Vector Index Reranking and Full Vector Persistence
:page-title: Reranking and Full Vector Persistence
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: You can enable reranking in queries using a Hyperscale Vector index to potentially improve the query results. 
:stem: 
:page-toclevels: 3
:index-name: Hyperscale Vector index
:index-name-plural: Hyperscale Vector indexes

[abstract]
{description}
It uses non-quantized versions of the search and indexed vectors to return more accurate results.
After the query locates similar vectors in the index, it performs a second round of comparisons using the full vector values stored in the index to reorder the results.
This reranking can make the most relevant vectors to the search vector appear higher in the search results.

== Enabling Reranking

To enable reranking, your index must have a copy of the full vector value in addition to the quantized value.
The `CREATE VECTOR INDEX` statement adds this copy of the full vector value to the index by default.

Queries do not perform reranking by default. 
To enable it, you must pass `TRUE` as the fifth parameter in the `APPROX_VECTOR_DISTANCE` function call in your query.

For example, the following query on the sample RGB dataset does not perform reranking:

[source,sqlpp]
----
include::vector-index:example$hyperscale-idx-examples.sqlpp[tag=rerank-before-example]
----

The results of this query are:

[source,json]
----
include::vector-index:example$hyperscale-idx-data.json[tag=rerank-before]
----

The color that's most relevant to the search vector, `#FFFFE0` Light Yellow, is third in the results. 

The following query enables reranking by passing `TRUE` as the fifth parameter in the `APPROX_VECTOR_DISTANCE` function call:

[source,sqlpp]
----
include::vector-index:example$hyperscale-idx-examples.sqlpp[tag=rerank-after-example]
----

The results of this query are:

[source,json]
----
include::vector-index:example$hyperscale-idx-data.json[tag=rerank-after]
----    

The result for Light Yellow improved from position 3 to position 2. 

[#prevent-vector-persistence]
== Preventing Vector Persistence

Reranking can improve the accuracy of recall in some cases. 
However, it always decreases queries per second (QPS) when enabled.
In many cases, you can achieve acceptable recall accuracy without reranking.
See xref:vector-index:vector-index-best-practices.adoc#reranking[Reranking] to learn in which cases reranking is useful.

Storing the full vector significantly increases the size of the index. 
If you do not plan to use reranking, you can save space in your index by having it not save the full vector value.

To prevent an index from persisting the full vector, set the `persist_full_vector` attribute to `False` in the `WITH` clause of the `CREATE VECTOR INDEX` statement you use to create it:

[source,sqlpp]
----
WITH {  "dimension":<dimensions> , 
        "similarity":<similarity-function>, 
        "description":<algorithm-settings>, 
        "persist_full_vector":false
     }; 
----

The following example creates a Hyperscale Vector index from the example RGB dataset that does not persist the full vector value:

[source,sqlpp]
----
include::vector-index:example$hyperscale-idx-examples.sqlpp[tag=create-rgb-no-persist]
----

The size of the resulting index is much smaller than the index that persists the full vector value  (269KiB verses 1.17MiB).

The actual savings you see in your own indexes depends on the number of dimensions in your vectors.
