= Vector Search Using Hyperscale Vector Indexes
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Hyperscale Vector Indexes are optimized to index a single vector column. They offer the highest performance of any index when it comes to vector data.
:stem:
:page-toclevels: 3
:index-name: Hyperscale Vector index
:index-name-plural: Hyperscale Vector indexes

[abstract]
{description}
They can scale up to a billion documents containing vectors with a large number of dimensions.

Because they provide the best performance, consider testing a Hyperscale Vector index for your application before resorting to the other types of indexes.
If you find their performance does not meet your needs, then test using a Composite Vector Index or a Search Vector Index.

== How the Hyperscale Vector Index Works

The Hyperscale Vector Index primarily relies on data stored in an optimized format on disk.
By relying on disk storage, they have lower memory requirements than other index types.

You add a single vector column to a Hyperscale Vector Index.
The vector value can be an array of floating point values.
You can nest the array in another array as long as you use an xref:n1ql:n1ql-language-reference/unnest.adoc[UNNEST clause] to extract it from the containing array.
You can also store the vector in a BASE64 string.

== Prerequisites

Hyperscale Vector Indexes have the following requirements:

* You must have the Index Service enabled on at least one node in your cluster.
For more information about how to deploy a new node and Services on your database, see xref:clusters:modify-database.adoc#modify-existing-service[Modify the Cluster Configuration].

* Your account must have the xref:organizations:organization-user-roles.adoc#organization-role-organization-owner[`Organization Owner`], xref:projects:project-roles.adoc#project-owner-role[`Project Owner`], or xref:projects:project-roles.adoc#project-cluster-data-reader-writer[`Data Writer`] role to be able to create an index.

* You must have a bucket your database.
For more information about how to create a bucket, see xref:clusters:data-service/manage-buckets.adoc[].

* You have documents in a collection that contain one or more vector embeddings.
You can add a single vector to a Hyperscale Vector Index.
If your documents contain multiple embedded vectors, you can create multiple indexes -- one for each vector attribute.
+
Embeddings can be an array of floating point numbers or a base64 encoded string.
Couchbase {product-name} does not embed vectors itself.
You can use an external embedding model to embed vectors into your data and add them to your documents, or use xref:ai:build:model-service/deploy-embed-model.adoc[Capella AI Services].

* The vectors you add to an index must contain the same number of dimensions.
Also the values in the vector must be 32-bit floating point numbers.
If a vector does not meet both of these requirements, the vector index treats it as a NULL value and the document is not added to the index.

* You must know the number of dimensions the vector contains.
The embedding model you use to embed the vectors may determine this value for you.
For example,  OpenAI API's `text-embedding-ada-002` embedding model creates vectors that have 1536 dimensions.

* You must decide whether you want to use the default distance metric and quantization for your index.
By default, a Hyperscale Vector index uses the xref:vector-index:vectors-and-indexes-overview.adoc#euclidean-squared[Euclidean distance squared] metric and xref:vector-index:vectors-and-indexes-overview.adoc#sq[Scalar Quantization (SQ)] with 8 bits per vector dimension (`SQ8`).
The metrics affect how the index compares vectors.
The quantization determines how much memory your index uses and the amount of processing Couchbase {product-name} must perform to train and search them.
See xref:vector-index:vectors-and-indexes-overview.adoc#vector_similarity[Vector Similarity Metrics] and xref:vector-index:vectors-and-indexes-overview.adoc#quantization[Quantization] for more information.

=== Examples on this Page

include::vector-search:partial$download-sample-partial.adoc[]

In addition, to get the best results with the examples on this page, download the following sample dataset:

https://cbc-remote-execution-examples-prod.s3.amazonaws.com/color_data_2vectors.zip[Download color_data_2vectors.zip]

When you have downloaded `color_data_2vectors.zip`, unzip it, then xref:guides:load.adoc[import] the `rgb_questions.json` file with the following settings:

* Use the `color-vector-sample` bucket.
* Use the `color` scope.
* Create a new target collection called `rgb-questions` -- with a hyphen `-`, not an underscore `&lowbar;`.
* To set your document keys, use the value of the `id` field from the JSON document.

[#create-index]

include::vector-index:partial$create-hyperscale-index-capella-ui.adoc[opts=optional]

== Create a Hyperscale Vector Index Using {sqlpp}

Use the `CREATE VECTOR INDEX` statement to create a Hyperscale Vector Index.
This statement is similar to the `CREATE INDEX` statement that you use to create Global Secondary Indexes (GSI).
See xref:guides:create-index.adoc[] for an overview of creating indexes.
You must also supply a `WITH` clause to set some additional information about the vector column that the Hyperscale index needs.

The following syntax shows the minimum required parameters to create a Hyperscale Vector index:

[source,sqlpp]
----
CREATE VECTOR INDEX `<index_name>`
       ON `<collection>`(`<key_name>` VECTOR)
       WITH {"dimension": <dimensions>,
             "similarity": <similarity_metric>,
             "description": <centroids_and_quantization>
        };
----

NOTE: This syntax for the `CREATE VECTOR INDEX` shows the minimum required parameters to get you started.
For the full syntax, see xref:n1ql:n1ql-language-reference/createvectorindex.adoc[] in the SQL++ for Query Reference.

The parameters in this statement are:

* `index_name` is a string that sets the name of the index.
* `collection` is the path of the collection to index.
* `key_name` is the name of the key containing the vector that you want to index.
The key value must be an array of floating point numbers or a base64 encoded string.
* `dimensions` The number of dimensions in the vector as an integer.
The embedded model you use to embed the vectors determines the number of dimensions in the vector.
* `similarity_metric` is a string that sets the distance metric to use when comparing vectors during index creation.
+
include::partial$distance-metric-list.adoc[]

+
For the greatest accuracy, use the distance metric you plan to use to query the data.
* `centroids_and_quantization` is a string containing the settings for the quantization and index algorithms.
See <<#algo_settings>> in the next section for more information.

include::partial$index-algorithm-settings.adoc[]


[#examples]
=== Create Hyperscale Vector Index Example

The examples in this section use the `color-vector-sample.color.rgb` collection.
This contains information about colors, including a text description of the color.

The following query returns a sample document from the data in the `color-vector-sample.color.rgb` collection, truncating the embedded vector to 4 values to make the result readable:

[source,sqlpp]
----
include::vector-index:example$hyperscale-idx-examples.sqlpp[tag=rgb-entry]
----

The result of running the query is:

[#example-results]
[source,json]
----
include::vector-index:example$hyperscale-idx-data.json[tag=rgb-document]
----

The following example creates an Hyperscale Vector index for the vector column named `embedding-vector-dot`.

[source,sqlpp]
----
include::vector-index:example$hyperscale-idx-examples.sqlpp[tag=create-rgb-idx]
----

The key pieces of this example are:

* The `CREATE VECTOR INDEX` statement creates a Hyperscale Vector index.
This differs from the `CREATE INDEX` statement used to create a Global Secondary Index (GSI).
* The `WITH` clause defines several settings specific to Hyperscale Vector indexes:
** It uses the Euclidean distance (`l2`) similarity function when locating centroids.
This function has high accuracy, which matters in a dataset with only 153 documents.
** Also, because the dataset is so small, the example sets the `description` to `IVF8,SQ4`.
This value has the xref:vector-index:vectors-and-indexes-overview.adoc#IVF[inverted file algorithm] use just 8 centroids.
It also uses 4-bit xref:vector-index:vectors-and-indexes-overview.adoc#sq[scalar quantization].
These settings limit the fragmentation of the small dataset.

In most cases, you'll not use these settings in a production environment.

== Query with a Hyperscale Vector Index

To use your Hyperscale Vector index, use the `SELECT` statement with an `ORDER BY` clause containing a call to the xref:n1ql:n1ql-language-reference/vectorfun.adoc#approx_vector_distance[APPROX_VECTOR_DISTANCE()] function.
The query selects the Hyperscale Vector index when this function includes the vector key that the index covers.

A typical query looks like this:

[source,sqlpp]
----
SELECT <fields>
       FROM <collection>
       ORDER BY APPROX_VECTOR_DISTANCE(
                <collection-vector-column>,
                <search-vector-value>,
                <distance-metric>,
                <centroids-to-probe>,
                <rerank>,
                <topNScan>
        ) LIMIT <number-of-results>;
----

The `APPROX_VECTOR_DISTANCE` parameters shown in the example are:

* `collection-vector-column` is the name of the key containing the vector in the collection.
* `search-vector-value` is the vector value to search for in the collection column.
It can be an array of floating point numbers or a base64 encoded string.
* `distance-metric` is the distance metric to use when comparing the vectors.
This value should match the distance metric you used when you created the index.
* `centroids-to-probe` is an optional integer value that sets the number of centroids to probe for matching vectors.
By default, the vector search only probes a single centroid.
* `rerank` is an optional Boolean that can only be used when `centroids-to-probe` is specified.
It specifies whether the function should use full vectors to achieve better results.
For more information, see xref:vector-index:hyperscale-reranking.adoc[].
* `topNScan` is an optional positive integer that can only be used when `centroids-to-probe` and `rerank` are specified.
If specified, it sets the number of records to scan.

Also use a `LIMIT` clause to return just the number of results you need.
The query pushes the `LIMIT` clause down into the index scan so that the scan ends after finding the number of matches you need.

NOTE: You can also call the function xref:n1ql:n1ql-language-reference/vectorfun.adoc#vector_distance[VECTOR_DISTANCE()] to find similar vectors.
However, this function does not use the Hyperscale Vector index to perform the vector search.
Instead, it performs a brute-force search for similar vectors.
It's useful to measure the recall of your Hyperscale Vector index.
See xref:vector-index:vector-index-best-practices.adoc#recall-accuracy[Determine Recall Rate] for more information about measuring recall.

[#query-example]
=== Hyperscale Vector Index Query Example

You must supply a vector value in your query that Couchbase {product-name} can compare to the vectors in the index.
In actual use, your application generates a vector for the query value using the same embedding model it used to embed the vectors in your documents.

To avoid the complication of calling an embedding model, this example uses embedded vectors in the `rgb_questions.json` file that's included in `color_data_2vectors.zip`.
For this example, the contents of this file are loaded into a collection named `color-vector-sample.color.rgb-questions`.
This collection contains a `question` attribute which is a search prompt for a particular color.
The `couchbase_search_query.knn.vector` attribute contains the embedded vector for the `question` attribute.
The following query lists several attributes from a document in the collection.
It truncates the `couchbase_search_query.knn.vector` attribute to just the first 4 dimensions of the vector for readability:

[source,sqlpp]
----
include::vector-index:example$hyperscale-idx-examples.sqlpp[tag=query-rgb-questions]
----

The output of the query looks like this:

[source,json]
----
include::vector-index:example$hyperscale-idx-data.json[tag=query-rgb-questions-output]
----

To use the embedded vector, you need to include the `couchbase_search_query.knn.vector` attribute in your query's `SELECT` statement.
You can either directly copy and paste the entire array into your query or use a subquery to retrieve it from the `color-vector-sample.color.rgb-questions` collection.
The following example uses a subquery to get the vector, and also includes the `wanted_similar_color_from_search` attribute in the output which shows you the color that the query should return.

[source,sqlpp]
----
include::vector-index:example$hyperscale-idx-examples.sqlpp[tag=query-rgb-with-subquery]
----

In this example, the `APPROX_VECTOR_DISTANCE` function compares the vector in the `couchbase_search_query.knn.vector` attribute to the vectors in the index.
The parameters the example passes to this function are:

* The `embedding-vector-dot` is the name of the indexed vector key in the collection.
* The `couchbase_search_query.knn[0].vector` is the vector search value to compare to the vectors in the index.
This value is the result of the subquery that gets the vector from the `rgb-questions` collection.
* `l2` is the distance metric to use.
* `4` is the number of centroids to probe for matching vectors.
This value defaults to `1`.
This example sets this value to `4` because the dataset is small.
In a small dataset, it's more likely that relevant vectors are not associated with the same centroid.
This parameter broadens the search beyond a single centroid to find more relevant vectors.
If you re-run the query with the default value of `1`, you'll see that the results are less relevant.

The result of running the query is:

[source,json]
----
include::vector-index:example$hyperscale-idx-data.json[tag=query-rgb-color]
----

The second result, `sky blue`, matches the `wanted_similar_color_from_search` attribute as the most relevant color to the question posed in the `question` attribute.
All of the results are still relevant to the question.

=== Getting the Vector Distance

You can use the `APPROX_VECTOR_DISTANCE` function as a predicate to return the distance between the search vector and the vectors in the index.
You may want to get this value when the distance is meaningful, such as when it represents a real-world measurement.

The following example returns the distance between the search vector and the vectors in the index by adding an alias for the results of the `APPROX_VECTOR_DISTANCE` function in the `SELECT` statement as well as the `ORDER BY` clause:

[source,sqlpp]
----
include::vector-index:example$hyperscale-idx-examples.sqlpp[tag=query-rgb-with-distance]
----

The result of running the query is:

[source,json]
----
include::vector-index:example$hyperscale-idx-data.json[tag=query-rgb-distance]
----

