= Use Vector Indexes for AI Applications
:page-topic-type: concept
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use Couchbase {page-product-name}'s Vector Index features to find documents based on content similarity or semantic meaning.

{description}

Vector Indexing lets you add vectors to Couchbase {product-name} indexes. 
You store index values as attributes in your documents, and then index those attributes.
You can then find relevant data by executing queries on the vector attributes, which use the index to find similar vectors.

== About Vectors

Vectors are a numerical representation of complex data such as text, images, or audio.
They distill this complex data into an array of floating-point values called dimensions. 
These dimensions capture features of the data in a way that makes the data easy to compare. 
Similar data, such as text about the same topic or images of a similar subject, have similar vectors. 
These vectors are close together the multi-dimensional space formed by all of the vectors in the dataset.
Vectors for dissimilar data (for example, articles discussing two different topics) have vectors that are further apart in this multi-dimensional space.

By comparing two vectors, you can find the similarity between two pieces of data.
This similarity goes beyond just finding parts of the data that's identical (for example, finding many of the same words in two pieces of text).
The vectors represent features such as the semantic meaning of text rather than just superficial similarities.

In Couchbase {product-name}, you can use vectors to find documents that are similar to an existing document or query values.
By searching your database for similar vectors, you can identify data that's semantically similar to your query value.

=== Embedding Vectors

Embedding is the process of generating vectors that represent a piece of complex data.
You use a model that's specific to the data's type to generate its vector.
For example, to generate vectors from text, you can use a use models such as https://en.wikipedia.org/wiki/Word2vec[Word2Vec^] or https://en.wikipedia.org/wiki/GloVe[Global Vectors for Word Representation (GloVe)^].
The models take into account the context around each potion of the text when generating a vector.
This context is what captures the semantic meaning of the text and embeds it in the vector's dimensions.

You can only compare the similarity of vectors when the same model generated them. 
For example, you cannot find the similarity of two pieces of text if the vector for one was generated by Word2Vec and the other was generated by GloVe.

Couchbase {product-name} does not implement any embedding models. 
To store vectors into your database, you must use external embedding models to generate vectors for your data.
A common method of embedding vectors in your database is to call the https://openai.com/index/introducing-text-and-code-embeddings/[OpenAI Embedding API^] to generate vectors for your data.   

=== Comparing Vectors

Once complex data embedded in your database as a vector, you can find data has a similar meaning by locating similar vectors. 
A vector database such as Couchbase {product-name} can help with this task by indexing vectors in a way that makes finding similar vectors faster.

Several algorithms exist that you can use to compare vectors. 
For example, 
When choosing an algorithm, you often have to balance accuracy for speed. 
Couchbase {product-name} supports several different comparison algorithms, such as 

=== Reducing Vector Complexity

The number of dimensions in a vector can vary. 
A vector that represents highly complex data such as images can contain several thousand dimensions.
Simpler data, such as text, can still have hundreds of dimensions.
When you execute a query to find similar vectors, this large number of dimensions can make the query computationally expensive.
A search for similar raw vectors in an index would require comparing hundreds or thousands of values for each index entry.

You can use several techniques to reduce the overhead of searching for similar vectors.

* Partitioning groups vectors together based on similarity. 
When searching for vectors that are similar to a value, you only need to search the relevant groups.

* Quantization reduces the space taken by a vector by lowering its precision. 
It maps each vector to the closest centroid which is vector contained in a compiled list of representative vectors called a codebook. 
Instead of storing the full original vector, this technique stores just the index of the centroid in the codebook.
It reduces the storage size without altering the dimensionality of the vector.
This storage reduction makes vector comparisons faster, because searches only compare the codebook index values instead of the full vectors.

For large amounts of complex data, you often use multiple techniques.

Some types of Couchbase {product-name} indexes can perform quantization and partitioning on your vectors.  

== Vectors in Couchbase {product-name} Indexes

To use vectors in Couchbase {product-name} queries, you store them in attributes in your documents and then add those attributes to an index. 
Couchbase {product-name} supports vectors in the following index types:

* Vector Indexes are specifically designed for vector searches. 
They can index billions of documents.
Most of the Vector Index is stored in a highly optimized format on disk.
Use this type of index when you want to query multiple vector values with a low memory footprint.
This index offers high accuracy even for vectors with a large number of dimensions. 

* Global Secondary Indexes (GSI) can be extended with a single vector column. 
Adding a vector to a GSI index is useful when your queries combine a single vector value with standard scalar attributes.
The scalar attributes in a query reduce the number of vectors the Couchbase {product-name} has to compare to find similar vectors.
Use GSI indexes with a vector column when you want to perform hybrid searches of documents using both scalars and a vector.
They consume a moderate amount of memory and can index billions of documents.
When querying, the scalar attributes in the query limit the number of vectors that the query has to compare.

* A Search index used for Full-Text Search can have an added vector attribute,
These indexes can index millions of documents.
The search results combine the scores of full text search and the semantic meanings of the vector search to give you hybrid results.
Use Search indexes with a vector attribute when you want to query based on keywords, geospacial data, and a vector value.

== Uses for Vectors in Couchbase {product-name} Indexes

Here's some ways you can use vector indexes in your applications:

* Improve your application's search ability by querying not just for values data, but also based on similar content.
For example, suppose your application is a product catalog. 
Using a GSI index extended with a vector column, it could find similar products based not just on attributes (such as color or size) but also the similarity of the product's description and customer reviews.

* Create a customized chatbot based on your own data by implementing a  Retrieval-Augmented Generation (RAG) workflow.
When a user enters a question, convert it to a vector using the same embedding model you used to embed vectors into your index.
Perform a query using the vector index to find relevant documents in your database.
Then pass the user's question and the relevant documents to a Large Language Model to generate a final response for the user. 


