= Use Vector Indexes for AI Applications
:page-topic-type: concept
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use Couchbase {page-product-name}'s Vector Index features to find documents based on content similarity or semantic meaning.
:page-toclevels: 3

{description}

Vector Indexing lets you add vectors to Couchbase {product-name} indexes. 
You store index values as attributes in your documents, and then index those attributes.
You can then find relevant data by executing queries on the vector attributes, which use the index to find similar vectors.

== About Vectors

Vectors are a numerical representation of complex unstructured data such as text, images, or audio.
They distill this complex data into an array of floating-point values called dimensions.
The dimensions in vectors capture features of the data in a way that makes them easy to compare mathematically. 
Similar data, such as text about the same topic or images of a similar subject, have similar vectors. 
Similar vectors are close together the multi-dimensional space formed by all of the vectors in the dataset.
Vectors for dissimilar data (for example, articles discussing two different topics) have vectors that are further apart in this multi-dimensional space.



By comparing two vectors, you can find the similarity between two pieces of data.
This similarity goes beyond just finding parts of the data that's identical (finding similar words in two pieces of text, for example).
The vectors represent features such as the meaning of text rather than just superficial similarities.

For example, suppose you have three text articles. 
The first is about feral cats, the second about domestic cats, and the third is about the UNIX/Linux `cat` command.
A text search for the term "cat" could return all three articles at the top of its search results due to their frequent use of the search term.
However, that does not mean that the articles are semantically related (about the same topic). 

By generating vectors for the articles and comparing them, you can determine any semantic relationship between them. 
Vectors can be similar in a variety of ways:

* Their vectors may point in similar directions.
* They may be close to each other in the vector space made up of all the dimensions in the vectors. 
* They may have a similar magnitude (length). 

Because the first two articles are about cats, their vectors point in a similar direction and are in a similar location in space. 
The third article, despite using the word "cat" as frequently as the two other articles, has a vector that  has significant differences from the other two.

image::vector-space-example.svg["Three-dimensional plot showing two vectors that are close by and parallel and a third vector that's away and points in another direction"]

NOTE: Many of the diagrams in this document (and in many other discussion available on the web) show vectors in three dimensions. 
These diagrams are a simplification. 
The vectors used in AI applications have hundreds to thousands of dimensions. 
They are easy for computers to handle, but rather difficult for humans to visualize.
So, when viewing these diagrams, remember that they only scratch the surface of the data encoded in a vector.

Vectors also let you search for similarity in data that's hard to search using traditional  techniques.
Image data, for example, is just a string of raw binary values. 
Matching portions of this data within two image files does not mean they're of the same subject, or even have any resemblance.
Also, comparing megabytes of raw image data is computationally expensive.
Generating vectors of the images distills features of the image into a smaller, more manageable amount of data.
It also emphasizes features of the images that viewers find important, such as shapes and textures.
Comparing the vectors is more manageable, and actually results in finding similar images.

In Couchbase {product-name}, you can use vectors to find documents that are similar to an existing document or query value.
By searching your database for similar vectors, you can identify data that's semantically similar to a value.

=== Embedding Vectors

Embedding is the process of generating vectors that represent a piece of complex unstructured data.
You use an embedding model that's specific to the data's type to generate a vector to represent it.

For example, to generate vectors from text, you can use a use models such as https://en.wikipedia.org/wiki/Word2vec[Word2Vec^], https://en.wikipedia.org/wiki/GloVe[Global Vectors for Word Representation (GloVe)^], or https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2[all-MiniLM-L6-v2^].
These models take into account the context around each potion of the text when generating a vector.
This context is what captures the semantic meaning of the text and embeds it in the vector's dimensions. 

To generate vectors from images, you use different embedding models such as a https://en.wikipedia.org/wiki/Residual_neural_network[Residual Neural Network (ResNet)^]. 
You can embed audio using a model such as OpenL3.

image::embedding-vectors.svg["Diagram showing text, image, and audio data being transformed by embedding models into a string of floating point numbers that represent vectors."]

Behind the scenes, embedding models use neural networks that mimic how the brain recognizes patterns.
The neural nets distill the complex data into an array of floating point values.
Beyond choosing an embedding model that's appropriate for your data, you generally do not worry about the details of how the model transforms data into a vector.

You can only compare the similarity of vectors generated by the same embedding model. 
For example, you cannot find the similarity of a vector generated by Word2Vec and one generated by GloVe.
You also cannot compare a vector for a piece of text generated by Word2Vec with the vector for an image generated by ResNet.

Couchbase {product-name} does not implement any embedding models. 
You must use external embedding models to generate them and then store the resulting vectors in your documents.
A common method of embedding vectors in your database is to call an https://openai.com/index/introducing-text-and-code-embeddings/[OpenAI Embedding API^] to generate vectors for your data.   
You then store the vector as an attribute in your document.

=== Vector Similarity

Once you have embedded vectors in your database, you find documents with a similar meaning by finding similar vectors. 
Several algorithms exist that you can use to find similar vectors.
When you search for similar vectors in Couchbase {product-name}, you must specify which similarity method to use to compare vectors.
Each algorithm is suited for different types of data.
+
Couchbase {product-name} supports three similarity methods:

Euclidean Distance (also known as L2)::
Calculates the geometric distance between two vectors by finding the distance between the individual dimensions in the vectors.
This method is most sensitive to the distance between the vectors in space, rather than their alignment. 
It's also sensitive to the scale of the vectors, where the length of one vector verses the other affects the relationship between the vectors.
Use this method when the proximity of the vectors and their magnitudes are important.
+
image::euclidean-distance-example.svg["Three-dimensional plot showing two vectors with points along each vector joined by dotted lines, indicating the summing of corresponding points."]
+
Euclidean Distance is useful for tasks such as image similarity searches. Vectors for similar images form clusters within vector space.

Dot Product::
Finds related vectors by comparing the magnitude and alignment of the vectors. 
In this method, the proximity of the vectors in space is less important than whether they point in a similar direction and have the a similar magnitude.
Vectors that point in similar directions (have a low angle between them) and have similar magnitude are strongly associated with each other.
This method uses the similarity of the vectors' magnitudes to rank their relation.
+
image::dot-product-example.svg["Three-dimensional plot showing two vectors labeled with their magnitudes and the angle between them labeled with the theta symbol."]
+
Use this method for tasks such as recommendation engines where you want to rank results from most to least related. 

Cosine Similarity::
This method is similar to the dot product. 
However, it normalizes the vectors (making them the same length) during comparison.
Normalization means their magnitudes are not taken into account, just their alignment. 
This normalization makes this method better for comparing textual data because it's less sensitive to the length of the data.
The magnitude of a vector generated by some textual data  embedding models depend on the length of the source text.
Normalizing vector magnitudes emphasizes the semantic meaning when performing comparisons.
Therefore, Cosine Similarity can find the semantic relationship between a short question and a long article that's relevant to answering it.
+
image::cosine-similarity-example.svg["Three-dimensional plot showing two vectors that are of equal length, with the angle between them labeled as theta."]
+
Use this method when you're performing similarity searches on text.

== Vector Indexes

As with other data types in Couchbase {product-name}, indexes make searching for similar vectors much faster.
Using indexes for vector searches is especially important due to the size of the vector data.
Vectors can contain hundreds to even thousands of dimensions. 
Using indexes helps limit the resources needed to perform vector searches.

=== Index Support for Vectors

You can include vectors in three types of indexes:

* Vector Indexes are specifically designed for vector searches. 
They can index billions of documents.
Most of the Vector Index resides in a highly optimized format on disk.
Use this type of index when you want to primarily query vector values with a low memory footprint.
They excel at traditional vector similarity and semantic searches.
This index offers high accuracy even for vectors with a large number of dimensions. 

* Global Secondary Indexes (GSI) can have a single vector column. 
Adding a vector to a GSI is useful when your queries combine a single vector value with standard scalar attributes.
The scalar attributes in a query reduce the number of vectors the Couchbase {product-name} has to scan to find similar vectors.
Use GSI indexes with a vector column when you want to perform hybrid searches of documents using both scalars and a vector.
They work well for cases where your queries are highly selective---returning a small number of results from a large dataset.
They consume a moderate amount of memory and can index billions of documents.

* A Search index used for Full-Text Search can have an added vector attribute,
The search results combine keyword matching of Full-Text Search with the semantic meaning matching of vectors to give you hybrid results.
Use Search indexes with a vector attribute when you want to query based on keywords, geospacial data, and a vector value.
These indexes can index millions of documents.

=== Indexing Algorithms

When you add a vector column to an index, you specify an algorithm that Couchbase {product-name} uses to process the vector values in the index.
These algorithms organize and consolidate vector data in the index to make it more efficient to search.

Couchbase {product-name} supports the following methods:

Flat Index::
This algorithm just stores the full vector value in the index without performing any sort of optimization. 
Searches using this index use a brute-force method to find similar vectors.
Adding new vectors to a flat index is fast, and the index does not need training.
It also offers high precision, because search compares the full vector values. 
However, it does not scale well. 
However, searching a flat index is inefficient, because the search must compare every vector in the index to find matchers.
You should only use it for small data sets or for testing. 

Inverted File (IVF)::
This method partitions the vector space to limit the number of vectors that a search must compare.
After creating the index, you must train it before using it.
This training locates clusters of similar vectors in the dataset. 
It then chooses representative vectors (called centroids) from these clusters.
Finally, it associates all vectors with their closest centroid in a structure called an inverted list.
+
image::ivf-diagram-with-vectors.svg["A plot showing clusters of points in a 3D graph being labvelled and assigned centroid vectors. The centroids them point to multiple vectors."]
+
When you search an IVF index, it first locates the centroids that are most relevant to the vector value you're searching for.
It then searches just the vectors associated to those centroids in the inverted list.
By limiting the number of vector comparisons to just the vectors close to the relevant centroids, IVF makes vector search faster.
+
A drawback of this method is the risk that the search will miss some relevant vectors.
These vectors can be missed if they're associated with a centroid that is not relevant to the search vector.
This risk increases as you add and delete data after you train the index.
The centroids chosen during the initial training may no longer accurately represent clusters in current dataset.
See <<#index-training>> for more information about index accuracy.
+
Use this method if you want a balance between precision and search speed.

Product Quantization (PQ)::
Product Quantization is similar to IVF, but adds additional steps to its training:
+
--
. It groups the vector's dimensions into chunks called subvectors.
For example, suppose the vectors contain 1024 dimensions.
Then PQ may break the vectors into 8 subvectors, each containing 128 dimensions.
. It finds groups of centroids in each subvector space and adds them to a data structure called a codebook.
The codebook assigns each centroid an index number. 
. PQ then reduces the size of the vectors in a process called quantizing.
Quantization replaces each subvector's dimensions with the index of the closest centroid in the codebook.
--
+
image::pq-diagram.svg["Three-dimensional plot showing two vectors that are of equal length, with the angle between them labeled as theta."]
+
The quantized vectors reduce a vector that's 1024 64-bit floating point values to 128 8 bit or 16 bit integer values.
This reduction improves performance because integer operations are less intensive than floating point operations. 
It also reduces memory use because each vector requires less data to store (for example, from 64KB to 128 bytes). 
+
Once it quantizes the vectors, PQ finds centroids in the dataset the same way IVF does.
The index stores the centroids and their related vectors in the inverted list using the quantized format.
+
A search of the PQ index performs the same steps on the vector you're searching for:
+
-- 
. It breaks the search vector into subvectors and quantizes it using the codebook.
. It then locates closest centroids to the quantized query vector.
. It searches the vectors related to the matching centroids for vectors that relate to the search vector.
--
+
PQ sacrifices some accuracy because it compares quantized vectors instead of their original raw values.
The process of quantization in addition to finding centroids makes training the index more computationally expensive than the other methods.
However, PQ reduces the amount of memory and processing time necessary when searching for related vectors in a large dataset.
It's the best indexing method choose when:
+
* Your vectors contain a large number of dimensions.
* You are willing to trade higher processing requirements during training for lower memory use during searches.
* Your dataset is large (millions to billions of vectors).

Scalar Quantization (SQ)::
Scalar Quantization partitions each dimension in the vector into equal segments (called bins) over the range of the dimension's values.
In the diagram, the first dimension's values range from 0 to 1, while the second dimension's range from 0.1 to 0.9.
It assigns each bin an index value that's 8 or 16 bits. 
SQ then quantizes the vectors by replacing their dimensional values with the index of the bin the value falls into.
+
image::sq-diagram.svg["Diagram showing each floating point dimension of a vector being converted to an 8-bit integer by looking up which bucket it falls into."]
+
This quantization reduces the dimensions from 32 or 64 bit floating point values to 8 or 16 bit integers.
It lowers the memory needed to perform the search.
It also makes search faster because integer operations are computationally less expensive than floating point operations.
+
Because this method quantizes the vectors, it loses precision.
It's less precise than the PQ method (which also quantizes vectors) because it assumes that each dimension can be evenly divided. 
Its accuracy suffers if your data has clusters.
However, the gain in performance is often worth the tradeoff.
+
SQ has a lower training overhead compared to the PQ and IVF methods because it does not search for clusters of vectors.
Its training just determines the range of values for each dimension.
It's best suited for data that's more evenly distributed and does not have high correlations.
For example, SQ may be a good fit for an IoT sensor dataset where the measured values (such as temperature) are evenly distributed over the range of measurements.
+
Use this method if you want to gain some of the memory efficiency offered by vector quantization, but want the processing overhead of training a PQ index. 

[#index-training]
=== The Importance of Index Training

Three of the four indexing methods rely on training the index on existing data. 
For example, both PQ and IVF locate centroids that represent clusters of vectors in vector space.
This training reflects the content of dataset at training time.
For this training to give you accurate search results, the data in your dataset must represent the full range of data you expect to search.
If it does not, the centroids the PQ or IVF indexing method selects may not accurately represent clusters of data in the dataset.
Having accurate centroids are key to these indexing methods returning accurate results. 

Over time, you may find the accuracy of your vector searches decreasing. 
Searches for similar vectors may miss relevant results or may rank less-related vectors higher than more relevant results.
These inaccuracies can occur because the data in the dataset changes over time as you add and remove documents.
The centroids identified by PQ and IVF may no longer adequately reflect the data in your database.
New clusters of vectors may have developed, and old ones may have dissipated.

Indexes using the SQ indexing algorithm can return inaccurate results if the range of values in the dimensions change. 
If one or more dimensional values fall outside the range that SQ assign  buckets to, they get assigned closest bucket.
These inaccuracies can build over time, skewing results,.

To resolve these accuracy issues, retrain your indexes. 
You can retrain indexes periodically, or after you have made significant changes to your dataset.

You should consider the need to retrain your indexes when choosing which index algorithm to use. 
For example, the PQ index method requires more resources to train than the IVF or SQ method. 
If your dataset evolves rapidly, you may want avoid using PQ because you will need to perform more frequent retraining.  

== Uses for Vectors in Couchbase {product-name} Indexes

Here's some ways you can use vector indexes in your applications:

* Improve your application's search ability by querying not just for discrete values, but also based on similar content.
For example, suppose your application is a product catalog. 
Using a GSI index extended with a vector column, it could find similar products based not just on attributes (such as color or size) but also the similarity of the product's description and customer reviews.

* Create a customized chatbot based on your own data by implementing a  Retrieval-Augmented Generation (RAG) workflow using a Vector Index.
When a user enters a question, convert it to a vector using the same embedding model you used to embed vectors into your database.
Perform a query using a Vector Index to find relevant documents in your database.
Then pass the user's question and the relevant documents to a Large Language Model (LLM) to generate a final response for the user. 

== Application Workflow with Vector Indexes

No matter which type of Couchbase {product-name} index you add vectors to, the workflow for your application to use them is similar. The following diagram shows a typical workflow.

[plantuml,ai-app-workflow,svg]
....
include::vector-index:partial$ai-app-workflow.puml[]
....

. Your application may need to load or update data that contains one or more attributes that have embedded vectors in Couchbase {product-name}. 
Before it can load the data into a Couchbase collection, it calls an embedding model to create vectors for these attributes.

. The application then sends the data including the embedded vector to Couchbase {product-name} for storage.
The Data Service handles creating or updating a document in a collection.

. The addition or update of data in an indexed collection causes the Index Service to update the index. 

. When your application needs to perform a query or search that includes a vector, it uses the  embedding model to generate a vector for the search value. 
It then passes this vector as part of the search request or query.

. Depending if the application is performing a search or a query, the Search Service or Query Service processes the request using the appropriate index

. The Search or Query Service returns any results to your application.

