= Use Vector Indexes for AI Applications
:page-topic-type: concept
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use Couchbase {page-product-name}'s Vector Index features to find documents based on content similarity or semantic meaning.
:page-toclevels: 3

{description}

You cam add vectors to Couchbase {product-name} indexes. 
You store index values as attributes in your documents, and then index those attributes.
You can then find relevant data by executing queries on the vector attributes, which use the index to find similar vectors.

As with other data types in Couchbase {product-name}, indexes make searching for similar vectors much faster.
Using indexes for vector searches is especially important due to the size of vector data.
Vectors contain hundreds to thousands of dimensions. 
Using indexes reduces the resources needed to perform vector searches.

If you're unfamiliar with vectors and vector indexing, see xref:vectors-and-indexes-overview.adoc[] for an overview.

You can include vectors in three types of Couchbase {product-name} indexes:

Hyperscale Vector Indexes::
These indexes are specifically designed for vector searches. 
They perform vector similarity and semantic searches faster than the other types of indexes.
They can scale to index billions of documents compared to the million-ranges for the other index types.
Most of the Hyperscale Vector indexes resides in a highly optimized format on disk.
Use this type of index when you want to primarily query vector values with a low memory footprint.
It offers high accuracy even for vectors with a large number of dimensions. 
It also supports concurrent searches and inserts for datasets that are constantly changing.

+
See xref:vector-index:hyperscale-vector-index.adoc[] for more information.

Composite Vector Indexes::
Composite Vector indexes combine a standard GSI index with a single vector column. 
This combination lets you perform a hybrid search using a single vector value with standard scalar attributes that are also indexed in the Composite Vector Index.
The scalar attributes in a query reduce the number of vectors the Couchbase {product-name} has to compare when performing an index scan to find similar vectors.
Use GSI indexes with a vector column when you want to perform hybrid searches of documents using both scalars and a vector.
They work well for cases where your queries are highly selective---returning a small number of results from a large dataset.
They consume a moderate amount of memory and can index billions of documents.

+ 
To learn how to use Composite Vector indexes, see xref:vector-index:composite-vector-index.adoc[].


FTS Vector Index::
An FTS Vector index is a hybrid that combines a Couchbase {product-name} Search index with a single vector column.
This combination adds semantic search to the Search index's full-text and geospatial search capabilities.
These indexes can index millions of documents.

+
To learn how to use FTS Vector indexes, see xref:vector-search:vector-search.adoc[].

== Choosing the Right Index Type

When choosing which type of index to use, you must consider:

* The size of your dataset.
* Whether you need to perform hybrid searches that combine scalar value or text searches along with the vector search.
* The performance requirements of your application.

The following table summarizes the differences between the three types of vector indexes:

[%autowidth]
|===
| Index Type | Dataset Size | Uses | Strength | Limitations

| *Hyperscale Vector Index* 
| Billions of documents
a| 
* Pure vector searches
* Content discovery or recommendations
a| 
* High performance for pure vector searches
* Low memory footprint
* Lowest TCO for huge datasets
* Best option for concurrent updates and searches
a| 
* Overkill on smaller datasets
* Indexing can take longer relative to other index types

| *Composite Vector Index*
| Tens to hundreds of millions
| Hybrid searches combining vector and scalar values
a| 
* Scalar values pre-filter data to reduce the scope of vector searches
* Can restrict searches based on scalars for use cases such as compliance.
* Based familiar Global Secondary indexes (GSI) 
a| 
* Accuracy suffers in huge datasets compared to Hyperscale Vector index
* Scalar values always override vector values in queries, potentially missing relevant results

| *FTS Vector Index*
| Tens of millions
| Hybrid searches combining vector and keywords or geospatial
a| 
* Combines semantic and Full-Text search and geospatial search in a single pass.
* Uses familiar Search indexes
a| 
* Not as efficient as Composite Vector indexes if the search includes purely numeric or scalar values
* Does not scale to the extent of the other index types.
Limited to approximately 100 million documents
|===


When choosing which type of index to use, consider the following:

* If your dataset will not grow beyond 100 million documents, you can consider Composite Vector or FTS Vector indexes, especially if you need to perform hybrid searches.
* If your dataset is larger than or may grow larger than 100 million documents, use a Hyperscale Vector index.
* When in doubt, try using a Hyperscale Vector index.
If you find that the performance is not what you need, you can try using one of the other index types.

== Applications for Vector Indexes

Each type of index is suited to different types of applications.
The following sections explain several common applications for each type of vector index.
They also describe the workflow your application follows when using each type of index.

=== Hyperscale Vector Index Applications

Hyperscale Vector indexes contain a single vector column.
They excel at huge dataset that can scale into the billions of documents.
They are optimized for pure vector searches, such as content discovery or recommendations.

The Hyperscale Vector index works well for applications such as:

Reverse image searches::
Embedded vectors for images often contain up to thousands of dimensions, which Hyperscale Vector indexes handle better than other index types.

Chatbot context matching::
Chatbot context for workflows like retreival-augmented generation (RAG) requires a huge dataset for accurate results.
The large dataset gives the chatbot a depth of knowledge that's not necessary in simpler applications.

Anomaly detection::
Anomaly detection applications such as those used in Internet of Things (IoT) sensor networks,   require huge datasets to find deviations from normally occurring patterns.
Hyperscale Vector indexes can handle the large datasets and perform these vector searches fast.

When using a Hyperscale Vector index, your application follows the workflow shown in the following diagram:

.Application Workflow with Hyperscale Vector Indexes
[plantuml,hyperscale-vector-app-workflow,svg]
....
include::vector-index:partial$hyperscale-vector-app-workflow.puml[]
....

The steps shown in the diagram are:
. When your application loads data with a complex data field it wants to search semantically, it calls an embedding model to generate a vector for it.
. It sends the data, including the vector, to Couchbase {product-name} for storage.
. The Data Service sends the embedded vector to the Indexing Service for inclusion in the Hyperscale Vector index.
. When your application needs to perform a query that includes a vector, it uses the same embedding model to generate a vector for the search value.
. It sends the vector as part of the search request or query to teh Couchbase {product-name} Search Service.
. The Query Service performs an index scan in the Hyperscale Vector index to find similar vectors to the search vector.
. The Search Service returns results to your application.

See xref:vector-index:hyperscale-vector-index.adoc[] for more information about Hyperscale Vector indexes.

=== Composite Vector Index Applications 
Composite Vector indexes contain a single vector column and one or more scalar columns.
They apply scalar filters before performing a vector similarity search.
This is ideal for workflows where you want to exclude documents entirely to reduce the number of vectors that the index has to compare.
Composite Vector indexes work well for applications such as:

Content Recommendations::
Viewers often want hard constraints on their searches, such as genre, language, or favorites actors or directors.
Composite Vector indexes can filter using these constraints before performing a vector similarity search on fields such as the plot description or reviews.

Job Searches::
Job seekers often want to filter jobs based on location, salary, or job title.
Composite Vector indexes can filter using these constraints before performing a vector similarity search on fields such as the job description or required skills.

Supply chain management::
Supply chain management applications often need to query based on product type, supplier, or location.
Vector similarity searches can be added to these searches to find similar demand patterns.


When using a Composite Vector index, your application follows the workflow shown in the following diagram:

.Application Workflow with Composite Vector Indexes
[plantuml,composite-vector-app-workflow,svg]
....
include::vector-index:partial$composite-vector-app-workflow.puml[]
....

The steps shown in the diagram are:

. When your application loads data with a complex data field it wants to search semantically, it calls an embedding model to generate a vector for it.
. It sends the data, including the vector, to Couchbase {product-name} for storage.
. The Data Service sends the embedded vector along with scalar fields to the Indexing Service for inclusion in the Composite Vector index.
. When your application needs to perform a query that includes a vector, it uses the same embedding model to generate a vector for the search value.
. It sends the vector and scalar values as part of a query to the Couchbase {product-name} Query Service.
. The Query Service performs an index scan in the Composite Vector index to find documents that match the scalar fields. 
Then it performs a vector similarity search in the documents using the search vector.
. The Search Service returns results to your application.

See xref:vector-index:composite-vector-index.adoc[] for more information about Composite Vector indexes.

[#fts]
=== FTS Vector Index Applications

FTS Vector indexes contain a single vector column in addition to a full-text search index.
Some of the applications for FTS Vector indexes include:

E-Commerce product recommendations::
E-Commerce applications can use scalar, text, and vector searches to find products that match a customer's search.
For example, a customer could search for red sneakers (text) that cost less than $100 (scalar) that are similar to an uploaded image of a sneaker (vector).

Travel recommendations::
Users often want to search for hotels using multiple criteria:

+
* Limiting searches to a specific area (for example, "walking distance to the Louvre") which relies on geospacial data. 
* Specific keywords for features they want ("quiet", "romantic", "gym") which requires Full-Text search.
* Semantic searches of descriptions and reviews for searches that do not rely on literal texzt matches ("modern beach resort with chic decor") which requires vector searches.

+
An FTS vector index can combine geospacial, keyword, and semantic searches into a single index.

Real estate searches::
Real estate applications can use FTS Vector indexes to find properties within a search region and have floor plan similar to an uploaded image.


When using a FTS Vector index, your application follows the workflow shown in the following diagram:

.Application Workflow with FTS Vector Indexes
[plantuml,fts-app-workflow,svg]
....
include::vector-index:partial$fts-vector-app-workflow.puml[]
....

The steps shown in the diagram are:

. When your application loads data it wants to search semantically, it calls an embedding model to generate a vector for it.
. It sends the data and the vector, to Couchbase {product-name} for storage.
. The Data Service sends the embedded vector along with scalar fields to the Search Service for inclusion in the FTS Vector index.
. When your application needs to perform a search that includes a vector, it uses the same embedding model to generate a vector for the search value.
. It sends the search vector and text, geospacial, and other search values as part of a search request to the Couchbase {product-name} Search Service.
. The Search Service performs an index scan in the FTS Vector index to find documents that match the scalar fields. 
Then it performs a vector similarity search in the documents using the search vector.
. The Search Service returns results to your application.

