= Use Vector Indexes for AI Applications
:page-topic-type: concept
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use Couchbase {page-product-name}'s Vector Index features to find documents based on content similarity or semantic meaning.
:page-toclevels: 3

{description}

Vector Indexing lets you add vectors to Couchbase {product-name} indexes. 
You store index values as attributes in your documents, and then index those attributes.
You can then find relevant data by executing queries on the vector attributes, which use the index to find similar vectors.

As with other data types in Couchbase {product-name}, indexes make searching for similar vectors much faster.
Using indexes for vector searches is especially important due to the size of vector data.
Vectors contain hundreds to thousands of dimensions. 
Using indexes reduces the resources needed to perform vector searches.

If you're unfamiliar with vectors and vector indexing, see xref:vectors-and-indexes-overview.adoc[] for an overview.

== Application Workflow with Vector Indexes

The following diagram shows a typical workflow for an application that uses vector values stored in Couchbase {product-name}.

[plantuml,ai-app-workflow,svg]
....
include::vector-index:partial$ai-app-workflow.puml[]
....

. Your application may need to load or update a document in Couchbase {product-name} that contains one or more attributes that store embedded vectors. 
Before it can load the data into a Couchbase collection, it calls an embedding model to create vectors for these attributes.

. The application then sends the data including the embedded vector to Couchbase {product-name} for storage.
The Data Service handles creating or updating a document in a collection.

. The addition or update of data in an indexed collection causes the Index Service to update the index. 

. When your application needs to perform a query or search that includes a vector, it uses the  embedding model to generate a vector for the search value. 
It then passes this vector as part of the search request or query.

. Depending if the application is performing a search or a query, the Search Service or Query Service processes the request using the appropriate index

. The Search or Query Service returns any results to your application.


== Uses for Vectors in Couchbase {product-name} Indexes

Here's some ways you can use vector indexes in your applications:

* Improve your application's search ability by querying not just for discrete values, but also based on similar content.
For example, suppose your application is a product catalog. 
Using a GSI index extended with a vector column, it could find similar products based not just on attributes (such as color or size) but also the similarity of the product's description and customer reviews.
You can even offer the ability for customers to upload a picture and have your application find similar products.

* Create a customized chatbot based on your own data by implementing a  Retrieval-Augmented Generation (RAG) workflow using a Vector Index.
When a user enters a question, convert it to a vector using the same embedding model you used to embed vectors into your database.
Perform a query using a Vector Index to find relevant documents in your database.
Then pass the user's question and the relevant documents to a Large Language Model (LLM) to generate a final response for the user. 



== Index Support for Vectors

You can include vectors in three types of indexes:

* Vector Indexes are specifically designed for vector searches. 
They perform vector similarity and semantic searches faster than the other types of indexes.
They can index billions of documents.
Most of the Vector Index resides in a highly optimized format on disk.
Use this type of index when you want  to primarily query vector values with a low memory footprint.
This index offers high accuracy even for vectors with a large number of dimensions. 
See xref:vector-index.adoc[] for more information.

* Global Secondary Indexes (GSI) can have a single vector column. 
Adding a vector to a GSI lets you perform a hybrid search combining a single vector value with standard scalar attributes that are also indexed in the GSI.
The scalar attributes in a query reduce the number of vectors the Couchbase {product-name} has to compare when performing an index scan to find similar vectors.
Use GSI indexes with a vector column when you want to perform hybrid searches of documents using both scalars and a vector.
They work well for cases where your queries are highly selective---returning a small number of results from a large dataset.
They consume a moderate amount of memory and can index billions of documents.
To learn how to use GSI with vectors, see xref:gsi-with-vector.adoc[].

* A Search index used for full-text and geospacial search can have an added vector attribute,
The search results combine keyword matching of Full-Text Search with the semantic meaning matching of vectors to give you hybrid results.
Use Search indexes with a vector attribute when you want to query based on keywords or geospacial data plus a vector value.
These indexes can index millions of documents.