= Work with Documents in Bulk
:description: How to perform bulk CRUD operations with a command line tool or an SDK.
:page-pagination: prev
:page-topic-type: guide
:github: Click the icon:github[] View button to see this code in context.

include::partial$example-attributes.adoc[]

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

Performing bulk operations with Couchbase Capella can be done in several ways, depending on the SDK or command line tool used to perform them.
This guide contains basic procedures for performing bulk CRUD operations on documents.

include::partial$clients.adoc[tag=refs]

include::partial$data-warning.adoc[]

== Creating Multiple Documents

To create multiple documents, perform a bulk insert operation.

[tabs]
====
cbsh::
+
--
. If you haven't already done so, use `cb-env` to set the bucket, scope, and collection in which to store the documents.

. Create an array of structured documents to insert.

. Pipe each item through the `wrap` filter to wrap it in a `content` field.

. Pipe each item through the `insert` filter to add an `id` field with a unique value: for example, by copying a unique field from the content.

. Pipe the output through the `doc insert` command to create the documents.

'''

{kv-bulk-insert-example}

[source,sh]
----
include::example$kv/kv-cbsh.nu[tag=cbsh-bulk-insert]
----

.Result
[source,console]
----
╭───┬───────────┬─────────┬────────┬──────────┬─────────╮
│ # │ processed │ success │ failed │ failures │ cluster │
├───┼───────────┼─────────┼────────┼──────────┼─────────┤
│ 0 │         3 │       3 │      0 │          │ capella │
╰───┴───────────┴─────────┴────────┴──────────┴─────────╯
----

For further details, refer to {cbsh-api-url}/#_mutating[Mutating^] in the Couchbase Shell documentation.
--

pass:[.NET]::
+
--
. Create some structured JSON documents to insert.

. Initialize a list of `IMutationResult` tasks.

. Perform an insert operation on each document and store the result in the tasks list.

. Wait for all the tasks to complete before accessing the results.

'''

{kv-bulk-insert-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-users,indent=0]

include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-bulk-insert,indent=0]

----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
. Create some structured JSON documents to insert.

. Using the `reactor.core.publisher.Flux` reactive library, call the `fromIterable()` method to perform multiple insert operations.

{kv-bulk-insert-example}

[source,java]
----
include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-users,indent=0]

include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-bulk-insert,indent=0]

----

NOTE: A `JsonDocument` class is used to supplement the example.

[source,java]
----
include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-bulk-class,indent=0]
----

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^] and https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[Project Reactor^].
--

Node.js::
+
--
. Create some structured JSON documents to insert.

. Perform an insert operation on each document and wait for all the promises to complete before accessing the results.

'''

{kv-bulk-insert-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-bulk-hello-world.js[tags=kv-users;kv-bulk-insert,indent=0]
----

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
. Create a dictionary of structured JSON documents.

. Pass the dictionary to the `insert_multi()` function. This will insert all the documents in the database.

A dictionary of `MutationResult` objects is returned.

CAUTION: `CBCollection.insert_multi` is a xref:python-sdk:project-docs:compatibility.adoc#interface-stability[volatile] API call that is still in flux and may likely be changed.

'''

{kv-bulk-insert-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_bulk_hello_world.py[tags=kv-users;kv-bulk-insert,indent=0]
----

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

== Reading Multiple Documents

To read multiple documents, perform a bulk `get` operation.

[tabs]
====
cbsh::
+
--
. If you haven't already done so, use `cb-env` to set the bucket, scope, and collection where the documents are stored.

. Create an array of document IDs.

. Pipe each document ID through the `wrap` filter to wrap it in an `id` field.

. Pipe the output through the `doc get` command to retrieve multiple documents by their IDs.

'''

{kv-bulk-get-example}

[source,sh]
----
include::example$kv/kv-cbsh.nu[tag=cbsh-bulk-get]
----

.Result
[source,console]
----
╭───┬────┬────────────────────┬─────────────────────┬───────┬─────────╮
│ # │ id │      content       │         cas         │ error │ cluster │
├───┼────┼────────────────────┼─────────────────────┼───────┼─────────┤
│ 0 │ 1  │ {record 11 fields} │ 1717505682500419584 │       │ capella │
│ 1 │ 0  │ {record 11 fields} │ 1717505682774949888 │       │ capella │
╰───┴────┴────────────────────┴─────────────────────┴───────┴─────────╯
----

For further details, refer to {cbsh-api-url}/#_reading[Reading^] in the Couchbase Shell documentation.
--

pass:[.NET]::
+
--
. Initialize a list of `IGetResult` tasks.

. Perform a `get` operation on each document and store the results in the tasks list.

. Wait for all the tasks to complete before accessing the results.

'''

{kv-bulk-get-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-users,indent=0]

include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-bulk-get,indent=0]

----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
Using the `reactor.core.publisher.Flux` reactive library, call the `fromIterable()` method to perform multiple `get` operations.

'''

{kv-bulk-get-example}

[source,java]
----
include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-users,indent=0]

include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-bulk-get,indent=0]

----

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^] and https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[Project Reactor^].
--

Node.js::
+
--
Perform a `get` operation on each document and wait for all the promises to complete before accessing the results.

'''

{kv-bulk-get-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-bulk-hello-world.js[tags=kv-users;kv-bulk-get,indent=0]
----

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
Pass some document IDs to fetch to the `get_multi()` function. This will fetch the documents from the database.

A dictionary of `GetResult` objects is returned.

CAUTION: `CBCollection.get_multi` is a xref:python-sdk:project-docs:compatibility.adoc#interface-stability[volatile] API call that is still in flux and may likely be changed.

'''

{kv-bulk-get-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_bulk_hello_world.py[tags=kv-users;kv-bulk-get,indent=0]
----

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

== Updating Multiple Documents

To update multiple documents, perform a bulk upsert or replace operation.

[tabs]
====
cbsh::
+
--
. If you haven't already done so, use `cb-env` to set the bucket, scope, and collection where the documents are stored.

. Create an array of updated structured documents.

. Pipe each item through the `wrap` filter to wrap it in a `content` field.

. Pipe each item through the `insert` filter to add an `id` field with a unique value: for example, by copying a unique field from the content.

. Pipe the output through the `doc upsert` or `doc replace` command to update the documents.

'''

{kv-bulk-update-example}

[source,sh]
----
include::example$kv/kv-cbsh.nu[tag=cbsh-bulk-upsert]
----

.Result
[source,console]
----
╭───┬───────────┬─────────┬────────┬──────────┬─────────╮
│ # │ processed │ success │ failed │ failures │ cluster │
├───┼───────────┼─────────┼────────┼──────────┼─────────┤
│ 0 │         3 │       3 │      0 │          │ capella │
╰───┴───────────┴─────────┴────────┴──────────┴─────────╯
----

For further details, refer to {cbsh-api-url}/#_mutating[Mutating^] in the Couchbase Shell documentation.
--

pass:[.NET]::
+
--
. Add new data to update some existing JSON documents.

. Initialize a list of `IMutationResult` tasks.

. Perform an upsert or replace operation on each document and store the results in the tasks list.

. Wait for all the tasks to complete before accessing the results.

'''

{kv-bulk-insert-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-users,indent=0]

include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-bulk-insert,indent=0]

----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
. Add new data to update some existing JSON documents.

. Using the `reactor.core.publisher.Flux` reactive library, call the `fromIterable()` method to perform multiple upsert or replace operations.

'''

{kv-bulk-update-example}

[source,java]
----
include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-users,indent=0]

include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-bulk-upsert,indent=0]

----

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^] and https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[Project Reactor^].
--

Node.js::
+
--
. Add new data to update some existing JSON documents.

. Perform an upsert operation on each document and wait for all the promises to complete before accessing the results.

'''

{kv-bulk-update-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-bulk-hello-world.js[tags=kv-users;kv-bulk-upsert,indent=0]
----

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
. Add new data to update some existing JSON documents.

. Pass the new document data to `upsert_multi()`. This will update all the documents in the database.

A dictionary of `MutationResult` objects is returned.

CAUTION: `CBCollection.upsert_multi` is a xref:python-sdk:project-docs:compatibility.adoc#interface-stability[volatile] API call that is still in flux and may likely be changed.

'''

{kv-bulk-update-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_bulk_hello_world.py[tags=kv-users;kv-bulk-upsert,indent=0]
----

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

== Deleting Multiple Documents

To delete multiple documents, perform a bulk remove operation.

[tabs]
====
cbsh::
+
--
. If you haven't already done so, use `cb-env` to set the bucket, scope, and collection where the documents are stored.

. Create an array of document IDs.

. Pipe each document ID through the `wrap` filter to wrap it in an `id` field.

. Pipe the output through the `doc remove` command to delete multiple documents by their IDs.

'''

{kv-bulk-delete-example}

[source,sh]
----
include::example$kv/kv-cbsh.nu[tag=cbsh-bulk-delete]
----

.Result
[source,console]
----
╭───┬───────────┬─────────┬────────┬──────────┬─────────╮
│ # │ processed │ success │ failed │ failures │ cluster │
├───┼───────────┼─────────┼────────┼──────────┼─────────┤
│ 0 │         3 │       3 │      0 │          │ capella │
╰───┴───────────┴─────────┴────────┴──────────┴─────────╯
----

For further details, refer to {cbsh-api-url}/#_removing[Removing^] in the Couchbase Shell documentation.
--

pass:[.NET]::
+
--
. Initialize a list of tasks.

. Perform a remove operation on each document and store the results in the tasks list.

. Wait for all the tasks to complete.

'''

{kv-bulk-delete-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-users,indent=0]

include::dotnet-sdk:hello-world:example$KvBulkHelloWorld.csx[tag=kv-bulk-remove,indent=0]

----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
Using the `reactor.core.publisher.Flux` reactive library, call the `fromIterable()` method to perform multiple remove operations.

'''

{kv-bulk-delete-example}

[source,java]
----
include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-users,indent=0]

include::java-sdk:hello-world:example$KvBulkHelloWorld.java[tag=kv-bulk-remove,indent=0]

----

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^] and https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[Project Reactor^].
--

Node.js::
+
--
Perform a remove operation on each document and wait for all the promises to complete before accessing the results.

'''

{kv-bulk-delete-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-bulk-hello-world.js[tags=kv-users;kv-bulk-remove,indent=0]
----

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
Pass the document IDs to remove to the `remove_multi()` function. This will delete the documents from the database.

A dictionary of `MutationResult` objects is returned.

CAUTION: `CBCollection.remove_multi` is a xref:python-sdk:project-docs:compatibility.adoc#interface-stability[volatile] API call that is still in flux and may likely be changed.

'''

{kv-bulk-delete-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_bulk_hello_world.py[tags=kv-users;kv-bulk-remove,indent=0]
----

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

== Related Links

Bulk Operations with SDKs:

* xref:c-sdk:howtos:concurrent-async-apis.adoc[C]
| xref:dotnet-sdk:howtos:concurrent-async-apis.adoc[.NET]
| xref:go-sdk:howtos:concurrent-async-apis.adoc[Go]
| xref:java-sdk:howtos:concurrent-async-apis.adoc[Java]
| xref:nodejs-sdk:howtos:concurrent-async-apis.adoc[Node.js]
| xref:php-sdk:howtos:concurrent-async-apis.adoc[PHP]
| xref:python-sdk:howtos:concurrent-async-apis.adoc[Python]
| xref:ruby-sdk:howtos:concurrent-async-apis.adoc[Ruby]
| xref:scala-sdk:howtos:concurrent-async-apis.adoc[Scala]
