= Call a User-Defined Function
:description: How to call a user-defined function from {sqlpp} statements.
:page-pagination: prev
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2
:imagesdir: ../assets/images
:no-escape-hatch:

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

// tag::intro[]
A user-defined function can be called like any other {sqlpp} function.
// end::intro[]

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

== Executing a {sqlpp} User-Defined Function

To execute a user-defined function, use the `EXECUTE FUNCTION` statement.

. Specify the name of the function:

* To execute a function within the current query context, specify the function name alone.

* To execute a global function, prefix the function name with the `default:` namespace.

* To execute a scoped function, prefix the function name with the namespace, bucket, and scope, such as ``default:`travel-sample`.inventory``.

. Specify the function parameters within brackets.


. Set the context to match the namespace of the function you're calling.

====
The following query executes a function called `GetBusinessDays`, which was created in the current query context.

[source, sqlpp]
----
include::example$javascript-udfs:execute-javascript-function.n1ql[]
----

The following query executes a function called `GetBusinessDays`, which was created in the `inventory` scope within the `travel-sample` bucket.

[source, sqlpp]
----
include::example$javascript-udfs/execute-scoped-function.n1ql[]
----
====

For more information, see xref:n1ql:n1ql-language-reference/executefunction.adoc[].

== Calling a {sqlpp} User-Defined Function

The {sqlpp} user-defined function can be used in any {sqlpp} statement in exactly the same way as a standard built-in function.

To call a user-defined function in any {sqlpp} statement:

. Specify the name of the function:

* To call a function within the current query context, specify the function name alone.

* To call a global function, prefix the function name with the `default:` namespace.

* To call a scoped function, prefix the function name with the namespace, bucket, and scope, such as ``default:`travel-sample`.inventory``.

. Specify the function parameters within brackets.

=====
The following query calls the `GetBusinessDays` function from a `SELECT` statement.

[source.no-callouts, sqlpp]
----
include::example$javascript-udfs:select-true-alias-get-business-days.n1ql[]
----
=====

For more information and examples, see xref:n1ql:n1ql-language-reference/userfun.adoc[].

== Related Links

* 
* 