= Call a User-Defined Function
:description: How to call a user-defined function from {sqlpp} statements.
:page-pagination: prev
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2
:imagesdir: ../assets/images
:no-escape-hatch:

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

// tag::intro[]
A user-defined function can be called like any other {sqlpp} function.

* When you call a *global* function, any partial keyspace references within the function definition are resolved against the `default:` namespace, regardless of the current xref:n1ql:n1ql-intro/queriesandresults.adoc#query-context[query context].

* When you call a *scoped* function, any partial keyspace references within the function definition are resolved against the function's bucket and scope, regardless of the current xref:n1ql:n1ql-intro/queriesandresults.adoc#query-context[query context].

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

== Executing a {sqlpp} User-Defined Function

To execute a user-defined function:

. If required, xref:select.adoc#query-context[set the query context] for a scoped function, or unset the context for a global function.

. Use the `EXECUTE FUNCTION` statement and specify the name of the function:

* To execute a function within the current query context, specify the function name alone.

* To execute a global function outside of the current query context, prefix the function name with the `default:` namespace.

* To execute a scoped function outside of the current query context, prefix the function name with the namespace, bucket, and scope, such as ``default:`travel-sample`.inventory``.

. Specify the function parameters within brackets.

====
The following query executes a function called `GetBusinessDays`, which was created in the current query context.

[source, sqlpp]
----
include::javascript-udfs:example$:execute-javascript-function.n1ql[]
----
====

== Calling a {sqlpp} User-Defined Function

The {sqlpp} user-defined function can be used in any {sqlpp} statement in exactly the same way as a standard built-in function.

To call a user-defined function in any {sqlpp} statement:

. If required, xref:select.adoc#query-context[set the query context] for a scoped function, or unset the context for a global function.

. Specify the name of the function:

* To call a function within the current query context, specify the function name alone.

* To call a global function outside of the current query context, prefix the function name with the `default:` namespace.

* To call a scoped function outside of the current query context, prefix the function name with the namespace, bucket, and scope, such as ``default:`travel-sample`.inventory``.

. Specify the function parameters within brackets.

=====
The following query calls the `GetBusinessDays` function, which was created in the current query context, from a `SELECT` statement.

[source.no-callouts, sqlpp]
----
include::javascript-udfs:example$:select-true-alias-get-business-days.n1ql[]
----
=====

For more information and examples, see xref:n1ql:n1ql-language-reference/userfun.adoc[].

== Related Links

Reference:

* xref:javascript-udfs:javascript-functions-with-couchbase.adoc[]
* xref:n1ql:n1ql-language-reference/createfunction.adoc[]
* xref:n1ql:n1ql-language-reference/execfunction.adoc[]
* xref:n1ql:n1ql-language-reference/explainfunction.adoc[]
* xref:n1ql:n1ql-language-reference/dropfunction.adoc[]
* xref:n1ql:n1ql-language-reference/userfun.adoc[]

Administrator guides:

* xref:n1ql:n1ql-intro/sysinfo.adoc#sys-functions[Monitor Functions]
