= Create a User-Defined Function
:description: Create a user-defined function (UDF) to call an inline function or JavaScript code stored in a library. 
:page-pagination:
:page-topic-type: guide
:page-toclevels: 2
:keywords: N1QL, UDF, user-defined function, SQL++
:imagesdir: ../assets/images
:no-escape-hatch:

[abstract]
{description}

For more information about how to create a UDF library, see xref:create-javascript-library.adoc[]. 

== Prerequisites

* If you want to use cbq to create your user-defined function, you must complete the prerequisites for using cbq. 
For more information, see xref:n1ql:nq1l-intro/cbq.adoc#prerequisites[Prerequisites].
* If you want to use libraries to organize your user-defined functions, you need to create a UDF library and add a JavaScript function.
For more information, see xref:create-javascript-library.adoc[].

[#creating-the-n1ql-udf-function]
== Create a User-Defined Function From a UDF Library

To create a user-defined function that references a JavaScript function from a UDF library: 

* Use the Query Tab.
* Use the {sqlpp} xref:n1ql:n1ql-language-reference/createfunction.adoc[CREATE FUNCTION] statement, and reference the UDF library and JavaScript function.

[tabs]
====
Query Tab::
+
--
. On the *Operational Clusters* page, select the operational cluster where you want to create a user-defined function from a UDF library. 
. Go to menu:Data Tools[Query].

. In the Data Insights area, to the left of the query editor, find the *Functions* section. 
. Next to the *Functions* section header, click menu:Create (+)[Function].
. In the *Function Name* field, enter a name for your function.
. Choose the access level for your user-defined function: 
.. Choose *Global* to allow all buckets and scopes on this cluster to use this function.
.. Choose *Specific* to choose a specific bucket and scope on this cluster that can use this function.
+
TIP: Choose the same access level and namespace as your UDF library for your user-defined function.
Users must set this bucket and scope as their xref:n1ql:n1ql-intro/queriesandresults.adoc#query-context[query context] to use this function later.
. In the *Parameters* field, enter a list of parameters, separated by commas (,), for any values you need to process or use in your function. 
+
For example, if you created a JavaScript function that has a variable named `a`, you should add a parameter `a`.
+
TIP: If you want to create a user-defined function that can take a variable length list of parameters, rather than a comma separated list of parameters, add `...` as a parameter. 
Your function will accept an array of values as a parameter, and assign each value it receives to the named variables in your function. 
. Click the *UDF Library* tab.
. Choose the UDF library and specific JavaScript function you want to assign to this user-defined function. 
. Click btn:[Create Function].
--

{sqlpp}::
+
--
Execute a `CREATE FUNCTION` statement in cbq to create a user-defined function:

[source, sqlpp]
----
include::example$javascript-udfs/create-scoped-n1ql-udf.n1ql[]
----

TIP: Set the same namespace as your UDF library for your user-defined function.
Users must set this bucket and scope as their xref:n1ql:n1ql-intro/queriesandresults.adoc#query-context[query context] to use this function later.

For more information on the `CREATE FUNCTION` statement, see xref:n1ql:n1ql-language-reference/createfunction.adoc[CREATE FUNCTION].
--
====

[#create-inline]
== Create an Inline User-Defined Function 

To create a user-defined function that uses inline JavaScript or {sqlpp}: 

* Use the Query Tab.
* Use the {sqlpp} xref:n1ql:n1ql-language-reference/createfunction.adoc[CREATE FUNCTION] statement.

[tabs]
====
Query Tab::
+
--
. On the *Operational Clusters* page, select the operational cluster where you want to create a user-defined function. 
. Go to menu:Data Tools[Query].

. In the Data Insights area, to the left of the query editor, find the *Functions* section. 
. Next to the *Functions* section header, click menu:Create (+)[Function].
. In the *Function Name* field, enter a name for your function.
. Choose the access level for your user-defined function: 
.. Choose *Global* to allow all buckets and scopes on this cluster to use this function.
.. Choose *Specific* to choose a specific bucket and scope on this cluster that can use this function.
+
TIP: Users must set this bucket and scope as their xref:n1ql:n1ql-intro/queriesandresults.adoc#query-context[query context] to use this function later.
. In the *Parameters* field, enter a list of parameters, separated by commas (,), for any values you need to process or use in your function. 
+
For example, if you created a JavaScript function that has a variable named `a`, you should add a parameter `a`.
+
[TIP]
====
If you want to create a user-defined function that can take a variable length list of parameters, rather than a comma separated list of parameters, add `...` as a parameter. 
Your function will accept an array of values as a parameter, and assign each value it receives to the named variables in your function. 

You can also define your function with a variable length parameter list, by adding a variable to your function definition that starts with `...` - such as `... args`.
====
. Click the *Inline {sqlpp}* or *Inline JavaScript* tab.
. Enter a {sqlpp} expression or JavaScript function. 
. Click btn:[Create Function].
--

{sqlpp}::
+
--
Execute a `CREATE FUNCTION` statement in cbq to create an inline user-defined function:

.Inline JavaScript
[source,sqlpp]
----
CREATE FUNCTION celsius(...) LANGUAGE INLINE AS (args[0] - 32) * 5/9;
----

.Inline {sqlpp}
[source,sqlpp]
----
CREATE FUNCTION locations(vActivity) { (
  SELECT id, name, address, city
  FROM landmark
  WHERE activity = vActivity) };
----

For more information about the `CREATE FUNCTION` statement, see xref:n1ql:n1ql-language-reference/createfunction.adoc[CREATE FUNCTION].
--
====

== Next Steps

* To use your new user-defined function from {sqlpp}, see xref:call-user-defined-function.adoc[].
