= Create Documents
:description: How to create documents with a command line tool or an SDK.
:page-pagination: full
:page-topic-type: guide
:page-toclevels: 2
:github: Click the icon:github[] View button to see this code in context.

include::partial$example-attributes.adoc[]

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

Couchbase stores its xref:server:learn:data/data.adoc[data] as either JSON or Binary [.term]#documents# with unique IDs (primary keys) by which they can be located.

Documents are organized and grouped in [.term]#buckets# using xref:clusters:data-service/about-buckets-scopes-collections.adoc[scopes and collections].
If a scope or collection is not provided when creating a document, Couchbase will automatically store data in the `_default` collection or `_default` scope.

include::partial$clients.adoc[tag=refs]

include::partial$data-warning.adoc[]

== Inserting a Document

To create a single document, perform an insert operation.

[tabs]
====
Couchbase Shell::
+
--
. If necessary, use `cb-env` to set the bucket, scope, and collection in which to store the document.

. Create a structured JSON object containing your data.

. Use `doc insert` to create the document.

'''

{kv-insert-example}

[source,sh]
----
include::example$kv/kv-cbsh.nu[tag=cbsh-kv-insert]
----

`hotel-123` is the document's ID.

.Result
[source,console]
----
╭───┬───────────┬─────────┬────────┬──────────┬─────────╮
│ # │ processed │ success │ failed │ failures │ cluster │
├───┼───────────┼─────────┼────────┼──────────┼─────────┤
│ 0 │         1 │       1 │      0 │          │ capella │
╰───┴───────────┴─────────┴────────┴──────────┴─────────╯
----

NOTE: If the document already exists, Couchbase Shell returns a `Key already exists` error.

For further details, refer to {cbsh-api-url}/#_mutating[Mutating^] in the Couchbase Shell documentation.
--

pass:[.NET]::
+
--
. Create a structured document object containing your data.

. Use the `InsertAsync()` method to insert the document in a given keyspace.

A `MutationResult` object is returned containing the result and metadata relevant to the insert operation.

'''

{kv-insert-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-insert,indent=0]
----

NOTE: If the document already exists, the SDK returns a `DocumentExistsException` error.

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
. Create a structured document object containing your data.

. Use the `insert()` method to insert the document in a given keyspace.

A `MutationResult` object is returned containing the result and metadata relevant to the insert operation.

'''

{kv-insert-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-insert,indent=0]
----

NOTE: If the document already exists, the SDK returns a `DocumentExistsException` error.

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^].
--

Node.js::
+
--
. Create a structured document object containing your data.

. Use the `insert()` method to insert the document in a given keyspace.

A `MutationResult` promise is returned containing the result and metadata relevant to the insert operation.

'''

{kv-insert-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-insert,indent=0]
----

NOTE: If the document already exists, the SDK returns a `DocumentExistsError` error.

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
. Create a structured document object containing your data.

. Use the `insert()` function to insert the document in a given keyspace.

A `MutationResult` object is returned containing the result and metadata relevant to the insert operation.

'''

{kv-insert-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_hello_world_scoped.py[tag=kv-insert,indent=0]
----

NOTE: If the document already exists, the SDK returns a `DocumentExistsException` error.

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

When a document is created, Couchbase assigns it a xref:java-sdk:howtos:concurrent-document-mutations.adoc[CAS (Compare And Swap)] value to keep track of the document's state within the database.
Each time a document is mutated the CAS will change accordingly.
This unique value allows the database to protect against concurrent updates to the same document.

=== Inserting with Options

To specify further parameters for the inserted document, such as expiry, add the options to the insert operation.

[tabs]
====
Couchbase Shell::
+
--
. If necessary, use `cb-env` to set the bucket, scope, and collection in which to store the document.

. Create a structured JSON object containing your data.

. Use `doc insert` to create the document.

. Pass any required options, such as `--expiry`.

'''

{kv-insert-with-options-example}

[source,sh]
----
include::example$kv/kv-cbsh.nu[tag=cbsh-kv-insert-expiry]
----

.Result
[source,console]
----
╭───┬───────────┬─────────┬────────┬──────────┬─────────╮
│ # │ processed │ success │ failed │ failures │ cluster │
├───┼───────────┼─────────┼────────┼──────────┼─────────┤
│ 0 │         1 │       1 │      0 │          │ capella │
╰───┴───────────┴─────────┴────────┴──────────┴─────────╯
----

For further details, refer to {cbsh-api-url}/#_mutating[Mutating^] in the Couchbase Shell documentation.
--

pass:[.NET]::
+
--
. Create a structured document object containing your data.

. Use the `InsertAsync()` method to insert the document with a given option parameter.

'''

{kv-insert-with-options-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-insert-with-opts,indent=0]
----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
. Create a structured document object containing your data.

. Use the `insert()` method to insert the document with a given option parameter.

'''

{kv-insert-with-options-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-insert-with-opts,indent=0]
----

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^].
--

Node.js::
+
--
. Create a structured document object containing your data.

. Use the `insert()` function to insert the document with a given option parameter.

'''

{kv-insert-with-options-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-insert-with-opts,indent=0]
----

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
. Create a structured document object containing your data.

. Use the `insert()` function to insert the document with a given option parameter.

'''

{kv-insert-with-options-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_hello_world_scoped.py[tag=kv-insert-with-opts,indent=0]
----

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

== Related Links

Key-Value Operations with SDKs:

* xref:c-sdk:howtos:kv-operations.adoc[C]
| xref:dotnet-sdk:howtos:kv-operations.adoc[.NET]
| xref:go-sdk:howtos:kv-operations.adoc[Go]
| xref:java-sdk:howtos:kv-operations.adoc[Java]
| xref:nodejs-sdk:howtos:kv-operations.adoc[Node.js]
| xref:php-sdk:howtos:kv-operations.adoc[PHP]
| xref:python-sdk:howtos:kv-operations.adoc[Python]
| xref:ruby-sdk:howtos:kv-operations.adoc[Ruby]
| xref:scala-sdk:howtos:kv-operations.adoc[Scala]
