= Create a User-Defined Function Library
:description: Create an user-defined function (UDF) library to store and organize your JavaScript functions.
:page-pagination:
:page-topic-type: guide
:page-toclevels: 2
:imagesdir: ../assets/images
:no-escape-hatch:

[abstract]
{description}

To create a UDF library that you can use to xref:create-user-defined-function.adoc[]:

. <<creating-the-library-and-adding-your-first-function,>>
. <<add-functions-now,>>

Or, you can <<add-functions-later,>>. 

[#creating-the-library-and-adding-your-first-function]
== Create a User-Defined Function (UDF) Library

To create a new UDF library from the Query Tab:

. On the *Operational Clusters* page, select the operational cluster where you want to work with user-defined functions. 
. Go to menu:Data Tools[Query].
. In the Data Insights area, to the left of the query editor, find the *Functions* section. 
. Next to the *Functions* section header, go to menu:Create (+)[Library].
. In the *Library Name* field, enter a name for your new UDF library. 
. Choose the access level for your UDF library: 
.. Choose *Global* to allow all buckets and scopes on this cluster to use functions in this library.
.. Choose *Specific* to choose a specific bucket and scope on this cluster that can use this library.
+
Use this bucket and scope as the namespace for xref:create-user-defined-function.adoc[your user-defined function] to use this library and its functions later.
. (Optional) Add functions to your UDF library.
See <<add-functions-now,>>.
. Click btn:[Create].

[#add-functions-now]
== Add Functions to a New User-Defined Function (UDF) Library

To add functions to your new UDF library while you create your library: 

. Do one of the following: 
.. To manually define functions for your library, on the *Define Functions* tab, enter the code for each function. 
.. To import a `.js` file that contains function definitions, on the *Import Library* tab, drag and drop or choose your `.js` file.
+
TIP: Each function should have an assigned name and follow the https://en.wikipedia.org/wiki/ECMAScript[ECMAScript^] standard. 

[#add-functions-later]
== Add Functions to an Existing User-Defined Function (UDF) Library

To add or edit functions in an existing UDF library: 

. On the *Operational Clusters* page, select the operational cluster where you want to work with user-defined functions. 
. Go to menu:Data Tools[Query].
. In the Data Insights area, to the left of the query editor, find the *Functions* section. 
. Next to the user-defined library where you want to add a function, go to menu:More Options (&vellip;)[Edit].
. Do one of the following: 
.. To manually define functions for your library, on the *Create Functions* tab, enter or edit the code for each function. 
.. To import a `.js` file that contains function definitions, on the *Import Library* tab, drag and drop or choose your `.js` file.
+
TIP: Each function should have an assigned name and follow the https://en.wikipedia.org/wiki/ECMAScript[ECMAScript] standard.
. Click btn:[Update].

== Creating Functions with Variable Length Parameter Lists 

If you want to create a JavaScript function that can take a variable length list of parameters, rather than a fixed number of parameters: 

. Add a variable that starts with `...` to your function - such as `... args`.
. Define your user-defined function with a `...` parameter. 

You can then pass a variable length list of parameters from your user-defined function to your JavaScript function.

If you define your JavaScript function with all named variables but still want to use a variable length of parameters in your user-defined function: 

. Define your user-defined function with a `...` parameter.

Your user-defined function will accept an array of values as a parameter. 
The user-defined function assigns each value it receives to the named variables in your JavaScript function. 

For more information and examples, see xref:javascript-udfs:calling-javascript-from-n1ql.adoc#variadic-parameters[Variadic Parameters].

[#delete-udf]
== Delete a User-Defined Function (UDF) Library

To delete an existing UDF library: 

. On the *Operational Clusters* page, select the operational cluster where you want to delete a UDF library. 
. Go to menu:Data Tools[Query].
. In the Data Insights area, to the left of the query editor, find the *Functions* section. 
. Next to the user-defined library where you want to add a function, go to menu:More Options (&vellip;)[Delete].
. Confirm that you want to delete your UDF library. 
. Click btn:[Delete Library].

== Next Steps

To use your JavaScript functions from {sqlpp} after you have added them to a library, see xref:create-user-defined-function.adoc[]. 