= Creating a JavaScript Library
:description: How to create a JavaScript library to store and organize your JavaScript functions.
:page-pagination:
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2
:imagesdir: ../assets/images
:no-escape-hatch:

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

You can create an external library for storing JavaScript functions.
Creating a JavaScript library for your JavaScript functions is optional, but simplifies organization and access control for user-defined functions.

include::partial$before-you-begin.adoc[tag=body]

.A Note on Namespaces
[sidebar]
****
The `Namespace` defines the `scope` of the library within the containing bucket.
(You can read about scopes xref:tutorials:buckets-scopes-and-collections.adoc[here].)
Setting the namespace means that functions in the library can only be called users who have their context set to the same scope.
****


[#creating-the-library-and-adding-your-first-function]
== Creating a JavaScript Library and Adding JavaScript Code

When you create a JavaScript library, you can add JavaScript functions to the library at the same time.

You can create a JavaScript library with the Couchbase Web Console or a REST API call.

[tabs]
====
Couchbase Web Console::
+
--
To create a JavaScript library:

. In the Couchbase Web Console, go to menu:Query[UDF].

. Under *JavaScript Function Libraries*, click the *{plus}{nbsp}add function library* link.
The *Add Library* dialog is displayed.

. In the *Namespace* drop-down list, select *(global)* for a global library, or select a bucket and scope for a scoped library.

. In the *Library Name* box, enter a name for the library.

. Specify *Parameters* for the function.

. Edit the library to add your own JavaScript functions.

. Click btn:[Save].

'''

The following code adds a JavaScript function called `getBusinessDays`.

[source, javascript]
----
include::example$javascript-udfs/get-business-days.js[]
----

--

REST API::
+
--
To create a JavaScript library with the Query Functions REST API:

. Use the xref:n1ql-rest-functions:index.adoc#post_library[`POST /evaluator/v1/libraries/{library}`] endpoint.

. Pass the name of the library as a path parameter.

. To create a scoped library, pass the bucket and scope as query parameters.

. Pass a string containing the JavaScript code for all functions in the library as the request body.

'''

The following request creates a JavaScript library in the `inventory` scope within the `travel-sample` bucket.

[source, console]
----
include::example$javascript-udfs/create-scoped-javascript-function-with-rest.sh[]
----
--
====

When you have created an external library and added JavaScript code, you must create an {sqlpp} user-defined function to reference the JavaScript code in the library, so it can be called as part of any {sqlpp} statement.

[#add-functions-later]
== Updating an Existing JavaScript Library

You can add or edit functions in an existing JavaScript library with the Couchbase Web Console or a REST API call.

[tabs]
====
Couchbase Web Console::
+
--
To add or edit functions in an existing JavaScript library:

. In the Couchbase Web Console, go to menu:Query[UDF].

. FIXME: Under *JavaScript Function Libraries*, click the *{plus}{nbsp}add function library* link.
The *Add Library* dialog is displayed.

. In the *Namespace* drop-down list, select *(global)* for a global library, or select a bucket and scope for a scoped library.

. In the *Library Name* box, enter a name for the library.

. Specify *Parameters* for the function.

. Edit the library to add your own JavaScript functions.

. Click btn:[Save].
--

REST API::
+
--
To update an existing JavaScript library with the Query Functions REST API:

. Use the xref:n1ql-rest-functions:index.adoc#post_library[`POST /evaluator/v1/libraries/{library}`] endpoint.

. Pass the name of the library as a path parameter.

. To update a scoped library, pass the bucket and scope as query parameters.

. Pass a string containing the JavaScript code for all functions, including the added or edited functions, as the request body.
--
====

[#delete-udf]
== Deleting a JavaScript Library

Before you can delete a library, you must first drop all {sqlpp} user-defined functions which point to any of the JavaScript functions within that library.
For more information, see xref:n1ql:n1ql-language-reference/dropfunction.adoc[].

You can delete a JavaScript library with the Couchbase Web Console or a REST API call.

[tabs]
====
Couchbase Web Console::
+
--
To delete a JavaScript library:

. In the Couchbase Web Console, go to menu:Query[UDF].

. FIXME: Under *JavaScript Function Libraries*, click the *{plus}{nbsp}add function library* link.
The *Add Library* dialog is displayed.

. In the *Namespace* drop-down list, select *(global)* for a global library, or select a bucket and scope for a scoped library.

. In the *Library Name* box, enter a name for the library.

. Specify *Parameters* for the function.

. Edit the library to add your own JavaScript functions.

. Click btn:[Save].
--

REST API::
+
--
To delete a JavaScript library with the Query Functions REST API:

. Use the xref:n1ql-rest-functions:index.adoc#delete_library[`DELETE /evaluator/v1/libraries/{library}`] endpoint.

. Pass the name of the library as a path parameter.

. To delete a scoped library, pass the bucket and scope as query parameters.

'''

The following request deletes a JavaScript library in the `inventory` scope within the `travel-sample` bucket.

[source, console]
----
include::example$javascript-udfs/remove-library.sh[]
----
--
====

== Related Links


* xref:n1ql-rest-functions:index.adoc[]