= Create a JavaScript Library
:description: How to create a JavaScript library to store and organize your JavaScript functions.
:page-pagination:
:page-topic-type: guide
:page-toclevels: 2
:imagesdir: ../assets/images
:no-escape-hatch:

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

You can create a JavaScript library for storing JavaScript functions.
Creating a JavaScript library for your JavaScript functions is optional, but simplifies organization and access control for user-defined functions.

A JavaScript library can be *global* or *scoped*.

* A *global* library is created within the `default:` namespace, at the same level as the buckets in your database.
A global library is available to all clients.

* A *scoped* library is created within a scope, at the same level as the collections within the scope.
A scoped library is only available to clients that have access to that bucket and scope.
Use a scoped JavaScript library to keep the code for user-defined functions separate.

The name of a JavaScript library must be unique within the specified namespace or scope.

include::partial$before-you-begin.adoc[tag=body]

[#creating-the-library-and-adding-your-first-function]
== Creating a JavaScript Library and Adding JavaScript Code

When you create a JavaScript library, you can add JavaScript functions to the library at the same time.

To create a JavaScript library:

. On the *Operational Clusters* page, select the operational cluster where you want to work with user-defined functions.

. Go to menu:Data Tools[Query].

. In the Data Insights area, to the left of the query editor, find the *Functions* section.

. Next to the *Functions* section header, go to menu:Create (+)[Library].

. In the *Library Name* field, enter a name for your new JavaScript library.

. Choose the access level for your JavaScript library:

* Choose *Global* for a global library.

* Choose *Specific* and select a bucket and scope for a scoped library.

. (Optional) Add functions to your JavaScript library.

* To manually define functions for your library, on the *Define Functions* tab, enter the code for each function.

* To import a `.js` file that contains function definitions, on the *Import Library* tab, drag and drop or choose your `.js` file.

. Click btn:[Create].

====
The following library contains a JavaScript function called `getBusinessDays`.

[source.no-callouts, javascript]
----
include::javascript-udfs:example$get-business-days.js[]
----
====

After you create a JavaScript library and add JavaScript code, you must create a {sqlpp} user-defined function to reference the JavaScript code in the library, so it can be called as part of any {sqlpp} statement.

[#add-functions-later]
== Updating an Existing JavaScript Library

To add or edit functions in an existing JavaScript library:

. On the *Operational Clusters* page, select the operational cluster where you want to work with user-defined functions.

. Go to menu:Data Tools[Query].

. In the Data Insights area, to the left of the query editor, find the *Functions* section.

. Next to the user-defined library that you want to update, go to menu:More Options (&vellip;)[Edit].

. Update the library to add new JavaScript functions, edit existing JavaScript functions, or both.

* To manually define functions for your library, on the *Create Functions* tab, enter or edit the code for each function.

* To import a `.js` file that contains function definitions, on the *Import Library* tab, drag and drop or choose your `.js` file.

. Click btn:[Update].

====
The following library contains JavaScript functions called `getBusinessDays` and `sumListOfNumbers`.

[source.no-callouts, javascript]
----
include::javascript-udfs:example$get-business-days-variadic-sum.js[]
----
====

[#delete-udf]
== Deleting a JavaScript Library

Before you can delete a library, you must first drop all {sqlpp} user-defined functions which point to any of the JavaScript functions within that library.
For more information, see xref:n1ql:n1ql-language-reference/dropfunction.adoc[].

To delete a JavaScript library:

. On the *Operational Clusters* page, select the operational cluster where you want to delete a JavaScript library.

. Go to menu:Data Tools[Query].

. In the Data Insights area, to the left of the query editor, find the *Functions* section.

. Next to the JavaScript library that you want to delete, go to menu:More Options (&vellip;)[Delete].

. Confirm that you want to delete your JavaScript library.

. Click btn:[Delete Library].

== Related Links

Reference:

* xref:javascript-udfs:javascript-functions-with-couchbase.adoc[]