= Create a User-Defined Function
:description: How to create a user-defined function (UDF) to call an inline function or a JavaScript function.
:page-pagination:
:page-topic-type: guide
:page-toclevels: 2
:keywords: N1QL, UDF, user-defined function, SQL++
:imagesdir: ../assets/images
:no-escape-hatch:

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

include::partial$before-you-begin.adoc[tag=body]
include::partial$query-tools.adoc[tags=body;!thumbs]

=== Global and Scoped User-Defined Functions

A user-defined function can be *global* or *scoped*.

* A *global* user-defined function is created within the `default:` namespace, at the same level as the buckets in your database.
A global user-defined function is available to all clients.

* A *scoped* user-defined function is created within a scope, at the same level as the collections within the scope.
A scoped user-defined function is only available to clients that have access to that bucket and scope.

The name of a user-defined function must be unique within the specified namespace or scope.

=== User-Defined Function Parameters

When you create a user-defined function, you can specify a list of parameters for any values you need to process or use in your function.
If you want to create a user-defined function that can take a variable length list of parameters, you can create a *variadic* function.

[#create-inline]
== Creating an Inline User-Defined Function

To create a user-defined function that uses inline {sqlpp}, use the Query Tab or a {sqlpp} statement.

[tabs]
====
Query Tab::
+
--
To create an inline user-defined function:

. On the *Operational Clusters* page, select the operational cluster where you want to create a user-defined function. 

. Go to menu:Data Tools[Query].

. In the Data Insights area, to the left of the query editor, find the *Functions* section.

. Next to the *Functions* section header, go to menu:Create (+)[Function].

. In the *Function Name* field, enter a name for the user-defined function.

. Choose the access level for your user-defined function:

* Choose *Global* for a global function.

* Choose *Specific* and select a bucket and scope for a scoped function.

. In the *Parameters* field, enter a list of parameters separated by commas (`,`) or specify `\...` for a variadic function.

. Click the *Inline {sqlpp}* tab.

. Enter a {sqlpp} expression as the body of the function.

* If you specified named parameters for the user-defined function, use the same named parameters as identifiers in the {sqlpp} expression.

* If the user-defined function is variadic, any arguments are passed to the {sqlpp} expression in an array called `args`.

. Click btn:[Create Function].

--

{sqlpp}::
+
--
To create an inline user-defined function:

. If required, xref:select.adoc#query-context[set the query context] for a scoped function, or unset the context for a global function.

. Use the `CREATE FUNCTION` statement and specify a name for the function.

. Specify a list of parameter names separated by commas (`,`) or specify `\...` for a variadic function.

. Use the braces syntax `{}` or the `LANGUAGE INLINE AS` clause to specify a {sqlpp} expression as the body of the function.

* If you specified named parameters for the user-defined function, use the same named parameters as identifiers in the {sqlpp} expression.

* If the user-defined function is variadic, any arguments are passed to the {sqlpp} expression in an array called `args`.

'''

.Queries
The following query creates an inline {sqlpp} function in the current query context, using the braces syntax.

[source,sqlpp]
----
include::n1ql:example$udf/create-inline-params-braces.n1ql[]
----

The following query creates an inline {sqlpp} function in the current query context, using the `LANGUAGE INLINE` syntax.

[source,sqlpp]
----
include::n1ql:example$udf/create-inline-params-language.n1ql[]
----

For more information, see xref:n1ql:n1ql-language-reference/createfunction.adoc[].
--
====

[#create-sqlpp-managed-external-udf]
== Creating a User-Defined Function with {sqlpp} Managed JavaScript

To create a user-defined function that uses {sqlpp} managed JavaScript, use the Query Tab or a {sqlpp} statement.

[tabs]
====
Query Tab::
+
--
To create a user-defined function with {sqlpp} managed JavaScript:

. On the *Operational Clusters* page, select the operational cluster where you want to create a user-defined function. 

. Go to menu:Data Tools[Query].

. In the Data Insights area, to the left of the query editor, find the *Functions* section. 

. Next to the *Functions* section header, go to menu:Create (+)[Function].

. In the *Function Name* field, enter a name for the user-defined function.

. Choose the access level for your user-defined function:

* Choose *Global* for a global function.

* Choose *Specific* and select a bucket and scope for a scoped function.

. In the *Parameters* field, enter a list of parameters separated by commas (`,`) or specify `\...` for a variadic function.

. Click the *Inline JavaScript* tab.

. Enter a JavaScript function.
The JavaScript function must have the same name as the {sqlpp} user-defined function.

* If the user-defined function has named parameters, specify the same number of parameters for the JavaScript function.

* If the user-defined function is variadic, specify a rest parameter for the JavaScript function, such as `\... args`.

. Click btn:[Create Function].
--

{sqlpp}::
+
--
To create a user-defined function with {sqlpp} managed JavaScript:

. If required, xref:select.adoc#query-context[set the query context] for a scoped function, or unset the context for a global function.

. Use the `CREATE FUNCTION` statement and specify a name for the function.

. Specify a list of parameter names separated by commas (`,`) or specify `\...` for a variadic function.

. Use the `LANGUAGE JAVASCRIPT AS` clause to define a JavaScript function.
The JavaScript function must have the same name as the {sqlpp} user-defined function.

* If the user-defined function has named parameters, specify the same number of parameters for the JavaScript function.

* If the user-defined function is variadic, specify a rest parameter for the JavaScript function, such as `\... args`.

'''

.Queries
The following query creates a {sqlpp} managed JavaScript function in the current query context.

[source,sqlpp]
----
include::n1ql:example$udf/create-javascript-managed.n1ql[]
----

For more information, see xref:n1ql:n1ql-language-reference/createfunction.adoc[].
--
====

[#creating-the-n1ql-udf-function]
== Creating a User-Defined Function with a JavaScript Library

If you have created a JavaScript function in a JavaScript library (see xref:create-javascript-library.adoc[]), you must create a {sqlpp} user-defined function to reference it.

If the JavaScript library is scoped, create a scoped user-defined function in the same scope as the library.

To create a user-defined function that references a JavaScript library, use the Query Tab or a {sqlpp} statement.

[tabs]
====
Query Tab::
+
--
To create a user-defined function that references a JavaScript library:

. On the *Operational Clusters* page, select the operational cluster where you want to create a user-defined function.

. Go to menu:Data Tools[Query].

. In the Data Insights area, to the left of the query editor, find the *Functions* section. 

. Next to the *Functions* section header, go to menu:Create (+)[Function].

. In the *Function Name* field, enter a name for the user-defined function.

. Choose the access level for your user-defined function:

* Choose *Global* for a global function.

* Choose *Specific* to select a bucket and scope for a scoped function.

. In the *Parameters* field, enter a list of parameters separated by commas (`,`) or specify `\...` for a variadic function.

. Click the *UDF Library* tab.

. Choose the JavaScript library and the specific JavaScript function you want to assign to this user-defined function.

* If the user-defined function has named parameters, the JavaScript function should accept the same number of parameters.

* If the user-defined function is variadic, the JavaScript function should accept a rest parameter, such as `\... args`.

. Click btn:[Create Function].
--

{sqlpp}::
+
--
To create a user-defined function that references a JavaScript library:

. If required, xref:select.adoc#query-context[set the query context] for a scoped function, or unset the context for a global function.

. Use the `CREATE FUNCTION` statement and specify a name for the function.

. Specify a list of parameter names separated by commas (`,`) or specify `\...` for a variadic function.

. Use the `LANGUAGE JAVASCRIPT AS` clause to specify the name of the JavaScript function.

* If the user-defined function has named parameters, the JavaScript function should accept the same number of parameters.

* If the user-defined function is variadic, the JavaScript function should accept a rest parameter, such as `\... args`.

. Use the `AT` keyword to specify the library which contains the JavaScript function.

'''

.Queries
The following query creates a user-defined function within the current query context that references a global JavaScript library.

[source.no-callouts, sqlpp]
----
include::javascript-udfs:example$create-globally-scoped-n1ql-udf.n1ql[]
----

The following query creates a user-defined function within the current query context that references a scoped JavaScript library in the same query context.

[source.no-callouts, sqlpp]
----
include::javascript-udfs:example$create-relatively-scoped-n1ql-udf.n1ql[]
----

For more information, see xref:n1ql:n1ql-language-reference/createfunction.adoc[].
--
====

== Related Links

Reference:

* xref:javascript-udfs:javascript-functions-with-couchbase.adoc[]
* xref:n1ql:n1ql-language-reference/createfunction.adoc[]
* xref:n1ql:n1ql-language-reference/execfunction.adoc[]
* xref:n1ql:n1ql-language-reference/explainfunction.adoc[]
* xref:n1ql:n1ql-language-reference/dropfunction.adoc[]
* xref:n1ql:n1ql-language-reference/userfun.adoc[] -- using user-defined functions (UDFs) in {sqlpp} statements

Administrator guides:

* xref:n1ql:n1ql-intro/sysinfo.adoc#sys-functions[Monitor Functions]
