= Delete Documents
:description: How to delete documents with a command line tool or an SDK.
:page-pagination: full
:page-topic-type: guide
:github: Click the icon:github[] View button to see this code in context.

include::partial$example-attributes.adoc[]

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

In situations where data is no longer needed, Couchbase Capella provides a remove operation to delete a document from the database permanently.

include::partial$clients.adoc[tag=refs]

include::partial$data-warning.adoc[]

== Deleting a Document

To delete a document, perform a remove operation.

[tabs]
====
cbsh::
+
--
Use the `doc remove` command to delete a document from the database.

'''

{kv-delete-example}

[source,sh]
----
include::example$kv/kv-cbsh.nu[tag=cbsh-kv-delete]
----

.Result
[source,console]
----
╭───┬───────────┬─────────┬────────┬──────────┬─────────╮
│ # │ processed │ success │ failed │ failures │ cluster │
├───┼───────────┼─────────┼────────┼──────────┼─────────┤
│ 0 │         1 │       1 │      0 │          │ capella │
╰───┴───────────┴─────────┴────────┴──────────┴─────────╯
----

For further details, refer to {cbsh-api-url}/#_removing[Removing^] in the Couchbase Shell documentation.
--

pass:[.NET]::
+
--
Use the `RemoveAsync()` method to delete a document from the database.

'''

{kv-delete-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-remove,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
Use the `remove()` method to delete a document from the database.

'''

{kv-delete-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-remove,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^].
--

Node.js::
+
--
Use the `remove()` function to delete a document from the database.

'''

{kv-delete-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-remove,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundError` error.

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
Use the `remove()` function to delete a document from the database.

'''

{kv-delete-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_hello_world_scoped.py[tag=kv-remove,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

== Deleting a Sub-Document

To delete a specific field within a document you can perform a sub-document remove operation.

[tabs]
====
cbsh::
+
--
. Use the `doc get` command to retrieve a document by ID.

. Pipe the document through the `reject` filter to remove the field containing the sub-document.

. Pipe the output, including the `id` and `content` fields, through the `doc replace` command to update the document.

'''

{kv-subdoc-delete-example}

[source,sh]
----
include::example$kv/kv-subdoc.nu[tag=cbsh-subdoc-reject]
----

.Result
[source,console]
----
╭───┬───────────┬─────────┬────────┬──────────┬─────────╮
│ # │ processed │ success │ failed │ failures │ cluster │
├───┼───────────┼─────────┼────────┼──────────┼─────────┤
│ 0 │         1 │       1 │      0 │          │ capella │
╰───┴───────────┴─────────┴────────┴──────────┴─────────╯
----

NOTE: If the field containing the sub-document cannot be found, the `reject` command returns a `Cannot find column` error.

For further details, refer to {nushell-api-url}/reject.html[reject for filters^] in the Nushell documentation.
--

pass:[.NET]::
+
--
. Call the `MutateInAsync()` method, which takes a document ID and an IEnumerable containing `MutateInSpec` objects.

. Use a `MutateInSpec` object to specify the sub-operation to be performed within the lookup.

A `MutateInResult` object is returned containing the result and metadata relevant to the sub-document remove operation.

'''

{kv-subdoc-delete-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-remove-subdoc,indent=0]
----

NOTE: If the path doesn't exist, the SDK will return a `PathNotFoundException` error.

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
. Call the `mutateIn()` method, which takes a document ID and an array of `MutateInSpec` objects.

. Use a `MutateInSpec` object to specify the sub-operation to be performed within the lookup.

A `MutateInResult` object is returned, containing the result and metadata relevant to the sub-document remove operation.

'''

{kv-subdoc-delete-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-remove-subdoc,indent=0]
----

NOTE: If the path doesn't exist, the SDK will return a `PathNotFoundException` error.

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^].
--

Node.js::
+
--
. Call the `mutateIn()` method, which takes a document ID and an array of `MutateInSpec` objects.

. Use a `MutateInSpec` object to specify the sub-operation to be performed within the lookup.

A `MutateInResult` object is returned, containing the result and metadata relevant to the sub-document remove operation.

'''

{kv-subdoc-delete-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-remove-subdoc,indent=0]
----

NOTE: If the path doesn't exist, the SDK will return a `PathNotFoundError` error.

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
. Call the `lookup_in()` function, which takes a document ID and a list of `MutateInSpec` objects.

. Use a `MutateInSpec` object to specify the sub-operation to be performed within the lookup.

A `MutateInResult` object is returned, containing the result and metadata relevant to the sub-document remove operation.

'''

{kv-subdoc-delete-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_hello_world_scoped.py[tag=kv-remove-subdoc,indent=0]
----

NOTE: If the path doesn't exist, the SDK will return a `PathNotFoundException` error.

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

== Related Links

Key-Value Operations with SDKs:

* xref:c-sdk:howtos:kv-operations.adoc[C]
| xref:dotnet-sdk:howtos:kv-operations.adoc[.NET]
| xref:go-sdk:howtos:kv-operations.adoc[Go]
| xref:java-sdk:howtos:kv-operations.adoc[Java]
| xref:nodejs-sdk:howtos:kv-operations.adoc[Node.js]
| xref:php-sdk:howtos:kv-operations.adoc[PHP]
| xref:python-sdk:howtos:kv-operations.adoc[Python]
| xref:ruby-sdk:howtos:kv-operations.adoc[Ruby]
| xref:scala-sdk:howtos:kv-operations.adoc[Scala]

Sub-Document operations with SDKs:

* xref:c-sdk:howtos:subdocument-operations.adoc[C]
| xref:dotnet-sdk:howtos:subdocument-operations.adoc[.NET]
| xref:go-sdk:howtos:subdocument-operations.adoc[Go]
| xref:java-sdk:howtos:subdocument-operations.adoc[Java]
| xref:nodejs-sdk:howtos:subdocument-operations.adoc[Node.js]
| xref:php-sdk:howtos:subdocument-operations.adoc[PHP]
| xref:python-sdk:howtos:subdocument-operations.adoc[Python]
| xref:ruby-sdk:howtos:subdocument-operations.adoc[Ruby]
| xref:scala-sdk:howtos:subdocument-operations.adoc[Scala]
