= User-Defined Functions for Queries
:navtitle: User-Defined Functions
:description: How to extend the {sqlpp} query language by adding your own user-defined functions.
:page-pagination: next
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2
:xrefstyle: short
:no-escape-hatch:

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

{sqlpp} includes built-in operations and functions for data manipulation.
User-defined functions enable you to create your own extensions to the language.

With user-defined functions, you can:

* Create reusable, domain-specific functions for use in your applications.
* Execute complex logic that may be difficult to do in {sqlpp}.
* Migrate from Relational Database Management System (RDBMS) stored procedures.

== User-Defined Functions in Couchbase Server

You can create 3 types of user-defined functions.
User-defined functions can be categorized based on the language used to define them, and the location where the function definitions are stored.

[cols="2,1,1", options="header"]
|===
| Type | Language | Stored

| <<inline-functions>>
| {sqlpp}
| Internally

| <<sqlpp-managed-javascript-functions>>
| JavaScript
| Internally

| <<library-functions>>
| JavaScript
| In JavaScript libraries
|===

User-defined functions written in JavaScript support the https://en.wikipedia.org/wiki/ECMAScript[ECMAScript^] standard, with some restrictions and extensions.
For more information, see xref:javascript-udfs:javascript-functions-with-couchbase.adoc[].

After you have created your user-defined functions, you can call them like any other {sqlpp} function.
For more information, see xref:call-user-defined-function.adoc[].

[#inline-functions]
=== Inline {sqlpp} Functions

An inline {sqlpp} function is a user-defined function that executes a {sqlpp} expression.
The {sqlpp} expression is stored internally by the Query Service.

For more information, see xref:create-user-defined-function.adoc#create-inline[Create an Inline User-Defined Function].

[#sqlpp-managed-javascript-functions]
=== {sqlpp} Managed JavaScript Functions

A {sqlpp} managed JavaScript function is a user-defined function that executes a JavaScript function.
The JavaScript function is stored internally by the Query Service.
You do not need to create a JavaScript library to create and use {sqlpp} managed JavaScript functions.

If you create a user-defined function this way, you cannot group related functions or change access restrictions for multiple related functions at once. 

For more information, see xref:create-user-defined-function.adoc#create-sqlpp-managed-external-udf[Creating a User-Defined Function with {sqlpp} Managed JavaScript].

[#library-functions]
=== JavaScript Library Functions

A JavaScript library function is a user-defined function that executes a JavaScript function.
The JavaScript function is stored in a JavaScript library.

A JavaScript library is a collection of JavaScript functions.
JavaScript libraries keep your JavaScript functions organized and allow you to set access controls across multiple functions at once.

To create an external library function, you must first create a JavaScript library and add JavaScript functions to that library.
For more information, see xref:create-javascript-library.adoc[].

After you have created a JavaScript library, you must create user-defined functions to use the JavaScript functions in that library.
The user-defined function creates a link between the JavaScript function in your library and {sqlpp}, letting you call your JavaScript code.
For more information, see xref:create-user-defined-function.adoc#creating-the-n1ql-udf-function[Creating a User-Defined Function with a JavaScript Library].

== Next Steps

User-defined function guides:
 
* xref:create-javascript-library.adoc[]
* xref:create-user-defined-function.adoc[]
* xref:call-user-defined-function.adoc[]