= User-Defined Functions with JavaScript
:description: Couchbase Capella lets you extend the {sqlpp} query language by adding your own functions written in JavaScript.
:page-pagination: next
:page-topic-type: guide
:page-toclevels: 2
:xrefstyle: short
:no-escape-hatch:

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

On its own, {sqlpp} includes built-in operations and functions for data manipulation.
You can use user-defined functions to create your own extensions to the language.

With user-defined functions, you can:

* Create reusable, domain-specific functions for use in your applications.
* Execute complex logic that may be difficult to do in {sqlpp}.
* Migrate from Relational Database Management System (RDBMS) stored procedures.

Couchbase Capella's user-defined functions are defined with JavaScript, specifically the https://en.wikipedia.org/wiki/ECMAScript[ECMAScript^] standard, with some restrictions and extensions.
For more information, see xref:javascript-udfs:javascript-functions-with-couchbase.adoc[].

== Using User-Defined Functions in Capella

You cannot call JavaScript code directly from a {sqlpp} query.
You must create a user-defined function to call JavaScript code in your queries. 

You can create 2 types of user-defined functions: 

* <<inline-functions,Inline {sqlpp} or JavaScript functions>>.
* <<library-functions,User-defined function (UDF) library functions>>.

Creating a UDF library for your JavaScript functions is optional, but simplifies organization and access control for user-defined functions. 

After you have created your user-defined functions, you can xref:call-user-defined-function.adoc[] like any other {sqlpp} function. 

[#inline-functions]
=== Inline Functions 

You can create a user-defined function that executes inline {sqlpp} commands or inline JavaScript. 

If you create a user-defined function this way, you cannot group related functions or change cluster access restrictions for multiple related functions at once. 

You do not need to create a UDF library before you can create and use inline functions.

For more information about how to create inline functions, see xref:create-user-defined-function.adoc#create-inline[Create an Inline User-Defined Function].

[#library-functions]
=== Functions From User-Defined Function (UDF) Libraries 

A UDF library is a collection of JavaScript functions. 
Libraries keep your JavaScript functions organized and allow you to set access controls across multiple functions at once.

You can define functions xref:create-javascript-library.adoc#add-functions-now[while creating a library] or xref:create-javascript-library.adoc#add-functions-later[add them to an existing library].

After you have xref:create-javascript-library.adoc[created a UDF library], you must xref:create-user-defined-function.adoc[create user-defined functions] to use the JavaScript functions in that library. 

The user-defined function creates a link between the JavaScript function in your library and {sqlpp}, letting you call your JavaScript code.

== Next Steps

* To get started with a UDF library, see xref:create-javascript-library.adoc[].
* To create inline functions, see xref:create-user-defined-function.adoc[].
* To start using your functions in the Query Tab, see xref:call-user-defined-function.adoc[]. 

For more information about the specifics of JavaScript for user-defined functions in Capella, see:

* xref:javascript-udfs:javascript-functions-with-couchbase.adoc[]
* xref:javascript-udfs:calling-javascript-from-n1ql.adoc[]
* xref:javascript-udfs:calling-n1ql-from-javascript.adoc[]
* xref:javascript-udfs:handling-errors-javascript-udf.adoc[]
