= User-Defined Functions with JavaScript
:description: How to extend the {sqlpp} query language by adding your own functions written in JavaScript.
:page-pagination: next
:page-edition: Enterprise Edition
:page-topic-type: guide
:page-toclevels: 2
:xrefstyle: short
:no-escape-hatch:

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

{sqlpp} includes a large number of built-in operations and functions that cover every aspect of data manipulation.
User-defined functions enable you to create your own extensions to the language.

Using user-defined functions, you can:

* Create reuseable, domain-specific functions for use in your applications.
* Execute complex logic that may be difficult to do in {sqlpp}.
* Migrate from RDBMS stored procedures.

== User-Defined Functions with JavaScript

JavaScript supported in Couchbase shares the same constructs of the https://en.wikipedia.org/wiki/ECMAScript[ECMAScript]. However, you should be aware of the restrictions and extensions that come with the Couchbase implementation.
These are covered in xref:javascript-udfs:javascript-functions-with-couchbase.adoc[]

== Next Steps

If you're looking to create your own JavaScript libraries, then there are a number of guides to get you started.
 
* xref:create-javascript-library.adoc[]
* xref:call-user-defined-function.adoc[]

If you wish to look into the constructs and available in the language itself, then you can have a look through the following pages:

* xref:javascript-udfs:javascript-functions-with-couchbase.adoc[]
* xref:javascript-udfs:calling-javascript-from-n1ql.adoc[]
* xref:javascript-udfs:calling-n1ql-from-javascript.adoc[]
* xref:javascript-udfs:handling-errors-javascript-udf.adoc[]
