= Read Documents
:description: How to read documents with a command line tool or an SDK.
:page-pagination: full
:page-topic-type: guide
:page-toclevels: 2
:github: Click the icon:github[] View button to see this code in context.

include::partial$example-attributes.adoc[]

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

Retrieving documents by ID is the fastest and simplest way to read xref:server:learn:data/data.adoc[data] in Couchbase Capella.
The xref:clusters:data-service/data-service.adoc[Key-Value (KV) or Data Service] allows you to retrieve a full document when you need to fetch all of the data stored.
However, in instances where this can be costly and unnecessary, Couchbase also provides access to specific [.term]#paths# within a document.

include::partial$clients.adoc[tag=refs]

include::partial$data-warning.adoc[]

== Reading a Document

To read a single document, perform a get operation.

[tabs]
====
cbsh::
+
--
Use the `doc get` command to retrieve a document by ID and output its data.

An object is returned, which includes the `id`, `content`, and other metadata.
The document itself is wrapped in the `content` field.

'''

{kv-get-example}

[source,sh]
----
include::example$kv/kv-cbsh.nu[tag=cbsh-kv-get]
----

.Result
[source,console]
----
╭───┬───────────┬────────────────────┬─────────────────────┬───────┬─────────╮
│ # │    id     │      content       │         cas         │ error │ cluster │
├───┼───────────┼────────────────────┼─────────────────────┼───────┼─────────┤
│ 0 │ hotel-123 │ {record 11 fields} │ 1717190781443309568 │       │ capella │
╰───┴───────────┴────────────────────┴─────────────────────┴───────┴─────────╯
----

NOTE: If the document cannot be found, Couchbase Shell returns a `Key not found` error.

For further details, refer to {cbsh-api-url}/#_reading[Reading^] in the Couchbase Shell documentation.
--

pass:[.NET]::
+
--
Use the `GetAsync()` method to retrieve a document by ID.

A `GetResult` object is returned, which includes the `content`, `cas` value, and other valuable metadata.

'''

{kv-get-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-get,indent=0]
----

NOTE: If the document doesn't exist, the SDK returns a `DocumentNotFoundException` error.

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
Use the `get()` method to retrieve a document by ID.

A `GetResult` object is returned, which includes the `content`, `cas` value, and other valuable metadata.

'''

{kv-get-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-get,indent=0]
----

NOTE: If the document doesn't exist, the SDK returns a `DocumentNotFoundException` error.

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^].
--

Node.js::
+
--
Use the `get()` function to retrieve a document by ID.

A `GetResult` promise is returned, which includes the `content`, `cas` value, and other valuable metadata.

'''

{kv-get-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-get,indent=0]
----

NOTE: If the document doesn't exist, the SDK returns a `DocumentNotFoundError` error.

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
Use the `get()` function to retrieve a document by ID.

A `GetResult` object is returned, which includes the `content`, `cas` value, and other valuable metadata.

'''

{kv-get-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_hello_world_scoped.py[tag=kv-get,indent=0]
----

NOTE: If the document doesn't exist, the SDK returns a `DocumentNotFoundException` error.

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

=== Reading with Options

To specify further parameters, add options to the get operation.

[tabs]
====
cbsh::
+
--
Use the `doc get` command to retrieve a document by ID and pass options as required.

'''

The example below pipes the `hotel-123` document and its metadata through the `to json` filter to transform the output to JSON.

[source,sh]
----
include::example$kv/kv-cbsh.nu[tag=cbsh-kv-get-with-opts]
----

.Result
[source,json]
----
[
  {
    "id": "hotel-123",
    "content":
    {
      "address": "Capstone Road, ME7 3JE",
      "city": "Medway",
      "country": "United Kingdom",
      "description": "40 bed summer hostel about 3 miles from Gillingham.",
      "geo":
      {
        "accuracy": "RANGE_INTERPOLATED",
        "lat": 51.35785,
        "lon": 0.55818
      },
      "id": 123,
      "name": "Medway Youth Hostel",
      "reviews":
      [
        {
          "author": "Ozella Sipes",
          "content": "This was our 2nd trip here and we enjoyed it more than last year.",
          "date": "2021-11-17T17:35:05.351Z"
        }
      ],
      "state": null,
      "url": "http://www.yha.org.uk",
      "vacancy": true
    },
    "cas": 1717190781443309568,
    "error": "",
    "cluster": "capella"
  }
]
----

For further details, refer to {cbsh-api-url}/#_reading[Reading^] in the Couchbase Shell documentation.
--

pass:[.NET]::
+
--
Pass any required options to the `GetAsync()` method when retrieving a document.

A `GetResult` object is returned, which may include extra metadata, depending on the options passed.

'''

{kv-get-example-with-options}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-get-with-opts,indent=0]
----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
Pass any required options to the `get()` method when retrieving a document.

A `GetResult` object is returned, which may include extra metadata, depending on the options passed.

'''

{kv-get-example-with-options}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-get-with-opts,indent=0]
----

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^].
--

Node.js::
+
--
Pass any required options to the `get()` method when retrieving a document.

A `GetResult` object is returned, which may include extra metadata, depending on the options passed.

'''

{kv-get-example-with-options}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-get-with-opts,indent=0]
----

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
Pass any required options to the `get()` method when retrieving a document.

A `GetResult` object is returned, which may include extra metadata, depending on the options passed.

'''

{kv-get-example-with-options}

[source,python]
----
include::python-sdk:devguide:example$python/kv_hello_world_scoped.py[tag=kv-get-with-opts,indent=0]
----

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====


== Reading a Sub-Document

JSON documents can contain a lot of nested data -- which might not necessarily need to be accessed all at once.
For example, the document `airport_1254` contains a sub-document called `geo`.

.airport_1254
[source,json]
----
{
  "id": 1254,
//  ...
  "geo": {
    "lat": 50.962097,
    "lon": 1.954764,
    "alt": 12
  }
}
----

Reading full documents to access a field or two is not ideal and could cause performance issues in your application.
Instead, a better practice would be to access specific paths, or [.term]#sub-documents#, to perform more efficient read operations.
To fetch a specific field inside a document, you can perform a sub-document get operation.

[tabs]
====
cbsh::
+
--
. Use the `doc get` command to retrieve a document by ID.

. Pipe the document through the `get` filter and specify the path to the field containing the sub-document.

'''

{kv-subdoc-get-example}

[source,sh]
----
include::example$kv/kv-subdoc.nu[tag=cbsh-subdoc-get]
----

.Result
[source,console]
----
╭───┬────────────────────┬─────────┬────────╮
│ # │      accuracy      │   lat   │  lon   │
├───┼────────────────────┼─────────┼────────┤
│ 0 │ RANGE_INTERPOLATED │ 51.3578 │ 0.5582 │
╰───┴────────────────────┴─────────┴────────╯
----

NOTE: If the field containing the sub-document cannot be found, the `get` command returns a `Cannot find column` error.

For further details, refer to {nushell-api-url}/get.html[get for filters^] in the Nushell documentation.
--

pass:[.NET]::
+
--
. Call the `LookupInAsync()` method, which takes a document ID and an IEnumerable containing `LookUpInSpec` objects.

. Use the `LookUpInSpec` object to specify the sub-operation to be performed within the lookup.

A `LookupInResult` object is returned, containing the result and metadata relevant to the sub-document get operation.

'''

{kv-subdoc-get-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-get-subdoc,indent=0]
----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
. Call the `lookupIn()` method, which takes a document ID and an array of `LookUpInSpec` objects.

. Use the `LookUpInSpec` object to specify the sub-operation to be performed within the lookup.

A `LookupInResult` object is returned, containing the result and metadata relevant to the sub-document get operation.

'''

{kv-subdoc-get-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-get-subdoc,indent=0]
----

NOTE: If the document path can't be found, the SDK returns a `PathNotFoundException` error.

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^].
--

Node.js::
+
--
. Call the `lookupIn()` function, which takes a document ID and an array of `LookUpInSpec` objects.

. Use the `LookUpInSpec` object to specify the sub-operation to be performed within the lookup.

A `LookupInResult` promise is returned containing the result and metadata relevant to the sub-document get operation.

'''

{kv-subdoc-get-example}

[source,nodejs,indent=0]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-get-subdoc]
----

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
. Call the `lookup_in()` function, which takes a document ID and a list of `LookUpInSpec` objects.

. Use the `LookUpInSpec` object to represent the sub-operation to be performed within the lookup.

A `LookupInResult` object is returned containing the result and metadata relevant to the sub-document get operation.

'''

{kv-subdoc-get-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_hello_world_scoped.py[tag=kv-get-subdoc,indent=0]
----

NOTE: If the document path can't be found, the SDK returns a `PathNotFoundException` error.

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

== Related Links

Key-Value Operations with SDKs:

* xref:c-sdk:howtos:kv-operations.adoc[C]
| xref:dotnet-sdk:howtos:kv-operations.adoc[.NET]
| xref:go-sdk:howtos:kv-operations.adoc[Go]
| xref:java-sdk:howtos:kv-operations.adoc[Java]
| xref:nodejs-sdk:howtos:kv-operations.adoc[Node.js]
| xref:php-sdk:howtos:kv-operations.adoc[PHP]
| xref:python-sdk:howtos:kv-operations.adoc[Python]
| xref:ruby-sdk:howtos:kv-operations.adoc[Ruby]
| xref:scala-sdk:howtos:kv-operations.adoc[Scala]

Sub-Document operations with SDKs:

* xref:c-sdk:howtos:subdocument-operations.adoc[C]
| xref:dotnet-sdk:howtos:subdocument-operations.adoc[.NET]
| xref:go-sdk:howtos:subdocument-operations.adoc[Go]
| xref:java-sdk:howtos:subdocument-operations.adoc[Java]
| xref:nodejs-sdk:howtos:subdocument-operations.adoc[Node.js]
| xref:php-sdk:howtos:subdocument-operations.adoc[PHP]
| xref:python-sdk:howtos:subdocument-operations.adoc[Python]
| xref:ruby-sdk:howtos:subdocument-operations.adoc[Ruby]
| xref:scala-sdk:howtos:subdocument-operations.adoc[Scala]
