= Update Documents
:description: How to update documents with a command line tool or an SDK.
:page-pagination: full
:page-topic-type: guide
:github: Click the icon:github[] View button to see this code in context.

include::partial$example-attributes.adoc[]

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

== Introduction

Couchbase Capella allows you to update data within a document by ID using either an upsert or a replace operation.
An upsert operation will update or create a full document with the given data.
A replace operation, on the other hand, will only replace a document if it exists within the database.

include::partial$clients.adoc[tag=refs]

include::partial$data-warning.adoc[]

== Upserting a Document

To update a document, or create the document if it doesn't exist, perform an upsert operation.

[tabs]
====
cbsh::
+
--
. If you haven't already done so, use `cb-env` to set the bucket, scope, and collection where the document is stored.

. Create a structured JSON object containing the updated data.

. Use `doc upsert` to update the document.

If the document doesn't exist, Couchbase Capella creates a new document.

'''

{kv-update-upsert-example}

[source,sh]
----
include::example$kv/kv-cbsh.nu[tag=cbsh-kv-upsert]
----

.Result
[source,console]
----
╭───┬───────────┬─────────┬────────┬──────────┬─────────╮
│ # │ processed │ success │ failed │ failures │ cluster │
├───┼───────────┼─────────┼────────┼──────────┼─────────┤
│ 0 │         1 │       1 │      0 │          │ capella │
╰───┴───────────┴─────────┴────────┴──────────┴─────────╯
----

For further details, refer to {cbsh-api-url}/#_mutating[Mutating^] in the Couchbase Shell documentation.
--

pass:[.NET]::
+
--
Use the `UpsertAsync()` method to update a document in the database.
If it doesn't exist, Couchbase Capella creates a new document.

'''

{kv-update-upsert-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-update-upsert,indent=0]
----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
Use the `upsert()` method to update a document in the database.
If it doesn't exist, Couchbase Capella creates a new document.

'''

{kv-update-upsert-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-update-upsert,indent=0]
----

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^].
--

Node.js::
+
--
Use the `upsert()` function to update a document in the database.
If it doesn't exist, Couchbase Capella creates a new document.

'''

{kv-update-upsert-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-update-upsert,indent=0]
----

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
Use the `upsert()` function to update a document in the database.
If it doesn't exist, Couchbase Capella creates a new document.

'''

{kv-update-upsert-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_hello_world_scoped.py[tag=kv-update-upsert,indent=0]
----

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

== Replacing a Document

To update a document that already exists, perform a replace operation.

[tabs]
====
cbsh::
+
--
. If you haven't already done so, use `cb-env` to set the bucket, scope, and collection where the document is stored.

. Create a structured JSON object containing the new data.

. Use `doc replace` to update the document.

'''

{kv-update-replace-example}

[source,sh]
----
include::example$kv/kv-cbsh.nu[tag=cbsh-kv-replace]
----

.Result
[source,console]
----
╭───┬───────────┬─────────┬────────┬──────────┬─────────╮
│ # │ processed │ success │ failed │ failures │ cluster │
├───┼───────────┼─────────┼────────┼──────────┼─────────┤
│ 0 │         1 │       1 │      0 │          │ capella │
╰───┴───────────┴─────────┴────────┴──────────┴─────────╯
----

NOTE: If the document cannot be found, Couchbase Shell returns a `Key not found` error.

For further details, refer to {cbsh-api-url}/#_mutating[Mutating^] in the Couchbase Shell documentation.
--

pass:[.NET]::
+
--
. Fetch an existing document and change some of its data.

. Use the `ReplaceAsync()` function to update a document in Couchbase.
  To ensure data has not been modified before executing the replace operation, pass the document's `CAS` value to the method.

A new `CAS` value is provided in the returned `MutationResult` object.

'''

{kv-update-replace-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-update-replace,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
. Fetch an existing document and change some of its data.

. Use the `replace()` method to update a document in Couchbase.
  To ensure data has not been modified before executing the replace operation, pass the document's `CAS` value to the method.

A new `CAS` value is provided in the returned `MutationResult` object.

'''

{kv-update-replace-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-update-replace,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^].
--

Node.js::
+
--
. Fetch an existing document and change some of its data.

. Use the `replace()` function to update a document in Couchbase.
  To ensure data has not been modified before executing the replace operation, pass the document's `CAS` value to the method.

A new `CAS` value is provided in the returned `MutationResult` object.

'''

{kv-update-replace-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-update-replace,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundError` error.

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
. Fetch an existing document and change some of its data.

. Use the `replace()` function to update a document in Couchbase.
  To ensure data has not been modified before executing the replace operation, pass the document's `CAS` value to the method.

A new `CAS` value is provided in the returned `MutationResult` object.

'''

{kv-update-replace-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_hello_world_scoped.py[tag=kv-update-replace,indent=0]
----

NOTE: If the document doesn't exist, the SDK will return a `DocumentNotFoundException` error.

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====


== Updating a Sub-Document

To change a specific field inside a document, you can perform a sub-document operation.
You can use either a sub-document upsert or replace operation depending on what is required for your application.

[tabs]
====
cbsh::
+
--
. If you haven't already done so, use `cb-env` to set the bucket, scope, and collection where the document is stored.

. Use the `doc get` command to retrieve a document by ID.

. Pipe the document through the `upsert` filter to update or add the field containing the sub-document, or use the `update` filter if you require the field to exist.

. Pipe the output, including the `id` and `content` fields, through the `doc replace` command to update the document.

'''

{kv-subdoc-update-example}

[source,sh]
----
include::example$kv/kv-subdoc.nu[tag=cbsh-subdoc-upsert]
----

.Result
[source,console]
----
╭───┬───────────┬─────────┬────────┬──────────┬─────────╮
│ # │ processed │ success │ failed │ failures │ cluster │
├───┼───────────┼─────────┼────────┼──────────┼─────────┤
│ 0 │         1 │       1 │      0 │          │ capella │
╰───┴───────────┴─────────┴────────┴──────────┴─────────╯
----

For further details, refer to {nushell-api-url}/upsert.html[upsert for filters^] or {nushell-api-url}/update.html[update for filters^] in the Nushell documentation.
--

pass:[.NET]::
+
--
. Call the `MutateInAsync()` method, which takes a document ID and an IEnumerable containing `MutateInSpec` objects. 

. Use a `MutateInSpec` object to specify the sub-operation to be performed within the lookup.

A `MutateInResult` object is returned, containing the result and metadata relevant to the sub-document update operation.

'''

{kv-subdoc-update-example}

[source,csharp]
----
include::dotnet-sdk:hello-world:example$KvHelloWorldScoped.csx[tag=kv-update-subdoc,indent=0]
----

{github}

For further details, refer to {dotnet-api-url}/Couchbase.KeyValue.CollectionExtensions.html[CollectionExtensions^].
--

Java::
+
--
. Call the `mutateIn()` method, which takes a document ID and an array of `MutateInSpec` objects. 

. Use a `MutateInSpec` object to specify the sub-operation to be performed within the lookup.

A `MutateInResult` object is returned, containing the result and metadata relevant to the sub-document update operation.

'''

{kv-subdoc-update-example}

[source,java]
----
include::java-sdk:hello-world:example$KvHelloWorldScoped.java[tag=kv-update-subdoc,indent=0]
----

{github}

For further details, refer to {java-api-url}/Collection.html[Collection^].
--

Node.js::
+
--
. Call the `mutateIn()` method, which takes a document ID and an array of `MutateInSpec` objects. 

. Use a `MutateInSpec` object to specify the sub-operation to be performed within the lookup.

A `MutateInResult` object is returned, containing the result and metadata relevant to the sub-document update operation.

'''

{kv-subdoc-update-example}

[source,nodejs]
----
include::nodejs-sdk:hello-world:example$kv-hello-world-scoped.js[tag=kv-update-subdoc,indent=0]
----

{github}

For further details, refer to {nodejs-api-url}/Collection.html[Collection^].
--

Python::
+
--
. Call the `mutate_in()` function, which takes a document ID and a list of `MutateInSpec` objects. 

. Use a `MutateInSpec` object to specify the sub-operation to be performed within the lookup.

A `MutateInResult` object is returned, containing the result and metadata relevant to the sub-document get operation.

'''

{kv-subdoc-update-example}

[source,python]
----
include::python-sdk:devguide:example$python/kv_hello_world_scoped.py[tag=kv-update-subdoc,indent=0]
----

{github}

For further details, refer to {python-api-url}#collection-object[Collection^].
--
====

== Related Links

Key-Value Operations with SDKs:

* xref:c-sdk:howtos:kv-operations.adoc[C]
| xref:dotnet-sdk:howtos:kv-operations.adoc[.NET]
| xref:go-sdk:howtos:kv-operations.adoc[Go]
| xref:java-sdk:howtos:kv-operations.adoc[Java]
| xref:nodejs-sdk:howtos:kv-operations.adoc[Node.js]
| xref:php-sdk:howtos:kv-operations.adoc[PHP]
| xref:python-sdk:howtos:kv-operations.adoc[Python]
| xref:ruby-sdk:howtos:kv-operations.adoc[Ruby]
| xref:scala-sdk:howtos:kv-operations.adoc[Scala]

Sub-Document operations with SDKs:

* xref:c-sdk:howtos:subdocument-operations.adoc[C]
| xref:dotnet-sdk:howtos:subdocument-operations.adoc[.NET]
| xref:go-sdk:howtos:subdocument-operations.adoc[Go]
| xref:java-sdk:howtos:subdocument-operations.adoc[Java]
| xref:nodejs-sdk:howtos:subdocument-operations.adoc[Node.js]
| xref:php-sdk:howtos:subdocument-operations.adoc[PHP]
| xref:python-sdk:howtos:subdocument-operations.adoc[Python]
| xref:ruby-sdk:howtos:subdocument-operations.adoc[Ruby]
| xref:scala-sdk:howtos:subdocument-operations.adoc[Scala]
