== Create a Hyperscale Vector Index with the Couchbase Web Console

To create a Hyperscale Vector index with the Couchbase Web Console:

. Go to menu:Vectors[].
. Click btn:[Add Vector Index].
. Choose btn:[Hyperscale Vector Index].
. In the *Index Name* field, enter a name for your new Vector index.
+
[NOTE]
====
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

Your index name must be unique inside your selected bucket and scope.
You cannot have 2 indexes with the same name inside the same bucket and scope.
====

. In the *Bucket*, *Scope*, and *Collection* lists, select the bucket, scope, and collection where you have documents that contain a vector field.

. Under *Vector Field*, in the *Field* list, select the vector field to use in your Hyperscale Vector index.

. [[filter-fields]](Optional) To add a field to use as a filter on the data included in your Hyperscale Vector index, click btn:[+ Add Filter Field].

.. Under *Filter Fields*, select the field you want to use to filter your documents.

.. Under *Include in Index*, choose whether the previously selected field should be included in your index.
+
You can still choose to partition using this field and not include it in your index.

.. Under *Partition*, choose whether the previously selected field should be used to partition your index, based on the values in your documents.
+
For example, you could partition your Hyperscale Vector index based on the value of a `supplier` field in your documents.
If you choose *No*, you can still filter using a `WHERE` clause, but your index will not be partitioned based on field values.

.. (Optional) Under *WHERE clause (Optional)*, enter a clause for the specific values that a document must contain in your filter field to be included in your index.
+
For example, you could filter your index so that only documents with `supplier = "HP"` or `brightness > 0.5` are included.

. Under *Index Configuration*, choose options to configure additional settings for your Hyperscale Vector index:

.. In the *Similarity Metric* list, select the similarity metric that you want to use for comparing vectors in your index.
For the best accuracy, use the same similarity that you plan to use to query your data.
+
For more information about vector similarity measures, see xref:vector-index:vectors-and-indexes-overview.adoc#vector_similarity[Vector Similarity].

.. In the *Quantization* list, select the type of quantization to use for simplifying the vectors stored in your index.
+
For more information about quantization, see xref:vector-index:vectors-and-indexes-overview.adoc#quantization[Quantization].
For more information about how to choose quantization on your index, see xref:vector-index:vectors-and-indexes-overview.adoc#choosing-a-quantization-method[Choosing a Quantization Method] and xref:vector-index:vector-index-best-practices.adoc#quantization[Tuning Index Creation - Quantization].

.. [[dimensions]]In the *Dimensions* field, enter the exact dimension of the vectors in your data.
+
Your embedding model determines this value, and Couchbase Server automatically configures it based on your chosen *Vector Field*.

.. In the *Replicas* list, select the number of replicas you want to create for your index.
+
Replicas affect the query throughput, memory footprint, and fault tolerance for your Hyperscale Vector index.
More replicas increase the required memory for your index, but can increase query throughput.

.. [[training-list]](Optional) In the *Training List* field, enter or select the number of vectors to consider when searching for centroids in your data.
+
[TIP]
====
If you have less than 10,000 vectors in your index, Couchbase sets the *Training List* value to your number of vectors.
If you have more than 10,000 vectors up to a maximum of 1,000,000, Couchbase sets the *Training List* value to either 10% of your total number of vectors or 10 times your number of centroids - whichever value is higher, up to a maximum of 1,000,000.

You can change your *Training List* value from these recommended defaults.
Increasing the value can improve recall, but increase build times.
Decreasing the value can improve build times, but reduces recall.
====

.. [[probes]](Optional) In the *Probes to scan* field, enter or select the number of centroids to check for similar vectors for each query.
+
The default value is *1*.
A higher value increases search times, but also increases accuracy.
You can also choose to override this value in your queries.

.. (Optional) In the *Number of centroids* field, enter or select the number of centroids to create in your index.
+
A larger value creates smaller centroids.
By default, Couchbase sets the *Number of centroids* to the number of vectors in your data divided by 1000.
For more information about how to set this value, see xref:vector-index:hyperscale-vector-index.adoc#number-of-centroids[Number of Centroids].

.. To store full vectors in the index, select *Persist Full Vector*.
+
This increases the storage required for your index but increases accuracy.

+
. (Optional) To confirm your Hyperscale Vector Index configuration:

.. Click btn:[View Index Definition].
.. To copy the {sqlpp} syntax to create your index in the Query Workbench, click btn:[Copy to Clipboard].
.. Click close icon:times[] to close the Index Definition tab.

+
. Click btn:[Create Index] to create your index.

=== Resolve Index Creation Errors

If an error occurs while Couchbase Server tries to create your Hyperscale Vector index, on the *Vector Indexes* page, the *Status* of your index changes to *Error*.

To view the details of the error:

. Click the *Error* status to open the Query Workbench.
. Click btn:[Execute] to drop and rebuild the index.
. In the query results, find the error details.

Depending on the error, you might need to try recreating your index with a new configuration.