== Create a Composite Vector Index with the Capella UI

To create a Composite Vector index with the Capella UI: 

. On the *Operational Clusters* page, select the operational cluster where you want to create a Composite Vector index.
. Go to menu:Data Tools[Vector Indexes].
. Click btn:[Create Vector Index].
. Choose btn:[Composite Vector Index].
. In the *Index Name* field, enter a name for your new Vector index.
+
[NOTE]
==== 
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

Your index name must be unique inside your selected bucket and scope.
You cannot have 2 indexes with the same name inside the same bucket and scope.
====
. In the *Bucket*, *Scope*, and *Collection* lists, select the bucket, scope, and collection where you have documents that contain a vector field.
. Under *Vector Field*, in the *Select Field* list, select the vector field to use in your Composite Vector index.
. In the *Filter Field* lists, do the following:
.. Under *Filter Fields*, select the field you want to use to filter your documents before running vector comparisons.
.. Under *Include in Index*, choose whether the previously selected field should be included in your index and returned in search results.
.. Under *Partition by Hash*, choose whether the previously selected field should be used to partition your index, based on the values in your documents.
+
For example, you could partition your HyperScale Vector index based on the value of a `supplier` field in your documents.
If you choose *No*, you can still filter using a `WHERE` clause, but your index will not be partitioned based on field values.
.. (Optional) Under *Add where clause*, enter the specific values, separated by commas (`,`) that a document must contain in your filter field to be included in your index.
+
For example, you could filter your index so that only documents with a `supplier` value of `HP` are included.

. Under *Index Configuration*, choose an option to automatically configure additional settings for your Composite Vector index: 
+
* *High Accuracy*: Choose when you need high precision and accuracy in your vectors.
* *Low Latency*: Choose when you need fast query performance over accuracy.
* *Balanced*: Choose when you need your index to be both fast and accurate.
+
You can also configure the following settings manually: 

.. In the *Similarity Distance* list, select the similarity metric that you want to use for comparing vectors in your index.
For the best accuracy, use the same similarity that you plan to use to query your data.
+
For more information about vector similarity measures, see xref:vector-index:vectors-and-indexes-overview.adoc#vector_similarity[Vector Similarity].
.. In the *Quantization* list, select the type of quantization to use for simplifying the vectors stored in your index.
+
For more information about quantization, see xref:vector-index:vectors-and-indexes-overview.adoc#quantization[Quantization].
For more information about how to choose quantization on your index, see xref:vector-index:vectors-and-indexes-overview.adoc#choosing_quantization[Choosing Quantization] and xref:vector-index:vector-index-best-practices.adoc#quantization[Tuning Index Creation - Quantization].
.. In the *Dimensions* field, enter the exact dimension of the vectors in your data.
+
Your embedding model determines this value.
.. In the *Number of replicas* list, select the number of replicas you want to create for your index.
+
Replicas affect the query throughput, memory footprint, and fault tolerance for your Composite Vector index.
More replicas increase the required memory for your index, but can increase query throughput.
.. In the *Number of Training List* list, select the number of vectors to consider when searching for centroids in your data.
+
By default, your training list value should be 50 times the number of centroids in the index.
Higher values can increase your query throughput and reduce latency, but increase memory usage.
. Click btn:[Review Index].
. Confirm your Composite Vector Index configuration. 
. Click btn:[Create Index] or copy the {sqlpp} syntax to create your index with the Query Workbench.