= Advanced Features
:page-role: tiles -toc
:!sectids:

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

== Flex Indexes

Flex Indexes provide the ability for a {sqlpp} query to use a Full Text Search index transparently with standard {sqlpp} syntax.

* xref:n1ql:n1ql-language-reference/flex-indexes.adoc[]

== Cost-Based Optimizer

The cost-based optimizer takes into account the cost of memory, CPU, network transport, and disk usage when choosing the optimal plan to execute a query.

* xref:n1ql:n1ql-language-reference/cost-based-optimizer.adoc[]

== {sqlpp} Support for Couchbase Transactions

{sqlpp} offers full support for Couchbase ACID transactions.

* xref:n1ql:n1ql-language-reference/transactions.adoc[]

== Time Series

In Couchbase Server 7.2 and later, {sqlpp} enables you to process and query time series data.

* xref:n1ql:n1ql-language-reference/time-series.adoc[]