= Advanced Query Features
:page-role: tiles -toc
:page-aliases: guides:optimize.adoc
:!sectids:

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

== Cost-Based Optimizer

The cost-based optimizer takes into account the cost of memory, CPU, network transport, and disk usage when choosing the optimal plan to execute a query.

* xref:n1ql:n1ql-language-reference/cost-based-optimizer.adoc[]
* xref:guides:cbo.adoc[]

== {sqlpp} Support for Couchbase Transactions

{sqlpp} offers full support for Couchbase ACID transactions.

* xref:n1ql:n1ql-language-reference/transactions.adoc[]
* xref:guides:transactions.adoc[]

ifdef::flag-devex-search[]
== Flex Indexes

Flex Indexes provide the ability for a {sqlpp} query to use a Full Text Search index transparently with standard {sqlpp} syntax.

* xref:n1ql:n1ql-language-reference/flex-indexes.adoc[]
endif::flag-devex-search[]

== Time Series Data

In Couchbase Server 7.2 and later, {sqlpp} enables you to store and query time series data.

* xref:n1ql:n1ql-language-reference/time-series.adoc[]