= Understand How to Access Your Data
:page-aliases: n1ql:index,n1ql:n1ql-intro/data-access-using-n1ql
:page-role: 
:imagesdir: ../assets/images
:!sectids:
:keywords: SQL++, N1QL, Query, Analytics, Search, Eventing
:description: You can use the Query, Analytics, or Full Text Search services to access your data using the {sqlpp} query language. You can also create functions to access data when it changes using the Eventing Service.

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]


[abstract]
{description}

A database query is a request to retrieve or change data in your database. You use queries to work with your data for tasks such as:

* Aggregating data
* Creating, reading, updating or deleting data (CRUD operations)
* Finding and summarizing information
* Defining indexes


== Choose the Right Service

[%header,cols="30%,70%"]
|===
| Service | Description 

| xref:clusters:query-service/query-service.adoc[Query Service]
| Use the Query Service for operational queries -- for example, the front-end queries behind every page display or navigation.

| xref:clusters:analytics-service/analytics-service.adoc[Analytics Service]
| The Analytics Service is the Couchbase Online analytical processing (OLAP) solution. Use the Analytics Service to efficiently run complex queries over many records. 

The Analytics Service supports large join, set, aggregation, and grouping operations, any of which may result in long running queries, high CPU usage, high memory consumption, and/or excessive network latency due to data fetching and cross node coordination. 

| xref:search:search.adoc[Full Text Search Service]
| Use the Full Text Search (FTS) Service when you want to take advantage of natural-language querying. With FTS you can create, manage, and query multi-purposed indexes defined on JSON documents.

In addition to exact matches, the full-text index can perform various search functions based on matching given terms/search parameters.

| xref:clusters:eventing-service/eventing-service.adoc[Eventing]
| Use the Eventing Service to create and execute custom JavaScript functions within the database based on timers or data changes. You can access and update data, write out to a log, or call out to an external system.
 

|===


== Query Language

You use a query language to construct queries that tell your service which data you want to retrieve or modify. 

Couchbase Capella uses a query language called {sqlpp}. 
The Couchbase implementation of {sqlpp} was formerly known as https://www.couchbase.com/products/n1ql[N1QL^] (pronounced "nickel").

{sqlpp} is an expressive, powerful, and complete SQL dialect for querying, transforming, and manipulating JSON data. 
Based on SQL, it’s familiar to developers who can quickly start developing rich applications.


== Indexes

An index is a data structure that stores where specific data is in your database. Database indexing speeds up data retrieval. Query indexes to look up where the data you need is, instead of using a query to scan through every document. 

Indexes take up space in your database, so it is important to plan out the most efficient index to store what you need to retrieve.

xref:clusters:query-service/query-service.adoc[Query], xref:clusters:analytics-service/analytics-service.adoc[Analytics], and xref:search:search.adoc[Search] services use indexes as targets for search-routines.

The Query Service relies on indexes created by the xref:clusters:index-service/index-service.adoc[Index Service]. Primary Indexes and Global Secondary Indexes (GSI) support queries made by the Query Service.

The Search and Analytics services provide their own indexes, internally.

