= Query Data with {sqlpp}
:page-aliases: n1ql:index,n1ql:n1ql-intro/data-access-using-n1ql
:page-role: tiles -toc
:imagesdir: ../assets/images
:!sectids:
:keywords: SQL++, N1QL, Query
:description: The Query Service supports the querying of data by means of the {sqlpp} query language.

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

[abstract]
{description}

include::ROOT:partial$component-signpost.adoc[]

As its primary function, the Query service enables you to issue queries to extract data from Couchbase server.
You can also issue queries for data definition (defining indexes) and data manipulation (adding or deleting data).
The Query Service needs both the Index Service and the Data Service to be running on Couchbase Server.

You can run queries from the Query workbench, the cbq shell, the REST API, or the Couchbase SDKs.

== When to Use Queries

Use the Query service for query analysis and execution to help you build applications.

Use the Analytics service for online analytical processing (OLAP) -- large datasets with complex analytical or ad hoc queries.

Use the Search service for full-text search with natural language processing across multiple data types and languages -- custom text analysis, Geospatial search, and more.

== {sqlpp} for Query

To create queries, you must use a query language that is structured so that the Query Service understands what it needs to retrieve.
Couchbase Server uses a query language called {sqlpp}.
The Couchbase implementation of {sqlpp} was formerly known as https://www.couchbase.com/products/n1ql[N1QL^] (pronounced "nickel").

{sqlpp} is an expressive, powerful, and complete SQL dialect for querying, transforming, and manipulating JSON data.
Based on SQL, it's immediately familiar to developers who can quickly start developing rich applications.

== How-To Guides

* xref:n1ql:n1ql-intro/index.adoc[]
* xref:guides:query.adoc[]
* xref:guides:indexes.adoc[]
* xref:guides:manipulate.adoc[]
* xref:guides:javascript-udfs.adoc[]
* xref:n1ql:advanced.adoc[]

== Query Administration

* xref:n1ql:n1ql-manage/index.adoc[]

== Query References

* xref:n1ql:n1ql-language-reference/index.adoc[]
* xref:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[]
* xref:javascript-udfs:javascript-functions-with-couchbase.adoc[]

== Related Links

* xref:learn:services-and-indexes/services/query-service.adoc[Query Service architecture]
* xref:learn:data/data.adoc[]
