= Query Data with {sqlpp}
:page-aliases: n1ql:index,n1ql:n1ql-intro/data-access-using-n1ql,clusters:query-service/query-service.adoc
:page-role: tiles -toc
:imagesdir: ../assets/images
:!sectids:
:keywords: SQL++, N1QL, Query
:description: The Query Service supports the querying of data by means of the {sqlpp} query language.

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title{
    flex-basis: 100%;
  }
</style>
++++
endif::[]

[abstract]
{description}

As its primary function, the Query service enables you to issue queries to extract data from Couchbase Capella.
You can also issue queries for data definition (defining indexes) and data manipulation (adding or deleting data).
The Query Service depends on both the Index Service and the Data Service.

To issue queries, you can use a Couchbase SDK, the REST API, or the tools provided by the Query service: the cbq shell or the Query workbench.

== When to Use Queries

Use the Query service for query analysis and execution to help you build applications.

Use the Analytics service for online analytical processing (OLAP) -- large datasets with complex analytical or ad hoc queries.

Use the Search service for full-text search with natural language processing across multiple data types and languages -- custom text analysis, Geospatial search, and more.

== {sqlpp} for Query

Couchbase Capella can be queried using the {sqlpp} query language.
The Couchbase implementation of {sqlpp} was formerly known as https://www.couchbase.com/products/n1ql[N1QL^] (pronounced "nickel"), which derives its name from the non-first normal form of the data model.

{sqlpp} is an expressive, powerful, and complete SQL dialect for querying, transforming, and manipulating JSON data.
Based on SQL, it's immediately familiar to developers who can quickly start developing rich applications.

== What's Next

* xref:n1ql:n1ql-intro/index.adoc[]
* xref:n1ql:tutorial.adoc[]
* xref:clusters:query-service/query-workbench.adoc[]
ifdef::flag-query-settings[]
* xref:settings:query-settings.adoc[]
endif::flag-query-settings[]
* xref:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[]
* xref:n1ql:advanced.adoc[]
* xref:n1ql:n1ql-language-reference/index.adoc[]
ifdef::flag-devex-javascript-udfs[]
* xref:javascript-udfs:javascript-functions-with-couchbase.adoc[]
endif::flag-devex-javascript-udfs[]

== Related Links

* xref:server:learn:services-and-indexes/services/query-service.adoc[Query Service architecture]
* xref:server:learn:data/data.adoc[]
