= Create a Vector Search Index with the Web Console
:page-topic-type: guide
:description: You can create a Vector Search index with the Couchbase Server Web Console. 

[abstract]
{description}

You must create a Vector Search index before you can xref:.adoc[run a search] that supports Vector Search.
// Add link

== Prerequisites

* You have deployed the Search Service on a node in your database. 

* You have a bucket with scopes and collections in your database. 

* Your user account has the *Search Admin* role for the bucket where you want to create the index.  

* You have logged in to the Couchbase Server Web Console. 

== Procedure 

To create a Vector Search index with the Couchbase Server Web Console: 

. Go to *Search*.
. Click btn:[Add Index].
. In the *Index Name* field, enter a name for the Vector Search index. 
+
[NOTE]
====
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

For version 7.6 and later, your index name must be unique inside your selected bucket and scope. You cannot have 2 indexes with the same name inside the same bucket and scope.
====

. In the *Bucket* list, select the bucket where you want to create the index. 
. Expand *Customize Index*. 
. Select *Use non-default scope/collection(s)*.
.. In the *Scope* list, select the scope where you want to create the index. 
. xref:create-type-mapping.adoc[] as you would for a regular Search index, on the collection in your database that contains documents with vector data.
. xref:create-child-field.adoc[] on the new collection type mapping with the following settings: 
.. In the *Field* field, enter the name of the field in your documents that contains an array of vector data.
.. In the *Type* list, select *vector*. 
.. In the *Dimension* field, enter the size of the array that holds the vector data for your documents. 
The Search Service supports arrays up to 2048 elements. 
// Check name of field and description
.. In the *Similarity metric* list, select the method to use to calculate the similarity between search term and Search index vectors. 
// Check name of field and description. How/where to describe similarity metrics?
.. Select *Index*.
. xref:create-child-field.adoc[Create another child field] on the new collection type mapping 
//? Is this necessary?
. Click btn:[Submit].
. Click btn:[Create Index].

== Next Steps 

This basic Vector Search index includes...
// Figure out what fields are included. 
You can customize your Vector Search index like any other Search index to add additional data and improve search results. 
 
For more information about how to customize an index, see xref:customize-index.adoc[].

For more information about how to run a search against a Vector Search index, see xref:.adoc[] or xref:.adoc[].
// Add links