= Create a Vector Search Index with the REST API and curl/HTTP
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: You can create a Vector Search index with the Search Service API and Couchbase Capella. 

[abstract]
{description}

You must create a Search index before you can xref:run-vector-search-rest-api.adoc[run a search] with the Search Service.

TIP: Vector Search indexes can include all the same features and settings as a Search index. 
For more information about Search indexes, see the xref:search:search.adoc[Search documentation].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your database.
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[]. 

* You have documents in a keyspace inside your bucket that contain vector embeddings.
+
include::partial$download-sample-partial.adoc[]

* You have the hostname for the node in your database that's running the Search Service.
+
For more information about how to find the hostname for a node in your Capella database, see xref:clouds:get-capella-host-name.adoc[].

== Procedure 

To create a Search index with the REST API and Couchbase Capella: 

. In your command-line tool, enter a `curl` command with the `XPUT` verb. 
. Set your header content to include `"Content-Type: application/json"`.
. Enter your username, password, and the Search Service endpoint on port `18094` with the name of the index you want to create: 
+
[source,console]
----
include::example$create-vector-search-index-header.sh[]
----
. Enter the JSON payload for the settings you want in your index. 
+
Do not include the xref:search:search-index-params.adoc#uuid[uuid] or xref:search:search-index-params.adoc#sourceuuid[sourceUUID] parameters. 
+
TIP: If you remove the xref:search:search-index-params.adoc#uuid[uuid] and xref:search:search-index-params.adoc#sourceuuid[sourceUUID] parameters, you can copy the Search index definition JSON payload from the {page-ui-name} to use in a REST API call.
For more information about how to create a Vector Search index with the UI, see xref:create-vector-search-index-ui.adoc[]. 

=== Example

In the following example, the JSON payload creates an index named `color-index` on the `vector-sample.color.rgb` keyspace. 
It creates two child field mappings, `colorvect_l2` and `embedding_vector_dot` on two different vector fields in the keyspace's documents.

It also adds 3 normal Search index fields (`brightness`, `color`, and `description`) to add more usable data to the Vector Search index:

[source,console]
----
include::example$create-vector-search-index-payload.sh[]
----

For more information about all the available JSON properties for a Search index, see xref:search:search-index-params.adoc[].

== Next Steps

After you create a Search index, you can xref:run-vector-search-rest-api.adoc[] to test your Search index. 

If you want to edit your index with another REST API call, include the xref:search:search-index-params.adoc#uuid[uuid] parameter with the UUID the Search Service assigned to your Vector Search index.

You can also xref:create-vector-search-index-ui.adoc[].