= Create a Vector Search Index in Quick Mode
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:page-toclevels: 2
:description: Use Quick Mode to create a Vector Search index in Couchbase Capella.

[abstract]
{description}

Quick Mode works best when you need to create a basic Search index to start testing and prototyping with the Search Service.
You must use Advanced Mode to have greater control over how the Search Service returns such results, such as changing your xref:search:customize-index.adoc#analyzers[analyzer]. 

For more information about how to create a Search index in Advanced Mode, see xref:search:create-search-index-ui.adoc[].

TIP: Vector Search indexes can include all the same features and settings as a Search index. 
For more information about Search indexes, see the xref:search:search.adoc[Search documentation].

You must create a Vector Search index before you can xref:run-vector-search-ui.adoc[run a search] that supports vector comparisons.

== Prerequisites 

* You have the Search Service enabled on a node in your cluster.
For more information about how to change Services on your cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your cluster.
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have documents in a keyspace inside your bucket that contain vector embeddings.
Embeddings can be an array of floats or a base64 encoded string. 
+
[TIP]
--
include::partial$download-sample-partial.adoc[]
--

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To create a Vector Search index with Quick Mode in Capella:

. On the *Operational Clusters* page, select the cluster where you want to create a Search index.
. Go to menu:Data Tools[Search].
. Click btn:[Create Search Index].
+
By default, *Quick Mode* should be on.
. In the *Index Name* field, enter a name for the Vector Search index. 
+
[NOTE]
====
Your index name must start with an alphabetic character (a-z or A-Z). It can only contain alphanumeric characters (a-z, A-Z, or 0-9), hyphens (-), or underscores (_).

For Couchbase Server version 7.6 and later, your index name must be unique inside your selected bucket and scope. You cannot have 2 indexes with the same name inside the same bucket and scope.
====
. Under *Type Mappings*, in the *Bucket* list, select the bucket that contains the documents you want to include in your index. 
. In the *Scope* list, select the scope that contains these documents. 
. Expand the collection that contains these documents. 
. In your document schema, select the child field that contains your vector embeddings. 
. Configure the options for the child field as follows:
.. In the *Type* list, select one of the following: 
... If your child field contains vector embeddings as an array, click *vector*. 
+
Vector embeddings formatted as arrays appear as `\{field-name} [ number ]` in the Capella Quick Mode editor.
... (Couchbase Server version 7.6.2 or later) If your child field contains vector embeddings formatted as a base64 encoded string, click *vector_base64*.
+
Vector embeddings formatted as base64 strings appear as `\{field-name} [ string ]` in the Capella Quick Mode editor.
.. In the *Dimension* field, check that the value matches the total number of elements in your vector embeddings array. 
+
The Search Service supports arrays up to 2048 elements.
Capella automatically fills in the dimension value for your selected child field when you choose the *vector* or *vector_base64* type.
.. In the *Similarity metric* list, choose the method to use to calculate the similarity between search term and Search index vectors.
+ 
For more information, see xref:search:quick-index-field-options.adoc#quick-field[Quick Field Type Mapping Options].
.. In the *Optimized for* list, choose whether the Search Service should optimize Search queries for accuracy (*recall*) or speed (*latency*).
+
For more information, see xref:search:quick-index-field-options.adoc#quick-field[Quick Field Type Mapping Options].
.. Select *Index*.
. Click btn:[Submit].
. (Optional) Add additional collections or child field type mappings to your index.
+
For example, you could add the text field that you used to generate your vector embeddings. 
. Click btn:[Create Index].

[#example]
=== Example: Creating a Vector Search Index for Vector Search Query Examples 

If you want to use the sample dataset for the examples in xref:run-vector-search-ui.adoc[] and xref:run-vector-search-sdk.adoc[], then you can xref:search:import-search-index.adoc[import] the following Search index definition into {page-ui-name}:

[source,json]
----
include::example$sample-vector-search-index-payload.json[]
----

NOTE: Make sure you imported the sample dataset with the recommended settings. 

This Vector Search index has a type mapping for a `color.rgb` collection and includes the following fields: 

* The *brightness number* field, which is included in search results and supports sorting and faceting.
* The *color string* and *description string* fields, which are included in search results, support highlighting, phrase matching, and sorting and faceting.
* The *colorvect_l2 [ number ]* field, which has a Dimension of `3` and uses the *l2_norm* Similarity Metric.
* The *embedding_vector_dot [ number ]* field, which has a dimension of `1536` and uses the *dot_product* Similarity Metric. 

== Next Steps 

This basic Vector Search index includes the vector embeddings from the child field you specified in your type mapping.
If you chose to add additional child fields and enabled *Include in search results*, the Search Service can also return data from those fields when you run a Vector Search query.

For example, if you used the Vector Search sample data, you might want to add another child field for the *color* string field to your Vector Search index, to return color names with your Search query.
For more information about how to add additional child fields to your index, see xref:search:create-quick-index.adoc[] or xref:search:create-child-field.adoc[].

You can customize your Vector Search index like any other Search index to add additional data and improve search results. 
For more information about how to customize an index, see xref:search:customize-index.adoc[].

CAUTION: Some Search index features are only available in Advanced Mode.
If you edit your Search index in Advanced Mode, you cannot make any additional edits in Quick Mode without losing all Advanced Mode settings. 

For more information about how to run a search against a Vector Search index, see xref:run-vector-search-ui.adoc[].