= Create a Vector Search Index with the REST API and curl/HTTP
:page-topic-type: guide
:description: You can create a Vector Search index with the Search Service API and Couchbase Capella. 

[abstract]
{description}

You must create a Search index before you can xref:run-vector-search-rest-api.adoc[run a search] with the Search Service.

TIP: Vector Search indexes can include all the same features and settings as a Search index. 
For more information about Search indexes, see the xref:search:search.adoc[Search documentation].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your database.
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[]. 

* You have documents in a keyspace inside your bucket that contain vector embeddings. 

* You have the hostname for your a node in your cluster running the Search service.  This typically is different than the hostname found in the `Public Connection String` under Connect. 
You can find a list of all  Nodes under Settings. 
+
For more information about how to find the hostname for your Capella database, see xref:clouds:get-capella-host-name.adoc[].

== Procedure 

To create a Search index with the REST API and Couchbase Capella: 

. In your command-line tool, enter a `curl` command with the `XPUT` verb. 
. Set your header content to include `"Content-Type: application/json"`.
. Enter your username, password, and the Search Service endpoint on port `18094` with the name of the index you want to create: 
+
[source,console]
----
include::example$create-vector-search-index-header.sh[]
----
. Enter the JSON payload for the settings you want in your index. 
+
Do not include the xref:search:search-index-params.adoc#uuid[uuid] or xref:search:search-index-params.adoc#sourceuuid[sourceUUID] parameters. 
+
TIP: If you remove the xref:search:search-index-params.adoc#uuid[uuid] and xref:search:search-index-params.adoc#sourceuuid[sourceUUID] parameters, you can copy the Search index definition JSON payload from the Capella UI to use in a REST API call.
For more information about how to create a Vector Search index with the UI, see xref:create-vector-search-index-ui.adoc[]. 

=== Example

In the following example we create an Search index on the keyspace `vector-sample.color.rgb` named `color-index`. 
The JSON payload defines: 

* Two child field mappings,`colorvect_l2` and `embedding_vector_dot` on two different vectors fields (numeric arrays) in the documents.  

* One traditional search index on the child field mapping `brightness` where the data is both indexed stored.

* Two child field mappings, `color` and `description`, where we only store the data.

[source,console]
----
include::example$create-vector-search-index-payload.sh[]
----

For more information about all the available JSON properties for a Search index, see xref:search:search-index-params.adoc[].

== Next Steps

After you create a Search index, you can xref:run-vector-search-rest-api.adoc[] to test your Search index. 

If you want to edit your index with another REST API call, include the xref:search:search-index-params.adoc#uuid[uuid] parameter with the UUID the Search Service assigned to your Vector Search index.

You can also xref:create-vector-search-index-ui.adoc[].
