= Fine-Tuning a Vector Search Query

:page-ui-name: {ui-name}
:page-product-name: {product-name}
:stem:
:description: Add additional parameters to a Vector Search REST API call to tune the search for recall or accuracy.

[abstract]
{description}



The Search Service automatically tunes your Vector Search indexes to achieve a balance between: 

* Recall, or the quality of your search results
* Latency, or your search response time
* Memory efficiency

This tuning occurs during indexing and querying. 
You do not need to adjust these parameters manually. 

Specifically, the Search Service dynamically adjusts two critical vector parameters:

`nlist`, also known as `Centroid` count::
The number of clusters used for indexing.
Centroids are used to quickly find the surrounding closest matches in the Vector Search index. 
Increasing the number of centroids will increase accuracy but will decrease the speed of the search.
+
The `nlist` is determined dynamically based on the size of the dataset, or the number of vectors in a partition:
+
[%header, cols="3*a"]
|===
| Number of vectors in partition (`nvec`)
| `nlist` calculation
| Notes

| stem:["nvec " ge " 200,000"]
| stem:[4 xx sqrt("nvec")]
| This formula is designed to handle larger datasets
 where increasing the number of datasets does not yield significant improvements in recall.

| stem:["1000" lt "nvec" le "200,000" ]
| stem:["nvec" / 100]
| This formula targets approximately 100 vectors per cluster,
which balances between too few and too many clusters, ensuring efficient indexing.

| stem:["nvec" lt 1000]
| N/A
| For a number of vectors less than 1000, the Search Service will carry out a straight forward one-to-one mapping between IDs and vectors with an exact vector comparison.
Vectors are directly stored without the need for additional processing for the `nlist` calculation.

|===

`nprobes` (or `probes`)::
The number of `centroids` that a Search query will check for similar vectors.
The `nprobe` value is only set when the Search Service is using an Inverted File Index. The Search Service will select the best index type and comparison method depending on the size of the dataset and your `vector_index_optimized_for` setting.
+
+
[%header, cols="3*a"]
|===
| Query optimization
| `nprobe` calculation
| Notes


| Default calculation
| stem:[sqrt("nlist")]
| This provides a balanced tradeoff between recall and latency by adjusting the number of clusters probed during queries.

| Latency-optimized (`vector_index_optimized_for: latency`)
| stem:[sqrt("nlist") / 2]
| A minimum value of 1 is enforced to avoid setting `nprobe` too low.

|===


== Fine-Tuning Query Parameters


Add an additional parameter object to any Vector Search query to tune the recall or accuracy of your search.

You can add the following parameters to your query: 

`ivf_nprobe_pct`::
Adjusts the number percentage of clusters searched during queries, allowing for fine-tuning of the balance between recall and performance.
If the value of `nprobe` is 5% of `nlist` (the centroid count), then setting the value of `ivf_nprobe_pct` higher than 5% will have the search cover a higher percentage of clusters, which will improve the accuracy of the search.

`ivf_max_codes_pct`::
The default value for this is 100, and the value represents the percentage of `centroids` that will be visited during a search. 
Reducing the value reduces the number of centroids visited, which will decrease accuracy and recall, but will result in faster compute times.

== Example: nlist and nprobe Calculations on a Vector Search Index Set to Recall 

For example, if you had a Vector Search index with `vector_index_optimized_for` set to `"recall"` and `indexPartitions` set to `5`,  `nlist` and `nprobe` are determined based on the current vector count in a given partition:

'''
[options="noheader", frame="none", grid="none" cols="1,1"]
|===
| stem:["Total vectors in index"] (optimization = recall)
| 10,000,000

| stem:["Average vectors in a partition for 5 partitions total"]
| 2,000,000

| stem:["nlist"] (or stem:["centroids"]) = stem:[4 times sqrt("total vectors in index")]
| 5657

| stem:["nprobes"] = stem:[sqrt(nlist)]
| 75

| stem:["Calculated default: ivf_nprobe_pct"]
| 1.325%

| stem:["Calculated default: ivf_max_codes_pct"]
| 100%

|===

'''

[source, json]
.Using tuning parameters
----
{
  "fields": ["*"],
  "knn": [{
    "k": 10,
    "params": {
      "ivf_nprobe_pct": 1,
      "ivf_max_codes_pct": 0.2
    },
    "field": "embedding",
    "vector": [0.024901132253900747, 1535]
  }]
}
----






