
= Importing Vector Data
:page-topic-type: guide
:description: Use the Capella UI to Import Vector Data.

[abstract]
{description}

== Importing Data

Importing Vector data sample sets is no different than importing other document data sets.  The documents just have on or more numeric Vectors of the form `"fieldname": [\#,#, . . .]`. See: xref:clusters:data-service/import-data-documents.adoc#import-data-from-your-browser[Import Data from Your Browser]. 

== Importing Sample Vector Data

. Ensure the two keyspaces of vector-sample.color.rgb and vector-sample.color.rgb.questions exist. 

. Download and extract the data form the Zip file color_data_2vectors.zip[https://cbc-remote-execution-examples-prod.s3.amazonaws.com/color_data_2vectors.zip]

. Import via the UI the extracted `rgb.json` into the keyspace of `vector-sample.color.rgb` with the document key key based on the Field of `id`

. Import via the UI the extracted `rgb_questions.json` into the keyspace of `vector-sample.color.rgb_questions` with the document key key based on the Field of `id`

When the import is complete, a banner appears at the top of the page to tell you it was successful.

Now view your documents in both collections, click the Documents tab.

For more information about how to import this data via other methods, see xref:guides:load.adoc[Import and Export Data].
