= Pre-filtering Vector Searches
:page-topic-type: guide
:page-ui-name: {ui-name}
:description: You can specify filters as part of a Vector Search query object to restrict the documents searched in a Search index.

[abstract]
{description}

== About Pre-filtering

Using pre-filtering as part of your vector search offers two key advantages:

. *Enhanced precision and relevance:*
Narrow your search results based on specific criteria, such as organization, date/time ranges, or geospatial locations.

. *Performance optimization:*
Reduce the search space before executing queries to improve query execution time and reduce computational overhead.

== Prerequisites

* You have the Search Service enabled on a node in your operational cluster.
For more information about how to change Services on your operational cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have a bucket with scopes and collections in your operational cluster. 
For more information, see xref:cloud:clusters:data-service/manage-buckets.adoc[].

* You have created a Vector Search index.
+
For more information about how to create a Vector Search index, see xref:create-vector-search-index-ui.adoc[].
+
[TIP]
--
include::partial$download-sample-partial.adoc[]

For the best results, consider using the sample Vector Search index from xref:create-vector-search-index-ui.adoc#example[Create a Vector Search Index with the {page-ui-name}].
--

== Procedure

To add pre-filtering to a Vector Search query: 

. On the *Operational Clusters* page, select the operational cluster where you created your Search index. 
. Go to menu:Data Tools[Search]. 
. Next to your Vector Search index, click btn:[Search].
. In the *Search* field, enter a search query that includes a `filter` object with your `knn` object.
+
For more information about the `filter` object, see xref:search:search-request-params.adoc#filter[filter].
. Press kbd:[Enter] or click btn:[Search].
. (Optional) To view a document and its source collection, click a document name in the search results list. 

=== Example: Pre-Filter A Vector Search Query For The Color "Navy"

For example, the following Vector Search query tries to find matches to a color with an RGB value of `[176, 0, 176]` with a minimum brightness of `70` and a maximum of `80`.
A pre-filter on the query will narrow the documents searched inside the Vector Search index to documents that have a `color` field value that closely matches `navy`:

[source, json]
----
include::example$run-pre-filtered-vector-search-ui.json[]
----


