= Run a Vector Search with the Capella UI 
:page-topic-type: guide
:description: Run a Vector Search query from the Couchbase Capella UI to preview and test the search results from a Vector Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database. 

* You have created a Vector Search index. 
+
For more information about how to create a Vector Search index, see xref:create-vector-search-index-ui.adoc[].

* You have logged in to the Couchbase Capella UI. 

== Procedure 

To run a Vector Search with the Capella UI: 

. On the *Databases* page, select the database where you created your Search index. 
. Go to menu:Data Tools[Search]. 
. Next to your Vector Search index, click btn:[Search].
. In the *Search* field, enter a search query. 
+
For example, the following query searches for the top 2 vectors similar to the vector `[ 0, 0, 128 ]` in the `colorvect_l2` field:
+
[source,json]
----
include::example$run-vector-search-payload-ui.jsonc[]
----
+
By using the special `match_none` query in the `query` field, the Search query is a pure Vector Search, i.e. it only returns the `k` number of similar vectors.
+
Search combines Vector search results from *"knn": [{},...]* with traditional search results (text, numeric, geoshape, etc.) from *"query": {}* using an OR function. However, if the same documents are returned from both both the `knn` and `query` components, those common documents will be ranked higher or boosted to the top of the results.

. Press kbd:[Enter] or Click btn:[Search].
. (Optional) To view a document and its source collection, click a document name in the search results list. 

== Next Steps 

If you do not get the search results you were expecting, you can change the xref:search:search-request-params.adoc[JSON query payload for your Search query].

You can also xref:search:search:customize-index.adoc[add additional features to your Search index]. 
