= Run A Vector Search with the {page-ui-name}
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Run a Vector Search query from the Couchbase {page-ui-name} to preview and test the search results from a Vector Search index.

[abstract]
{description}

For more information about how the Search Service scores documents in search results, see xref:run-searches.adoc#scoring[Scoring for Search Queries].

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to deploy a new node and Services on your database, see xref:server:manage:manage-nodes/node-management-overview.adoc[].

* You have a bucket with scopes and collections in your database.
For more information about how to create a bucket, see xref:server:manage:manage-buckets/create-bucket.adoc[]. 

* Your user account has the *Search Admin* or *Search Reader* role. 

* You have created a Vector Search index. 
+
For more information about how to create a Vector Search index, see xref:create-vector-search-index-ui.adoc[].
+
[TIP]
--
include::partial$download-sample-partial.adoc[]

For the best results, xref:search-create-quick-index.adoc[create child fields in Quick Mode] or xref:search:create-child-field.adoc[in Advanced Mode] for the `colorvect_l2` and `color` fields. 
--

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To run a Vector Search with the Couchbase {page-ui-name}: 

. Go to *Search*.
. Click the index where you want to run a search.
. In the *Search this index* field, enter a search query.
. Press kbd:[Enter] or click btn:[Search].

[#similarity]
=== Example: Running a Simple Vector Similarity Query

For example, the following query searches for the top 2 vectors similar to the vector `[ 0, 0, 128 ]` in the `colorvect_l2` field:

[source,json]
----
include::example$run-vector-search-payload-ui.jsonc[]
----

By using the special `match_none` query in the `query` field, the Search query is only a Vector Search query.
It only returns the `k` number of similar vectors.

The Search Service combines the Vector search results from a `knn` object with the traditional `query` object by using an `OR` function. 
If the same documents match the `knn` and `query` objects, the Search Service ranks those documents higher in search results. 

[#large]
=== Example: Running a Semantic Search Query with a Large Embedding Vector

The following query searches for matches to a large embedding vector, generated by the https://platform.openai.com/docs/guides/embeddings[OpenAI embedding model^], `text-embedding-ada-002-v2`.

TIP: You can find generated embedding vectors for each color's `description` field in `rgb.json`.

This query should return the document for the color `navy`, based on a generated embedding vector for:

----
What is a classic, refined hue that exudes elegance and is often linked to power and stability?
----

The following shows part of the sample Search query: 

[source,json]
----
include::example$run-vector-search-long-payload-ui.jsonc[tag=partial]
----
[NOTE]
====
Due to the size of the embedding vector, only part of the full query is being displayed in the documentation. 

Click btn:[View on GitHub] to view and copy the entire Vector Search query payload. 
Make sure you remove the lines for `// tag::partial[]` and `// end::partial[]`.
==== 

== Next Steps 

If you do not get the search results you were expecting, you can change the xref:search:search-request-params.adoc[JSON payload for your Search query].

You can also xref:search:customize-index.adoc[customize your Search index] with additional features. 

Either of the example queries on this page can also be used with the xref:run-vector-search-rest-api.adoc[REST API] to run a search.