= Run A Vector Search with the Capella UI 
:page-topic-type: guide
:description: Run a Vector Search query from the Couchbase Capella UI to preview the search results from a Vector Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database. 

* You have created a Vector Search index. 
+
For more information about how to create a Vector Search index, see xref:create-vector-search-index-ui.adoc[].

* You have logged in to the Couchbase Capella UI. 

== Procedure 

To run a Vector Search with the Capella UI: 

. On the *Databases* page, select the database where you created your Search index. 
. Go to menu:Data Tools[Search]. 
. Next to your Vector Search index, click btn:[Search].
. In the *Search* field, enter a search query. 
+
For example, the following query searches for the top 2 vectors similar to the vector `[ 0.707106781186548, 0, 0.707106781186548 ]` in the `colorvect_dot` field:
+
[source,json]
----
include::example$run-vector-search-payload-ui.jsonc[]
----
+
By using the special `match_none` query in the `query` field, the Search query only returns the `k` number of similar vectors.

. Press kbd:[Enter].
. (Optional) To view a document and its source collection, click a document name in the search results list. 

== Next Steps 

If you do not get the search results you were expecting, you can change the xref:search-request-params.adoc[JSON payload for your Search query].

You can also xref:search:customize-index.adoc[add additional features to your Search index]. 