= Run A Vector Search with the Web Console 
:page-topic-type: guide
:description: Run a Vector Search query from the Couchbase Server Web Console to preview the search results from a Vector Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database. 

* Your user account has the `Search Admin` or `Search Reader` role. 

* You have created a Vector Search index. 
+
For more information about how to create a Vector Search index, see xref:create-vector-search-index-ui.adoc[].

* You have logged in to the Couchbase Server Web Console. 

== Procedure 

To run a Vector Search with the Couchbase Server Web Console: 

. Go to *Search*.
. Click the index where you want to run a search.
. In the *Search this index* field, enter a search query. 
+
For example, the following query searches for the top 2 vectors similar to the vector `[ 0.707106781186548, 0, 0.707106781186548 ]` in the `colorvect_dot` field:
+
[source,json]
----
include::example$run-vector-search-payload-ui.jsonc[]
----
+
By using the special `match_none` query in the `query` field, the Search query only returns the `k` number of similar vectors.

. Press kbd:[Enter] or click btn:[Search].

== Next Steps 

If you do not get the search results you were expecting, you can change the xref:search:search-request-params.adoc[JSON payload for your Search query].

You can also xref:search:customize-index.adoc[]. 