= Run a Vector Search with the {page-ui-name} 
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Run a Vector Search query from the Couchbase {page-ui-name} to preview and test the search results from a Vector Search index.

[abstract]
{description}

== Prerequisites 

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have created a Vector Search index. 
+
For more information about how to create a Vector Search index, see xref:create-vector-search-index-ui.adoc[].
+
include::partial$download-sample-partial.adoc[]

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure 

To run a Vector Search with the {page-ui-name}: 

. On the *Databases* page, select the database where you created your Search index. 
. Go to menu:Data Tools[Search]. 
. Next to your Vector Search index, click btn:[Search].
. In the *Search* field, enter a search query.
. Press kbd:[Enter] or click btn:[Search].
. . (Optional) To view a document and its source collection, click a document name in the search results list. 

[#similarity]
=== Example: Running a Simple Vector Similarity Query

For example, the following query searches for the top 2 vectors similar to the vector `[ 0, 0, 128 ]` in the `colorvect_l2` field:

[source,json]
----
include::example$run-vector-search-payload-ui.jsonc[]
----

By using the special `match_none` query in the `query` field, the Search query is only a Vector Search query.
It only returns the `k` number of similar vectors.

The Search Service combines the Vector search results from a `knn` object with the traditional `query` object by using an `OR` function. 
If the same documents match the `knn` and `query` objects, the Search Service ranks those documents higher in search results. 

[#large]
=== Example: Running a Semantic Search Query with a Large Embedding Vector

TIP: This example uses the `rgb_questions.json` sample data, which provides ready-made vector embeddings and queries that you can use for searches. 
You can find a link to download this sample dataset from xref:create-vector-search-index-ui.adoc[] or xref:create-vector-search-index-rest-api.adoc[].

The following query searches for matches to a large embedding vector, generated by the https://platform.openai.com/docs/guides/embeddings[OpenAI embedding model^], `text-embedding-ada-002-v2`.

The embedding vector for the query was generated from the text in the `question` field in `rgb_questions.json`. 
You can also find the full contents of the query in the `couchbase_search_query` field in the same file.
You can find generated embedding vectors for each color's `question` field in `rgb_questions.json`, and generated embedding vectors for each `description` in `rgb.json`.

This query should return the document for the color `navy`, based on a generated embedding vector for:

----
What is a classic, refined hue that exudes elegance and is often linked to power and stability?
----

The following shows part of the sample Search query: 

[source,json]
----
include::example$run-vector-search-long-payload-ui.jsonc[tag=partial]
----
[NOTE]
====
Due to the size of the embedding vector, only part of the full query is being displayed in the documentation. 

Click btn:[View on GitHub] to view and copy the entire Vector Search query payload. 
Make sure you remove the lines for `// tag::partial[]` and `// end::partial[]`.

You can also copy the query by going to menu:Data Tools[Documents] and copying the full contents from the `couchbase_search_query` field.

If you configured your data import to use the `id` field as the document identifier, you can locate the document for `navy` with the ID `#000080`.
====

== Next Steps 

If you do not get the search results you were expecting, you can change the xref:search:search-request-params.adoc[JSON payload for your Search query].

You can also xref:search:search:customize-index.adoc[add additional features to your Search index]. 

Either of the example queries on this page can also be used with the xref:run-vector-search-rest-api.adoc[REST API] to run a search.
You can find more example embedding vectors and full queries inside the `couchbase_search_query` field for any color in the `rgb_questions.json` sample file.