= Run a Vector Search with the Java SDK
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Using Couchbase's Java SDK, you can run a simple or more complex vector search against a Vector Search index.

[abstract]
{description}


== Prerequisites

* You have the Search Service enabled on a node in your database.
For more information about how to change Services on your database, see xref:cloud:clusters:modify-database.adoc[].

* You have the hostname for the node in your database that's running the Search Service.
+
For more information about how to find the hostname for a node in your Capella database, see xref:clouds:get-capella-host-name.adoc[].

* Make sure to install the Couchbase Java SDK
+
For more information about on installing and using the Couchbase Java SDK, see xref:java-sdk:hello-world:start-using-sdk.adoc[Start Using the Java SDK].

== Example: Searching for a Similar Color Vector with a Java Program 

The sample dataset inside `rgb.json` has small embedding vectors inside the `colorvect_l2` field. 
These embedding vectors describe a color using RGB values. 
For example, the color red has an embedding vector of `[255, 0, 0]`. 

The following example code searches for the color navy (`[0.0, 0.0, 128.0]`) in the `rgb.json` dataset: 

[source,java]
----
include::example$RunVectorSearchSimpleColor.java[]
----

== Example: Semantic Search with Color Descriptions 

[NOTE]
====
The following code sample requires you to have a paid subscription to the OpenAI API to generate an embedding vector from a sample text string.
For more information about pricing for the OpenAI API, see https://openai.com/pricing[OpenAI's Pricing page^] for embedding models.

The `rgb_questions.json` and sample data contains ready-made embedding vectors for different questions.
For an example of how to use a ready-made vector with Vector Search, see xref:run-vector-search-rest-api.adoc[] or xref:run-vector-search-ui.adoc[].
====

Still using the sample dataset inside `rgb.json`, you can use the OpenAI API to generate an embedding from any text string. 

The following code generates an embedding vector with the question `What color hides everything like the night?`:

[source,java]
----
include::example$RunVectorSearchGenerateEmbed.java[]
----

You can try other questions from `rgb_questions.json`, such as: 

* `"What is the most romantic color?"`

* `"What color makes people fall in love?"`

* `"What is the most depressing color?"`

== Next Steps

Edit and update your Search index, `color-index`, and store the `description` field and rerun the second example.  This will also return the `description` paragraph with the results.

If you did not get the search results you were expecting, you can try to recreate your Vector Search index xref:create-vector-search-index-rest-api.adoc[with the REST API].

Vector Search indexes can use the same settings and features as regular Search indexes.
If you want to add additional fields and features to your index, see xref:search:customize-index.adoc[].
