= Use Vector Search for AI Applications
:page-topic-type: concept
:description: Use Couchbase Server's Vector Search features to add fast and accurate semantic search to your applications.

[abstract]
{description}
// Use the description you provided as a quick introduction to the page.

== About Vector Search

Vector Search builds on Couchbase Server's xref:search.adoc[Search Service] to provide vector index support for Retrieval Augmented Generation (RAG) with an existing Large Language Model (LLM).

Vector Search adds a new index type to the Search Service to support AI application development, known as a Vector Search index.
Using Vector Search and Couchbase Server, you can develop applications with an existing LLM while giving context and up-to-date information from your own data. 

You can use an LLM and Vector Search to develop applications that include: 

* *Similarity search:* Search for documents, products, images, and more that are similar to a given query. 

* *Generative AI:* Create new text, images, and more based on a prompt given to the LLM.  

// More use cases worth calling out?

Vector Search supports integrations with frameworks like https://python.langchain.com/docs/get_started/introduction[LangChain^] to support AI application development. 
For more information about all frameworks and integrations supported by Vector Search, see xref:[].
//Don't forget to fill in this link!

== Using Vector Search Indexes

Use a Couchbase Server database to store the data you want to use to provide context to a LLM. 
Use a Vector Search index to store the necessary vectors for your data, created using a LLM. 

Give a search query to the LLM to create an embedding and vector, then use the generated embeddings from the data in your database to return a response to the LLM. 

For more information about how to create a Vector Search index, see xref:[].
For information about how to run a Vector Search query, see xref:[].
// Don't forget to provide these links! And add to See Also

== See Also

* xref:search:search.adoc[]