= Use Vector Search for AI Applications
:page-topic-type: concept
:description: Use Couchbase Server's Vector Search features to add fast and accurate semantic search to your applications.

[abstract]
{description}
// Use the description you provided as a quick introduction to the page.

== About Vector Search

Vector Search builds on Couchbase Server's xref:search.adoc[Search Service] to provide vector index support.
You can use these new Vector Search indexes for Retrieval Augmented Generation (RAG) with an existing Large Language Model (LLM). 

Using Vector Search, Couchbase Server, and your chosen LLM, you can develop AI applications while giving context and up-to-date information from your own data.

You can develop applications that include: 

* *Similarity search:* Search for documents, products, images, and more that are similar to a given query.
Using vector embeddings to represent data, your end users can search based on descriptions, rather than using specific keywords.

* *Generative AI:* Create new text, images, and more based on a prompt given to the LLM.  

// More use cases worth calling out?

Vector Search supports integrations with frameworks like https://python.langchain.com/docs/get_started/introduction[LangChain^] to support AI application development. 
For more information about all frameworks and integrations supported by Vector Search and Couchbase Server, see xref:[].
//Don't forget to fill in this link!

== Using Vector Search Indexes

Use a Couchbase Server database to store the data you want to use to provide context to a LLM. 
Generate vector embeddings using your chosen LLM, then store the embeddings in an array inside your documents. 

Create a Vector Search index to use the vector embeddings from your data and find matches from a search query's generated vectors.

NOTE: When creating a Vector Search index, the dimension of your data vector embeddings must match the dimension for any search query vectors.

For more information about how to create a Vector Search index, see xref:[].
For information about how to run a Vector Search query, see xref:[].
// Don't forget to provide these links! And add to See Also

== See Also

* xref:search:search.adoc[]