= Statistics
:description: You can fetch Eventing Statistics for each deployed Function from an Eventing node using the Web Console or using the Capella UI.
:page-edition: Enterprise Edition

[abstract]
{description}


== Via the Capella UI Eventing Tab

As of 7.0.0, Eventing Statistics can be displayed in the Eventing main UI page for each deployed Function by clicking on the Function name to expand the Function controls. 
The following key metrics or Deployment Statistics are updated every 10 seconds by default and displayed as numeric values:

* *success*	- displays the number of processed Functions and also Eventing timer callbacks.
* *failure*	- displays the number of failures while processing the Eventing Function code.
* *timeout*	- displays the number of Functions which have encountered a timeout condition.
* *backlog* - displays the number of Functions in the backlog. 


In addition to the numeric statistics, you can also click the Log button (icon:fine-Lines[]) to display the log for any deployed function. 

== Via the Web Console's Custom Dashboards

Eventing Statistics, for each deployed Function, can be fetched from an Eventing node using the Web Console.

You can make custom dashboards for a node or a cluster to get aggregated Eventing statistics. 
Access the *Couchbase Web Console* > *Dashboard* page. 
Select "_new dashboard..._" from the *Choose Dashboard* dropdown, then "Add Group" and finally select "Add a Chart" (you of course are interested in Eventing charts). 

There are six Eventing measures (three rates + three counts) these Dashboard statistics are NOT per bucket and are NOT per function.

* Successful Function Invocations Rate
* Failed Function Invocations Rate
* Eventing Timeouts Rate
* Successful Function Invocations
* Failed Function Invocations
* Eventing Timeouts
