= Function: Advanced Sub-Document MUTATEIN array operation
:description: pass:q[Perform the Advanced Sub-Document MUTATEIN operation on an array where Eventing interacts with the Data service.]
:page-edition: Enterprise Edition
:tabs:

*Goal*: {description}

* This function *advancedMutateInArrayd* merely demonstrates the CAS free MutateIn operation on a document array field.
* Requires Eventing Storage (or metadata collection) and a "source" collection.
* Needs a Binding of type "bucket alias" (as documented in the Scriptlet).
* Will operate on any mutation where meta.id or the KEY equals "combine_landmark_names".
* You need to great an input document with KEY *combine_landmark_names* DATA *{ "id": "combine_landmark_names",  "landmark_names": [] }*
* Set a high number of workers in the Eventing Function's settings like 18
* The function will add 4,495 landmark names to an array without conflict in no particular order.
* For more information refer to xref:eventing-advanced-keyspace-accessors.adoc#sub-document-mutatein-operation[Sub-Document MUTATEIN Operation] in the detailed documentation.

[{tabs}]
====
advancedMutateInArray::
+
--
[source,javascript]
----
// To run configure the settings for this Function, advancedTouchOp, as follows:
//
// Version 7.6+
//   "Function Scope"
//     *.* (or try bulk.data if non-privileged)
//   "Listen to Location"
//     travel-sample.inventory.landmark
//   "Eventing Storage"
//     rr100.eventing.metadata
//   Binding(s)
//    1. "binding type", "alias name...", "bucket.scope.collection", "Access"
//       "bucket alias", "dst_col",       "bulk.data.source",        "read and write"

function OnUpdate(doc, meta) {
 var accum_meta = {"id": "combine_landmark_names" };
 couchbase.mutateIn(dst_col, accum_meta, [
    couchbase.MutateInSpec.arrayAppend("landmark_names", doc.name),
  ]);
}
----
--

Input Data Before Deploy::
+
--
[source,json]
----
INPUT: KEY combine_landmark_names

{
  "id": "combine_landmark_names",
  "landmark_names": []
}
----
--

Output Data After Deploy::
+
--
[source,json]
----
OUTPUT: KEY combine_landmark_names

{
  "id": "combine_landmark_names",
  "landmark_names": [
    "Gabriel's Wharf",
    "Blue Bear Performance Hall",
    "Circle Bar",
        *** 4490 lines removed ***
    "Quarry Bank Mill & Styal Estate",
    "Mad Cat Brewery",
    "Casbah Café"
  ]
}
----
--
====
