= Eventing Role-Based Access Control (RBAC)
:description: To create and manage Eventing Functions, you need the proper Organization Role, Project Role, or Cluster Access Credentials.

[abstract]
{description}

[#description]
== What is RBAC

Couchbase provides _Role-Based Access Control_ (RBAC), in which access privileges are assigned to fixed roles, which are in turn assigned to users, (each of which may be an administrator or an application) either _directly_ or _indirectly_, through _user-groups_.

A Couchbase _role_ permits one or more _resources_ to be accessed according to defined _privileges_.
Roles can be assigned to individual users, and to groups, by means of either the UI or the REST API.

Couchbase Server Enterprise Edition provides RBAC with multiple roles for finer access control.
Community Edition provides multiple users that can be assigned to a limited set of roles.

To be able to use the Eventing service through the Capella UI, you need to have one of the following organization or project roles:

he Organization Owner, Project Creator, or Organization Member role, as described in xref:organizations:organization-user-roles.adoc[].

* The Project Owner, Cluster Manager, or Data Writer role, as described in xref:projects:project-roles.adoc[Project Roles]. 

To be able to use the Eventing service, via an SDK or a REST API, your client application must have cluster access credentials with Read or Read/write access to the buckets, scopes, and collections that your Eventing functions listen to. 
Also, you need Write or Read/Write access to the buckets, scopes, and collections that the Eventing functions write to, as described in xref:clusters:manage-database-users.adoc[Manage Cluster Access Credentials]

NOTE: Most roles are assigned only on the _Enterprise Edition_ of Couchbase Server: on the _Community Edition_ of Couchbase Server, only the `bucket_full_access`, `admin`, and `ro_admin` roles can be assigned.

//I am not sure if the above Note is applicable to Capella as well! Kindly confirm if we need to keep it or delete it. 

For more information about the Couchbase Server authorization, see xref:server:learn:security/authorization-overview.adoc[Authorization].

For more information about roles and corresponding privileges, see xref:server:learn:security/roles.adoc[Roles].

For more information about managing users and groups, see xref:server:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups, and Roles].

//We will be adding more information on fine-grain RBAC later. 
//Hence am not sure if the following sections are required in the Capella docs for now! Kindly confirm if we need to keep them or delete them. 

== Function Scope

A bucket.scope combination is used for identifying functions belonging to the same group.

Only the "Eventing Full Admin" role and also the "Full Admin" role can set the bucket.scope to  *+*+.+*+*; all other Eventing non-privileged users need to define a *Function Scope* for their Eventing functions that references an existing resource of bucket.scope. 
This provides role-based isolation of Eventing functions between non-privileged users

include::partial$rbac-warning.adoc[]

Typically, you should set Function Scope to the `bucket.scope`
that holds the collection that is the source of your mutations to your Eventing Function.
This best practice ensures that you _do not_  inadvertently cause an Eventing Function to undeploy
by removing a *Function Scope* pointing to a resource that is not required for the function to run.

NOTE: A user can be assigned multiple "Eventing / Manage Scope Function" RBAC roles. If any of these roles match an existing Eventing Function's *Function Scope*, then that user can manage, modify, or delete the Eventing Function, even if it was created or imported by someone else.

== Privileged Users

If a user role of either "Full Admin" or "Eventing Full Admin", then by default this user has all the necessary access to every resource in a cluster required to run the Eventing Service and create and manage Eventing Functions.

When creating an Eventing Function, either of these roles can set the *Function Scope* to *+*+.+*+*;  no other RBAC role is allowed to use this *Function Scope*.

NOTE: When upgrading to 7.1, all Eventing Functions are assumed to be running as a privileged user and have their *Function Scope* set to *+*+.+*+* to ensure continuity of your Eventing Functions.

=== Full Admin v. Eventing Full Admin

Prior to 7.0.0, Eventing always runs as "Full Admin". This blocked some use cases and adoption as this role allowed creation of new users and the ability to escalate privilege sets. The  "Eventing Full Admin" role introduced in 7.0 simply removes the capability of creating users and assigning/modifying RBAC credentials, thus providing more security.

For the Function Scope or RBAC grouping, we will use the 'bulk.data' assuming you have the role of either "Full Admin" or "Eventing Full Admin". 
For standard or non-privileged users, refer to Role-Based Access Control.

== Eventing and RBAC for Non-privileged Users

NOTE: If a user role of either "Full Admin" or "Eventing Full Admin", then this user, by default, has all the necessary access to every resource in a cluster required to run the Eventing Service and create and manage Eventing Functions.

_In RBAC, although you can assign roles directly to a *USER*, it is generally more flexible to define a *GROUP* and assign that group or set of roles to a *USER*.
This allows reusing a *GROUP* across multiple users.

