= Eventing Access Control

:description: To create and manage Eventing Functions, you need the proper Organization Role, Project Role, or Cluster Access Credentials. 

[abstract]
{description}

[#description]
== Role-Based Access Control (RBAC)

Couchbase provides _Role-Based Access Control_ (RBAC), in which access privileges are assigned to fixed roles, which are in turn assigned to users, (each of which may be an administrator or an application) either _directly_ or _indirectly_, through _user-groups_.

A Couchbase _role_ permits one or more _resources_ to be accessed according to defined _privileges_.
Roles can be assigned to individual users, and to groups, by means of either the UI or the REST API. 

Couchbase Enterprise edition provides RBAC with multiple roles for finer access control. 

In Capella, RBAC is implemented at the organization, project, and cluster levels.

For a complete list of roles, see xref:learn:security/roles.adoc[Roles].

NOTE: Most roles can be assigned only on the _Enterprise Edition_ of Couchbase Server: on the _Community Edition_ of Couchbase Server, only the `bucket_full_access`, `admin`, and `ro_admin` roles can be assigned.

For more information, see xref:learn:security/authorization-overview.adoc[Authorization], and xref:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups, and Roles].

To learn more about Eventing RBAC, Function Scope, privileged and non-privileged users, and eventing RBAC roles see xref:eventing:eventing-rbac.adoc[Eventing Role-Based Access Control].

////
Writer's Note

I want to provide a link to the appropriate Server documentation. Will have to check how to do that and replace the above link to the Eventing RBAC Server doc.

Should we also include all the relevant RBAC information like Roles, privileges etc that are discussed in the Server documentation, here as well? or is it sufficient to just link to the Server documentation?

////

== Access Credentials
Eventing access credentials provide programmatic and application-level access to data on a cluster.
These credentials are separate from the xref:organizations:organization-user-roles.adoc[organization roles] and xref:projects:project-roles.adoc[project roles].
The Capella user account's organization and project roles control the access to the Capella UI, while Eventing access credentials control programmatic and application-level access to data.

Eventing access credentials are specific to a cluster and consist of an access name, password, and a set of access levels or roles, depending on the chosen credential type.

To be able to use the Eventing service through the Capella UI, you need to have one of the following organization or project roles:

* The Organization Owner, Project Creator, or Organization Member role, as described in xref:organizations:organization-user-roles.adoc[Organization Roles]

* The Project Owner or Data Writer role, as described in xref:projects:project-roles.adoc[Project Roles]

To be able to use the Eventing service via an SDK or a REST API, the client application must have Eventing access credentials with Read, Write, or Read/write access to the buckets, scopes, and collections that your Eventing functions listen to. 

Also provide Read, Write, or Read/Write access to the buckets, scopes, and collections that the Eventing functions write to, as described in xref:clusters:manage-database-users.adoc[Manage Cluster Access Credentials].

== Access Credential Types

The available Eventing access credential types are basic access credentials and advanced access credentials.

=== Basic Access Credentials
Allows you to assign read, write, or read/write access at the bucket, scope, and collection level.

For example, you can grant access to all buckets and scopes in a cluster, assign different access levels to individual buckets, or grant access to just a single collection. 

This allows you to mix and match access levels to different buckets, scopes, and collections in a cluster to match your application and security requirements. 
For more information, see the xref:clusters:manage-database-users.adoc[Cluster Access].

=== Advanced Access Credentials
Provides customized combinations of fine-grained privileges and access roles with precise control over individual operations. 

For example, allows you to assign access to the Owner, Project Creator, or Organization Member role, as described in xref:organizations:organization-user-roles.adoc[], or to the Project Owner or Data Writer role as described in xref:projects:project-roles.adoc[Project Roles]. 

=== Matrix for Eventing UI Access 
If the client is using Basic access credentials, then the user must have the "Eventing Full Admin" role, that provides full access to all Eventing functions and resources.

The following table summarizes the advanced access credentials and the mapping to be set for Couchbase Eventing Capella users for managing the Eventing Functions. 

[#table-eventing-uiaccess-privileges, cols="1,2,3,4",options="header"]
|===
| Action 
| Data Reader 
| Data Writer 
| Project Owner 

a|[#create-import-edit]
`*Create / Import / Edit*` 
a| No 
a| Yes 
a| Yes 

a|[#deploy-undeploy]
`*Deploy / Undeploy*` 
a| No 
a| Yes 
a| Yes 

a|[#view-logs-js-settings]
`*View Logs / JS / Settings*` 
a| Yes 
a| Yes 
a| Yes 

a|[#delete-function]
`*Delete Function*` 
a| No 
a| *Check* 
a| Yes 

a|[#export-function]
`*Export Function*`
a| Yes
a| Yes
a| Yes 

|=== 

NOTE: The Cluster Viewer and Cluster Manager roles do not grant Eventing privileges. 
The "Eventing / Manage Scope Function" role can be assigned to a user multiple times, each time with a different bucket.scope or bucket.

=== Programmatic Access via SDK / API
To prevent unauthorized access to your Eventing functions, you must use appropriate cluster access credentials with the necessary access levels or roles for your client applications. 
Data DCP Reader and Eventing / Manage Functions access are required to read from or write to the resources.

The following table summarizes the keyspace access permissions to be set for Couchbase Eventing users for managing the Eventing functions via SDK or API. 

[#table-eventing-keyspace-required-privileges, cols="1,2",options="header"]
|===
| Target Keyspace 
| Required Role / Privilege 

a|[#source-mutation]
`*Source / Mutation*`
a| Read or Read / Write 

a|[#metadata-storage]
`*Metadata / Storage*` 
a| Read or Write 

a|[#bindings]
`*Bindings*` 
a| Read or Read / Write 

|===

== See Also

* xref:clusters:cluster-rbac.adoc[]
* xref:clusters:manage-database-users.adoc[]
* xref:organizations:organizations.adoc[]
* xref:organizations:organization-user-roles.adoc[]
* xref:projects:projects.adoc[]
* xref:projects:project-roles.adoc[]
* xref:clusters:manage-database-users.adoc[]
* xref:clusters:allow-ip-address.adoc[]

////
Writer: Not sure if the above references are required. 
Kindly review and let me know if we need to have them!
////
