= Eventing Access Control

:description: To create and manage Eventing Functions, you need the proper Organization Role, Project Role, or Cluster Access Credentials. 

[abstract]
{description}

[#description]
////
== What is RBAC

Couchbase provides _Role-Based Access Control_ (RBAC), in which access privileges are assigned to fixed roles, which are in turn assigned to users, (each of which may be an administrator or an application) either _directly_ or _indirectly_, through _user-groups_.

A Couchbase _role_ permits one or more _resources_ to be accessed according to defined _privileges_.
Roles can be assigned to individual users, and to groups, by means of either the UI or the REST API.

Couchbase Server Enterprise Edition provides RBAC with multiple roles for finer access control.
Community Edition provides multiple users that can be assigned to a limited set of roles.

////

To be able to use the Eventing service through the Capella UI, you need to have one of the following organization or project roles: 

* The Organization Owner, Project Creator, or Organization Member role, as described in xref:organizations:organization-user-roles.adoc[].

* The Project Owner, Cluster Manager, or Data Writer role, as described in xref:projects:project-roles.adoc[Project Roles]. 

To be able to use the Eventing service, via an SDK or a REST API, your client application must have cluster access credentials with Read or Read/write access to the buckets, scopes, and collections that your Eventing functions listen to. 
Also, you need Write or Read/Write access to the buckets, scopes, and collections that the Eventing functions write to, as described in xref:clusters:manage-database-users.adoc[Manage Cluster Access Credentials].

////
 Commenting for Future consideration. 
 
== Function Scope

A bucket.scope combination is used for identifying functions belonging to the same group.

Only the "Eventing Full Admin" role and also the "Full Admin" role can set the bucket.scope to  *+*+.+*+*; all other Eventing non-privileged users need to define a *Function Scope* for their Eventing functions that references an existing resource of bucket.scope. 
This provides role-based isolation of Eventing functions between non-privileged users

include::partial$rbac-warning.adoc[]

Typically, you should set Function Scope to the `bucket.scope`
that holds the collection that is the source of your mutations to your Eventing Function.
This best practice ensures that you _do not_  inadvertently cause an Eventing Function to undeploy
by removing a *Function Scope* pointing to a resource that is not required for the function to run.

NOTE: A user can be assigned multiple "Eventing / Manage Scope Function" RBAC roles. If any of these roles match an existing Eventing Function's *Function Scope*, then that user can manage, modify, or delete the Eventing Function, even if it was created or imported by someone else.

////