= Eventing Access Control

:description: To create and manage Eventing Functions, you need the proper Organization Role, Project Role, or Cluster Access Credentials. 

[abstract]
{description}

[#description]
== Access Eventing with the Capella UI 
To be able to use the Eventing service through the Capella UI, you must have one of the following project roles: 

* Data Reader
* Data Writer
* Project Owner

For more information about the project roles and their privileges, see xref:projects:project-roles.adoc[].

The following table summarizes the actions that you can perform with the Eventing Service using each of these project roles.

[#table-eventing-uiaccess-privileges, cols="2s,1,1,1",options="header"]
|===
| Action 
| Data Reader 
| Data Writer 
| Project Owner 

a|[#create-import-edit]
Create / Import / Edit Function 
a| No 
a| Yes 
a| Yes 

a|[#deploy-undeploy]
Deploy / Undeploy
a| No 
a| Yes 
a| Yes 

a|[#view-logs-js-settings]
View Logs / JavaScript/ Settings
a| Yes 
a| Yes 
a| Yes 

a|[#delete-function]
Delete Function 
a| No 
a| Yes
a| Yes 

a|[#export-function]
Export Function
a| Yes
a| Yes
a| Yes 

|=== 

NOTE: The Cluster Viewer and Cluster Manager roles do not grant Eventing privileges. 


== Access Eventing with Cluster Access Credentials
To access the Eventing Service programmatically via an SDK or API, your client must have the appropriate cluster access credentials, with access to the buckets, scopes, and collections that your Eventing functions use. 
For more information, see xref:clusters:cluster-rbac.adoc[].

The following table summarizes the basic access levels or advanced access privileges that your cluster access credentials must have, for each of the target keyspaces that your Eventing functions read from or write to. 

[#table-eventing-keyspace-required-privileges, cols="1,1,1",options="header"]
|===
| Target Keyspace 
| Basic Access Level
| Advanced Access Privilege

a|[#source-mutation]
Source / Mutation
a| `Read` or `Read / Write`
a| `Data Read` and `Eventing Manage`

a|[#metadata-storage]
Metadata / Storage 
a| `Read / Write`
a| `Data Read` and `Eventing Manage`

a|[#bindings]
Bindings
a| `Read` or `Read / Write`
a| `Data Read` and `Eventing Manage` 

|===

== See Also

* xref:organizations:organizations.adoc[]
* xref:projects:projects.adoc[]
* xref:clusters:cluster-rbac.adoc[]

