= Query without Indexes
:page-topic-type: concept
:page-status: Couchbase Server 7.6
:description: Sequential scans enable you to query a keyspace, even if the keyspace has no indexes.

:authorization-overview: xref:learn:security/authorization-overview.adoc
:install-sample-buckets: xref:manage:manage-settings/install-sample-buckets.adoc

[abstract]
{description}

.Examples on this Page
****
The examples in this topic use the travel-sample dataset which is shipped with Couchbase Server.
For instructions on how to install the sample bucket, see {install-sample-buckets}[].
****

== Sequential Scans

If a keyspace does not have any suitable primary or secondary indexes for a query, the Query service can fall back on a sequential scan of the data to retrieve the document keys.
(A sequential scan is also known as a K/V range scan.)

Sequential scans are intended for simple, ready access to data, and are not intended as a high performance solution.

Sequential scans are best suited to small collections where key order is unimportant, or where the overhead of maintaining an index can't be justified.
For larger collections and greater performance, define the appropriate indexes to speed up your queries.
For ordered document key operations, a primary index provides the same functionality, and will outperform a sequential scan.

NOTE: Sequential scans are unavailable on ephemeral buckets.

== Prerequisites

[discrete]
===== RBAC Privileges

Users must have the *Query Use Sequential Scans* role on the keyspace to be able to execute a request with a sequential scan.
For more details about user roles, see
{authorization-overview}[].

== Examples

For this example, set the query context to the `tenant_agent_01` scope in the travel sample dataset.
For more information, see xref:n1ql:n1ql-intro/queriesandresults.adoc#query-context[Query Context].

====
[source,sqlpp]
----
SELECT * FROM system:indexes
WHERE scope_id = "tenant_agent_01"
  AND keyspace_id = "users";
----

[source,json]
----
{
  "results": []
}
----

The collection has no indexes.
====

====
[source,sqlpp]
----
SELECT name FROM users;
----

[source,json]
----
[
  {
    "name": "Haley Rohan"
  },
  {
    "name": "Johnnie Lind"
  },
  {
    "name": "Verdie Jaskolski"
  },
  {
    "name": "Marc Mills"
  },
  {
    "name": "Valentine Funk"
  },
  {
    "name": "Jocelyn Wuckert"
  },
  {
    "name": "Gretchen Auer"
  },
  {
    "name": "Meghan Homenick"
  },
  {
    "name": "Kraig Hilll"
  },
  {
    "name": "Destini Turcotte"
  },
  {
    "name": "Sienna Cummerata"
  }
]
----

The query returns 11 documents.
====

====
[source,sqlpp]
----
EXPLAIN SELECT name FROM users;
----

[source,json]
----
[
  {
    "plan": {
      "#operator": "Sequence",
      "~children": [
        {
          "#operator": "PrimaryScan3",
          "bucket": "travel-sample",
          "index": "#sequentialscan",
          "index_projection": {
            "primary_key": true
          },
          "keyspace": "users",
          "namespace": "default",
          "scope": "tenant_agent_01",
          "using": "sequentialscan"
        },
        {
          "#operator": "Fetch",
          "bucket": "travel-sample",
          "early_projection": [
            "name"
          ],
          "keyspace": "users",
          "namespace": "default",
          "scope": "tenant_agent_01"
        },
        {
          "#operator": "Parallel",
          "~child": {
            "#operator": "Sequence",
            "~children": [
              {
                "#operator": "InitialProject",
                "discard_original": true,
                "preserve_order": true,
                "result_terms": [
                  {
                    "expr": "(`users`.`name`)"
                  }
                ]
              }
            ]
          }
        }
      ]
    },
    "text": "SELECT name FROM users;"
  }
]
----

The query uses a Primary Scan called `sequentialscan`.
====

== Monitor Sequential Scans

You can monitor sequential scans using the `completed_requests` catalog.

[source,sqlpp]
----
SELECT * FROM system:completed_requests
WHERE phaseCounts.`primaryScan.Seq` IS NOT MISSING;
----

[source,json]
----
[
  {
    "completed_requests": {
      "clientContextID": "4eb44ea6-170a-4700-ae79-e22f57100e43",
      "cpuTime": "820.464µs",
      "elapsedTime": "4.728840089s",
      "errorCount": 0,
      "errors": [],
      "n1qlFeatCtrl": 76,
      "node": "127.0.0.1:8091",
      "phaseCounts": {
        "fetch": 11,
        "primaryScan": 11,
        "primaryScan.Seq": 11
      },
      "phaseOperators": {
        "authorize": 1,
        "fetch": 1,
        "primaryScan": 1,
        "primaryScan.Seq": 1,
        "project": 1,
        "stream": 1
      },
      "phaseTimes": {
        "authorize": "8.471µs",
        "fetch": "107.915507ms",
        "instantiate": "19.769µs",
        "parse": "870.813µs",
        "plan": "293.479µs",
        "plan.index.metadata": "17.998µs",
        "plan.keyspace.metadata": "7.601µs",
        "primaryScan": "4.72730895s",
        "primaryScan.Seq": "4.72730895s",
        "project": "161.687µs",
        "run": "4.727550611s",
        "stream": "234.174µs"
      },
      "queryContext": "default:travel-sample.tenant_agent_01",
      "remoteAddr": "127.0.0.1:43164",
      "requestId": "d80b0d08-1794-4932-8188-af7e7e57b7b3",
      "requestTime": "2024-02-09T15:05:09.343Z",
      "resultCount": 11,
      "resultSize": 435,
      "scanConsistency": "unbounded",
      "serviceTime": "4.728754078s",
      "state": "completed",
      "statement": "SELECT name FROM users;",
      "statementType": "SELECT",
      "useCBO": true,
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0",
      "users": "builtin:Administrator",
      "~qualifier": "threshold"
    }
  },
  {
    "completed_requests": {
      "clientContextID": "04a32d09-028d-48a5-88e5-c927f574190c",
      "cpuTime": "47.303832ms",
      "elapsedTime": "904.030735ms",
      "errorCount": 0,
      "errors": [],
      "n1qlFeatCtrl": 76,
      "node": "127.0.0.1:8091",
      "phaseCounts": {
        "fetch": 4495,
        "primaryScan": 4495,
        "primaryScan.GSI": 4495
      },
      "phaseOperators": {
        "authorize": 1,
        "fetch": 1,
        "primaryScan": 1,
        "primaryScan.GSI": 1,
        "project": 1,
        "stream": 1
      },
      "phaseTimes": {
        "authorize": "9.074µs",
        "fetch": "873.153484ms",
        "instantiate": "24.38µs",
        "parse": "400.687µs",
        "plan": "281.728µs",
        "plan.index.metadata": "24.149µs",
        "plan.keyspace.metadata": "9.682µs",
        "primaryScan": "28.154968ms",
        "primaryScan.GSI": "28.154968ms",
        "project": "17.0392ms",
        "run": "903.212145ms",
        "stream": "5.641339ms"
      },
      "queryContext": "default:travel-sample.inventory",
      "remoteAddr": "127.0.0.1:43164",
      "requestId": "15d4bc72-3fec-4cf6-b525-8d7ddc1f131f",
      "requestTime": "2024-02-09T15:58:48.711Z",
      "resultCount": 4495,
      "resultSize": 45781,
      "scanConsistency": "unbounded",
      "serviceTime": "903.935582ms",
      "state": "completed",
      "statement": "SELECT image_direct_url FROM landmark;",
      "statementType": "SELECT",
      "useCBO": true,
      "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0",
      "users": "builtin:Administrator",
      "~qualifier": "threshold"
    }
  }
]
----

In most environments, sequential scans that produce a large number of keys are an indication of a missing index.
To help identify such cases, a completed requests qualifier is automatically added that captures requests where more than 10000 keys have been returned by sequential scans.
The `~qualifier` field in `completed_requests` indicates the reason the request was captured.
Statistics on sequential scan usage are also available in request profiling information.
