= Storage Settings
:description: All indexes in Couchbase Capella use the Couchbase Plasma storage engine. 
:page-topic-type: concept
:page-aliases: indexes:storage-modes,understanding-couchbase:services-and-indexes/indexes/storage-modes,architecture:index-storage

[abstract]
{description}


[#standard-index-storage]
== Standard Index Storage

In Couchbase Capella, _Standard_ is the storage-setting for Secondary Indexes: the indexes are saved on disk; in a disk-optimized format that uses both memory and disk for index-update and scanning.
The performance of standard index storage depends on overall I/O performance.

The standard global secondary index uses a B-Tree index and keeps the optimal working set of data in the buffer.
This means the total size of the index can be much bigger than the amount of memory available in each index node.

Standard index-storage is supported by the _Plasma_ storage engine.
Plasma is highly scalable and performant storage engine that is optimized specifically for indexes.
Compaction is handled automatically.


== Plasma Memory Enhancements

Couchbase Server Version 7.1 provides the following enhancements for Plasma:

* Per page _Bloom Filters_.

* In-memory compression.

These are described below.

[#per-page-bloom-filters]
=== Per Page Bloom Filters

A https://en.wikipedia.org/wiki/Bloom_filter[Bloom filter^] gives guidance as to whether a searched-for item resides on disk.
By indicating that the item is _not_ on disk, the filter prevents unnecessary on-disk searches.

If Bloom filters are enabled (which is the default), when a lookup occurs, and the correct Plasma page is located, the Bloom filter indicates either that the item is _not_ on the page, or that it _may be_ on the page.
If the filter indicates that:

* The item is _not_ on the page, then the item is not on disk, and no disk read need occur.

* The item _may be_ on the page, then the item can continue to be searched for, and a disk read must therefore occur.

The consequent reduction in disk reads promotes the efficiency of mutation processing, when the mutations are insert heavy.

Bloom filters can be enabled or disabled by means of the Couchbase Web Console UI, or the REST API.
See the information provided on establishing xref:manage:manage-settings/general-settings.adoc[General] settings for the cluster.

=== In-Memory Compression

In Couchbase Server Version 7.1, Plasma memory-management routinely performs the _compression_ of a subset of items, in order to free memory; and thereby, due to the additional memory made available, keep a greater number of items in memory overall.
By keeping more items in memory, the need for disk reads is reduced, as are corresponding latencies.

The selection of items to be compressed occurs periodically.
Only items that have already been flushed to disk are compressed: after compression, such items are principal candidates for subsequent ejection.

Disk-flushing occurs every ten minutes: items not yet flushed to disk are not compressed; nor is any recently used item.
In consequence, items most likely to be accessed remain _uncompressed_ in memory, and are therefore accessible with the least latency; while items less likely to be accessed are retained in memory in _compressed_ form, until their ejection; beyond which, they must be accessed through disk reads.

This new model of memory usage leads to higher _residence ratios_, and greater _access-efficiency_; at the cost of some additional CPU utilization, due to the more frequent performance of compression and decompression routines.
