= Integrations, Connectors, and Tools
:page-toclevels: 2
:page-topic-type: concept
:description: Integrate Couchbase with your development ecosystem and production and deployment tools.


[abstract]
{description}


////
Documenting All Couchbase Integrations

Replacing https://developer.couchbase.com/open-source-projects/ with a page in the docs, to reflect and promote Couchbase’s reach across a broad ecosystem of platforms, tools, and integrations.


Note, we have individual pages already for integrations for two of our SDKs:
https://docs.couchbase.com/java-sdk/current/project-docs/third-party-integrations.html
https://docs.couchbase.com/ruby-sdk/current/project-docs/third-party-integrations.html
…which give a model for how we deal with mentioning unsupported projects in the docs.

The first task is to assemble a list of all of the integrations to include, and a little information on the level of support, and likely future viability of each project.
////

// TABLE
//  / info / links / Capella / on-prem


Third-party and community products and integrations -- 
although not by and large supported by Couchbase --
are a vital tool for most larger development projects.

On this page:

* <<partner-integrations-with-couchbase,Partner integrations for Couchbase Capella and self-managed Server>>
* <<????,Connectors>>
* <<sdk-language-ecosystem,SDK Language Ecosystem>>
** <<jvm-sdks,JVM>>
*** Java
*** Kotlin
*** Scala
* C
// * {cpp}
* .NET
** Go
** Node.js
** PHP
** Python
** Ruby




[#partner-integrations-with-couchbase]
== Partner Integrations with Couchbase


.Partner Integrations List
[cols=""]
|===
| Integration | Summary | Links | Capella | Self-managed


| Netlify
| Use Couchbase Capella and Netlify Serverless Functions to handle dynamic content without needing infrastructure.
a| 
* https://www.netlify.com/integrations/couchbase/[Netlify partner page]
* https://developer.couchbase.com/tutorial-quickstart-netlify[Tutorial]
| ✔
| ✖


| Vercel
| 
a|
* Vercel partner page
* [Tutorial]
* [blog]
| ✔
| ✖


| HashiCorp Verified Terraform Provider
| 
| 
* https://github.com/couchbasecloud/terraform-provider-couchbasecapella[GitHub repo]
| ✔
| 
// AV-42685 Capella for H Vault

| VS Code extension for Couchbase
| 
a|
* https://marketplace.visualstudio.com/items?itemName=Couchbase.vscode-couchbase[Visual Studio Marketplace]
* https://github.com/couchbaselabs/VSCode-Couchbase/blob/main/GETTING-STARTED.md[Tutorial]
* https://github.com/couchbaselabs/VSCode-Couchbase/blob/main/SNIPPETS.md[Code snippets]
| ✔
| ✔ 


| JetBrains
| 
a|
* https://plugins.jetbrains.com/plugin/22131-couchbase[JetBrains Marketplace]
* [Tutorial]
| ✔
| ✔


| Molo17
| 
| 
| 
| 


| 
| 
| 
| 
| 
|===





[connected-ecosystem?????]
== Connected Ecosystem


Couchbase develops and supports connectors for:
* Elasticsearch and OpenSearch
* The Kafka Connect Framework
* Apache Spark Data Processing Platform
* The Tableau interactive data visualization platform

Couchbase ODBC and JDBC drivers enable any application based on the ODBC/JDBC standards, for example Microsoft Excel, QlikView, or SAP Lumira, as well as Tableau, to connect to a Couchbase Server or cluster.



.Big Data Connectors
[cols=""]
|===
| Connector
| Docs
| Source
| 
| Other Integrations


| Elasticsearch
| xref:elasticsearch-connector:getting-started.adoc[]
| 
| 
| 


| Kafka
| xref:kafka-connector:index.adoc[]
| https://github.com/couchbase/kafka-connect-couchbase[]
| 
| 


| 
| 
| https://github.com/couchbase/couchbase-spark-connector[Couchbase Spark Connector on GitHub]
| 
a| 
* https://docs.databricks.com/_extras/notebooks/source/couchbase.html[Apache Spark Notebook]


| Tableau
| 
| 
| 
| 


| ODBC / JDBC
| 
| 
| 
| 

|===


[#sdk-language-ecosystem]
== SDK Language Ecosystem

Couchbase has SDKs in ten popular languages --
xref:c-sdk:hello-world:overview.adoc[C], 
xref:dotnet-sdk:hello-world:overview.adoc[C# (.NET)], 
xref:go-sdk:hello-world:overview.adoc[Go], 
xref:java-sdk:hello-world:overview.adoc[Java], 
xref:kotlin-sdk:hello-world:overview.adoc[Kotlin], 
xref:nodejs-sdk:hello-world:overview.adoc[Node.js], 
xref:php-sdk:hello-world:overview.adoc[PHP], 
xref:python-sdk:hello-world:overview.adoc[Python], 
xref:ruby-sdk:hello-world:overview.adoc[Ruby], and 
xref:scala-sdk:hello-world:overview.adoc[Scala].

If you develop in one of these languages, you may be interested in (or already using) other libraries in that language's ecosystem, and wondering if it will integrate with Couchbase.

There are too many third party integrations to evaluate and list (and absence of a mention in these pages is no judgement on importance or quality), but the following are well worth investigating:


=== JVM SDKs


** JVM

The JVM SDKs -- Java, Kotlin, and Scala -- can all benefit from the same integrations.
Thus 


Apache Camel Quarkus
Apache Camel with CData JDBC Driver for Couchbase
(Talend? Spring Boot?) https://github.com/Talend/apache-camel/blob/master/components/camel-couchbase/src/main/docs/couchbase-component.adoc

https://www.jhipster.tech/using-couchbase/
// from their site:
////
When Couchbase is selected:

Spring Data Couchbase will be used to access the database. This is very close to Spring Data JPA, and this is why Couchbase support is very close to the (default) JPA support
Couchmove is used instead of Liquibase to manage database changes
The entity sub-generator will not ask you for entity relationships, as you can’t have relationships with a NoSQL database (at least not in the way you have relationships with JPA)
Couchbase Testcontainers is used to launch a containerized version of the database for running unit tests.
////

// Micronaut Framework is a modern, JVM-based, full stack Java framework designed for building modular, easily testable JVM applications with support for Java, Kotlin and the Groovy language.
https://github.com/micronaut-projects/micronaut-core
https://github.com/micronaut-projects/micronaut-couchbase

Scala and Java:
https://github.com/mumoshu/play2-memcached
// Does it work with 7.x?

https://spring.io/projects/spring-data-couchbase


*** Java
*** Kotlin
*** Scala
* C
// * {cpp}
* .NET
** Go
** Node.js
** PHP

////
So Is the community project linked (https://github.com/friendsofcat/laravel-couchbase ) in ticket  description the one that you were referring to or is this https://github.com/ytake/Laravel-Couchbase the one you were thinking about. The latter has Sergey Avseyev  involved but not updated for a while.
////


** Python
** Ruby


=== Interactive Shells

Couchbase Shell (cbsh) -- in Developer Preview -- is an interactive shell, based upon nushell, which you can use to extract, transform, and load different data formatsin Couchbase.

You can also use IDEs interactively with Couchbase, through our VS Code and JetBrains plugins, <<partner-integrations-with-couchbase,see above>>.


Some languages, such as Ruby, come with REPLs (interactive shells) as standard -- as is normal with functional programming languages.
Others have them available as _Notebooks_, such as Python, with https://jupyter.org/[Jupyter Notebook] (which works with _several_ different languages), through which you can interactively develop functionality for a Couchbase app, or blend with analytic tools and charts.



////



| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 

////
////
IDEs
VS Code plugin β
JetBrains plugin α

Other
Java / JVM
Apache Camel
JHipster with Couchbase
Micronaut Couchbase
Scala Play Framework Cache
Spring Data Couchbase
https://github.com/liquibase/liquibase-couchbase 
.NET
Akka.NET
Linq 2 Couchbase
SignalR
Node.js
Ottoman
Golang
Bleve
Analytics
Apache Spark Notebook
Data Migration, Integrations & Backup
Apache Nifi
cbbackup and cbrestore
Elastic Search
Kafka
Spark
SQL Server to Couchbase
Connectors
ODBC and JDBC Drivers
Elasticsearch Plug-in
Kafka Connector
Spark Connector
Ruby
Doctrine 
https://github.com/doctolib/couchbase-orm 
PHP
Laravel
Schema Management
couchmove
couchbase-index-manager
SDKs and ORMs
.NET Core Extensions
ASP.NET Integration
Handcouchbaseentity
Linq2Couchbase
Ottoman
Spring Data
Spring Session
sql-formatter
synctos Sync Function
CLIs
Couchbase-Lite-CLI
Couchbase Shell or cbsh
Test Data Generation
couchbasefakeit FakeIt Docker
YCSB
Load Testing Tools
MeepMeep - .NET workload gen
N1QLBack
Deployment: Containers and K8s
Docker Hub for Couchbase
Helm Charts for Couchbase
Mobile
Couchbase Lite for Dart and Flutter
Cordova Plugin
Ionic Framework


////





