= Integrations, Connectors, and Tools
:page-toclevels: 2
:page-topic-type: concept
:description: Integrate Couchbase with your development ecosystem and production and deployment tools.


[abstract]
{description}


////
Documenting All Couchbase Integrations

Replacing https://developer.couchbase.com/open-source-projects/ with a page in the docs, to reflect and promote Couchbase’s reach across a broad ecosystem of platforms, tools, and integrations.


Note, we have individual pages already for integrations for two of our SDKs:
https://docs.couchbase.com/java-sdk/current/project-docs/third-party-integrations.html
https://docs.couchbase.com/ruby-sdk/current/project-docs/third-party-integrations.html
…which give a model for how we deal with mentioning unsupported projects in the docs.

The first task is to assemble a list of all of the integrations to include, and a little information on the level of support, and likely future viability of each project.
////

// TABLE
//  / info / links / Capella / on-prem


Third-party and community products and integrations -- 
although not by and large supported by Couchbase (see <<#support-model,Support Model section>>) --
are a vital tool for most larger development projects.

////
On this page:

* <<partner-integrations-with-couchbase,Partner integrations for Couchbase Capella and self-managed Server>>
* <<big-data-connectors,Connectors>>
** <<interactive-shells,Interactive Shells>>
* <<sdk-language-ecosystem,SDK Language Ecosystem>>
** <<jvm-sdks,JVM>>
*** Java
*** Kotlin
*** Scala
** C
** .NET
** Go
** Node.js
** PHP
** Python
** Ruby

// added soon:
// * {cpp}

////

These are examples of integrations that Couchbase or partners have developed to enhance Couchbase, Capella, and partner services.


[#partner-integrations-with-couchbase]
== Partner Integrations


.Partner Integrations List
[cols="20,45,30,30,30,28"]
|===
| Integration | Summary | Links | Capella | Self-managed |  <<#support-model,Support Model>>


| Netlify
| Use Couchbase Capella and Netlify Serverless Functions to handle dynamic content without needing infrastructure.
a| 
* https://www.netlify.com/integrations/couchbase/[Netlify partner page]
* https://developer.couchbase.com/tutorial-quickstart-netlify[Tutorial]
| ✔
| ✖
| Couchbase Officially Supported


| Vercel
| Easy build and deploy for your applications.
a|
* https://vercel.com/integrations/couchbase-capella[Vercel partner page]
* [Tutorial]
* [blog]
| ✔
| ✖
| Couchbase Officially Supported

////
| HashiCorp Verified Terraform Provider
| Update and manage Couchbase Capella resources as code through HashiCorp Terraform.
a| 
* https://github.com/couchbasecloud/terraform-provider-couchbasecapella[GitHub repo]
| ✔
| ✖
| Couchbase Officially Supported
// AV-42685 Capella for H Vault
////

| Molo17 GlueSync
| Real-time, cloud-native data replication suite for NoSQL.
a| 
* https://www.couchbase.com/partners/molo17/[Intro & Tutorial]
* https://molo17.com/gluesync/[GlueSync homepage]
| ✔
| ✔
| Partner Supported
|===






== IDE Integrations


.IDE Plugins
[cols="20,45,30,30,30,35"]
|===
| Integration | Summary | Links | Capella | Self-managed |  <<#support-model,Support Model>>

| VS Code extension for Couchbase
| A seamless experience for Couchbase Server users who want to work within the popular Visual Studio Code editor.
a|
* https://marketplace.visualstudio.com/items?itemName=Couchbase.vscode-couchbase[Visual Studio Marketplace]
* https://github.com/couchbaselabs/VSCode-Couchbase/blob/main/GETTING-STARTED.md[Tutorial]
* https://github.com/couchbaselabs/VSCode-Couchbase/blob/main/SNIPPETS.md[Code snippets]
| ✔
| ✔ 
| Couchbase Community Support


| JetBrains
| Provides support for Couchbase in JetBrains IDEs --  to develop Couchbase applications, complete with code completion, syntax highlighting, and debugging support.
a|
* https://plugins.jetbrains.com/plugin/22131-couchbase[JetBrains Marketplace]
// * [Tutorial]
* https://github.com/couchbaselabs/couchbase_jetbrains_plugin[GitHub source repo]
| ✔
| ✔
| Couchbase Community Support
|===



== Data Tools

Import, export, and query data from the command line.

.Data Tools
[cols="20,45,30,30,30,35"]
|===
| Integration | Summary | Links | Capella | Self-managed |  <<#support-model,Support Model>>


| Couchbase Shell (cbsh)
| Interactive shell, based upon nushell, which you can use to extract, transform, and load different data formats in Couchbase.
a| 
| 
| 
| Couchbase Officially Supported (currently in _Developer Preview_)


| cbimport
| Utilitly for importing data into Couchbase clusters.
Included in self-managed Couchbase Server, or downloadable as part of the xref:cloud:reference:command-line-tools.adoc#download-and-install-the-couchbase-command-line-tools[Capella Tools package].
a| https://docs.couchbase.com/server/current/tools/cbimport.html
| 
| 
| Couchbase Officially Supported


| cbexport
| 
a| https://docs.couchbase.com/server/current/tools/cbexport.html
| 
| Couchbase Officially Supported


| cbbackupmgr
| 
| 
| 
| 
| Couchbase Officially Supported
| ===


=== Other Shells

Some languages, such as Ruby, come with REPLs (interactive shells) as standard -- as is normal with many programming languages.
Others have them available as _Notebooks_, such as Python, with https://jupyter.org/[Jupyter Notebook] (which works with _several_ different languages), through which you can interactively develop functionality for a Couchbase app, or blend with analytic tools and charts.



[big-data-connectors]
== Big Data Connectors


Couchbase develops and supports connectors for:

* Elasticsearch and OpenSearch
* The Kafka Connect Framework
* Apache Spark Data Processing Platform
* The Tableau interactive data visualization platform

Couchbase ODBC and JDBC drivers enable any application based on the ODBC/JDBC standards, for example Microsoft Excel, QlikView, or SAP Lumira, as well as Tableau, to connect to a Couchbase Server or cluster.



.Big Data Connectors
[cols="20,45,30,30,30,17"]
|===
| Connector | Summary | Docs | Source | Other Integrations | <<#support-model,Support Model>>


| Elasticsearch
| Replicate your documents from Couchbase Server or Capella to Elasticsearch or OpenSearch in near real time. 
| xref:elasticsearch-connector:getting-started.adoc[]
| https://docs.couchbase.com/elasticsearch-connector/current/release-notes.html[]
| https://docs.couchbase.com/elasticsearch-connector/current/autonomous-operations.html[AO Mode]
| Couchbase Official Support


| Kafka
| A plug-in for the Kafka Connect framework, which provides source and sink components.
| xref:kafka-connector:index.adoc[]
| https://github.com/couchbase/kafka-connect-couchbase[]
| https://kafka.apache.org/uses[Use cases]
| Couchbase Official Support


| Spark
| Connect to the scalable computing engine for Big Data.
| https://docs.couchbase.com/spark-connector/current/index.html[]
| https://github.com/couchbase/couchbase-spark-connector[Couchbase Spark Connector on GitHub]
a| 
* https://docs.databricks.com/_extras/notebooks/source/couchbase.html[Apache Spark Notebook]
| Couchbase Official Support


| Tableau
| Integrate Couchbase Server tabular views and the Tableau interactive data visualization platform.
| https://docs.couchbase.com/tableau-connector/current/index.html[]
| https://www.tableau.com/products/desktop/download[Tableau Desktop Downloads]
| https://www.tableau.com/products/server[Other Tableau Integrations]
| Couchbase Official Support


| ODBC / JDBC
| Easily access live Couchbase data from BI, Analytics, Reporting, ETL, & Custom Apps.
| https://docs.couchbase.com/server/current/connectors/odbc-jdbc-drivers.html[Couchbase ODBC and JDBC Drivers]
| https://www.cdata.com/drivers/couchbase/docs/[CData Driver]
a| 
* https://www.cdata.com/drivers/couchbase/#section-etl-anchor[Popular Data Warehousing Integrations]
* https://www.cdata.com/drivers/couchbase/#section-data-anchor[Data Management Tools]
* https://www.cdata.com/drivers/couchbase/#section-dev-anchor[Developer Tools]
* https://www.cdata.com/drivers/couchbase/#section-bi-anchor[BI & Data Visualization]
| Partner Supported
|===


[#sdk-language-ecosystem]
== SDK Language Ecosystem

Couchbase has SDKs in ten popular languages --
xref:c-sdk:hello-world:overview.adoc[C], 
xref:dotnet-sdk:hello-world:overview.adoc[C# (.NET)], 
xref:go-sdk:hello-world:overview.adoc[Go], 
xref:java-sdk:hello-world:overview.adoc[Java], 
xref:kotlin-sdk:hello-world:overview.adoc[Kotlin], 
xref:nodejs-sdk:hello-world:overview.adoc[Node.js], 
xref:php-sdk:hello-world:overview.adoc[PHP], 
xref:python-sdk:hello-world:overview.adoc[Python], 
xref:ruby-sdk:hello-world:overview.adoc[Ruby], and 
xref:scala-sdk:hello-world:overview.adoc[Scala].

If you develop in one of these languages, you may be interested in (or already using) other libraries in that language's ecosystem, and wondering if it will integrate with Couchbase.

There are too many third party integrations to evaluate and list (and absence of a mention in these pages is no judgement on importance or quality), but the following are well worth investigating:

While Couchbase can't evaluate and list every possible third-party integration, we've provided a list of some you might consider in the sections below.


=== JVM SDKs


The JVM SDKs -- Java, Kotlin, and Scala -- can all benefit from the same integrations.

The Couchbase Java SDK is a first class citizen in the https://spring.io/projects/spring-data-couchbase[Spring Data] world, and there are many examples of using the SDK with https://blog.couchbase.com/couchbase-spring-boot-spring-data/[Spring Boot] and Spring Data (and Spring Data JPA).

Couchbase also supports integrating with xref:3.2@spark-connector:ROOT:java-api.adoc[Spark].

////
// Need checking (especially Flink):
Many dataflow tools integrate with Couchbase, including https://github.com/apache/nifi/tree/main/nifi-nar-bundles/nifi-couchbase-bundle[Apache NiFi], 
https://wildfly-extras.github.io/wildfly-camel/#_camel_couchbase[Apache Camel] 
(also used with https://github.com/Talend/apache-camel/blob/master/components/camel-couchbase/src/main/docs/couchbase-component.adoc[Talend]),
and https://github.com/couchbaselabs/flink-connector-couchbase[Apache Flink].
Why not make development easier, and use https://blog.couchbase.com/create-a-zeppelin-interpreter-for-couchbase/[Apache Zeppelin]?
////


==== SQL Migration

https://github.com/differentway/couchmove[Couchmove] is an open-source Java migration tool for Couchbase, inspired by Flyway.
It can help you "track, manage and apply changes, in your Couchbase buckets."
The philosophy of the project claims to "strongly favor simplicity and convention over configuration".

Couchmove, rather than https://github.com/liquibase/liquibase-couchbase[Liquibase] is used with Spring Data by https://www.jhipster.tech/using-couchbase/[JHipster], for deployment in microservice architectures.


In CouchMove, you write your migrations in {sqlpp_url}[{sqlpp} (formerly N1QL)], while in https://github.com/couchbaselabs/CouchVersion[CouchVersion], you can write them using the Java SDK, which essentially allow you to create more complex migrations.
CouchVersion provides a new approach for adding changes (change sets) based on Java classes and methods with appropriate annotations.

////
// Micronaut Framework is a modern, JVM-based, full stack Java framework designed for building modular, easily testable JVM applications with support for Java, Kotlin and the Groovy language.
https://github.com/micronaut-projects/micronaut-core
https://github.com/micronaut-projects/micronaut-couchbase

Scala and Java:
https://github.com/mumoshu/play2-memcached
// Does it work with 7.x?

https://spring.io/projects/spring-data-couchbase
////

////
* C
// * {cpp}
* .NET
** Go
** Node.js
** PHP
////

=== Node.js

https://ottomanjs.com/[Ottoman] is an ODM (Object Document Mapper) for Couchbase.
It offers a https://ottomanjs.com/docs/advanced/sdk-comparison#supportability-and-sustainability[several advantages] in working with document shape and data accuracy.


=== PHP
????
So Is the community project linked (https://github.com/friendsofcat/laravel-couchbase ) in ticket  description the one that you were referring to or is this https://github.com/ytake/Laravel-Couchbase the one you were thinking about. The latter has Sergey Avseyev  involved but not updated for a while.
????

////
** Python
** Ruby
////

=== Ruby

The Couchbase Ruby SDK integrates well with Ruby-on-Rails, particularly for use as a https://guides.rubyonrails.org/caching_with_rails.html#cache-stores[Rails Cache Store^] (see our xref:ruby-sdk:project-docs:third-party-integrations.adoc[config guide]).


== Support Model



.Support Model
[cols="20,88"]
|===
| Support Level
| Definitions

| Partner Supported
| This integration is developed and supported directly through the partner. 
Couchbase provides support for the couchbase components and interfaces.

| Couchbase Community Supported
a| Open source integration that is developed by Couchbase. 
Issues can also be raised in the relevant Github repositories or via couchbase forums(LINK), discord (LINK).
Support is provided best effort by development team

| Couchbase Officially supported
a| Open source integration that is developed by Couchbase and officially supported.  
A subscription to the Enterprise Edition of Couchbase includes technical support with service level commitments via our 24/7 support organization.
Issues can also be raised in the relevant Github repositories or via couchbase forums(LINK), discord (LINK).

| Community Supported
| Open source integration that is developed and supported directly by third party community contributor. 
Issues can also be raised in the relevant Github repositories.
|===

////
== Useful Tools

// Tools

=== Test Data Generation

couchbasefakeit FakeIt Docker
YCSB

=== Load Testing Tools

MeepMeep -- .NET workload gen
N1QLBack

////


////
| 
| 
| 
| 
| 



| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 


| 
| 
| 
| 
| 

////
////
IDEs
VS Code plugin β
JetBrains plugin α

////


////
== Below this line = TBD


Other
Java / JVM
Apache Camel
JHipster with Couchbase
Micronaut Couchbase
Scala Play Framework Cache
Spring Data Couchbase
https://github.com/liquibase/liquibase-couchbase 
.NET
Akka.NET
Linq 2 Couchbase
SignalR
Node.js
Ottoman
Golang
Bleve
Analytics
Apache Spark Notebook
Data Migration, Integrations & Backup
Apache Nifi
cbbackup and cbrestore
Elastic Search
Kafka
Spark
SQL Server to Couchbase
Connectors
ODBC and JDBC Drivers
Elasticsearch Plug-in
Kafka Connector
Spark Connector
Ruby
Doctrine 
https://github.com/doctolib/couchbase-orm 
PHP
Laravel
Schema Management
couchmove
couchbase-index-manager
SDKs and ORMs
.NET Core Extensions
ASP.NET Integration
Handcouchbaseentity
Linq2Couchbase
Ottoman
Spring Data
Spring Session
sql-formatter
synctos Sync Function
CLIs
Couchbase-Lite-CLI
Couchbase Shell or cbsh
Deployment: Containers and K8s
Docker Hub for Couchbase
Helm Charts for Couchbase
Mobile
Couchbase Lite for Dart and Flutter
Cordova Plugin
Ionic Framework





import
Utility for loading data into Couchbase and running performance tests. Includes the ability to load randomized data based on a template.
https://github.com/mminichino/cbperf



CAO
https://blog.crossplane.io/crossplane-openshift-operator-cloud-native-services/
////