= Developer Intro
:page-role: tiles -toc
:description: This section contains tutorials, how-to guides, and information about Couchbase Services to help you develop applications.
:!sectids:
:page-aliases: concepts:application-development;guides:intro.adoc

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title,
  div.contributor-list-box,
  div#preamble,
  nav.pagination {
    flex-basis: 100%;
  }
</style>
++++
endif::[]

{description}
It also provides links to the documentation for software development kits and other integrations.

include::partial$escape-hatch.adoc[]

== Developer Tutorial

This tutorial provides an introductory worked example for developers, showing how to use a software development kit with a simple database.

* xref:tutorials:couchbase-tutorial-student-records.adoc[]

== Data

Use the Data Service for key-value (CRUD) operations and to import or export data.

* xref:guides:kv-operations.adoc[]

== Query

Use the Query Service and the Index Service to issue {sqlpp} queries to extract and manipulate data.

* xref:n1ql:query.adoc[]

== Search

Use the Search Service for full-text search with natural language processing across multiple data types and languages.
Use custom text analysis, Geospatial search, and more.

* xref:search:search.adoc[]

== Eventing

Use the Eventing Service to respond to changes to your data in near real-time.
It enables you to execute code either in response to mutations, or as scheduled by timers.

* xref:eventing:eventing-overview.adoc[]

== Analytics

Use the Analytics Service for online analytical processing (OLAP) for large datasets, with complex analytical or ad hoc queries.

* xref:analytics:introduction.adoc[Introduction to Analytics]

== SDKs

Couchbase offers numerous software development kits (SDKs) that provide programmatic access to Couchbase Server.

* xref:home:ROOT:sdk.adoc[]

== Integrations

Integrations that Couchbase or partners have developed to enhance Couchbase, Capella, and partner services --
a vital tool for many larger development projects.

* xref:develop:integrations.adoc[]
