= Developer Intro
:page-role: tiles -toc
:description: This section contains tutorials, how-to guides, and information about Couchbase Services to help you develop applications.
:!sectids:
:page-aliases: concepts:application-development,guides:intro.adoc

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title,
  div.contributor-list-box,
  div#preamble,
  nav.pagination {
    flex-basis: 100%;
  }
</style>
++++
endif::[]

{description}
It also provides links to the documentation for software development kits and other integrations.

include::ROOT:partial$component-signpost.adoc[]

ifdef::flag-devex-tutorial[]
== Developer Tutorial

This tutorial provides an introductory worked example for developers, showing how to use a software development kit with a simple database.

* xref:tutorials:couchbase-tutorial-student-records.adoc[]
endif::flag-devex-tutorial[]

== Connect

Choose how you want to connect your app to Couchbase Capella.

* xref:cloud:get-started:connect.adoc[]

== Data

Use the Data Service for key-value (CRUD) operations and to import or export data.

* xref:guides:data.adoc[]

== Query

Use the Query Service and the Index Service to issue {sqlpp} queries to extract and manipulate data.

* xref:n1ql:query.adoc[]

== Vector Search

Vector Search builds on the Search Service to provide support for vector indexes.
You can use vector indexes with existing Large Language Models to develop AI applications.

* xref:vector-search:vector-search.adoc[]

== Search

Use the Search Service for full-text search with natural language processing across multiple data types and languages.
Use custom text analysis, Geospatial search, and more.

* xref:search:search.adoc[]

== Eventing

Use the Eventing Service to respond to changes to your data in near real-time.
Execute custom code in response to mutations, or as scheduled by timers.

* xref:eventing:eventing-overview.adoc[]

== Analytics

Use the Analytics Service for online analytical processing (OLAP) for large datasets, with complex analytical or ad hoc queries.

* xref:clusters:analytics-service/analytics-service.adoc[]

== Mobile

Use App Services in combination with Couchbase Mobile to develop mobile apps.

* xref:mobile-guides:intro.adoc[]

== SDKs

Couchbase offers numerous software development kits (SDKs) that provide programmatic access to Couchbase Capella.

* xref:home:ROOT:sdk.adoc[]

== Integrations

Integrations that Couchbase or partners have developed to enhance Couchbase, Capella, and partner services --
a vital tool for many larger development projects.

* xref:third-party:integrations.adoc[]
