= Developer's Intro
:page-role: tiles -toc
:description: This section contains tutorials, how-to guides, and information about Couchbase Services to help you develop applications.
:!sectids:
:page-aliases: concepts:application-development

// Pass through HTML styles for this page.

ifdef::basebackend-html[]
++++
<style type="text/css">
  /* Extend heading across page width */
  div.page-heading-title,
  div.contributor-list-box,
  div#preamble,
  nav.pagination {
    flex-basis: 100%;
  }
</style>
++++
endif::[]

{description}
It also provides links to the documentation for software development kits and starter kits.

include::partial$escape-hatch.adoc[]

== Developer Tutorial

This tutorial provides an introductory worked example for developers, showing how to use a software development kit with a simple database.

* xref:tutorials:couchbase-tutorial-student-records.adoc[]

== Developer Guides

These how-to guides walk you through common tasks for Couchbase Server development, such as storing, retrieving, and querying documents.

* xref:guides:intro.adoc[Developer Guides]

== SDKs

Couchbase offers numerous software development kits (SDKs) that provide programmatic access to Couchbase Server.

* xref:home:ROOT:sdk.adoc[]

== Query Service Information

The Query Service enables you to issue queries to extract data from Couchbase clusters.
You can also issue queries for defining indexes and data manipulation.

* xref:n1ql:query.adoc[]

== Search Service Information

The Search Service (Full Text Search or FTS) enables you to create and manage full-text indexes, and provides extensive capabilities for natural-language and geospatial queries.

* xref:fts:fts-introduction.adoc[]

== Eventing Service Information

The Eventing Service provides near real-time handling of changes to data.
It enables you to execute code either in response to mutations, or as scheduled by timers.

* xref:eventing:eventing-overview.adoc[]

== Analytics Service Information

The Analytics Service is a parallel data management capability for Couchbase Server, designed to run ad-hoc, analytical queries efficiently over many records.

* xref:analytics:introduction.adoc[Introduction to Analytics]

== Integrations

Integrations that Couchbase or partners have developed to enhance Couchbase, Capella, and partner services --
a vital tool for many larger development projects.

* xref:develop:integrations.adoc[]
