== Create a HyperScale Vector Index with the Capella UI

To create a HyperScale Vector index with the Capella UI: 

. On the *Operational Clusters* page, select the operational cluster where you want to create a HyperScale Vector index.
. Go to menu:Data Tools[Vector Indexes].
. Click btn:[Create Vector Index].
. Choose btn:[HyperScale Vector Index].
. In the *Index Name* field, enter a name for your new Vector index.
// Are there limitations on Index names?
. In the *Bucket*, *Scope*, and *Collection* lists, select the bucket, scope, and collection where you have documents that contain a vector field.
. In the *Select Field* list, select the vector field to use in your HyperScale Vector index.
. In the *Filter Field* lists, select the field, 
// How do you configure the Filter Field?
. Under *Index Configuration*, choose an option to automatically configure additional settings for your HyperScale Vector index: 
+
* *High Accuracy*
* *Low Latency* 
* *Balanced*
+
You can also configure the following settings manually: 
.. In the *Similarity Distance* list, select the similarity metric that you want to use for comparing vectors in your index.
For the best accuracy, use the same similarity that you plan to use to query your data.
+
For more information about vector similarity measures, see xref:vector-index:vectors-and-indexes-overview.adoc#vector_similarity[Vector Similarity].
.. In the *Quantization* list, select the type of quantization to use for simplifying the vectors stored in your index.
+
For more information about quantization, see xref:vector-index:vectors-and-indexes-overview.adoc#quantization[Quantization].
For more information about how to choose quantization on your index, see xref:vector-index:vectors-and-indexes-overview.adoc#choosing_quantization[Choosing Quantization] and xref:vector-index:vector-index-best-practices.adoc#quantization[Tuning Index Creation - Quantization].
.. In the *Dimensions* field, enter the exact dimension of the vectors in your data.
+
Your embedding model determines this value.
.. In the *Number of replicas* list, select the number of replicas you want to create for your index.
+
Replicas affect the query throughput, memory footprint, and fault tolerance for your HyperScale Vector index.
More replicas increase the required memory for your index, but can increase query throughput.
.. In the *Number of Training List* list, select the number of vectors to consider when searching for centroids in your data.
+
By default, your training list value should be 50 times the number of centroids in the index.
Higher values can increase your query throughput and reduce latency, but increase memory usage.
. Click btn:[Review Index].
. Confirm your HyperScale Vector Index configuration. 
. Click btn:[Create Index] or copy the {sqlpp} syntax to create your index with the Query Workbench.